### ISSUE TITLE
File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/image/geometric.py", line 242, in imrescale     h, w = img.shape[:2] ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#1011]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

    ``` GPUS=8 GPUS_PER_NODE=8 ./tools/slurm_train.sh pat_earth SEG4heads configs/segformer/segformer_mit-b5_256x256_interhand_1101.py --work-dir ./work_dirs```

2. Did you make any modifications on the code or config? Did you understand what you have modified? yes
in mmseg/datasets/pipelines/transforms.py def _resize_seg

orighinal : 
```            
if self.keep_ratio:
            gt_seg = mmcv.imrescale(
             results[key], results['scale'], interpolation='nearest')
```

and I changed it into 
```
if self.keep_ratio:
gt_seg = [mmcv.imrescale(
                        result_key, results['scale'], interpolation='nearest') for result_key in results[key]]
```
This is because I modified it into 4 decode heads and have 4 segmap predictions.

3. What dataset did you use? my own dataset

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```2021-11-03 02:06:49,113 - mmseg - INFO - Iter [600/250000]      lr: 1.147e-03, eta: 8 days, 8:52:19, time: 2.767, data_time: 0.042, memory: 29192, decode.loss_ce_0: 0.2475, decode.acc_seg_0: 74.8867, decode.loss_ce_1: 0.2367, decode.acc_seg_1: 75.4260, decode.loss_ce_2: 0.2481, decode.acc_seg_2: 74.8131, decode.loss_ce_3: 0.2368, decode.acc_seg_3: 75.3920, loss: 0.9691
2021-11-03 02:11:43,676 - mmseg - INFO - Iter [700/250000]      lr: 1.338e-03, eta: 8 days, 9:11:15, time: 2.940, data_time: 0.041, memory: 29192, decode.loss_ce_0: 0.2777, decode.acc_seg_0: 73.0710, decode.loss_ce_1: 0.2671, decode.acc_seg_1: 73.7216, decode.loss_ce_2: 0.2789, decode.acc_seg_2: 73.0848, decode.loss_ce_3: 0.2695, decode.acc_seg_3: 73.6560, loss: 1.0933
Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 176, in main
    meta=meta)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/apis/train.py", line 136, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 58, in train
    data_batch = next(data_loader)
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 218, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/custom.py", line 223, in __getitem__
    return self.prepare_train_img(idx)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/custom.py", line 240, in prepare_train_img
    return self.pipeline(results)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/pipelines/transforms.py", line 293, in __call__
    self._resize_seg(results)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/pipelines/transforms.py", line 268, in _resize_seg
    result_key, results['scale'], interpolation='nearest') for result_key in results[key]]
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/pipelines/transforms.py", line 268, in <listcomp>
    result_key, results['scale'], interpolation='nearest') for result_key in results[key]]
  File "/mnt/lustre/menghao/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/image/geometric.py", line 242, in imrescale
    h, w = img.shape[:2]
ValueError: not enough values to unpack (expected 2, got 0)

srun: error: SH-IDC1-10-198-4-85: task 5: Exited with exit code 1
srun: Terminating job step 4733448.0
slurmstepd: *** STEP 4733448.0 ON SH-IDC1-10-198-4-85 CANCELLED AT 2021-11-03T02:14:54 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.

```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by MengHao666** [comment]
@xvjiarui @Junjun2016 @xiexinch
