### ISSUE TITLE
Error when using hrnet to train my own dataset

### ISSUE THREAD

**Issue by ljy1998-cool** [open-mmlab/mmsegmentation#1015]
/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmseg/models/backbones/hrnet.py:318: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
2021-11-04 16:13:32,226 - mmseg - INFO - initialize HRNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'open-mmlab://msra/hrnetv2_w18'}
2021-11-04 16:13:32,227 - mmcv - INFO - load model from: open-mmlab://msra/hrnetv2_w18
2021-11-04 16:13:32,227 - mmcv - INFO - Use load_from_openmmlab loader
Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 140, in main
    model.init_weights()
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 612, in initialize
    _initialize(module, cp_cfg)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 517, in _initialize
    func(module)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 494, in __call__
    logger=logger)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 527, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 466, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 420, in load_from_openmmlab
    checkpoint = load_from_http(model_url, map_location=map_location)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/torch/hub.py", line 495, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ljyxsm/anaconda3/envs/hrnet/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by MengzhangLI** [comment]
Hi, could you download the model (using link below) locally and change pretrained model string from `open-mmlab://msra/hrnetv2_w18 ` to `./hrnetv2_w18-00eb2006.pth`? 

If it works, it means links error, if not, it is caused by codebase init module.

"msra/hrnetv2_w18": "https://download.openmmlab.com/pretrain/third_party/hrnetv2_w18-00eb2006.pth",

**Comment by ljy1998-cool** [comment]
it works!!!!!!!!!!!!!!!!thank you sooooo much!!!

**Comment by MengzhangLI** [comment]
I think this problem could be solved by upgrading `MMCV`.
