### ISSUE TITLE
constant folding error when exporting SegFormer to ONNX

### ISSUE THREAD

**Issue by nick-clarifai** [open-mmlab/mmsegmentation#1023]
**Description**

Exporting the SegFormer model using one of the repo configs creates an error in the constant folding step of `torch.onnx.export`.

**Reproduction**

```
python /mmsegmentation/tools/pytorch2onnx.py \
    /mmsegmentation/configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py \
    --output-file /mmsegmentation/configs/segformer/out.onnx \
    --input-img /mmsegmentation/tests/data/color.jpg \
    --verify \
    --dynamic-export
```

**Environment**
```
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: False
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.5.3
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMSegmentation: 0.19.0+bd3c1a6
```

a Dockerfile can be provided if that doesn't give enough info

**Error traceback**

```
Traceback (most recent call last):
  File "/mmsegmentation/tools/pytorch2onnx.py", line 403, in <module>
    dynamic_export=args.dynamic_export)
  File "/mmsegmentation/tools/pytorch2onnx.py", line 210, in pytorch2onnx
    do_constant_folding=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 502, in _model_to_graph
    _export_onnx_opset_version)
RuntimeError: expected scalar type Long but found Float
```
there are lots of C warnings/errors output too, see attached file
[error_log.txt](https://github.com/open-mmlab/mmsegmentation/files/7500245/error_log.txt)

**Bug fix**

none yet, my current workaround is to set `do_constant_folding=False` on the [`torch.onnx.export` call](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/pytorch2onnx.py#L194) but this sometimes causes some pixels to be incorrect during the subsequent verification step

**Comment by MengzhangLI** [comment]
Hi, @nick-clarifai 

Thanks for your feedback. I will let my colleagues for deployment review this problem.

As far as I know, right now most deployment method of OpenMMLab is based on PyTorch 1.8. So could you have a try on PyTorch 1.8 version if it is not time-consuming for you? 

Looking forward to your feedback.

Best,

**Comment by nick-clarifai** [comment]
No problem. I was able to run the same thing in an environment with pytorch 1.8.1 and the error fortunately did not surface. There was unfortunately some discrepancy in outputs in the verification step:

```
Traceback (most recent call last):
  File "/mmsegmentation/tools/pytorch2onnx.py", line 385, in <module>
    pytorch2onnx(
  File "/mmsegmentation/tools/pytorch2onnx.py", line 277, in pytorch2onnx
    np.testing.assert_allclose(
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05
The outputs are different between Pytorch and ONNX
Mismatched elements: 6 / 4718592 (0.000127%)
Max absolute difference: 0.76666665
Max relative difference: 79.
 x: array([[[0.226667, 0.226667, 0.226667, ..., 0.1     , 0.1     ,
         0.1     ],
        [0.226667, 0.226667, 0.226667, ..., 0.1     , 0.1     ,...
 y: array([[[0.226667, 0.226667, 0.226667, ..., 0.1     , 0.1     ,
         0.1     ],
        [0.226667, 0.226667, 0.226667, ..., 0.1     , 0.1     ,...
```

**Comment by MengzhangLI** [comment]
@RunningLeon Could you have a look at this issue? Thanks.

**Comment by RunningLeon** [comment]
@VVsssssk Coud you take a look at this? thanks

**Comment by VVsssssk** [comment]
Hello, our pytorch2onnx doesn't support this model. And I think if you want to use it, you can test onnx model in a dataset to determine whether use it.
