### ISSUE TITLE
About decode_head & auxiliary_head

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1047]
感谢您提供的mmsegmentation框架
目前我正在尝试实验一些decode_head和auxiliary_head来进行网络性能测试，譬如替换heads以及适当不使用一些auxiliary_head等操作，过程中我遇到了一些问题：
1. 当我尝试删除auxiliary_head时（在config/_base_/models中改动，只留下backbone+decode_head+train_cfg+test_cfg）有如下情况出现，但当我加上auxiliary_head时就是CUDA out of memory
Traceback (most recent call last):
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 40, in __init__
    self._init_auxiliary_head(auxiliary_head)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 61, in _init_auxiliary_head
    self.auxiliary_head = builder.build_head(auxiliary_head)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/builder.py", line 30, in build_head
    return HEADS.build(cfg)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 24, in build_from_cfg
    raise KeyError(
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'in_channels\': 384, \'num_classes\': 150}\nNone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 136, in main
    model = build_segmentor(
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'EncoderDecoder: \'`cfg` or `default_args` must contain the key "type", but got {\\\'in_channels\\\': 384, \\\'num_classes\\\': 150}\\nNone\''

2. 当我尝试替换decode head和加入一些neck时，会有如下情况（decode--PSPHead & Neck=JPU）：
Traceback (most recent call last):
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/decode_heads/psp_head.py", line 75, in __init__
    super(PSPHead, self).__init__(**kwargs)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 75, in __init__
    self._init_inputs(in_channels, in_index, input_transform)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 150, in _init_inputs
    assert isinstance(in_channels, int)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 39, in __init__
    self._init_decode_head(decode_head)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 49, in _init_decode_head
    self.decode_head = builder.build_head(decode_head)
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/builder.py", line 30, in build_head
    return HEADS.build(cfg)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: PSPHead: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 136, in main
    model = build_segmentor(
  File "/nfs/my/lsz/mmsegmentation/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/py38_torch1.7/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: EncoderDecoder: PSPHead: 

感谢您的回复

**Comment by MengzhangLI** [comment]
Hi, could you show me the snapshots of your file in `config/base/models`? 

Thank you so much.

**Comment by MengzhangLI** [comment]
From the error description, it seems `type` is missing but I am not sure whether it is caused by incorrect config file.

**Comment by Lsz-20** [comment]
> From the error description, it seems `type` is missing but I am not sure whether it is caused by incorrect config file.

感谢您的回复，我尝试修改config/base/models下的文件以及config/swin下的配置文件解决了type的问题 但是我在官方提供原config下只是删除了auxiliary head之后出现了CUDA out of memory的问题，而原本带有auxiliary head的情况下并没有该问题 请问是怎么回事呢？感谢！

**Comment by Lsz-20** [comment]
> Hi, could you show me the snapshots of your file in `config/base/models`?
> 
> Thank you so much.


当我删除了swin下的auxiliary head之后的问题：我尝试了几个其他的网络也出现了同样的报错问题
![image](https://user-images.githubusercontent.com/60343452/142148991-2f48f195-5927-4b36-a74f-48183512eec0.png)
感谢解答

**Comment by MengzhangLI** [comment]
Thank you for your feedback. 

Sorry I can not answer this question directly because I do not meet this problem before. But I will record it for further refactoring.

From the snapshot, it shows `CUDA error` without specified memory number, it is wired which often happened when no GPU specified. Could you try to define `CUDA_VISIBLE_DEVICES`? Here is related [Chinese website](https://www.bbsmax.com/A/mo5kgD7L5w/).

**Comment by Lsz-20** [comment]
> Thank you for your feedback.
> 
> Sorry I can not answer this question directly because I do not meet this problem before. But I will record it for further refactoring.
> 
> From the snapshot, it shows `CUDA error` without specified memory number, it is wired which often happened when no GPU specified. Could you try to define `CUDA_VISIBLE_DEVICES`? Here is related [Chinese website](https://www.bbsmax.com/A/mo5kgD7L5w/).

好的 感谢您的回复 我先去试试看kk

**Comment by Wanttoretire** [comment]
> > From the error description, it seems `type` is missing but I am not sure whether it is caused by incorrect config file.
> 
> 感谢您的回复，我尝试修改config/base/models下的文件以及config/swin下的配置文件解决了type的问题 但是我在官方提供原config下只是删除了auxiliary head之后出现了CUDA out of memory的问题，而原本带有auxiliary head的情况下并没有该问题 请问是怎么回事呢？感谢！

你好我想问问你都具体修改了什么呢  我也出现了一样的问题
