### ISSUE TITLE
关于Neck的问题

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1055]
您好 我在尝试使用neck时发现报错：
KeyError：‘JPU’ is not in the {register}
KeyError：‘EncoderDecoder’ ：‘JPU’ is not in the models register
我检查了mmseg/models/_init_.py中的文件，似乎在_all_中缺少了关于neck的引入？
感谢回复！

**Comment by MengzhangLI** [comment]
Hi, could you use `pip install -e .` in your mmseg repo and try again?

The `NECKS` has been built here:

https://github.com/open-mmlab/mmsegmentation/blob/2b2f107fd6f52f6a516747bfb1a2a83f074f2448/mmseg/models/builder.py#L25

**Comment by Lsz-20** [comment]
> Hi, could you use `pip install -e .` in your mmseg repo and try again?
> 
> The `NECKS` has been built here:
> 
> https://github.com/open-mmlab/mmsegmentation/blob/2b2f107fd6f52f6a516747bfb1a2a83f074f2448/mmseg/models/builder.py#L25

感谢您的回复，我查看了mmseg/model/下的init以及builder文件，确认和官方的并无差异，其中init为：
![image](https://user-images.githubusercontent.com/60343452/142803193-797d4ec5-171d-491c-a011-e50e8f5a6274.png)
其中没有NECK的对吗？

**Comment by MengzhangLI** [comment]
> > Hi, could you use `pip install -e .` in your mmseg repo and try again?
> > The `NECKS` has been built here:
> > https://github.com/open-mmlab/mmsegmentation/blob/2b2f107fd6f52f6a516747bfb1a2a83f074f2448/mmseg/models/builder.py#L25
> 
> 感谢您的回复，我查看了mmseg/model/下的init以及builder文件，确认和官方的并无差异，其中init为： ![image](https://user-images.githubusercontent.com/60343452/142803193-797d4ec5-171d-491c-a011-e50e8f5a6274.png) 其中没有NECK的对吗？

Yep, actually I've checked my original repo re-implementing FastFCN, and it is the same as official code whose `init` does not have `'NECKS'` in `__all__`.

**Comment by Lsz-20** [comment]
> Yep, actually I've checked my original repo re-implementing FastFCN, and it is the same as official code whose `init` does not have `'NECKS'` in `__all__`.

感谢您的回复~我重新安装了一下mmsegmentation，并检查了model/neck文件夹如下：
![image](https://user-images.githubusercontent.com/60343452/142860156-e1cb06f7-195f-4e45-9606-a9de7b1e99aa.png)
但似乎仍有以上错误？

**Comment by MengzhangLI** [comment]
> > Yep, actually I've checked my original repo re-implementing FastFCN, and it is the same as official code whose `init` does not have `'NECKS'` in `__all__`.
> 
> 感谢您的回复~我重新安装了一下mmsegmentation，并检查了model/neck文件夹如下： ![image](https://user-images.githubusercontent.com/60343452/142860156-e1cb06f7-195f-4e45-9606-a9de7b1e99aa.png) 但似乎仍有以上错误？

It is really wired. Can you write a detailed error report thus we could record it? Thanks!

**Comment by Lsz-20** [comment]
> 好的 感谢解答
报错如下：
Traceback (most recent call last):
  File "/home/anaconda3/envs/py37_torch1.8/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/lsz/Transformer/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 38, in __init__
    self.neck = builder.build_neck(neck)
  File "/home/lsz/Transformer/mmsegmentation/mmseg/models/builder.py", line 25, in build_neck
    return NECKS.build(cfg)
  File "/home/anaconda3/envs/py37_torch1.8/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/anaconda3/envs/py37_torch1.8/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/anaconda3/envs/py37_torch1.8/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'JPU is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 139, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/lsz/Transformer/mmsegmentation/mmseg/models/builder.py", line 49, in build_segmentor
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/anaconda3/envs/py37_torch1.8/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/anaconda3/envs/py37_torch1.8/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/anaconda3/envs/py37_torch1.8/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "EncoderDecoder: 'JPU is not in the models registry'"

感谢~

**Comment by Lsz-20** [comment]
> It is really wired. Can you write a detailed error report thus we could record it? Thanks!
还有一个问题想要请教一下。看到您提供的neck是在fastfcn这个网络中使用的，请问其他网络（原先没有这个的）如果在configs文件中加入这个neck，是否可以正常使用呢？还是也会出现以上的‘JPU未被注册到模型中’的报错出现？
谢谢

**Comment by MengzhangLI** [comment]
Hi, theoretically it should work if input/output channels are aligned.

Could you try to use our provided FastFCN models [here](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/fastfcn) to testify whether JPU could be used in MMSegmentation?
