### ISSUE TITLE
fastscnn export onnx error

### ISSUE THREAD

**Issue by silaopi** [open-mmlab/mmsegmentation#1133]
FastSCNN fail to export onnx format when using tools/pytorch2onnx.py. Here is the detail:
Traceback (most recent call last):
  File "/home/tian/projects/mmsegmentation/tools/pytorch2onnx.py", line 225, in pytorch2onnx
    torch.onnx.export(
  File "/home/tian/anaconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/tian/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/tian/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/tian/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/tian/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/tian/anaconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/tian/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 1032, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/tian/anaconda3/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/tian/anaconda3/lib/python3.8/site-packages/mmcv/onnx/symbolic.py", line 333, in symbolic_fn
    raise NotImplementedError(
NotImplementedError: [Adaptive pool]:input size not accessible

And I mad some modification of the model by remove auxiliary_head. Like this:
# model settings
norm_cfg = dict(type='SyncBN', requires_grad=True, momentum=0.01)
model = dict(
    type='EncoderDecoder',
    # pretrained='https://download.openmmlab.com/mmsegmentation/v0.5/fast_scnn/fast_scnn_lr0.12_8x4_160k_cityscapes/fast_scnn_lr0.12_8x4_160k_cityscapes_20210630_164853-0cec9937.pth',
    backbone=dict(
        type='FastSCNN',
        downsample_dw_channels=(32, 48),
        global_in_channels=64,
        global_block_channels=(64, 96, 128),
        global_block_strides=(2, 2, 1),
        global_out_channels=128,
        higher_in_channels=64,
        lower_in_channels=128,
        fusion_out_channels=128,
        out_indices=(0, 1, 2),
        norm_cfg=norm_cfg,
        align_corners=False),
    decode_head=dict(
        type='DepthwiseSeparableFCNHead',
        in_channels=128,
        channels=128,
        concat_input=False,
        num_classes=19,
        in_index=-1,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1
            # type='DiceLoss', use_sigmoid=True, loss_weight=1
        )),
    # auxiliary_head=[
    #     dict(
    #         type='FCNHead',
    #         in_channels=128,
    #         channels=32,
    #         num_convs=1,
    #         num_classes=19,
    #         in_index=-2,
    #         norm_cfg=norm_cfg,
    #         concat_input=False,
    #         align_corners=False,
    #         loss_decode=dict(
    #             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=0.4)),
    #     dict(
    #         type='FCNHead',
    #         in_channels=64,
    #         channels=32,
    #         num_convs=1,
    #         num_classes=19,
    #         in_index=-3,
    #         norm_cfg=norm_cfg,
    #         concat_input=False,
    #         align_corners=False,
    #         loss_decode=dict(
    #             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=0.4)),
    # ],
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/1044
