### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'iter_100.pth'

### ISSUE THREAD

**Issue by xiaweiguang** [open-mmlab/mmsegmentation#1158]
021-12-23 20:03:37,935 - mmseg - INFO - workflow: [('train', 1)], max: 2000 iters
2021-12-23 20:03:52,269 - mmseg - INFO - Iter [50/2000]	lr: 9.781e-03, eta: 0:08:13, time: 0.253, data_time: 0.072, memory: 2528, decode.loss_seg: 2.4536, decode.acc_seg: 18.3672, aux.loss_seg: 0.9248, aux.acc_seg: 21.6723, loss: 3.3783
2021-12-23 20:04:02,189 - mmseg - INFO - Saving checkpoint at 100 iterations
Traceback (most recent call last):
  File "F:/TMANet-master/tools/train.py", line 167, in <module>
    main()
  File "F:/TMANet-master/tools/train.py", line 163, in main
    meta=meta)
  File "F:/TMANet-master/tools\..\mmseg\apis\train.py", line 115, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "f:\1.2.0+0.7.0\mmcv-1.2.0\mmcv\runner\iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "f:\1.2.0+0.7.0\mmcv-1.2.0\mmcv\runner\iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "f:\1.2.0+0.7.0\mmcv-1.2.0\mmcv\runner\base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "f:\1.2.0+0.7.0\mmcv-1.2.0\mmcv\runner\hooks\checkpoint.py", line 101, in after_train_iter
    self._save_checkpoint(runner)
  File "f:\1.2.0+0.7.0\mmcv-1.2.0\mmcv\runner\dist_utils.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "f:\1.2.0+0.7.0\mmcv-1.2.0\mmcv\runner\hooks\checkpoint.py", line 62, in _save_checkpoint
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "f:\1.2.0+0.7.0\mmcv-1.2.0\mmcv\runner\iter_based_runner.py", line 215, in save_checkpoint
    shutil.copy(filename, dst_file)
  File "D:\anaconda3\envs\TMA\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\anaconda3\envs\TMA\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'iter_100.pth'

Process finished with exit code 1
----------------------------------------------------------------------------------------------------------
Excuse me, how to solve this error report?

**Comment by xiaweiguang** [comment]
I run train.py on Windows 10 , such an error will occur, but it can run correctly in Linux system.

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply. I think you can directly ask the author of TMANet, it is probably caused by their customization modification.
