### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by renmmmmmm** [open-mmlab/mmsegmentation#117]
2020-09-09 23:53:22,492 - mmseg - INFO - Loaded 1449 images
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1452/1449, 13.6 task/s, elapsed: 107s, ETA:     0s
writing results to results.pkl
Traceback (most recent call last):
  File "./tools/test.py", line 142, in <module>
    main()
  File "./tools/test.py", line 138, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/home/rss/tmp/mmsegmentation-master/mmseg/datasets/custom.py", line 247, in evaluate
    assert len(metric) == 1
AssertionError
Traceback (most recent call last):
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/rss/anaconda3/envs/mmlab/bin/python', '-u', './tools/test.py', '--local_rank=3', 'configs/deeplabv3plus/deeplabv3plus_r101-d8_512x512_40k_voc12aug.py', 'checkpoints/deeplabv3plus_r101-d8_512x512_40k_voc12aug_20200613_205333-faf03387.pth', '--launcher', 'pytorch', '--out', 'results.pkl', '--eval', 'mIoU', 'voc12aug']' returned non-zero exit status 1.
how can i solve it?

**Comment by xvjiarui** [comment]
Hi @renmmmmmm 
You should exclude `voc12aug` in your testing cmd. `voc12aug` is not an evaluation metric.
