### ISSUE TITLE
CUDA error with OHEM

### ISSUE THREAD

**Issue by jiangnini** [open-mmlab/mmsegmentation#1180]
I receive an error report when using OHEM with the following code:
`cfg.model.decoder_head.sampler = dict(type='OHEMPixelSampler', thresh=0.5, min_kept=100000)`

`/opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [450,0,0], thread: [59,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [450,0,0], thread: [60,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [450,0,0], thread: [62,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "trainServer.py", line 327, in <module>
    main()
  File "trainServer.py", line 316, in main
    train_segmentor(
  File "/home/inspur/WorkSpace/Python/PytorchWorkSpace/mmsegmentation/mmseg/apis/train.py", line 167, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/inspur/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/inspur/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/inspur/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/inspur/WorkSpace/Python/PytorchWorkSpace/mmsegmentation/mmseg/models/segmentors/base.py", line 138, in train_step
    losses = self(**data_batch)
  File "/home/inspur/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/inspur/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/inspur/WorkSpace/Python/PytorchWorkSpace/mmsegmentation/mmseg/models/segmentors/base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/inspur/WorkSpace/Python/PytorchWorkSpace/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 143, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "/home/inspur/WorkSpace/Python/PytorchWorkSpace/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 86, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "/home/inspur/WorkSpace/Python/PytorchWorkSpace/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 204, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "/home/inspur/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/inspur/WorkSpace/Python/PytorchWorkSpace/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 241, in losses
    seg_weight = self.sampler.sample(seg_logit, seg_label)
  File "/home/inspur/WorkSpace/Python/PytorchWorkSpace/mmsegmentation/mmseg/core/seg/sampler/ohem_pixel_sampler.py", line 56, in sample
    sort_prob, sort_indices = seg_prob[valid_mask].sort()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

Is anyone have any experiences on this?

**Comment by MengzhangLI** [comment]
Hi, did you follow the ohem method like this config?

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/bisenetv2/bisenetv2_fcn_ohem_4x4_1024x1024_160k_cityscapes.py

**Comment by jiangnini** [comment]
Not exactly the same.

I was using `deeplabv3plus_r101-d8_512x512_80k_ade20k.py` as the base config, and I haven't modify the `sampler` in the `auxiliary_head`. Besides, my task have 3 classes and class 0 as background was set to ignore_index, also, `samples_per_gpu` was set to 2.

I will try make the change in `auxiliary_head` or other option next.

**Comment by jiangnini** [comment]
I tried other options, still get the same error.

Is OHEM only work for some particular model?

**Comment by MengzhangLI** [comment]
No, it is an universal method. You may check whether it is correct in config file.

**Comment by sainivedh19pt** [comment]
Hi @MengzhangLI ,

The problem still persists, got the same error when training [stdc](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/stdc.py) config. Works fine if the OHEM sampler is removed in all heads

**Comment by MMY1994** [comment]
Hi @MengzhangLI 
Actually I meet the same preblem,when I use my data to train stdc model. I got the same error, If I get rid of the OHEM sampler it works. I think ther is something wrong in OHEM sampler.

**Comment by ynhuhu** [comment]
I meet the same problem when i train using segformer.

**Comment by ynhuhu** [comment]
when you remove ignore_index, it will work.

**Comment by ArthasMil** [comment]
I think it's something wrong with the _reduce_zero_label_ or _ignore_index_. Obviously this function works well **without**  _reduce_zero_label_ , such as the cityscapes settings. When training the ADE20k or LoveDA，this problem will occur.

**Comment by Mr-Clutch-China** [comment]
I have the same problem and the dataset I used was binary, which also worked well without ohem. 
By the way, it works well when I use the color category [(0, 0, 0), (1, 1, 1)], but this error occurs when I use [(0, 0, 0), (255, 255, 255)]
