### ISSUE TITLE
What is the format of the application mosaic augumentation?

### ISSUE THREAD

**Issue by ChenJiangxi** [open-mmlab/mmsegmentation#1207]
I learned about the mosaic in issues and implemented it in the cfg like this：
`train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='RandomMosaic', prob=0.3, img_scale=(512,1024)),
    # dict(type='Resize', img_scale=(512, 1024), keep_ratio=True),
    dict(type='Resize', img_scale=(512, 1024), multiscale_mode='range', ratio_range=(0.5, 2.0), keep_ratio=True),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]`

I know it still needs to be written somewhere `type = MultiImageMixDataset` ,but I don't know at where since mmsegmentation and mmdetection have different cfg formats

**Comment by ChenJiangxi** [comment]
```
train=dict(
        type='MultiImageMixDataset',
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            img_dir='rawdata/train',
            ann_dir='labeldata/train',
            pipeline=train_pipeline)),
```
 I've tried this way,but an Error come out:
```
Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 152, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/sjtu/mmsegmentation_old/mmseg/datasets/builder.py", line 76, in build_dataset
    cp_cfg['dataset'] = build_dataset(cp_cfg['dataset'])
  File "/home/sjtu/mmsegmentation_old/mmseg/datasets/builder.py", line 83, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/sjtu/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SingleGreenDataset: __init__() missing 1 required positional argument: 'split'
```

**Comment by ChenJiangxi** [comment]
But it is very strange that IoU dropped very, very much after adding mosaic according to the tutorial.

**Comment by lkm2835** [comment]
> But it is very strange that IoU dropped very, very much after adding mosaic according to the tutorial.


This pipeline(Mosaic -> Resize -> ~) makes your objects smaller.

When I used it, (Mosaic -> Crop) was more reasonable.

example,
```
train_pipeline = [
    ~,
    dict(type='RandomMosaic', prob=0.3, img_scale=(512, 512)),
    dict(type='RandomCrop', crop_size=crop_size),
    # dict(type='Resize', img_scale=(512, 512)),
    ~    
]
```

better than

```
train_pipeline = [
    ~,
    dict(type='RandomMosaic', prob=0.3, img_scale=(512, 512)),
    dict(type='Resize', img_scale=(512, 512)),
    dict(type='RandomCrop', crop_size=crop_size),
    ~    
]
```

**Comment by ChenJiangxi** [comment]
> > But it is very strange that IoU dropped very, very much after adding mosaic according to the tutorial.
> 
> This pipeline(Mosaic -> Resize -> ~) makes your objects smaller.
> 
> When I used it, (Mosaic -> Crop) was more reasonable.
> 
> For example,
> 
> ```
> train_pipeline = [
>     ~,
>     dict(type='RandomMosaic', prob=0.3, img_scale=(512, 512)),
>     dict(type='RandomCrop', crop_size=crop_size),
>     dict(type='Resize', img_scale=(512, 512)),
>     ~    
> ]
> ```
> 
> better than
> 
> ```
> train_pipeline = [
>     ~,
>     dict(type='RandomMosaic', prob=0.3, img_scale=(512, 512)),
>     dict(type='Resize', img_scale=(512, 512)),
>     dict(type='RandomCrop', crop_size=crop_size),
>     ~    
> ]
> ```

thank you very much! But I tried what you said and this did not work; an error would be reported. I used a cfg like this：
```
    dict(type='RandomMosaic', prob=0.3, img_scale=(512,1024)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    # dict(type='Resize', img_scale=(512, 1024), multiscale_mode='range', ratio_range=(0.5, 2.0), keep_ratio=True),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
```
this means don't resize then it'll work. It's still in training, I'll update the results later, thank you very much for guidance.
