### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpvbi4s5yy/tmpg2syq97k.py

### ISSUE THREAD

**Issue by huang45** [open-mmlab/mmsegmentation#122]
Hi, a error was happened when I try to train my own dataset by the custom format. could you pls help to check? Thanks.

**Error traceback**
Traceback (most recent call last):
  File "/home/jovan/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 94, in _validate_py_syntax
    ast.parse(content)
  File "/home/jovan/anaconda3/envs/mmlab/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 43
    val=dict(
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 66, in main
    cfg = Config.fromfile(args.config)
  File "/home/jovan/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 213, in fromfile
    use_predefined_variables)
  File "/home/jovan/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 172, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/jovan/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 143, in _file2dict
    Config._validate_py_syntax(filename)
  File "/home/jovan/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 96, in _validate_py_syntax
    raise SyntaxError('There are syntax errors in config '
SyntaxError: There are syntax errors in config file /home/jovan/work/Github/mmsegmentation/configs/_base_/datasets/yjh.py: invalid syntax (<unknown>, line 43)
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7ff7f0684950>
Traceback (most recent call last):
  File "/home/jovan/anaconda3/envs/mmlab/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/jovan/anaconda3/envs/mmlab/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpvbi4s5yy/tmpg2syq97k.py'

**Comment by xvjiarui** [comment]
Hi @huang45 
There is SynatixError in your config file.

**Comment by huang45** [comment]
Yes, it is!  Thanks. @xvjiarui

**Comment by York1996OutLook** [comment]
### **i found Chinese character in config file will result in above error**

**Comment by ManuBN786** [comment]
I did a 'python config.yaml' and there were no issues
But I still get this error.

How to resolve?
