### ISSUE TITLE
deploy builtin segformer model with torchserve 

### ISSUE THREAD

**Issue by CaRRotOne** [open-mmlab/mmsegmentation#1221]
**Describe the bug**
I am trying to deploy builtin model(segformer) with torchserve.But the deploy is failed,  see the more info in "Error traceback". please help to resolve it. Thanks.

1. What command or script did you run?
I followed the [guideline ](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/useful_tools.md#%E6%A8%A1%E5%9E%8B%E6%9C%8D%E5%8A%A1).  

**Environment**

```
sys.platform: linux
Python: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA GeForce RTX 3080
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.2+cu110
OpenCV: 4.2.0
MMCV: 1.4.3
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
MMSegmentation: 0.20.2+7512f05
```

**Error traceback**

If applicable, paste the error trackback here.

```none
2022-01-20T07:00:23,137 [INFO ] W-9007-segformer_1.0-stdout MODEL_LOG - No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
2022-01-20T07:00:23,153 [INFO ] W-9004-segformer_1.0-stdout MODEL_LOG - No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
2022-01-20T07:00:25,104 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - Backend worker process died.
2022-01-20T07:00:25,104 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2022-01-20T07:00:25,105 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_loader.py", line 83, in load
2022-01-20T07:00:25,105 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     module, function_name = self._load_handler_file(handler)
2022-01-20T07:00:25,105 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_loader.py", line 123, in _load_handler_file
2022-01-20T07:00:25,105 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     module = importlib.import_module(module_name)
2022-01-20T07:00:25,105 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
2022-01-20T07:00:25,105 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2022-01-20T07:00:25,105 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2022-01-20T07:00:25,106 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2022-01-20T07:00:25,106 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2022-01-20T07:00:25,106 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2022-01-20T07:00:25,106 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2022-01-20T07:00:25,106 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-01-20T07:00:25,106 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/4afc0d2ee39642248a2e03ecd436e3ec/mmseg_handler.py", line 9, in <module>
2022-01-20T07:00:25,106 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     from ts.torch_handler.base_handler import BaseHandler
2022-01-20T07:00:25,107 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/torch_handler/base_handler.py", line 12, in <module>
2022-01-20T07:00:25,107 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     from torch.profiler import profile, record_function, ProfilerActivity
2022-01-20T07:00:25,107 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - ModuleNotFoundError: No module named 'torch.profiler'
2022-01-20T07:00:25,107 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -
2022-01-20T07:00:25,107 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - During handling of the above exception, another exception occurred:
2022-01-20T07:00:25,108 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -
2022-01-20T07:00:25,108 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2022-01-20T07:00:25,107 [INFO ] epollEventLoopGroup-5-5 org.pytorch.serve.wlm.WorkerThread - 9002 Worker disconnected. WORKER_STARTED
2022-01-20T07:00:25,108 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_service_worker.py", line 189, in <module>
2022-01-20T07:00:25,108 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     worker.run_server()
2022-01-20T07:00:25,108 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_service_worker.py", line 161, in run_server
2022-01-20T07:00:25,108 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2022-01-20T07:00:25,109 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_service_worker.py", line 123, in handle_connection
2022-01-20T07:00:25,109 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2022-01-20T07:00:25,109 [DEBUG] W-9002-segformer_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2022-01-20T07:00:25,109 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_service_worker.py", line 96, in load_model
2022-01-20T07:00:25,109 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     batch_size, envelope, limit_max_image_pixels)
2022-01-20T07:00:25,109 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_loader.py", line 85, in load
2022-01-20T07:00:25,109 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     module = self._load_default_handler(handler)
2022-01-20T07:00:25,109 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_loader.py", line 128, in _load_default_handler
2022-01-20T07:00:25,110 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     module = importlib.import_module(module_name, 'ts.torch_handler')
2022-01-20T07:00:25,110 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
2022-01-20T07:00:25,110 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2022-01-20T07:00:25,110 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2022-01-20T07:00:25,110 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2022-01-20T07:00:25,110 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
2022-01-20T07:00:25,110 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-01-20T07:00:25,111 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2022-01-20T07:00:25,111 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2022-01-20T07:00:25,111 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
2022-01-20T07:00:25,111 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - ModuleNotFoundError: No module named 'ts.torch_handler.mmseg_handler'
2022-01-20T07:00:25,109 [DEBUG] W-9002-segformer_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432) ~[?:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:189) [model-server.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-01-20T07:00:25,130 [WARN ] W-9002-segformer_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: segformer, error: Worker died.
2022-01-20T07:00:25,130 [DEBUG] W-9002-segformer_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-segformer_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2022-01-20T07:00:25,130 [WARN ] W-9002-segformer_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-segformer_1.0-stderr
2022-01-20T07:00:25,130 [WARN ] W-9002-segformer_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-segformer_1.0-stdout
2022-01-20T07:00:25,131 [INFO ] W-9002-segformer_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9002 in 1 seconds.
2022-01-20T07:00:25,145 [INFO ] W-9002-segformer_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-segformer_1.0-stdout
2022-01-20T07:00:25,145 [INFO ] W-9002-segformer_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-segformer_1.0-stderr
2022-01-20T07:00:25,167 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG - Backend worker process died.
2022-01-20T07:00:25,167 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2022-01-20T07:00:25,168 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_loader.py", line 83, in load
2022-01-20T07:00:25,168 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -     module, function_name = self._load_handler_file(handler)
2022-01-20T07:00:25,168 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/site-packages/ts/model_loader.py", line 123, in _load_handler_file
2022-01-20T07:00:25,168 [INFO ] epollEventLoopGroup-5-7 org.pytorch.serve.wlm.WorkerThread - 9006 Worker disconnected. WORKER_STARTED
2022-01-20T07:00:25,168 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -     module = importlib.import_module(module_name)
2022-01-20T07:00:25,168 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
2022-01-20T07:00:25,168 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2022-01-20T07:00:25,168 [DEBUG] W-9006-segformer_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2022-01-20T07:00:25,169 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2022-01-20T07:00:25,169 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2022-01-20T07:00:25,169 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2022-01-20T07:00:25,169 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2022-01-20T07:00:25,169 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2022-01-20T07:00:25,169 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-01-20T07:00:25,169 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/4afc0d2ee39642248a2e03ecd436e3ec/mmseg_handler.py", line 9, in <module>
2022-01-20T07:00:25,169 [INFO ] W-9006-segformer_1.0-stdout MODEL_LOG -     from ts.torch_handler.base_handler import BaseHandler
2022-01-20T07:00:25,169 [DEBUG] W-9006-segformer_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432) ~[?:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:189) [model-server.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Kenneth-X** [comment]
from torch.profiler import profile, record_function, ProfilerActivity
2022-01-20T07:00:25,107 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - ModuleNotFoundError: No module named 'torch.profiler'

maybe your torch version is not right，torch.profiler only exist in pytorch 1.8.1 or higher

**Comment by CaRRotOne** [comment]
> from torch.profiler import profile, record_function, ProfilerActivity 2022-01-20T07:00:25,107 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - ModuleNotFoundError: No module named 'torch.profiler'
> 
> maybe your torch version is not right，torch.profiler only exist in pytorch 1.8.1 or higher

my torch version is 1.7.1+cu110. And I am  using the master [Dockerfile](https://github.com/open-mmlab/mmsegmentation/blob/master/docker/serve/Dockerfile), the torch version in TorchServe is 1.6.

**Comment by CaRRotOne** [comment]
> > from torch.profiler import profile, record_function, ProfilerActivity 2022-01-20T07:00:25,107 [INFO ] W-9002-segformer_1.0-stdout MODEL_LOG - ModuleNotFoundError: No module named 'torch.profiler'
> > maybe your torch version is not right，torch.profiler only exist in pytorch 1.8.1 or higher
> 
> my torch version is 1.7.1+cu110. And I am using the master [Dockerfile](https://github.com/open-mmlab/mmsegmentation/blob/master/docker/serve/Dockerfile), the torch version in TorchServe is 1.6.
> 
> I used master [dockerfile ](https://github.com/open-mmlab/mmsegmentation/blob/master/docker/Dockerfile)which pytorch version is 1.6.0 to build an image, and convert model to torchserve. Then I run the torchserve container which build from master [dockefile](https://github.com/open-mmlab/mmsegmentation/blob/master/docker/serve/Dockerfile). The problem still exists.

I fix it by specify torchserve version(torchserve==0.5.1), https://github.com/pytorch/serve/blob/v0.5.1/ts/torch_handler/base_handler.py
