### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'group'

### ISSUE THREAD

**Issue by QingshuiL** [open-mmlab/mmsegmentation#123]
2020-09-11 09:21:21,564 - mmseg - INFO - workflow: [('train', 1)], max: 20000 iters
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
    meta=meta)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmseg\apis\train.py", line 106, in train_segmentor
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "c:\users\10295\mmcv\mmcv\runner\iter_based_runner.py", line 119, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "c:\users\10295\mmcv\mmcv\runner\iter_based_runner.py", line 55, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "c:\users\10295\mmcv\mmcv\parallel\data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmseg\models\segmentors\base.py", line 149, in train_step
    losses = self.forward_train(**data_batch, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 152, in forward_train
    x = self.extract_feat(img)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 78, in extract_feat
    x = self.backbone(img)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmseg\models\backbones\resnet.py", line 635, in forward
    x = self.stem(x)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\batchnorm.py", line 490, in forward
    process_group = torch.distributed.group.WORLD
AttributeError: module 'torch.distributed' has no attribute 'group'

**Comment by xvjiarui** [comment]
Hi @QingshuiL 
You may use `BN` instead of `SyncBN` on Windows PC.
