### ISSUE TITLE
site-packages/mmcv/image/geometric.py", line 242, in imrescale h, w = img.shape[:2] ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by ethanliuzhuo** [open-mmlab/mmsegmentation#1297]
2022-02-17 11:55:31,763 - mmseg - INFO - Loaded 692 images
2022-02-17 11:55:34,870 - mmseg - INFO - Loaded 173 images
2022-02-17 11:55:34,871 - mmseg - INFO - Start running, host: root@07e1e7df0076, work_dir: /home/mmsegmentation/VOC
2022-02-17 11:55:34,872 - mmseg - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-02-17 11:55:34,872 - mmseg - INFO - workflow: [('train', 1)], max: 4000 iters
2022-02-17 11:55:34,872 - mmseg - INFO - Checkpoints will be saved to /home/mmsegmentation/VOC by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 214, in <module>
    main()
  File "tools/train.py", line 203, in main
    train_segmentor(
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmsegmentation-0.20.2-py3.8.egg/mmseg/apis/train.py", line 171, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 59, in train
    data_batch = next(data_loader)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmsegmentation-0.20.2-py3.8.egg/mmseg/datasets/custom.py", line 203, in __getitem__
    return self.prepare_train_img(idx)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmsegmentation-0.20.2-py3.8.egg/mmseg/datasets/custom.py", line 220, in prepare_train_img
    return self.pipeline(results)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmsegmentation-0.20.2-py3.8.egg/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmsegmentation-0.20.2-py3.8.egg/mmseg/datasets/pipelines/transforms.py", line 288, in __call__
    self._resize_seg(results)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmsegmentation-0.20.2-py3.8.egg/mmseg/datasets/pipelines/transforms.py", line 266, in _resize_seg
    gt_seg = mmcv.imrescale(
  File "/root/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/image/geometric.py", line 242, in imrescale
    h, w = img.shape[:2]
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by MeowZheng** [comment]
This seems to be a problem with your dataset.

**Comment by xiexinch** [comment]
Hi! Thank you for your quick response. I'm more curious about the reasoning behind a lack of class weighting though. Especially with the heavy imbalance of certain classes such as poles and trains in the Cityscapes dataset, it seems that class weighting would be necessary for the model to perform well as various CNN semantic segmentation architectures such as UNet or LinkNet utilize it in their experiments.

**Comment by jacksteussie** [comment]
What was wrong here with the dataset? I am currently getting the same error for my dataset I'm incorporating into the framework.
