### ISSUE TITLE
STDC checkpoints have no `meta` key

### ISSUE THREAD

**Issue by RunningLeon** [open-mmlab/mmsegmentation#1303]
STDC checkpoints have no `meta` key.
### ran script
```
python /home/PJLAB/maningsheng/projects/openmmlab/mmsegmentation/demo/image_demo.py \
demo/demo.png \
configs/stdc/stdc2_in1k-pre_512x1024_80k_cityscapes.py \
checkpoints/stdc2_in1k-pre_512x1024_80k_cityscapes_20211125_220437-d2c469f8.pth
```

### error message
```
load checkpoint from local path: checkpoints/stdc2_in1k-pre_512x1024_80k_cityscapes_20211125_220437-d2c469f8.pth
Traceback (most recent call last):
  File "/home/PJLAB/maningsheng/projects/openmmlab/mmsegmentation/demo/image_demo.py", line 40, in <module>
    main()
  File "/home/PJLAB/maningsheng/projects/openmmlab/mmsegmentation/demo/image_demo.py", line 27, in main
    model = init_segmentor(args.config, args.checkpoint, device=args.device)
  File "/home/PJLAB/maningsheng/projects/openmmlab/mmsegmentation/mmseg/apis/inference.py", line 35, in init_segmentor
    model.CLASSES = checkpoint['meta']['CLASSES']
KeyError: 'meta
```

**Comment by MengzhangLI** [comment]
It is because after pushing the STDC model, pr reviewer made some comments about variable names, so I have to transfer key names to ensure lateset version could directly use STDC model which is actually using older variable names. 

META info is lost during transferring keys process. I would try to find original models back, otherwise I would train new STDC models and push again.

Best,

**Comment by daigang896** [comment]
Encountered the same problem.
