### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hushuai1** [open-mmlab/mmsegmentation#1327]
I just test the code:
`from mmseg.apis import inference_segmentor, init_segmentor
import mmcv`

error:
(open-mmlab) root@b6497071f687:~/mmsegmentation-master/mmsegmentation-master# python demo.py 
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from mmseg.apis import inference_segmentor, init_segmentor
  File "/root/mmsegmentation-master/mmsegmentation-master/mmseg/__init__.py", line 4, in <module>
    import mmcv
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by sainivedh19pt** [comment]
Try doing

- sudo apt-get update
- sudo apt-get install libsm6 libxext6 ffmpeg -y

**Comment by MeowZheng** [comment]
No further discussion
