### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)

### ISSUE THREAD

**Issue by sihuo521** [open-mmlab/mmsegmentation#1356]
### 1. shell
**python tools/train.py configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_40k_voc12aug.py**
### 2. bug
**ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).**
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/opt/conda/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
**RuntimeError: DataLoader worker (pid 7579) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

The above exception was the direct cause of the following exception:**

Traceback (most recent call last):
  File "tools/train.py", line 245, in <module>
    main()
  File "tools/train.py", line 240, in main
    meta=meta)
  File "/data19/sy/code/openmmlab/mmsegmentation/mmseg/apis/train.py", line 180, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 59, in train
    data_batch = next(data_loader)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
**RuntimeError: DataLoader worker (pid(s) 7579) exited unexpectedly**

**Comment by sihuo521** [comment]
when validate, it occur

**Comment by MengzhangLI** [comment]
It is usually cause by your own cluster, PC or docker where not enough shared memory for training/validation.
