### ISSUE TITLE
Error: Invalid number of channels in input image

### ISSUE THREAD

**Issue by ys830** [open-mmlab/mmsegmentation#1358]
I saved three  RGB images as a nine-channel image in .tif format, and then changed the input channel of the network to nine, and the following error occurred, how should I solve it?

Traceback (most recent call last):
  File "tools/train.py", line 234, in <module>
    main()
  File "tools/train.py", line 223, in main
    train_segmentor(
  File "/ys_prjs/MyWork/mmsegmentation-master/mmseg/apis/train.py", line 174, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 59, in train
    data_batch = next(data_loader)
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ys_prjs/MyWork/mmsegmentation-master/mmseg/datasets/dataset_wrappers.py", line 188, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/ys_prjs/MyWork/mmsegmentation-master/mmseg/datasets/custom.py", line 203, in __getitem__
    return self.prepare_train_img(idx)
  File "/ys_prjs/MyWork/mmsegmentation-master/mmseg/datasets/custom.py", line 220, in prepare_train_img
    return self.pipeline(results)
  File "/ys_prjs/MyWork/mmsegmentation-master/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/ys_prjs/MyWork/mmsegmentation-master/mmseg/datasets/pipelines/transforms.py", line 932, in __call__
    img = self.saturation(img)
  File "/ys_prjs/MyWork/mmsegmentation-master/mmseg/datasets/pipelines/transforms.py", line 893, in saturation
    img = mmcv.bgr2hsv(img)
  File "/root/.anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/image/colorspace.py", line 280, in convert_color
    out_img = cv2.cvtColor(img, code)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<3>; VDepth = cv::impl::{anonymous}::Set<0, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 9

**Comment by MengzhangLI** [comment]
Right now MMSeg only supports 1-channel or 3-channel input image.
