### ISSUE TITLE
cfg.pretty_text is not able to parse cfg.checkpoint_config.meta correctly

### ISSUE THREAD

**Issue by SBCV** [open-mmlab/mmsegmentation#1359]
**Describe the bug**
`cfg.pretty_text` is not able to parse `cfg.checkpoint_config.meta` correctly.

In [mmsegmentation/tools/train.py](https://github.com/open-mmlab/mmsegmentation/blob/e8cc3224e1b44ae44bf7f22f356f64059a8d82b9/tools/train.py#L214-L218) the meta data of the `checkpoint_config` is set according to:

 https://github.com/open-mmlab/mmsegmentation/blob/e8cc3224e1b44ae44bf7f22f356f64059a8d82b9/tools/train.py#L214-L218

When using `print(cfg.pretty_text)` (afterwards), the following error message is thrown. 

```
config='norm_cfg = dict(type='SyncBN', requires_grad=True)
                                   ^
SyntaxError: invalid syntax
```

**Reproduction**

1. This toy example reproduces the error

```
from mmcv.utils import Config
first_part_of_pspnet_config = """
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='open-mmlab://resnet50_v1c',
)
"""
cfg = Config.fromstring(first_part_of_pspnet_config,".py")
cfg.some_name = dict(config=cfg.pretty_text)
print(cfg.pretty_text)
```

**Error traceback**

```
Traceback (most recent call last):
  File "/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 131, in ParseCodeToTree
    raise e
  File "/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 129, in ParseCodeToTree
    ast.parse(code)
  File "/miniconda3/envs/open-mmlab/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 8
    config='norm_cfg = dict(type='SyncBN', requires_grad=True)
                                       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tests/mmseg/pretty_text.py", line 18, in <module>
    print(cfg.pretty_text)
  File "/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 501, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:8:40: invalid syntax

Process finished with exit code 1
```

**Comment by zenjieli** [comment]
I have got the same issue.

**Comment by LansonChen** [comment]
how do u  resolve it ?

**Comment by Huiimin5** [comment]
How do you fix this?
