### ISSUE TITLE
Could find my file 'train_ours.txt' which is in fact exist

### ISSUE THREAD

**Issue by linchangyi1** [open-mmlab/mmsegmentation#1367]
Traceback (most recent call last):
  File "/home/changyilin/lib/anaconda3/envs/ganav/lib/python3.7/site-packages/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
  File "/home/changyilin/Final_Project/SSDMUE/unstructure_segmentor/mmseg/datasets/rugd_group6.py", line 24, in __init__
    **kwargs)
  File "/home/changyilin/Final_Project/SSDMUE/unstructure_segmentor/mmseg/datasets/custom.py", line 113, in __init__
    self.seg_map_suffix, self.split)
  File "/home/changyilin/Final_Project/SSDMUE/unstructure_segmentor/mmseg/datasets/custom.py", line 141, in load_annotations
    with open(split) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/rugd/train_ours.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/changyilin/Final_Project/SSDMUE/unstructure_segmentor/tools/train.py", line 173, in <module>
    main()
  File "/home/changyilin/Final_Project/SSDMUE/unstructure_segmentor/tools/train.py", line 146, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/changyilin/Final_Project/SSDMUE/unstructure_segmentor/mmseg/datasets/builder.py", line 73, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/changyilin/lib/anaconda3/envs/ganav/lib/python3.7/site-packages/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: RUGDDataset_Group6: [Errno 2] No such file or directory: 'data/rugd/train_ours.txt'

And I think my placement is right as it show:
![image](https://user-images.githubusercontent.com/71823391/157854666-acab45aa-f09f-4f58-bcaf-f3c2e847d2ca.png)
![image](https://user-images.githubusercontent.com/71823391/157854721-a2c96a73-17dd-46cd-9fee-85a38a01935c.png)

Could you please tell me how to solve it? (I can train it several days ago, but today I can't run it without changing during these days?

**Comment by MengzhangLI** [comment]
Hi, we do not have these folders or files, so you may ask authors who customize our codebase.
