### ISSUE TITLE
How to use mixed precision training in command line mode

### ISSUE THREAD

**Issue by LutaoChu** [open-mmlab/mmsegmentation#1394]
在配置文件中可以设置FP16的参数，例如https://github.com/open-mmlab/mmsegmentation/blob/6b3e5506c56fa6a04a5d2bde086919d62310884f/configs/deeplabv3plus/deeplabv3plus_r101-d8_fp16_512x1024_80k_cityscapes.py

但如果想要从命令行指定对应参数进行训练的话，应该如何指定呢？

我尝试
```
python tools/train.py mmseg_benchmark_configs/fcn_hrnetw18.py --no-validate \
--options log_config.interval=10 runner.max_iters=500 data.samples_per_gpu=8 \
optimizer_config.Fp16OptimizerHook.loss_scale=512. fp16=None \
data.workers_per_gpu=5
```
但遇到问题
```
2022-03-18 12:26:49,750 - mmseg - INFO - Loaded 30 images
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'Fp16OptimizerHook'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 234, in <module>
    main()
  File "tools/train.py", line 230, in main
    meta=meta)
  File "/clt/benchmark/frame_benchmark/pytorch/dynamic/PaddleSeg/models/mmsegmentation/mmseg/apis/train.py", line 127, in train_segmentor
    cfg.get('momentum_config', None))
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 272, in register_training_hooks
    custom_hooks_config=custom_hooks_config)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 540, in register_training_hooks
    self.register_optimizer_hook(optimizer_config)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 448, in register_optimizer_hook
    hook = mmcv.build_from_cfg(optimizer_config, HOOKS)
  File "/usr/local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: OptimizerHook: __init__() got an unexpected keyword argument 'Fp16OptimizerHook'
```

**Comment by MengzhangLI** [comment]
Hi, please check this https://github.com/open-mmlab/mmsegmentation/blob/master/configs/convnext/upernet_convnext_base_fp16_512x512_160k_ade20k.py#L35-L40.

Add these lines in your config file.

**Comment by LutaoChu** [comment]
谢谢回复。这是配置文件的方式，我想知道不修改配置文件，能否在命令行中实现？

**Comment by MengzhangLI** [comment]
Not supported yet.

**Comment by businiaoo** [comment]
Do we need to install apex when using mixed precision training?

**Comment by MengzhangLI** [comment]
> Do we need to install apex when using mixed precision training?

No need to install apex.
