### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'checkpoint_config'

### ISSUE THREAD

**Issue by BebDong** [open-mmlab/mmsegmentation#1436]
Thanks for providing such a great repo for benchmarking segmentation methods. But I encountered an error when trained with a self-defined backbone. Details are as follows:
```
Traceback (most recent call last):
  File "tools/train.py", line 217, in <module>
    main()
  File "tools/train.py", line 194, in main
    if cfg.checkpoint_config is not None:
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/mmcv/utils/config.py", line 510, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'checkpoint_config'
```
It seems that I wrote an unmatched config file, but there was no attribute named `checkpoint_config`. The config file is as follows:
```python
# coding=utf-8
_base_ = ['../_base_/datasets/ade20k.py', '../_base_/default_runtime.py']

# model
model = dict(
    type='EncoderDecoder',
    backbone=dict(
        type='SegmentationImageTransformer',
        img_size=512,
        in_channels=3,
        embed_dims=48,
        num_layers=(1, 2, 4, 1),
        num_heads=(1, 2, 5, 8),
        out_indices=(0, 1, 2, 3),
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=.0,
        attn_drop_rate=.0,
        drop_path_rate=.1,
        pretrained='sit-tiny_pt-8xb128_in1k.pth'
    ),
    decode_head=dict(
        type='SegformerHead',
        in_channels=(96, 240, 384, 384),
        in_index=(0, 1, 2, 3),
        channels=256,
        dropout_ratio=.1,
        num_classes=150,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
    ),
    train_cfg=dict(),
    test_cfg=dict(mode='whole')
)

# data
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(data_root='data/ade/ADEChallengeData2016'),
    val=dict(data_root='data/ade/ADEChallengeData2016'),
    test=dict(data_root='data/ade/ADEChallengeData2016')
)

# schedules
optimizer = dict(
    _delete=True,
    type='AdamW',
    lr=6e-5,
    weight_decay=0.01,
    paramwise_cfg=dict(
        custom_keys={'.pos_embed': dict(decay_mult=0.0),
                     'norm': dict(decay_mult=.0),
                     'head': dict(lr_mult=10.)}
    )
)
lr_config = dict(
    _delete_=True,
    policy='poly',
    warmup='linear',
    warmup_iters=1500,
    warmup_ratio=1e-6,
    power=1.0,
    min_lr=0.0,
    by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=160000)

```

**Comment by MengzhangLI** [comment]
It is located in `./configs/_base_/schedules/`: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/schedules/schedule_160k.py#L8.

**Comment by BebDong** [comment]
I have added the missing _base_ file in './configs/_base_/schedules/' and it works well. Thanks!
