### ISSUE TITLE
Distributed training error with stop gradients

### ISSUE THREAD

**Issue by emily-lin** [open-mmlab/mmsegmentation#1466]
Hi all,

When I add a "with torch.no_grad():" scope to the decoder of my segmentation model, I got the following runtime error message when I tried to use distributed training on multiple GPUs (single GPU training works correctly with the stop gradients). The training works fine on multiple GPUs before we added the "with torch.no_grad():" line to a few decoder layers.

Any advice on how to debug/fix this?

Many thanks,

Emily

==========================================================================================
Traceback (most recent call last):
Traceback (most recent call last):
  File "./tools/train.py", line 181, in <module>
  File "./tools/train.py", line 181, in <module>
    main()
main()  File "./tools/train.py", line 177, in main

  File "./tools/train.py", line 177, in main
    meta=meta)
Traceback (most recent call last):
  File "/export/data/yuhlab1/emily/mmsegmentation/mmseg/apis/train.py", line 136, in train_segmentor
  File "./tools/train.py", line 181, in <module>
    meta=meta)
  File "/export/data/yuhlab1/emily/mmsegmentation/mmseg/apis/train.py", line 136, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    runner.run(data_loaders, cfg.workflow)
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    iter_runner(iter_loaders[i], **kwargs)
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)      File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train

main()  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 65, in train_step

  File "./tools/train.py", line 177, in main
        outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)self.reducer.prepare_for_backward([])

  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 65, in train_step
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
    self.reducer.prepare_for_backward([])
    meta=meta)RuntimeError
: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).  File "/export/data/yuhlab1/emily/mmsegmentation/mmseg/apis/train.py", line 136, in train_segmentor

    runner.run(data_loaders, cfg.workflow)
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 65, in train_step
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/export/data/yuhlab1/emily/miniconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=2', 'configs/swin/20220409_ftlayer_v1.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by MeowZheng** [comment]
Might add `find_unused_parameters=True` in your cfg

**Comment by emily-lin** [comment]
Thanks for the help, adding this to the cfg fixed the issue. Much appreciated!

**Comment by AAAdecade** [comment]
> 感谢您的帮助，将其添加到 cfg 解决了问题。非常感谢！

您好，我也遇到了相同的问题，请问应该在哪里加入：find_unused_parameters=True？求求您了 被困住好几天了
