### ISSUE TITLE
Cityscapes test error on HRNet

### ISSUE THREAD

**Issue by Dootmaan** [open-mmlab/mmsegmentation#1512]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.  -----**yes**
2. The bug has not been fixed in the latest version.  -----**yes**

**Describe the bug**
I trained HRNet on Cityscape with
```
CUDA_VISIBLE_DEVICES=0 python -u tools/train.py configs/hrnet/fcn_hr48_512x1024_160k_cityscapes.py
```
and it works pretty well (validation works fine). 

Then i would like to use the weights for testing, so i added 
```
data = dict(
    test=dict(
        img_dir='leftImg8bit/test',
        ann_dir='gtFine/test'))
```
to "configs/hrnet/fcn_hr48_512x1024_160k_cityscapes.py" and tried to run:
```
CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/hrnet/fcn_hr48_512x1024_160k_cityscapes.py work_dirs/fcn_hr48_512x1024_160k_cityscapes/iter144000.pth --eval cityscapes
```
From the terminal i can see 1525 images are loaded and processed, but an error occurred when calculating the mIoU, which says:
```
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1525/1525, 2.9 task/s, elapsed: 530s, ETA:     0s
Evaluating in Cityscapes style
Evaluating results under .format_cityscapes ...
Evaluating 1525 pairs of images...
Traceback (most recent call last):
  File "/home/why/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/why/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/why/.vscode-server/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/why/.vscode-server/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/why/.vscode-server/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/why/miniconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/why/miniconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/why/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/why/Workspace-Python/mmsegmentation/tools/test.py", line 319, in <module>
    main()
  File "/home/why/Workspace-Python/mmsegmentation/tools/test.py", line 310, in main
    metric = dataset.evaluate(results, **eval_kwargs)
  File "/home/why/Workspace-Python/mmsegmentation/mmseg/datasets/cityscapes.py", line 160, in evaluate
    self._evaluate_cityscapes(results, logger, imgfile_prefix))
  File "/home/why/Workspace-Python/mmsegmentation/mmseg/datasets/cityscapes.py", line 212, in _evaluate_cityscapes
    CSEval.evaluateImgLists(pred_list, seg_map_list, CSEval.args))
  File "/home/why/miniconda3/lib/python3.8/site-packages/cityscapesscripts/evaluation/evalPixelLevelSemanticLabeling.py", line 475, in evaluateImgLists
    nbPixels += evaluatePair(predictionImgFileName, groundTruthImgFileName, confMatrix, instStats, perImageStats, args)
  File "/home/why/miniconda3/lib/python3.8/site-packages/cityscapesscripts/evaluation/evalPixelLevelSemanticLabeling.py", line 590, in evaluatePair
    encoded = (groundTruthNp.astype(np.int32) * encoding_value) + predictionNp
ValueError: operands could not be broadcast together with shapes (1024,2048,3) (1024,2048)
```

Maybe ive done something wrong because i never noticed anybody has the same problem. 

**Reproduction**

1. What command or script did you run?

```
CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/hrnet/fcn_hr48_512x1024_160k_cityscapes.py work_dirs/fcn_hr48_512x1024_160k_cityscapes/iter144000.pth --eval cityscapes
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
- **No code is modified.**

3. What dataset did you use?
- Cityscapes

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.8.3 (default, May 19 2020, 18:47:26) [GCC 7.3.0]
CUDA available: True
GPU 0,1: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.4
MMCV: 1.4.8
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 11.1
MMSegmentation: 0.23.0+62c3a7d
```

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] ----conda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Dootmaan** [comment]
I found the model outputs a (1024,2048) shape pred_label and the ground truth is shaped as (1024,2048,3). 

However, i believe usually the output should be (1024,2048,19) while gt is (1024,2048).

**Comment by Dootmaan** [comment]
figured it out finally. it turns out that gtFine/test only have the fake labels and i can only submit the results to their server to have the test score. 

Sorry for the trouble.
