### ISSUE TITLE
when i use multi gpus,there is an NCCL error!help

### ISSUE THREAD

**Issue by Anny-Anny** [open-mmlab/mmsegmentation#1521]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:748, internal error, NCCL version 2.7.8

**Reproduction**

1. What command or script did you run?

    ```none
      #!/usr/bin/env bash
      
      CONFIG='/home/dgx/workspace/xjw/mmsegmentation/SeRe/config/dgx/xt/xt_finetune/myconfig_xt.py'
      GPUS=2
      PORT=${PORT:-29509}
      export NCCL_DEBUG=VERSION
      
      
      PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
      python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \
          $(dirname "$0")/train1.py $CONFIG --launcher pytorch ${@:3} \
          --load-from /home/dgx/workspace/xjw/mmsegmentation/tools/work_dirs/xiangtan/union/train_100/epoch_100.pth \
          --work-dir /home/dgx/workspace/xjw/mmsegmentation/tools/work_dirs/xiangtan/finetune/train_80
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
<pre>
    (wayy) dgx@geox-DGX-Station-A100-920-23487-2531-000:~/workspace/xjw/mmsegmentation/mmseg$ python utils/collect_env.py            
    sys.platform: linux                                                                                                              
    Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]                                                                      
    CUDA available: True                                                                                                             
    GPU 0,1,2,3: Graphics Device                                                                                                     
    GPU 4: DGX Display                                                                                                               
    CUDA_HOME: /usr/local/cuda
    NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
    GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
    PyTorch: 1.7.1+cu110
    PyTorch compiling details: PyTorch built with:
      - GCC 7.3
      - C++ Version: 201402
      - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
      - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
      - OpenMP 201511 (a.k.a. OpenMP 4.5)
      - NNPACK is enabled
      - CPU capability usage: AVX2
      - CUDA Runtime 11.0
      - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
      - CuDNN 8.0.5
      - Magma 2.5.2
      - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX5$<pre>12=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
    
    TorchVision: 0.8.2+cu110
    OpenCV: 4.5.5
    MMCV: 1.4.4
    MMCV Compiler: GCC 7.3
    MMCV CUDA Compiler: 11.0
    MMSegmentation: 0.22.0+e8cc322
</pre>
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [conda]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

```none
(wayy) dgx@geox-DGX-Station-A100-920-23487-2531-000:~/workspace/xjw/mmsegmentation/tools$ bash dist_train1.sh                    
*****************************************                                                                                        
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please f
urther tune the variable for optimal performance in your application as needed.                                                  
*****************************************                                                                                        
2022-04-27 23:06:51,787 - mmseg - INFO - Multi-processing start method is `None`                                                 
2022-04-27 23:06:51,787 - mmseg - INFO - OpenCV num_threads is `<built-in function getNumThreads>                                
2022-04-27 23:06:51,787 - mmseg - INFO - OMP num threads is 1                                                                    
2022-04-27 23:06:51,802 - mmseg - INFO - Multi-processing start method is `None`                                                 
2022-04-27 23:06:51,802 - mmseg - INFO - OpenCV num_threads is `<built-in function getNumThreads>                                
2022-04-27 23:06:51,802 - mmseg - INFO - OMP num threads is 1                                                                    
Traceback (most recent call last):                                                                                               
  File "./train1.py", line 238, in <module>                                                                                      
    main()                                                                                                                       
  File "./train1.py", line 156, in main                                                                                          
    init_dist(args.launcher, **cfg.dist_params)                                                                                  
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist              
    _init_dist_pytorch(backend, **kwargs)                                                                                        
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 32, in _init_dist_pytorch     
    dist.init_process_group(backend=backend, **kwargs)                                                                           
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_proce
ss_group                                                                                                                         
    barrier()                                                                                                                    
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier  
    work = _default_pg.barrier()                                                                                                 
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:748, internal error, NCCL version 2.7.8                
Traceback (most recent call last):                                                                                               
  File "./train1.py", line 238, in <module>                                                                                      
    main()                                                                                                                       
  File "./train1.py", line 156, in main                                                                                          
    init_dist(args.launcher, **cfg.dist_params)
File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_proce
ss_group
    barrier()
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier() 
RuntimeError: Connection reset by peer
Traceback (most recent call last):
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/dgx/anaconda3/envs/wayy/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dgx/anaconda3/envs/wayy/bin/python', '-u', './train1.py', '--local_rank=1', '/hom
e/dgx/workspace/xjw/mmsegmentation/SeRe/config/dgx/xt/xt_finetune/myconfig_xt.py', '--launcher', 'pytorch', '--load-from', '/home
/dgx/workspace/xjw/mmsegmentation/tools/work_dirs/xiangtan/union/train_100/epoch_100.pth', '--work-dir', '/home/dgx/workspace/xjw
/mmsegmentation/tools/work_dirs/xiangtan/finetune/train_80']' returned non-zero exit status 1.
```

**Bug fix**
i have google this problem,but it doesnt work! 
like
export NCCL_DEBUG=info
export NCCL_SOCKET_IFNAME=eth0
export NCCL_IB_DISABLE=1

but nothing more showed.

**Comment by MeowZheng** [comment]
It might be a bug from PyTorch ref: https://github.com/pytorch/pytorch/issues/47885
I suggest you might try this environment https://github.com/pytorch/pytorch/issues/47885#issuecomment-886327449
