### ISSUE TITLE
Instructions lead to errornous test script

### ISSUE THREAD

**Issue by eyildiz-ugoe** [open-mmlab/mmsegmentation#1535]
The setup instructions [here](https://mmsegmentation.readthedocs.io/en/latest/get_started.html) show a piece of code that should run once the setup is completed successfully:

```
from mmseg.apis import inference_segmentor, init_segmentor
import mmcv

config_file = 'configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py'
checkpoint_file = 'checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth'

# build the model from a config file and a checkpoint file
model = init_segmentor(config_file, checkpoint_file, device='cuda:0')

# test a single image and show the results
img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_segmentor(model, img)
# visualize the results in a new window
model.show_result(img, result, show=True)
# or save the visualization results to image files
# you can change the opacity of the painted segmentation map in (0, 1].
model.show_result(img, result, out_file='result.jpg', opacity=0.5)

# test a video and show the results
video = mmcv.VideoReader('video.mp4')
for frame in video:
   result = inference_segmentor(model, frame)
   model.show_result(frame, result, wait_time=1)
```

Upon launching that piece of code, and error is thrown, saying the following:

```
FileNotFoundError: checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth can not be found.
```

I've taken a look and found out that there is no such "checkpoints" folder in the first place.

**Comment by eyildiz-ugoe** [comment]
Thanks for the quick response. After doing that, it threw another error:

```
load checkpoint from local path: checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth
Traceback (most recent call last):
  File "/home/eyildiz/Desktop/mmsegmentation/test_installation.py", line 12, in <module>
    result = inference_segmentor(model, img)
  File "/home/eyildiz/Desktop/mmsegmentation/mmseg/apis/inference.py", line 88, in inference_segmentor
    data = test_pipeline(data)
  File "/home/eyildiz/Desktop/mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/eyildiz/Desktop/mmsegmentation/mmseg/apis/inference.py", line 63, in __call__
    img = mmcv.imread(results['img'])
  File "/home/eyildiz/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/image/io.py", line 203, in imread
    img_bytes = file_client.get(img_or_path)
  File "/home/eyildiz/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/fileio/file_client.py", line 993, in get
    return self.client.get(filepath)
  File "/home/eyildiz/anaconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/fileio/file_client.py", line 518, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test.jpg'
```

**Comment by eyildiz-ugoe** [comment]
> > 
> 
> Perhaps you need to prepare an image named `test.jpg` to testify its performance?
> 
> We would review colab and doc carefully to evade similar errors / bugs in the next few months.

This test image is not requested in that piece of code you shared as verification code. It actually goes way back in the trace if you look:

```
File "/home/eyildiz/Desktop/mmsegmentation/test_installation.py", line 12, in <module>
    result = inference_segmentor(model, img)
  File "/home/eyildiz/Desktop/mmsegmentation/mmseg/apis/inference.py", line 88, in inference_segmentor
    data = test_pipeline(data)
  File "/home/eyildiz/Desktop/mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/eyildiz/Desktop/mmsegmentation/mmseg/apis/inference.py", line 63, in __call__
    img = mmcv.imread(results['img'])
```

The line:

**Comment by eyildiz-ugoe** [comment]
Yes, that solved the problem. Thanks.
