### ISSUE TITLE
Can you suggest how to depoly mmcv detection on server without GPU

### ISSUE THREAD

**Issue by BenjaminPang** [open-mmlab/mmsegmentation#1545]
I have trained a segementation model on my personal computer with GPU. However I need to depoly the segmentation module to the server which has no GPU. Since the server has no GPU, I can only install mmcv on it rather than mmcv-full. When I run the inference code , it comes the error ModuleNotFoundError: No module named 'mmcv._ext'. 
Clearly, it is because I did not install the mmcv-full on the server. Could you please give me some suggestion about this problem. Looking forward to any reply.

-------------------------------------
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from tryon.items import build_item, pipelines
  File "/python_code/Multi-layer-Virtual-Try-on/tryon/items/__init__.py", line 2, in <module>
    from .clothing import Clothing
  File "/python_code/Multi-layer-Virtual-Try-on/tryon/items/clothing.py", line 4, in <module>
    from .pipelines import Compose
  File "/python_code/Multi-layer-Virtual-Try-on/tryon/items/pipelines/__init__.py", line 4, in <module>
    from .segmentation import Segmentation
  File "/python_code/Multi-layer-Virtual-Try-on/tryon/items/pipelines/segmentation.py", line 6, in <module>
    from mmsegmentation.mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/models/backbones/__init__.py", line 6, in <module>
    from .fast_scnn import FastSCNN
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/python_code/Multi-layer-Virtual-Try-on/mmsegmentation/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/python_env/pytorch18/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/python_env/pytorch18/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/python_env/pytorch18/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by RunningLeon** [comment]
@BenjaminPang Hi, what's backend you use on your deploy machine? If it is onnxruntime, you could export the model on a machine with GPU and run the onnx model on target deploy machine.

**Comment by MeowZheng** [comment]
no further discussion
