### ISSUE TITLE
can not  train two datasets on the same machine with different GPU at the same time by two difference process？

### ISSUE THREAD

**Issue by lurenlym** [open-mmlab/mmsegmentation#163]
I want to parallel train two datasets on the same machine with different GPU at the same time by two difference process
But I got the error

CUDA_VISIBLE_DEVICES=2,3 ./tools/dist_train.sh configs/deeplabv3plus/deeplabv3plus_r101-d8_512x1024_80k_sutcity.py 2 --work-dir work_dirs/deeplabv3plus_r101-d8_512x1024_80k_sutcity/sutcity2/
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 95, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/opt/conda/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/deeplabv3plus/deeplabv3plus_r101-d8_512x1024_80k_sutcity.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/deeplabv3plus_r101-d8_512x1024_80k_sutcity/sutcity2/']' returned non-zero exit status 1.
(open-mmlab) root@c28767f822dd:/lym/mmsegmentation# Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 131, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/lym/mmsegmentation/mmseg/models/builder.py", line 56, in build_segmentor
    return build(cfg, SEGMENTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/lym/mmsegmentation/mmseg/models/builder.py", line 31, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/lym/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 39, in __init__
    self.init_weights(pretrained=pretrained)
  File "/lym/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 68, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/lym/mmsegmentation/mmseg/models/backbones/resnet.py", line 609, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 247, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 207, in _load_checkpoint
    checkpoint = load_url_dist(model_url)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 113, in load_url_dist
    torch.distributed.barrier()
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1710, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8

**Comment by xvjiarui** [comment]
Hi @lurenlym 
Sorry for the late reply.
Please refer to [here](https://mmsegmentation.readthedocs.io/en/latest/getting_started.html#launch-multiple-jobs-on-a-single-machine) for details.
