### ISSUE TITLE
Training on multiple machine error loading .eval_hook/part_2.pkl file

### ISSUE THREAD

**Issue by majnas** [open-mmlab/mmsegmentation#1713]
I am training Segformer with custom dataset on two machines each with two A40 gpus. I have modified class names and palette in mmseg/datasets/custom.py. the training works well when I use only one machine with two gpus, but when using two machine the traing works but when it comes to evaluete after 4000 iteration it faces following errors. When I checked the i realized that part_0.pkl and part_1.pkl are in "/work_dirs/segformer_mit-b5_512x512_160k_es/.eval_hook/" folder on master machine and  part_2.pkl and part_3.pkl are in "/work_dirs/segformer_mit-b5_512x512_160k_es/.eval_hook/" folder on slave machine and master machine can not load part_2.pkl from another machine!!!

on master /work_dirs/segformer_mit-b5_512x512_160k_es/.eval_hook/
* part_0.pkl 
* part_1.pkl 

on slave /work_dirs/segformer_mit-b5_512x512_160k_es/.eval_hook/
* part_2.pkl 
* part_3.pkl 

**MASTER** 
```shell
NNODES=2 NODE_RANK=0 PORT=$MASTER_PORT MASTER_ADDR=$MASTER_ADDR tools/dist_train.sh configs/segformer/segformer_mit-b5_512x512_160k_es.py 2
```
**SLAVE**
```shell
NNODES=2 NODE_RANK=1 PORT=$MASTER_PORT MASTER_ADDR=$MASTER_ADDR tools/dist_train.sh configs/segformer/segformer_mit-b5_512x512_160k_es.py 2
```

** necessary environment information **
```shell
sys.platform: linux
Python: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
CUDA available: True
GPU 0,1: NVIDIA A40
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.8.2+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.2+cu111
OpenCV: 4.6.0
MMCV: 1.5.3
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.1
MMSegmentation: 0.25.0+7eccb21
```

** Error on master machine **
```shell
2022-06-26 01:18:00,844 - mmseg - INFO - Iter [4000/160000]	lr: 5.850e-05, eta: 8 days, 18:22:19, time: 4.830, data_time: 0.015, memory: 39311, decode.loss_ce: 0.2048, decode.acc_seg: 92.4343, loss: 0.2048
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 392/390, 7.1 task/s, elapsed: 55s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 231, in main
    train_segmentor(
  File "/home/s2/Documents/segmentation/mmsegmentation/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 138, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 68, in train
    self.call_hook('after_train_iter')
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 262, in after_train_iter
    self._do_evaluate(runner)
  File "/home/s2/Documents/segmentation/mmsegmentation/mmseg/core/evaluation/eval_hooks.py", line 113, in _do_evaluate
    results = multi_gpu_test(
  File "/home/s2/Documents/segmentation/mmsegmentation/mmseg/apis/test.py", line 232, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/engine/test.py", line 148, in collect_results_cpu
    part_result = mmcv.load(part_file)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/fileio/io.py", line 67, in load
    with BytesIO(file_client.get(file)) as f:
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 1014, in get
    return self.client.get(filepath)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 535, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/s2/Documents/segmentation/mmsegmentation/work_dirs/segformer_mit-b5_512x512_160k_es/.eval_hook/part_2.pkl'
Killing subprocess 116456
Killing subprocess 116457
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/s2/.virtualenvs/mmlab/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/segformer/segformer_mit-b5_512x512_160k_es.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Comment by xiexinch** [comment]
Hi @majnas
Sorry for the late reply.
Would you check the master node could access the files in the slave node's storage?

**Comment by majnas** [comment]
> 

Thanks for reply. How can I check? 
on master machine I get error for this line
```shell
File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 535, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/s2/Documents/segmentation/mmsegmentation/work_dirs/segformer_mit-b5_512x512_160k_es/.eval_hook/part_2.pkl'
```
which the File '/home/s2/Documents/segmentation/mmsegmentation/work_dirs/segformer_mit-b5_512x512_160k_es/.eval_hook/part_2.pkl' is on slave machine and the address is correct.

Note:  both codes on same address on both machine
master $HOME = /home/s2
slave $HONE = /home/s2

Also I have commented the evaluation line "evaluation = dict(interval=4000, metric='mIoU')" in config file, but it happens again when saving the checkpoint in 16000 iteration.

**Comment by majnas** [comment]
Also I have changed the mmsegmentation path on master machine and get same erroer

mmsegmentation path on master:  '/home/s2/Documents/segmentations1/mmsegmentation"
mmsegmentation path on slave:  '/home/s2/Documents/segmentation/mmsegmentation"


```shell
y: 39312, decode.loss_ce: 2.3779, decode.acc_seg: 47.5218, loss: 2.3779
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 392/390, 7.6 task/s, elapsed: 51s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 231, in main
    train_segmentor(
  File "/home/s2/Documents/segmentations1/mmsegmentation/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 138, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 68, in train
    self.call_hook('after_train_iter')
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 262, in after_train_iter
    self._do_evaluate(runner)
  File "/home/s2/Documents/segmentations1/mmsegmentation/mmseg/core/evaluation/eval_hooks.py", line 113, in _do_evaluate
    results = multi_gpu_test(
  File "/home/s2/Documents/segmentations1/mmsegmentation/mmseg/apis/test.py", line 232, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/engine/test.py", line 148, in collect_results_cpu
    part_result = mmcv.load(part_file)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/fileio/io.py", line 67, in load
    with BytesIO(file_client.get(file)) as f:
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 1014, in get
    return self.client.get(filepath)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 535, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/s2/Documents/segmentations1/mmsegmentation/work_dirs/segformer_mit-b5_512x512_160k_es/.eval_hook/part_2.pkl'
Killing subprocess 217323
Killing subprocess 217324
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/s2/.virtualenvs/mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/s2/.virtualenvs/mmlab/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/segformer/segformer_mit-b5_512x512_160k_es.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

```

please help me

**Comment by xiexinch** [comment]
Does your two machine share the same storage? The default file client is `disk`, that requires different machines share a single disk or the same file system. 
https://github.com/open-mmlab/mmcv/blob/d71d067da19d71d79e7b4d7ae967891c7bb00c05/mmcv/fileio/file_client.py#L787

If possible, might try to install a DFS or any other file clients supported by `mmcv`, then the two machine may share a same storage.
And you might modify the file client at the schedule config:
https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/configs/_base_/schedules/schedule_80k.py#L9

Ref https://github.com/open-mmlab/mmcv/blob/2708fac6c5ec017d384a4f41fa74d91c9e79b47d/mmcv/runner/hooks/evaluation.py#L63

**Comment by majnas** [comment]
> Does your two machine share the same storage? The default file client is `disk`, that requires different machines share a single disk or the same file system. https://github.com/open-mmlab/mmcv/blob/d71d067da19d71d79e7b4d7ae967891c7bb00c05/mmcv/fileio/file_client.py#L787
> 
> If possible, might try to install a DFS or any other file clients supported by `mmcv`, then the two machine may share a same storage. And you might modify the file client at the schedule config:
> 
> https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/configs/_base_/schedules/schedule_80k.py#L9
> 
> Ref https://github.com/open-mmlab/mmcv/blob/2708fac6c5ec017d384a4f41fa74d91c9e79b47d/mmcv/runner/hooks/evaluation.py#L63

I have copied the dataset and mmsegmentation repository on both machine, so they have the same structure, am i right?

**Comment by xiexinch** [comment]
I think the key problem is that the `work_dirs` is not on the same machine. Also they have the same structure, Machine A cannot read files saved at Machine B.

Or you may try to set `gpu_collect=True`
https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/apis/test.py#L143

**Comment by majnas** [comment]
gpu_collect=True does not work,  I have tested it before.
setting same address for workdir solved the problem :smile: :smile: :smile: :rose: :rose: 

master:
NNODES=2 NODE_RANK=0 PORT=$MASTER_PORT MASTER_ADDR=$MASTER_ADDR tools/dist_train.sh configs/segformer/segformer_mit-b5_512x512_160k_es.py 2 --work-dir /path/to/shared/folder

slave:
NNODES=2 NODE_RANK=1 PORT=$MASTER_PORT MASTER_ADDR=$MASTER_ADDR tools/dist_train.sh configs/segformer/segformer_mit-b5_512x512_160k_es.py 2 --work-dir /path/to/shared/folder

Thank you so much :+1: :mechanical_arm:
