### ISSUE TITLE
voc test 报错问题

### ISSUE THREAD

**Issue by cm0561** [open-mmlab/mmsegmentation#1724]
voc跑测试集， 测试集真实值在官网 ，但是配置文件需要填写测试集路径，没有怎么填写呢，不填的话就会报错，很奇怪 ，求解，求指导

**Comment by MeowZheng** [comment]
I have checked the config file of voc dataset, but I found the path for the test dataset.
https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/configs/_base_/datasets/pascal_voc12.py#L44-L57

**Comment by MeowZheng** [comment]
Might check the cfg with the below code:
```
from mmcv.utils import Config

cfg = Config.fromfile('cfg_file')

print(cfg.data.test.ann_dir)
```
Besides, based on my limited knowledge, I think `Not implementedError` might occur when the function or class misses, and the path of the dataset might not the main problem. Would you mind provide the whole error log?

**Comment by cm0561** [comment]
> Might check the cfg with the below code:
> 
> ```
> from mmcv.utils import Config
> 
> cfg = Config.fromfile('cfg_file')
> 
> print(cfg.data.test.ann_dir)
> ```
> 
> Besides, based on my limited knowledge, I think `Not implementedError` might occur when the function or class misses, and the path of the dataset might not the main problem. Would you mind provide the whole error log?

The whole error code is below:
``
 warnings.warn(
[                                                  ] 0/1456, elapsed: 0s, ETA:/home/clz/.local/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "mmsegmentation/tools/test.py", line 320, in <module>
    main()
  File "mmsegmentation/tools/test.py", line 273, in main
    results = single_gpu_test(
  File "/home/clz/mmsegmentation/mmseg/apis/test.py", line 123, in single_gpu_test
    result = dataset.format_results(
  File "/home/clz/mmsegmentation/mmseg/datasets/custom.py", line 252, in format_results
    raise NotImplementedError
``

**Comment by MeowZheng** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/datasets/custom.py#L250-L252

**Comment by cm0561** [comment]
> 
So,how can i solve this problem

**Comment by MeowZheng** [comment]
might check this arg 
https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/apis/test.py#L41
or just remove these lines
https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/apis/test.py#L122-L124

**Comment by cm0561** [comment]
> might check this arg
> 
> https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/apis/test.py#L41
> 
> 
> or just remove these lines
> https://github.com/open-mmlab/mmsegmentation/blob/5c113d98ecf362d9a215fbb3016ea7e76850ed98/mmseg/apis/test.py#L122-L124

ok   thanks ,I will try right now, I think there is something wrong with the code of  voc dataset,can the official fix it!

**Comment by MeowZheng** [comment]
VOC dataset didn't support saving the predicted results, and we will support it asap, or if you have interest, could you please create a nice pr for this function, which only needs to implement `format_results` in VOC dataset.
