### ISSUE TITLE
Is there a way to change mmsegmentation cache dir?

### ISSUE THREAD

**Issue by dazzle-me** [open-mmlab/mmsegmentation#1734]
When I'm trying to load pre-trained model I get the following error
```
2022-07-02 13:10:49,362 - mmseg - INFO - initialize HRNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'open-mmlab://msra/hrnetv2_w18'}
2022-07-02 13:10:49,362 - mmcv - INFO - load model from: open-mmlab://msra/hrnetv2_w18
2022-07-02 13:10:49,362 - mmcv - INFO - load checkpoint from openmmlab path: open-mmlab://msra/hrnetv2_w18
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 202, in main
    model.init_weights()
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 636, in initialize
    _initialize(module, cp_cfg)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 539, in _initialize
    func(module)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 509, in __call__
    load_checkpoint(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 617, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 552, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 299, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 501, in load_from_openmmlab
    checkpoint = load_from_http(model_url, map_location=map_location)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 342, in load_from_http
    checkpoint = load_url(
  File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 571, in load_state_dict_from_url
    os.makedirs(model_dir)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
```
Usually, there is some environment variable which tells library to save cache to some directory, for example, in timm library it is "TORCH_HOME".

Is there a way to change a directory to which mmseg saves pre-trained models?

**Comment by xiexinch** [comment]
Hi @dazzle-me, sorry for the late reply.
`TORCH_HOME` works to MMSegmentation.
It's a system environment variable used by PyTorch.
https://pytorch.org/docs/stable/hub.html#where-are-my-downloaded-models-saved

**Comment by dazzle-me** [comment]
Thank you, I didn't expect it to be TORCH_HOME, but I just tried setting TORCH_HOME to the allowed directory and it worked out.
