### ISSUE TITLE
KeyError: 'EncoderDecoder: \'`cfg` or `default_args` must contain the key "type", but got {\\\'num_classes\\\': 171}\\nNone\''

### ISSUE THREAD

**Issue by tjdgus6255** [open-mmlab/mmsegmentation#1739]
Hello.

I run the command " python demo/webcam_demo.py configs/bisenetv1/bisenetv1_r18-d32_in1k-pre_lr5e-3_4x4_512x512_160k_coco-stuff164k.py checkpoint/bisenetv1_r18-d32_in1k-pre_lr5e-3_4x4_512x512_160k_coco-stuff164k_20211023_013100-f700dbf7.pth --device cuda:0 --palette cocostuff --camera-id 0 --show "

And  I got an error message like " KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'num_classes\': 171}\nNone'  "

I don't know what it means..

**Comment by MeowZheng** [comment]
If you don't mind, would you like to provide the full error log?

**Comment by tjdgus6255** [comment]
/home/unstruct/anaconda3/envs/openmmlab/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/home/unstruct/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
Traceback (most recent call last):
  File "/home/unstruct/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/unstruct/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 40, in __init__
    self._init_auxiliary_head(auxiliary_head)
  File "/home/unstruct/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 59, in _init_auxiliary_head
    self.auxiliary_head.append(builder.build_head(head_cfg))
  File "/home/unstruct/mmsegmentation/mmseg/models/builder.py", line 30, in build_head
    return HEADS.build(cfg)
  File "/home/unstruct/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/unstruct/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/unstruct/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 41, in build_from_cfg
    raise KeyError(
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'num_classes\': 171}\nNone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/video_demo.py", line 229, in <module>
    main()
  File "demo/video_demo.py", line 172, in main
    model = init_segmentor(args.config, args.checkpoint, device=args.device)
  File "/home/unstruct/mmsegmentation/mmseg/apis/inference.py", line 32, in init_segmentor
    model = build_segmentor(config.model, test_cfg=config.get('test_cfg'))
  File "/home/unstruct/mmsegmentation/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/home/unstruct/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/unstruct/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/unstruct/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'EncoderDecoder: \'`cfg` or `default_args` must contain the key "type", but got {\\\'num_classes\\\': 171}\\nNone\''

**Comment by tjdgus6255** [comment]
It is executed without any problems when using other algorithms. (ex. pspnet, twins, deeplabv3)

I tried all algorithms of bisenetv1(pretrained) and got same error message.
