### ISSUE TITLE
Using inference_segmentor(model, img) with receiving KeyError: 'pad_shape'

### ISSUE THREAD

**Issue by MIMIWAWA** [open-mmlab/mmsegmentation#1762]
Thank you for your marvelous work!

**Describe the bug**
Using inference_segmentor(model, img) with receiving KeyError: 'pad_shape'

python test_images_outputs.py

Error traceback:
```
mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: 
tiny_fp16_512x512_160k_ade20k/epoch_300.pth
Traceback (most recent call last):
  File "test_images_outputs.py", line 17, in <module>
    result = inference_segmentor(model, img)
  File "mmsegmentation/mmseg/apis/inference.py", line 88, in inference_segmentor
    data = test_pipeline(data)
  File "mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "mmsegmentation/mmseg/datasets/pipelines/test_time_aug.py", line 128, in __call__
    data = self.transforms(_results)
  File "mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "mmsegmentation/mmseg/datasets/pipelines/formatting.py", line 281, in __call__
    img_meta[key] = results[key]
KeyError: 'pad_shape'
```
**Reproduction**
1. What command or script did you run?

python test_images_outputs.py

My python codes:
```
from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
from mmseg.core.evaluation import get_palette

config_file = "configs/convnext/tiny_fp16_512x512_160k_ade20k.py"
checkpoint_file = "work_dirs/tiny_fp16_512x512_160k_ade20k/epoch_300.pth"

model = init_segmentor(config_file, checkpoint_file, device='cuda:0')
img = '358.tif'

result = inference_segmentor(model, img)

show_result_pyplot(model, img, result, get_palette('classA'))
```
3. Did you make any modifications on the code or config? Did you understand what you have modified?

I have tried to fix this issue with this workaround:
https://github.com/open-mmlab/mmsegmentation/issues/1742#issuecomment-1176238219

None of the scripts above is working.

4. What dataset did you use?
custom dataset:
images: .tif
annotations: .png

**Environment**
1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.

sys.platform: linux
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA A100-SXM4-40GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.2, V11.2.67
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.8.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0+cu111
OpenCV: 4.5.5
MMCV: 1.6.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.2
MMSegmentation: 0.26.0+891448f

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
     Follow official instructions and ConvNext official instrctions

**Error traceback**
```
mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: 
tiny_fp16_512x512_160k_ade20k/epoch_300.pth
Traceback (most recent call last):
  File "test_images_outputs.py", line 17, in <module>
    result = inference_segmentor(model, img)
  File "mmsegmentation/mmseg/apis/inference.py", line 88, in inference_segmentor
    data = test_pipeline(data)
  File "mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "mmsegmentation/mmseg/datasets/pipelines/test_time_aug.py", line 128, in __call__
    data = self.transforms(_results)
  File "mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "mmsegmentation/mmseg/datasets/pipelines/formatting.py", line 281, in __call__
    img_meta[key] = results[key]
KeyError: 'pad_shape'
```
**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by MeowZheng** [comment]
you might try to remove `'pad_shape'` in `meta_keys` default value.
https://github.com/open-mmlab/mmsegmentation/blob/fe16402251bbd80092f482c23857e4c6a8694320/mmseg/datasets/pipelines/formatting.py#L259-L261

**Comment by MeowZheng** [comment]
The config file `configs/convnext/tiny_fp16_512x512_160k_ade20k.py` might be different from config file in MMSeg.

Would you mind sharing with us the cfg you used, or try to use CovnNeXt cfg in MMSeg

**Comment by MIMIWAWA** [comment]
After applying the original config file, there is no error, and it works like a charm.
Thank you very much~

**Comment by baristahell** [comment]
Hey @MeowZheng 

I'm encountering the same issue with a model I trained myself. I load the config and the model both from the same directory so everything lets me think the config and pth match perfectly. The segmentor is initialized using init_segmentor and it seems to work.

Yet I run into this issue where Collect tries to copy the keys from results to `img_meta` in `formatting.py`, but results is a dict with keys `['img', 'filename', 'ori_filename', 'img_shape', 'ori_shape', 'scale', 'flip', 'flip_direction', 'img_norm_cfg']` and there are some missing keys (`pad_shape` and `scale_factor`) which make the pipeline fail.

Is this because I haven't used padding in the test pipeline? My test pipeline is the following:
```
pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(256, 256),
                flip=False,
                transforms=[
                    dict(
                        type='Normalize',
                        mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
```

I managed to make it work when I added the following padding and rescale to the transforms, which are those I used in the training. So I guess the model's looking to match the train and test augmentations?

```
dict(type='Pad', size=(256, 256), pad_val=0, seg_pad_val=255),
dict(type='Resize', img_scale=(256, 256)),
```
