### ISSUE TITLE
How to train models on single machine with multiple GPUs?

### ISSUE THREAD

**Issue by Aspirinkb** [open-mmlab/mmsegmentation#1821]
What is the correct way to train a model on single machine with multiple GPUs? For example I have 8 GPUs on my machine, should I use `tools/dist_train.sh` or some other script??? I tried use `tools/dist_train.sh` but failed, so I run 
```
python -m torch.distributed.launch \
--nnodes=1 \
--node_rank=0 \
--master_addr="127.0.0.1" \
--nproc_per_node=4 \
--master_port=29500 \
tools/train.py \
--launcher pytorch \
--gpus 4 \
--work_dir work_dirs \
./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py
```
as the tips It only support dingle GPU mode...
So what is the correct way to use multiple GPUs on single machine to train a model?

**Comment by MengzhangLI** [comment]
Could you try to use `CUDA_VISIBLE_DEVICES=0,1 python tools/train.py ./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py --work_dir work_dirs ` in your environment?

**Comment by Aspirinkb** [comment]
> Could you try to use `CUDA_VISIBLE_DEVICES=0,1 python tools/train.py ./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py --work_dir work_dirs ` in your environment?

I set `CUDA_VISIBLE_DEVICES=0,1,2,3` for the first four V100 GPUs, and run the above command. There is a CUDA OOM Error as followed at the very beginning of the train, **even set only one image for per GPU**:
```
...
2022-07-25 23:59:08,708 - mmseg - INFO - workflow: [('train', 1)], max: 160000 iters
2022-07-25 23:59:08,708 - mmseg - INFO - Checkpoints will be saved to /general-user/frank/spot/mmsegmentation/work_dirs by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 231, in main
    train_segmentor(
  File "/general-user/frank/spot/mmsegmentation/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/segmentors/base.py", line 138, in train_step
    losses = self(**data_batch)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/segmentors/base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 139, in forward_train
    x = self.extract_feat(img)
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 65, in extract_feat
    x = self.backbone(img)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/backbones/swin.py", line 747, in forward
    x, hw_shape, out, out_hw_shape = stage(x, hw_shape)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/backbones/swin.py", line 456, in forward
    x = block(x, hw_shape)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/backbones/swin.py", line 375, in forward
    x = _inner_forward(x)
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/backbones/swin.py", line 362, in _inner_forward
    x = self.attn(x, hw_shape)
  File "/general-user/frank/spot/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/general-user/frank/spot/mmsegmentation/mmseg/models/backbones/swin.py", line 194, in forward
    shifted_query = torch.roll(
RuntimeError: CUDA out of memory. Tried to allocate 1.13 GiB (GPU 0; 31.75 GiB total capacity; 25.54 GiB already allocated; 407.81 MiB free; 26.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Aspirinkb** [comment]
@MengzhangLI Hi, is there a formal tutorial of how to use mmseg to train models on single machine with multiple GPUs? Maybe [使用多卡GPU训练](https://mmsegmentation.readthedocs.io/zh_CN/latest/train.html#id3) is too old to use?

**Comment by MengzhangLI** [comment]
> @MengzhangLI Hi, is there a formal tutorial of how to use mmseg to train models on single machine with multiple GPUs? Maybe [使用多卡GPU训练](https://mmsegmentation.readthedocs.io/zh_CN/latest/train.html#id3) is too old to use?

Perhaps it needs to be updated but it is indeed tutorial we recommand to new beginner. 

As for your error, it is wired because swin tiny could be handled in V100 and your error log `Tried to allocate 1.13 GiB (GPU 0; 31.75 GiB total capacity; 25.54 GiB already allocated; 407.81 MiB free; 26.66 GiB reserved in total by PyTorch)` shows it has already used too much GPU memory. Does it also used for other task?

I suggest you try to train several related small model first on 4 GPUs first, such as https://github.com/open-mmlab/mmsegmentation/blob/master/configs/pspnet/pspnet_r50-d8_512x512_80k_ade20k.py, we would get to know what's going on.

Best,

**Comment by Aspirinkb** [comment]
I change the run command as followed, to use 4 GPUs on the host machine by running 4 processes:   
RANK 0:
```
export CUDA_VISIBLE_DEVICES=2,3,4,5
export MASTER_PORT=29500
export MASTER_ADDR="127.0.0.1"
export WORLD_SIZE=4
export RANK=0

python tools/train.py \
--launcher pytorch \
./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py
```   
RANK 1:     
```
export CUDA_VISIBLE_DEVICES=2,3,4,5
export MASTER_PORT=29500
export MASTER_ADDR="127.0.0.1"
export WORLD_SIZE=4
export RANK=1

python tools/train.py \
--launcher pytorch \
./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py
```   
RANK 2:   
```
export CUDA_VISIBLE_DEVICES=2,3,4,5
export MASTER_PORT=29500
export MASTER_ADDR="127.0.0.1"
export WORLD_SIZE=4
export RANK=2

python tools/train.py \
--launcher pytorch \
./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py
```   
RANK 3:
```
export CUDA_VISIBLE_DEVICES=2,3,4,5
export MASTER_PORT=29500
export MASTER_ADDR="127.0.0.1"
export WORLD_SIZE=4
export RANK=3

python tools/train.py \
--launcher pytorch \
./configs/swin_spot/upernet_swin_tiny_patch4_window7_512x512_160k_spot_pretrain_224x224_1K.py
```
**But it failed too. I have some observations:**
1. the RANK 0 still use CUDA:0, the `CUDA_VISIBLE_DEVICES=2,3,4,5` does not work.
2. the RANK 0 pauses at the 1st step waiting for the other training processes.
3. the Rank 1 2 and 3 processes fail to training, error as follows:   
RANK 1:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper__cudnn_convolution)
```
RANK 2:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:2! (when checking argument for argument weight in method wrapper__cudnn_convolution)
```
RANK 3:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3! (when checking argument for argument weight in method wrapper__cudnn_convolution)
```

**Comment by MengzhangLI** [comment]
Sorry for late reply. Did you solve your error? From latest error I think these errors happen earlier than your first GPU memory error. We would better fix GPU memory error first. 


Could you try to change another config:
```
python -m torch.distributed.launch \
--nnodes=1 \
--node_rank=0 \
--master_addr="127.0.0.1" \
--nproc_per_node=4 \
--master_port=29500 \
tools/train.py \
--launcher pytorch \
--gpus 4 \
--work_dir work_dirs \
.configs/pspnet/pspnet_r50-d8_512x512_80k_ade20k.py
```

BTW, from your command I guess you use slurm?

**Comment by Aspirinkb** [comment]
The following command works:
```
export LOCAL_RANK=0
export RANK=0
export CUDA_VISIBLE_DEVICES=4,5,6,7
export MASTER_PORT=29500
export MASTER_ADDR="127.0.0.1"
export WORLD_SIZE=4
python -m torch.distributed.launch \
--nproc_per_node=4 \
tools/train.py \
--launcher pytorch \
./configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_pretrain_224x224_1K.py
```
