### ISSUE TITLE
DLL load failed: 找不到指定的程序。

### ISSUE THREAD

**Issue by endaoguansanlu** [open-mmlab/mmsegmentation#1826]
D:\Python\lib\site-packages\mmcv\cnn\bricks\transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "e:/MyModel/train.py", line 13, in <module>
    from mmsegmentation.mmseg.apis import set_random_seed, train_segmentor
  File "e:\MyModel\mmsegmentation\mmseg\apis\__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
    from .decode_head import BaseDecodeHead
  File "e:\mymodel\mmsegmentation\mmseg\models\decode_heads\decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "e:\mymodel\mmsegmentation\mmseg\models\losses\__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "e:\mymodel\mmsegmentation\mmseg\models\losses\focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "D:\Python\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\Python\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "D:\Python\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的程序。

I have this problem when I use mmsegmentation, do you know why, thanks！！

**Comment by xiexinch** [comment]
Hi @endaoguansanlu,
It seems that mmcv-full is not properly installed, you could try to reinstall mmcv-full with the following command.
```shell
pip uninstall mmcv
pip install openmim
mim install mmcv-full
```

**Comment by endaoguansanlu** [comment]
> Hi @endaoguansanlu, It seems that mmcv-full is not properly installed, you could try to reinstall mmcv-full with the following command.
> 
> ```shell
> pip uninstall mmcv
> pip install openmim
> mim install mmcv-full
> ```

Thank you very much for your selfless help. Currently this problem has been solved, but I have this problem when importing build_segmentor, do you know how to solve it? thank you very much！！！
Traceback (most recent call last):
  File "e:/MyModel/train.py", line 15, in <module>
    from mmsegmentation.mmseg.models import build_segmentor
  File "e:\MyModel\mmsegmentation\mmseg\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "e:\MyModel\mmsegmentation\mmseg\models\backbones\__init__.py", line 2, in <module>
    from .beit import BEiT
  File "e:\MyModel\mmsegmentation\mmseg\models\backbones\beit.py", line 17, in <module>
    from ..builder import BACKBONES
  File "e:\MyModel\mmsegmentation\mmseg\models\builder.py", line 8, in <module>
    MODELS = Registry('models', parent=MMCV_MODELS)
  File "D:\Python\lib\site-packages\mmcv\utils\registry.py", line 127, in __init__
    parent._add_children(self)
  File "D:\Python\lib\site-packages\mmcv\utils\registry.py", line 254, in _add_children
    f'scope {registry.scope} exists in {self.name} registry'
AssertionError: scope mmseg exists in model registry

**Comment by xiexinch** [comment]
Could you show the codes you modified if possible? The scope is usually registered only once.

**Comment by MengzhangLI** [comment]
Another potential reason: Sometimes this error happens when certain libaries installation are not complete, or certain libaries are overlapped or destroyed thus they can not be imported and program does not know corresponding libaries.

Potential solution:

First
```shell
pip uninstall Pillow
```

And then 

```shell
pip install Pillow
```
