### ISSUE TITLE
AssertionError: ADE20KDataset: MultiScaleFlipAug: 

### ISSUE THREAD

**Issue by cm0561** [open-mmlab/mmsegmentation#1846]
When i perform the test,it's all ok ,But when i perform the test with MuitiScaleFlipAug,it will have an error:AssertionError: ADE20KDataset: MultiScaleFlipAug: 

The normal cfg of test:

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 1024),
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),

 
The MultiScaleFlipAug test of cfg:

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 1024),
        img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=True,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])

And  the full error report is :

File "/home/anaconda3/envs/ccc/lib/python3.9/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/admin/clz/mmsegmentation/mmseg/datasets/pipelines/test_time_aug.py", line 72, in __init__
    assert mmcv.is_list_of(img_ratios, float)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/ccc/lib/python3.9/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/admin/clz/mmsegmentation/mmseg/datasets/ade.py", line 87, in __init__
    super(ADE20KDataset, self).__init__(
  File "/home/admin/clz/mmsegmentation/mmseg/datasets/custom.py", line 95, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/admin/clz/mmsegmentation/mmseg/datasets/pipelines/compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/anaconda3/envs/ccc/lib/python3.9/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: MultiScaleFlipAug:

**Comment by xiexinch** [comment]
Hi @cm0561,
Could you provide the model and the command you used if possible? I can't reproduce this error.

**Comment by Aspirinkb** [comment]
From your error trace, I see `assert mmcv.is_list_of(img_ratios, float)`. Maybe the `img_ratios` is not a list of floating numbers. Check it or remove `img_ratios` from your config file.
