### ISSUE TITLE
loss_decode=dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4))

### ISSUE THREAD

**Issue by cunese24** [open-mmlab/mmsegmentation#1906]
why can not i replace the loss_decode?
loss_decode=[dict(type='CrossEntropyLoss',loss_weight=1.0),dict(type='DiceLoss', loss_weight=3.0)],#####
replace
loss_decode=dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)) , ##############
##########
failed，it reported that：
Traceback (most recent call last):
  File "/home/intern_01/anaconda3/envs/mmseg/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/home/intern_01/anaconda3/envs/mmseg/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9d0jcn7i/tmpvl3wjqqm.py'

**Comment by MeowZheng** [comment]
There might be syntax error in your config file, and I just suggest you try to use syntax checking in your IDE.
