### ISSUE TITLE
How to deal with this error: in __call__     img_meta[key] = results[key] KeyError: 'flip'?

### ISSUE THREAD

**Issue by cheul0518** [open-mmlab/mmsegmentation#1938]
I tried to train my custom dataset in Colab using Segformer, and encountered an error called 'flip'. I tried to figure out what caused this issue but I still have no idea. Please help me to handle the issue. Here is a snippet of my code: 
```
import mmcv
from mmseg.datasets import build_dataset
from mmseg.models import build_segmentor
from mmseg.apis import train_segmentor

# Build the dataset
datasets = [build_dataset(cfg.data.train)]

# Build the detector
model = build_segmentor(cfg.model)#, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_segmentor(model, datasets, cfg, distributed=False, validate=True, meta=dict())
```
And here is the output (error):
```
2022-08-19 06:46:48,009 - mmseg - INFO - workflow: [('train', 1)], max: 100 iters
2022-08-19 06:46:48,011 - mmseg - INFO - Checkpoints will be saved to /content/mmsegmentation/work_dirs/tutorial by HardDiskBackend.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-17-877d2f2b4a9b>](https://localhost:8080/#) in <module>
     14 # Create work_dir
     15 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 16 train_segmentor(model, datasets, cfg, distributed=False, validate=True, meta=dict())

7 frames
[/usr/local/lib/python3.7/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    459             # instantiate since we don't know how to
    460             raise RuntimeError(msg) from None
--> 461         raise exception
    462 
    463 

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmsegmentation/mmseg/datasets/custom.py", line 215, in __getitem__
    return self.prepare_train_img(idx)
  File "/content/mmsegmentation/mmseg/datasets/custom.py", line 232, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/content/mmsegmentation/mmseg/datasets/pipelines/formatting.py", line 281, in __call__
    img_meta[key] = results[key]
KeyError: 'flip'
```
Here are test_pipeline and data.val
```
cfg.test_pipeline = [dict(type='LoadImageFromFile'),
                     dict(type='MultiScaleFlipAug',
                            img_scale=(768, 768),
                            flip=False,
                            transforms=[dict(type='Normalize', **cfg.img_norm_cfg),
                                        dict(type='ImageToTensor', keys=['img']),
                                        dict(type='Collect', keys=['img']),]
                          )
                    ]

cfg.data.val.type= cfg.dataset_type
cfg.data.val.data_root = cfg.data_root
cfg.data.val.img_dir = img_dir
cfg.data.val.ann_dir = ann_dir
cfg.data.val.pipeline = cfg.test_pipeline
cfg.data.val.split = 'splits/valid_1.txt'
```
Please enlighten me.

**Comment by cheul0518** [comment]
The issue's gone when I modified train_pipeline from:
```
cfg.train_pipeline = [dict(type='LoadImageFromFile'),
                      dict(type='LoadAnnotations'),
                      dict(type='DefaultFormatBundle'),
                      dict(type='Collect', keys=['img', 'gt_semantic_seg']),
                     ]
```
to 
```
cfg.train_pipeline = [dict(type='LoadImageFromFile'),
                      dict(type='LoadAnnotations'),
                      dict(type='Resize', img_scale=(256, 256), ratio_range=(0.5, 2.0)),
                      dict(type='RandomCrop', crop_size=cfg.crop_size, cat_max_ratio=0.75),
                      dict(type='RandomFlip', flip_ratio=0.5),
                      dict(type='PhotoMetricDistortion'),
                      dict(type='Normalize', **cfg.img_norm_cfg),
                      dict(type='Pad', size=cfg.crop_size, pad_val=0, seg_pad_val=255),
                      dict(type='DefaultFormatBundle'),
                      dict(type='Collect', keys=['img', 'gt_semantic_seg']),
                     ]
```
Is the issue caused by multiscaleflipaug? And multiscaleflipaug won't properly work without augmentation in train_pipeline? I'll do more test and keep you updated.

**Comment by xiexinch** [comment]
Hi @cheul0518,
You should modify the `meta_keys` parameter of `Collect` method. #1753

**Comment by cheul0518** [comment]
@xiexinch  Thank you so much!

**Comment by cheul0518** [comment]
@xiexinch  Thank you so much!
