### ISSUE TITLE
An unresolvable error occurred:(unicode error) 'unicodeescape' codec can't decode bytes in position 2-3

### ISSUE THREAD

**Issue by Frankxiongxiong** [open-mmlab/mmsegmentation#1961]
An unresolvable error occurred:
2022-08-23 23:20:07,640 - mmseg - INFO - Environment info:
------------------------------------------------------------
sys.platform: win32
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1050 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30146 版
GCC: n/a
PyTorch: 1.8.0+cu101
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.4, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.9.0+cu101
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 10.1
MMSegmentation: 0.26.0+0e37281
------------------------------------------------------------

2022-08-23 23:20:07,640 - mmseg - INFO - Distributed training: False
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\yapf\yapflib\verifier.py", line 43, in VerifyCode
    compile(textwrap.dedent(code).encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 11
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\yapf\yapflib\verifier.py", line 46, in VerifyCode
    ast.parse(textwrap.dedent(code.lstrip('\n')).lstrip(), '<string>', 'exec')
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<string>", line 10
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\yapf\yapflib\verifier.py", line 50, in VerifyCode
    compile(normalized_code.encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 10
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Admin/mmsegmentation/mmsegmentation-0.20.2/tools/train.py", line 210, in <module>
    main()
  File "C:/Users/Admin/mmsegmentation/mmsegmentation-0.20.2/tools/train.py", line 154, in main
    print('cfg.pretty_text',cfg.pretty_text)
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\utils\config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\yapf\yapflib\yapf_api.py", line 188, in FormatCode
    reformatted_source = FormatTree(
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\yapf\yapflib\yapf_api.py", line 151, in FormatTree
    return reformatter.Reformat(_SplitSemicolons(llines), verify, lines)
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\yapf\yapflib\reformatter.py", line 105, in Reformat
    return _FormatFinalLines(final_lines, verify)
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\yapf\yapflib\reformatter.py", line 413, in _FormatFinalLines
    verifier.VerifyCode(formatted_code[-1])
  File "C:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\yapf\yapflib\verifier.py", line 52, in VerifyCode
    raise InternalError(sys.exc_info()[1])
yapf.yapflib.verifier.InternalError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<string>, line 10)

C:\ProgramData\Anaconda3\envs\mmsegmentation\python.exe C:/Users/Administrator/mmsegmentation-0.20.2/mmsegmentation-0.20.2/tools/train.py C:\\Users\\Administrator\\mmsegmentation-0.20.2\\mmsegmentation-0.20.2\\configs\\deeplabv3plus\\my_deeplabv3plus_r50-d8_480x480_40k_pascal_context.py
'tail' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
2022-08-24 14:27:09,169 - mmseg - INFO - Environment info:
------------------------------------------------------------
sys.platform: win32
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
NVCC: Not Available
GCC: n/a
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0+cu113
OpenCV: 4.6.0
MMCV: 1.4.7
MMCV Compiler: MSVC 192930140
MMCV CUDA Compiler: 11.3
MMSegmentation: 0.20.2+unknown
------------------------------------------------------------

2022-08-24 14:27:09,169 - mmseg - INFO - Distributed training: False
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\yapf\yapflib\verifier.py", line 43, in VerifyCode
    compile(textwrap.dedent(code).encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 2
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\yapf\yapflib\verifier.py", line 46, in VerifyCode
    ast.parse(textwrap.dedent(code.lstrip('\n')).lstrip(), '<string>', 'exec')
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\yapf\yapflib\verifier.py", line 50, in VerifyCode
    compile(normalized_code.encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/mmsegmentation-0.20.2/mmsegmentation-0.20.2/tools/train.py", line 210, in <module>
    main()
  File "C:/Users/Administrator/mmsegmentation-0.20.2/mmsegmentation-0.20.2/tools/train.py", line 154, in main
    print('cfg.pretty_text',cfg.pretty_text)
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\mmcv\utils\config.py", line 499, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\yapf\yapflib\yapf_api.py", line 188, in FormatCode
    reformatted_source = FormatTree(
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\yapf\yapflib\yapf_api.py", line 151, in FormatTree
    return reformatter.Reformat(_SplitSemicolons(llines), verify, lines)
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\yapf\yapflib\reformatter.py", line 105, in Reformat
    return _FormatFinalLines(final_lines, verify)
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\yapf\yapflib\reformatter.py", line 413, in _FormatFinalLines
    verifier.VerifyCode(formatted_code[-1])
  File "C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\yapf\yapflib\verifier.py", line 52, in VerifyCode
    raise InternalError(sys.exc_info()[1])
yapf.yapflib.verifier.InternalError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<string>, line 1)

**Comment by xiexinch** [comment]
Hi @Frankxiongxiong,
It's similar to this issue #1914.

**Comment by xiexinch** [comment]
Hi @Frankxiongxiong,
Could you try the solution provided by mmcv? open-mmlab/mmcv#2185
