### ISSUE TITLE
Error on mAP evaluation with mae as segformer backbone

### ISSUE THREAD

**Issue by WangZan0899** [open-mmlab/mmsegmentation#1972]
I replaced the backbone network of the segformer with the MAE model, and after iterating 16,000 iters, I performed the mAP evaluation. The following error occurred. Is there a problem with the backbone network model?

###################################################################################
load checkpoint from local path: work_dirs/segformer_mae-vit_512x512_160k_loveda/iter_16000.pth
tools/test.py:264: UserWarning: SyncBN is only supported with DDP. To be compatible with DP, we convert SyncBN to BN. Please use dist_train.sh which can avoid this error.
  warnings.warn(
[                                                  ] 0/1669, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 320, in <module>
    main()
  File "tools/test.py", line 273, in main
    results = single_gpu_test(
  File "/root/autodl-tmp/mmsegmentation/mmseg/apis/test.py", line 91, in single_gpu_test
    result = model(return_loss=False, **data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/root/autodl-tmp/mmsegmentation/mmseg/models/segmentors/base.py", line 110, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/root/autodl-tmp/mmsegmentation/mmseg/models/segmentors/base.py", line 92, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/root/autodl-tmp/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 262, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/root/autodl-tmp/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 247, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "/root/autodl-tmp/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 206, in whole_inference
    seg_logit = self.encode_decode(img, img_meta)
  File "/root/autodl-tmp/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 73, in encode_decode
    x = self.extract_feat(img)
  File "/root/autodl-tmp/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 65, in extract_feat
    x = self.backbone(img)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/mmsegmentation/mmseg/models/backbones/mae.py", line 246, in forward
    x = x + self.pos_embed
RuntimeError: The size of tensor a (4097) must match the size of tensor b (1025) at non-singleton dimension 1
root@container-cab011ade2-0f027d72:~/autodl-tmp/mmsegmentation#

**Comment by MeowZheng** [comment]
mAP is not supported in mmseg

**Comment by WangZan0899** [comment]
> mAP is not supported in mmseg

Sorry for my typo, I wanted to say mIoU

**Comment by MengzhangLI** [comment]
> > mAP is not supported in mmseg
> 
> Sorry for my typo, I wanted to say mIoU

Sorry for late reply.
```python
self.num_patches = self.patch_shape[0] * self.patch_shape[1]
self.pos_embed = nn.Parameter(
    torch.zeros(1, self.num_patches + 1, embed_dims))
```
So could you check `self.num_patches` and `embed_dims` in your network? I checked the `beit.py`:

```python
self.window_size = (img_size[0] // patch_size,
                    img_size[1] // patch_size)
self.patch_shape = self.window_size
```
I guess it may be a potential bug because it depends on `img_size` which may be different in validation phase when each image size is different. But I am not pretty sure, maybe you can check it out and looking forward to your reply.
