### ISSUE TITLE
Ade20k dataset val/test problem

### ISSUE THREAD

**Issue by puppet-life** [open-mmlab/mmsegmentation#2041]
When using ade20k for Val, it shows that there are problems with different scales.
`RuntineError: stack expects each tensor to be equal size, but got [3，512，512] at entry 8 and [3,704,512]at entry 1`

**Comment by puppet-life** [comment]
I tried to test_ Pipeline specifies the size of resize, but it still cannot be solved. Note: the dataset is downloaded from the official website

**Comment by MeowZheng** [comment]
Would you mind providing the full-error log and following the issue template to tell us where raise this error?

**Comment by puppet-life** [comment]
> Would you mind providing the full-error log and following the issue template to tell us where raise this error?

OK, the specific error log is as follows:
`...[                                                  ] 0/2000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "train.py", line 167, in <module>
    main()
  File "train.py", line 156, in main
    train_segmentor(
  File "../mmseg/apis/train.py", line 118, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "../mmseg/core/evaluation/eval_hooks.py", line 30, in after_train_iter
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "../mmseg/apis/test.py", line 59, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 79, in collate
    return {
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 80, in <dictcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 84, in collate
    return default_collate(batch)
  File "/opt/anaconda3/envs/torch_zgq/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 141, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 512, 512] at entry 0 and [3, 683, 512] at entry 1
`

**Comment by MeowZheng** [comment]
during validation, `sample_per_gpu` must be 1, and mmseg haven't supported batch inference, as the shape of image is different. By default, mmseg set validation batch_size=1, did you modify it?

**Comment by puppet-life** [comment]
OK, let me try. I still use multi batch size when verifying
