### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'D:\\Asteria Aerospace\\projects\\solar_roof_potential\\<input>'

### ISSUE THREAD

**Issue by amarnath-asteria** [open-mmlab/mmsegmentation#2145]
Hi,
- I have been trying to use custom dataset for PSPNet r50 training. i followed the code available in [colab ](https://github.com/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb) and used 2 labels (say a and b) and converted the masks and also created the split folder. 
- I am using cpu based training and below are the system details:
- Processor	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   1.80 GHz
Installed RAM	16.0 GB (15.4 GB usable)
System type	Windows 64-bit operating system, x64-based processor

**Reproduction**

1. What command or script did you run?

```
from mmseg.datasets import build_dataset
from mmseg.models import build_segmentor
from mmseg.apis import train_segmentor

datasets = [build_dataset(cfg.data.train)]

model = build_segmentor(cfg.model)
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_segmentor(model, datasets, cfg, distributed=False, validate=True,
                meta=dict())

```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
- i modified the necessary config variable as instructed [here](https://mmsegmentation.readthedocs.io/en/latest/tutorials/config.html) namely:

4. What dataset did you use?

**Environment**

sys.platform: win32
Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
CUDA available: False
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31329 for x64
GCC: n/a
PyTorch: 1.12.1+cpu
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experime
ntal -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH
_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 
USE_ROCM=OFF,

TorchVision: 0.13.1+cpu
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: MSVC 192829924
MMCV CUDA Compiler: not available
MMSegmentation: 0.28.0+6c746fa

**Error traceback**

2022-10-06 14:49:25,313 - mmseg - INFO - workflow: [('train', 1)], max: 200 iters
2022-10-06 14:49:25,313 - mmseg - INFO - Checkpoints will be saved to D:\Asteria Aerospace\projects\solar_roof_potential\work_dirs\tutorial by HardDiskBackend.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Amarnath\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Amarnath\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Amarnath\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Amarnath\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Amarnath\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\Amarnath\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 237, in _get_code_from_file
    with io.open_code(decoded_path) as f:
OSError: [Errno 22] Invalid argument: 'D:\\Asteria Aerospace\\projects\\solar_roof_potential\\<input>'
Traceback (most recent call last):
  File "D:\Asteria Aerospace\projects\solar_roof_potential\drone_env\lib\site-packages\torch\utils\data\dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\Amarnath\AppData\Local\Programs\Python\Python39\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\Amarnath\AppData\Local\Programs\Python\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 198, in <module>
  File "d:\asteria aerospace\projects\solar_roof_potential\mmsegmentation\mmseg\apis\train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "D:\Asteria Aerospace\projects\solar_roof_potential\drone_env\lib\site-packages\mmcv\runner\iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "D:\Asteria Aerospace\projects\solar_roof_potential\drone_env\lib\site-packages\mmcv\runner\iter_based_runner.py", line 61, in train
    data_batch = next(data_loader)
  File "D:\Asteria Aerospace\projects\solar_roof_potential\drone_env\lib\site-packages\mmcv\runner\iter_based_runner.py", line 34, in __next__
    data = next(self.iter_loader)
  File "D:\Asteria Aerospace\projects\solar_roof_potential\drone_env\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "D:\Asteria Aerospace\projects\solar_roof_potential\drone_env\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "D:\Asteria Aerospace\projects\solar_roof_potential\drone_env\lib\site-packages\torch\utils\data\dataloader.py", line 1325, in _get_data
    success, data = self._try_get_data()
  File "D:\Asteria Aerospace\projects\solar_roof_potential\drone_env\lib\site-packages\torch\utils\data\dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 20240) exited unexpectedly

**Comment by MengzhangLI** [comment]
It is a common error in Windows OS which is caused by different format types of file path. Perhaps path in your dataloader contains `\`, `\\` and `/` at the same time.

You can try to modify `\\` to `/` or `\`, if still get error, just use your hand typing (not copying path) to make sure the path could be parsed by your computer.

Best,

**Comment by MengzhangLI** [comment]
> > @MengzhangLI
> 
> I have tried many ways to define the path. I made sure that the config file contains the right path for training but still i am getting the error.
> 
> OSError: [Errno 22] Invalid argument: 'D:\Asteria Aerospace\projects\solar_roof_potential'
> 
> i am sure this is the error but i am unable to track it to the origin. it is loading the images but which input is it talking about?

Sorry for late reply. 


`i am sure this is the error but i am unable to track it to the origin. it is loading the images but which input is it talking about?` Sorry I do not understand what you mean.

Could you run MMSegmentation codebase normally in your Windows OS computer? Looking forward to your reply.
