### ISSUE TITLE
run python tools/train.py on cpu get error

### ISSUE THREAD

**Issue by AnRanbel** [open-mmlab/mmsegmentation#2163]
**Hi,i run python tools/train.py config on cpu get the following error:**

Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 202, in main
    model.init_weights()
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\runner\base_module.py", line 117, in init_weights
    m.init_weights()
  File "e:\pycharmprojects\segnext\mmseg\models\backbones\mscan.py", line 238, in init_weights
    super(MSCAN, self).init_weights()
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\runner\base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 636, in initialize
    _initialize(module, cp_cfg)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 539, in _initialize
    func(module)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 514, in __call__
    logger=logger)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\runner\checkpoint.py", line 627, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\runner\checkpoint.py", line 561, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\runner\checkpoint.py", line 303, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\mmcv\runner\checkpoint.py", line 323, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\torch\serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\torch\serialization.py", line 1001, in load_tensor
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\torch\serialization.py", line 152, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "D:\ProgramFile\Anaconda3\envs\python37\lib\site-packages\torch\serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.
load with map_location=torch.device('cpu') to map your storages to the CPU.

**i find some resolution for this error,be like add torch.device('cpu'), but l don't know add this setting to where, could you please give me some guidance, thank you!**

**mmsegmentation version is 0.24.1 
mmcv-full version is 1.6.0**

**Comment by xiexinch** [comment]
Hi @AnRanbel,
You might set `map_location='cpu'` at the `init_cfg`.
An example:
```python
model=dict(
     type='EncoderDecoder',
     backbone=dict(
        ...,
        init_cfg=dict(type='pretrained', checkpoint='xxx', map_location='cpu')
     )
)
```
