### ISSUE TITLE
Training appears, argument 'input' (position 1) must be Tensor, not NoneType

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmsegmentation#2166]
2022-10-10 11:10:22,528 - mmseg - INFO - Loaded 20210 images
2022-10-10 11:10:23,983 - mmseg - INFO - Loaded 2000 images
2022-10-10 11:10:23,984 - mmseg - INFO - Start running, host: dell@dell-Precision-7920-Tower, work_dir: /home/dell/bag-torch/darkpull/Paddle/mmsegmentation/work_dirs/segnext.small.512x512.voc.160k
2022-10-10 11:10:23,984 - mmseg - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) PolyLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-10-10 11:10:23,984 - mmseg - INFO - workflow: [('train', 1)], max: 80000 iters
2022-10-10 11:10:23,984 - mmseg - INFO - Checkpoints will be saved to /home/dell/bag-torch/darkpull/Paddle/mmsegmentation/work_dirs/segnext.small.512x512.voc.160k by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 231, in main
    train_segmentor(
  File "/home/dell/bag-torch/darkpull/Paddle/mmsegmentation/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/dell/bag-torch/darkpull/Paddle/mmsegmentation/mmseg/models/segmentors/base.py", line 138, in train_step
    losses = self(**data_batch)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/mmsegmentation/mmseg/models/segmentors/base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 140, in forward_train
    x = self.extract_feat(img)
  File "/home/dell/bag-torch/darkpull/Paddle/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 66, in extract_feat
    x = self.backbone(img)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/mmsegmentation/mmseg/models/backbones/mscan.py", line 251, in forward
    x = blk(x, H, W)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/mmsegmentation/mmseg/models/backbones/mscan.py", line 144, in forward
    * self.mlp(self.norm2(x)))
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/mmsegmentation/mmseg/models/backbones/mscan.py", line 31, in forward
    x = self.act(x)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 669, in forward
    return F.gelu(input)
  File "/home/dell/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/functional.py", line 1555, in gelu
    return torch._C._nn.gelu(input)
TypeError: gelu(): argument 'input' (position 1) must be Tensor, not NoneType
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 10292) of binary: /home/dell/anaconda3/envs/mmlab/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_2lf3qe98/none_ev3ptsbc/attempt_1/0/error.json

**Comment by MengzhangLI** [comment]
Hi, we do not support SegNeXt yet, you can raise the issue in [SegNeXt](https://github.com/Visual-Attention-Network/SegNeXt) repo.

Best,

**Comment by chen-del** [comment]
Well, thank you, I have tuned in mmseg, and I can train normally now.

**Comment by MengzhangLI** [comment]
> Well, thank you, I have tuned in mmseg, and I can train normally now.

Cool! So what reason causes the error you mentioned before?

**Comment by chen-del** [comment]
When reproducing, the backbones structure was adjusted, and there was a deviation in the implementation of the class, which caused the data input into the backbone network to become none, that is, a null value. I made a mistake in the template definition of bankbone.
