### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'weight'

### ISSUE THREAD

**Issue by endaoguansanlu** [open-mmlab/mmsegmentation#2237]
When I use multiple loss functions, this problem occurs, but when I use only one loss function, I don't have this problem, where is the problem? Looking forward to your reply!

Traceback (most recent call last):
  File "train.py", line 166, in <module>
    main()
  File "train.py", line 162, in main
    meta=meta)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmseg/models/segmentors/base.py", line 152, in train_step
    losses = self(**data_batch)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmseg/models/segmentors/base.py", line 122, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 158, in forward_train
    gt_semantic_seg)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 102, in _decode_head_forward_train
    self.train_cfg)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmseg/models/decode_heads/decode_head.py", line 406, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmseg/models/decode_heads/decode_head.py", line 449, in losses
    ignore_index=self.ignore_index)
  File "/home/liz/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'weight'

config：
`loss_decode=[dict(type='CrossEntropyLoss', use_sigmoid=False ,loss_weight=1.0),
                        dict(type='DiceLoss', loss_weight=1.0)]),`

mmcv 1.4.2 mmseg 0.13.0 python 3.6

**Comment by MengzhangLI** [comment]
Hi, please update mmseg version.

Multiple loss feature was added into MMSegmentation in this [PR](https://github.com/open-mmlab/mmsegmentation/pull/818). If I remember well, mmseg should >=v0.18([link](https://github.com/open-mmlab/mmsegmentation/releases?page=2)).

**Comment by endaoguansanlu** [comment]
So how can I upgrade my mmseg without losing my current model configuration, looking forward to your reply!

**Comment by MengzhangLI** [comment]
> 

Just make a copy for your current config files, basically it could run smoothly because I think most part of v0.13.0 and v0.18.0 is identical.

**Comment by ChunmingLi-SJTU** [comment]
Hi, I think I found a possible solution: add `**kwargs` to the `__init__() `and `forward()` interfaces of the loss class.
![image](https://github.com/open-mmlab/mmsegmentation/assets/150920882/f97c5980-cd53-4978-ab0f-e5cb1e22ba8c)
After I jadded, the problem disappeared.

**Comment by llyyccccc** [comment]
请问您解决了吗？

**Comment by llyyccccc** [comment]
> > 
> 
> Just make a copy for your current config files, basically it could run smoothly because I think most part of v0.13.0 and v0.18.0 is identical.

我的mmsegmentation在0.18.0 还是会报错  mmcv-full==1.6.0
