### ISSUE TITLE
Binary segmentation for custom dataset issue

### ISSUE THREAD

**Issue by MABatin** [open-mmlab/mmsegmentation#2263]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

Hi, I am trying to do binary segmentation with deeplabv3_unet model. I am getting the following error for out_channel=2 in decode_head and auxiliary_head:
```none
RuntimeError: CUDA error: an illegal memory access was encountered 
```
And then the following error for out_channel=1:
```none
AssertionError: For pred with shape [N, 1, H, W], its label must have at most 2 classes
```

**Reproduction**

1. What command or script did you run?

   ```none
   python Wheat/tools/segmentor/train.py Wheat/configs/models/deeplabv3_unet_s5-d16_32x32_1k_custom.py
   ```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
My model config is as below:
```none
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained=None,
    backbone=dict(
        type='UNet',
        in_channels=3,
        base_channels=64,
        num_stages=5,
        strides=(1, 1, 1, 1, 1),
        enc_num_convs=(2, 2, 2, 2, 2),
        dec_num_convs=(2, 2, 2, 2),
        downsamples=(True, True, True, True),
        enc_dilations=(1, 1, 1, 1, 1),
        dec_dilations=(1, 1, 1, 1),
        with_cp=False,
        conv_cfg=None,
        norm_cfg=norm_cfg,
        act_cfg=dict(type='ReLU'),
        upsample_cfg=dict(type='InterpConv'),
        norm_eval=False),
    decode_head=dict(
        type='ASPPHead',
        in_channels=64,
        in_index=4,
        channels=16,
        dilations=(1, 12, 24, 36),
        dropout_ratio=0.1,
        num_classes=2,
        out_channels=1,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=128,
        in_index=3,
        channels=64,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=2,
        out_channels=1,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=0.4)),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='slide', crop_size=(32, 32), stride=(21, 21)))
```
3. What dataset did you use?
 I made a custom dataset class as below:
```none

@DATASETS.register_module()
class SpikeletDataset(CustomDataset):
    """COCO-Stuff dataset.

    In segmentation map annotation for COCO-Stuff, Train-IDs of the 10k version
    are from 1 to 171, where 0 is the ignore index, and Train-ID of COCO Stuff
    164k is from 0 to 170, where 255 is the ignore index. So, they are all 171
    semantic categories. ``reduce_zero_label`` is set to True and False for the
    10k and 164k versions, respectively. The ``img_suffix`` is fixed to '.jpg',
    and ``seg_map_suffix`` is fixed to '.png'.
    """
    CLASSES = ('bg', 'Spikelet')

    PALETTE = [(255, 255, 255), (0, 0, 0)]

    def __init__(self, **kwargs):
        super(SpikeletDataset, self).__init__(
            img_suffix='.jpg', seg_map_suffix='.png', **kwargs)
```
**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
```none
fatal: not a git repository (or any of the parent directories): .git
sys.platform: win32
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2070
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30145 for x64
GCC: n/a
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,c
ode=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -o
penmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF
_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.3
OpenCV: 4.5.5
MMCV: 1.6.1
MMCV Compiler: MSVC 192930145
MMCV CUDA Compiler: 11.3
MMSegmentation: 0.29.0+
```
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "D:\Leon\SpikeDetection\Wheat\tools\segmentor\train.py", line 242, in <module>
    main()
  File "D:\Leon\SpikeDetection\Wheat\tools\segmentor\train.py", line 231, in main
    train_segmentor(
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\apis\train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\parallel\data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\models\segmentors\base.py", line 138, in train_step
    losses = self(**data_batch)
  File "C:\Users\leonh\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\models\segmentors\base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 144, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 87, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\models\decode_heads\decode_head.py", line 233, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
    return old_func(*args, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\models\decode_heads\decode_head.py", line 281, in losses
    loss[loss_decode.loss_name] = loss_decode(
  File "C:\Users\leonh\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\models\losses\cross_entropy_loss.py", line 271, in forward
    loss_cls = self.loss_weight * self.cls_criterion(
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\models\losses\cross_entropy_loss.py", line 124, in binary_cross_entropy
    assert label[label != ignore_index].max() <= 1, \
AssertionError: For pred with shape [N, 1, H, W], its label must have at most 2 classes
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

seg_maps weren't properly created i.e. with label 0 and 1. It solved the issue.

**Comment by MengzhangLI** [comment]
Hi, we just update FAQ doc which adds binary segmentation, please have a try:https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/faq.md#how-to-handle-binary-segmentation-task.

Best,

**Comment by MABatin** [comment]
Hi, thanks for the quick response. I did configure the dataset according to the FAQ but didn't make the seg_maps properly. That was the main issue. Thankfully it's solved now.
