### ISSUE TITLE
train CamVid using mmsegmentation

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmsegmentation#2273]
I want train Camvid dataset using mmseg, If anyone has experience with this dataset, can you share it? I would like to know all the steps required after downloading the data from the official to processing into a standard format supported by mmseg, can anyone help me？

**Comment by MengzhangLI** [comment]
Sorry we do not plan to implement CamVid dataset yet. You can discuss it in our wechat or QQ forum.

![image](https://user-images.githubusercontent.com/24582831/200285579-6b5c9ff0-e3e0-4a9e-b78a-a2c9b87d2cbd.png)

**Comment by Bin-ze** [comment]
think you!

**Comment by Yang-Parky** [comment]
> Sorry we do not plan to implement CamVid dataset yet. You can discuss it in our wechat or QQ forum.

Hi, do you solve this problem yet?

**Comment by Bin-ze** [comment]
yes，just need to convert the format to a standard segmentation style，such  as ADE20K

**Comment by endaoguansanlu** [comment]
> yes，just need to convert the format to a standard segmentation style，such as ADE20K

Hello, can you share your configuration, I always get an error here

Original Traceback (most recent call last):
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 789, in prepare_data
    return self.pipeline(data_info)
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
    data = t(data)
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/mmseg/datasets/transforms/formatting.py", line 78, in transform
    data_sample.gt_sem_seg = PixelData(**gt_sem_seg_data)
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/mmengine/structures/base_data_element.py", line 219, in __init__
    self.set_data(kwargs)
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/mmengine/structures/base_data_element.py", line 249, in set_data
    setattr(self, k, v)
  File "/home/liz/anaconda3/envs/test/lib/python3.8/site-packages/mmengine/structures/pixel_data.py", line 78, in __setattr__
    assert value.ndim in [
AssertionError: The dim of value must be 2 or 3, but got 4

**Comment by yangzaidao** [comment]
> 是的，只需将格式转换为标准分段样式即可，例如ADE20K
Hello, it is the camvid data set that I configured in ade20k format. However, during training, some categories iou and acc are nan. Have you encountered such a problem? Could you tell me how to solve it? Thank you very much

**Comment by Lio123456789** [comment]
> 是的，只需要将格式转换为标准的分割样式，例如 ADE20K

请问如何操作呢
