### ISSUE TITLE
collate function in inference doesn't work for images with different dimension

### ISSUE THREAD

**Issue by MABatin** [open-mmlab/mmsegmentation#2327]
**Describe the bug**

Using inference_segmentor for inference on multiple images with different dimensions doesn't work. It gives the following error:
```RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 300] at entry 0 and [3, 460, 256] at entry 1```

Workaround for this isinferencing on the images one at a time with a loop which takes quite a lot of time.

**Reproduction**

1. What command or script did you run?

   ```none
   from mmseg.apis import inference_segmentor, init_segmentor
    model = init_segmentor(config, checkpoint)
    results = inference_segmentor(model, images)

    return results
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

3. What dataset did you use?
I used a custom dataset with the following config:
```none
# dataset settings
dataset_type = 'SpikeletDataset'
data_root = 'Wheat/data/Spikelet_small_v3'

CLASSES = ['background', 'spikelet']

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (128, 128)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 256),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=0,
    persistent_workers=False,
    train=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='images/train',
        ann_dir='annotations/train',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='images/test',
        ann_dir='annotations/test',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='images/test',
        ann_dir='annotations/test',
        pipeline=test_pipeline))
```

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: win32
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2070
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30145 for x64
GCC: n/a
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,c
ode=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -o
penmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF
_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.3
OpenCV: 4.5.5
MMCV: 1.6.1
MMCV Compiler: MSVC 192930145
MMCV CUDA Compiler: 11.3
MMSegmentation: 0.29.0+
```
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "D:\Leon\SpikeDetection\Wheat\yield.py", line 173, in <module>
    main()
  File "D:\Leon\SpikeDetection\Wheat\yield.py", line 155, in main
    spikelet_results = inference_spikelet(spikelet_config, spikelet_checkpoint, spike_images)
  File "D:\Leon\SpikeDetection\Wheat\yield.py", line 42, in inference_spikelet
    results = inference_segmentor(model, images)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmseg\apis\inference.py", line 95, in inference_segmentor
    data = collate(data, samples_per_gpu=len(imgs))
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\parallel\collate.py", line 79, in collate
    return {
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\parallel\collate.py", line 80, in <dictcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\parallel\collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\parallel\collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\parallel\collate.py", line 84, in collate
    return default_collate(batch)
  File "C:\Users\leonh\anaconda3\lib\site-packages\torch\utils\data\_utils\collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 300] at entry 0 and [3, 460, 256] at entry 1

Process finished with exit code 1

```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xiexinch** [comment]
Hi @MABatin,
Sorry for the late reply.
In your script, what is the data type of the `images`?
```python
from mmseg.apis import inference_segmentor, init_segmentor
model = init_segmentor(config, checkpoint)
results = inference_segmentor(model, images)

return results
```

And we require all images in the same batch should be of the same shape.
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/base.py#L85

**Comment by MABatin** [comment]
Hi @xiexinch , thanks for the reply
In my script, ```images``` is a ```list``` containing the filenames of the images

I assumed for inference, images could be of different shapes like in ```inference_detector``` for mmdetection. So, now if I have images with different shapes I have to run ```inference_segmentor``` individually for each image and append the results to a list for a workaround, right?

**Comment by xiexinch** [comment]
Right, it's the only way now.

**Comment by xiexinch** [comment]
Closing the issue, as there is no activity for a while.
We hope your issue has been resolved.
If not, please feel free to open a new one.
