### ISSUE TITLE
RuntimeError for multi-GPUs segmentation model training

### ISSUE THREAD

**Issue by JiahaoXia** [open-mmlab/mmsegmentation#233]
Thanks for your project!
I want to train the segmentation model with multi-GPUs using the following codes:
_train_segmentor(model, datasets, cfg, **distributed=True**, validate=True, meta=dict())_
but I get the following error:
Traceback (most recent call last):
  File "/media/rise1/New Volume/Flood-Level-Estimation/fine_tuning_fcn.py", line 153, in <module>
    meta=dict())
  File "/home/rise1/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmseg/apis/train.py", line 67, in train_segmentor
    find_unused_parameters=find_unused_parameters)
  File "/home/rise1/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 273, in __init__
    self.process_group = _get_default_group()
  File "/home/rise1/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 268, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
I have searched online for solutions but none useful information got. Could you please help me with this problem?

**Comment by xvjiarui** [comment]
Same as #23

**Comment by grs8848** [comment]
Have you solved this problem? Can you give me some guidance
