### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

### ISSUE THREAD

**Issue by kzhao94** [open-mmlab/mmsegmentation#2357]
When I use the model to train my own dataset, this error always occurs. I feel that my config settings are OK, but I don't know where the error is? How can I solve it?

   ```none
  Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 231, in main
    train_segmentor(
  File "/home/zhkai/OpenMMLab/mmsegmentation-0.29.1/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhkai/OpenMMLab/mmcv-1.6.2/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/zhkai/OpenMMLab/mmcv-1.6.2/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/zhkai/OpenMMLab/mmcv-1.6.2/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/zhkai/OpenMMLab/mmsegmentation-0.29.1/mmseg/models/segmentors/base.py", line 138, in train_step
    losses = self(**data_batch)
  File "/home/zhkai/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhkai/OpenMMLab/mmcv-1.6.2/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/zhkai/OpenMMLab/mmsegmentation-0.29.1/mmseg/models/segmentors/base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/zhkai/OpenMMLab/mmsegmentation-0.29.1/mmseg/models/segmentors/encoder_decoder.py", line 144, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "/home/zhkai/OpenMMLab/mmsegmentation-0.29.1/mmseg/models/segmentors/encoder_decoder.py", line 87, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "/home/zhkai/OpenMMLab/mmsegmentation-0.29.1/mmseg/models/decode_heads/decode_head.py", line 233, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "/home/zhkai/OpenMMLab/mmcv-1.6.2/mmcv/runner/fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "/home/zhkai/OpenMMLab/mmsegmentation-0.29.1/mmseg/models/decode_heads/decode_head.py", line 293, in losses
    loss['acc_seg'] = accuracy(
  File "/home/zhkai/OpenMMLab/mmsegmentation-0.29.1/mmseg/models/losses/accuracy.py", line 49, in accuracy
    correct = correct[:, target != ignore_index]
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered
Aborted (core dumped)
   ```

**Comment by xiexinch** [comment]
Hi @kzhao94
Did you modify the source code? Perhaps the values of `target != ignore_index` are out of the range of `correct`, could you set a breakpoint to this line and check the max and min values of `correct` and `target`?

**Comment by xiexinch** [comment]
Closing the issue, as there is no activity for a while.
We hope your issue has been resolved. 
If not, please feel free to open a new one.
