### ISSUE TITLE
KeyError: 'ann_info' for a file when training/validating, on a CustomDataset

### ISSUE THREAD

**Issue by baristahell** [open-mmlab/mmsegmentation#2393]
Hi OpenMM, thanks for all your work. Having a small issue thought.
I got an issue similar to what https://github.com/open-mmlab/mmsegmentation/issues/2349 got.
I have the same problem, but my `ann_info` is only sometimes missing from the `results` dict in loading.py: 
>   File "/path/to/venv/lib/python3.8/site-packages/mmseg/datasets/pipelines/loading.py", line 120, in __call__
>     filename = osp.join(results["seg_prefix"], results["ann_info"]["seg_map"])
> KeyError: 'ann_info'

My data is loaded like VOC through the use of a CustomDataset:

```python
dataset_type = "CustomDataset"

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=1,
    train=dict(
        classes=classes,
        type=dataset_type,  
        data_root=project_data_root_dir, 
        img_dir=img_dir_train,  
        img_suffix=".jpeg",
        ann_dir=mask_dir_train,  
        pipeline=[  
            dict(type="LoadImageFromFile"),
            dict(type="LoadAnnotations"),
            dict(type="Resize", img_scale=crop_size, min_size=crop_size, keep_ratio=False),
            dict(type="RandomCrop", crop_size=crop_size),
            dict(type="RandomFlip", flip_ratio=0.5),
            dict(type="PhotoMetricDistortion"),
            dict(type="Normalize", **img_norm_cfg),
            dict(type="DefaultFormatBundle"),
            dict(type="Collect", keys=["img", "gt_semantic_seg"]),
        ],
    ),
    val=dict(
        classes=classes,
        type=dataset_type,
        data_root=project_data_root_dir,
        img_dir=img_dir_val,
        img_suffix=".jpeg",
        ann_dir=mask_dir_val,
        pipeline=[ 
            dict(type="LoadImageFromFile"),
            dict(type="LoadAnnotations"),
            dict(type="Resize", img_scale=crop_size, min_size=crop_size, keep_ratio=False),
            dict(type="RandomCrop", crop_size=crop_size),
            dict(type="RandomFlip", flip_ratio=0.5),
            dict(type="PhotoMetricDistortion"),
            dict(type="Normalize", **img_norm_cfg),
            # dict(type="ImageToTensor", keys=["img"]),
            dict(type="Collect", keys=["img", "gt_semantic_seg"]),
        ],
    ),
    test=dict(
        classes=classes,
        type=dataset_type,
        data_root=project_data_root_dir,
        img_dir=img_dir_val,
        img_suffix=".jpeg",
        ann_dir=mask_dir_val,
        pipeline=[  # Pipeline is passed by test_pipeline created before
            dict(type="LoadImageFromFile"),
            dict(type="Resize", img_scale=crop_size, min_size=crop_size, keep_ratio=False),
            dict(type="RandomCrop", crop_size=crop_size),
            dict(type="RandomFlip", flip_ratio=0.5),
            dict(type="PhotoMetricDistortion"),
            dict(type="Normalize", **img_norm_cfg),
            dict(type="ImageToTensor", keys=["img"]),
            dict(type="Collect", keys=["img"]),
        ],
    ),
)
```

Code to generate the data and train the model is the same as the demo:
```python
datasets = [build_dataset(cfg.data.train)]
if len(cfg.workflow) == 2:
    val_dataset = copy.deepcopy(cfg.data.val)
    val_dataset.pipeline = cfg.data.train.pipeline
    datasets.append(build_dataset(val_dataset))

model.CLASSES = datasets[0].CLASSES
train_segmentor(
    model,
    datasets,
    cfg,
    distributed=distributed,
    validate=(not args.no_validate),
    timestamp=timestamp,
    meta=meta)
```

Tried debugging and got this problematic "results" dict in loading.py line 120:
```python
>>>results
{'img_info': {'filename': 'xxx.jpeg', 'ann': {'seg_map': 'xxx.png'}}, 
'seg_fields': [], 
'img_prefix': '/path/to/data/images/val', 'seg_prefix': '/path/to/data/masks/val', 
'label_map': None, 'filename': '/path/to/data/images/val/xxx.jpeg', 'ori_filename': 'xxx.jpeg', 
'img': array([...], dtype=uint8), 'img_shape': (256, 257, 3), 'ori_shape': (256, 257, 3), 
'pad_shape': (256, 257, 3), 'scale_factor': 1.0, 
'img_norm_cfg': {'mean': array([0., 0., 0.], dtype=float32), 'std': array([1., 1., 1.], dtype=float32), 'to_rgb': False}}
```

I tried loading the files, image and mask both exist. 
```python
PIL.Image.open(osp.join(results["img_prefix"], results["img_info"]["filename"])).show()
PIL.Image.open(osp.join(results["seg_prefix"], results["img_info"]["ann"]["seg_map"])).show()
```
(got the mask from "ann" key because "ann_info" is missing)

What's weird is it's the first error I got in more than 20 debugger steps, all other results are alright, both with train and val files:
```python
>>>results
{'img_info': {'filename': 'aaa.jpeg', 'ann': {'seg_map': 'aaa.png'}}, 
'ann_info': {'seg_map': 'aaa.png'},
'seg_fields': [], 
'img_prefix': '/path/to/data/images/val', 'seg_prefix': '/path/to/data/masks/val', 
'label_map': None, 'filename': '/path/to/data/images/val/aaa.jpeg', 'ori_filename': 'aaa.jpeg', 
'img': array([...], dtype=uint8), 'img_shape': (267, 268, 3), 'ori_shape': (267, 268, 3), 
'pad_shape': (267, 268, 3), 'scale_factor': 1.0, 
'img_norm_cfg': {'mean': array([0., 0., 0.], dtype=float32), 'std': array([1., 1., 1.], dtype=float32), 'to_rgb': False}}
```
So as you can see, for the problematic results the key is just missing, with all other fileds being perfectly fine. I guess the dataset builder failed somewhere but where? `CustomDataset.load_annotations()` would've failed if something wrong happend...

My env:

> sys.platform: linux
> Python: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
> CUDA available: True
> GPU 0: NVIDIA GeForce GTX 1650 Ti
> CUDA_HOME: /usr/local/cuda
> NVCC: Cuda compilation tools, release 11.3, V11.3.109
> GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> PyTorch: 1.10.0+cu113
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - LAPACK is enabled (usually provided by MKL)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 11.3
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
>   - CuDNN 8.2
>   - Magma 2.5.2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
> 
> TorchVision: 0.11.1+cu102
> OpenCV: 4.6.0
> MMCV: 1.7.0
> MMCV Compiler: GCC 9.3
> MMCV CUDA Compiler: 11.3
> MMSegmentation: 0.29.1+8ea7a78

**Comment by xiexinch** [comment]
Hi @baristahell,
The `LoadAnnotation` method shouldn't be added to the val dataset pipeline since the results dict doesn't contain the 'ann_info' field. And the gt would be loaded after inference.

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/custom.py#L246

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/custom.py#L299

**Comment by baristahell** [comment]
Hmm alright thanks, but let me get through my thought process because removing it creates other issues for me...

Regular config (no LoadAnnotations in val, workflow = [("train", 1)]):
>   File "mmseg/models/segmentors/base.py", line 73, in forward_test
>     raise TypeError(f"{name} must be a list, but got " f"{type(var)}")
> TypeError: imgs must be a list, but got <class 'torch.Tensor'>
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 870, in run

So I added "gt_semantic_seg" to `dict(type="Collect", keys=["img", "gt_semantic_seg"]),` (I think it's because I thought I was missing masks for the validation step) but since I'm not loading  annotations of course I get this "bug":
>   File "mmseg/datasets/pipelines/formatting.py", line 290, in __call__
>     data[key] = results[key]
> KeyError: 'gt_semantic_seg'

So I added this `LoadAnnotation` method and it seemed to work, until I got the bug in this issue (most masks are loaded except this one image)

What am I missing? :grimacing:

**Comment by baristahell** [comment]
Alright I found the issue, my pipeline was wrong because of the use of DefaultFormatBundle.

```
val_pipeline=[
            dict(type="LoadImageFromFile"),
            dict(type="Resize", img_scale=crop_size, min_size=crop_size, keep_ratio=False),
            dict(type="RandomCrop", crop_size=crop_size),
            dict(type="RandomFlip", flip_ratio=0.5),
            dict(type="Normalize", **img_norm_cfg),
            dict(type="ImageToTensor", keys=["img"]),
            dict(type="Collect", keys=["img"])  # , "gt_semantic_seg"]),
        ]
```
made it work.

I still have a weird bug with CrossEntropyLoss (probably because I had use_sigmoid=False, will check that later) but training works with DiceLoss, and validation steps work too.

**Comment by baristahell** [comment]
Closing this issue, I'll do another one with the exact bug:

```
raise TypeError(f'{name} must be a list, but got '
TypeError: imgs must be a list, but got <class 'torch.Tensor'>

```
