### ISSUE TITLE
Validation fails: TypeError: imgs must be a list, but got <class 'torch.Tensor'> in mmseg/models/segmentors/base.py", line 74, in forward_test

### ISSUE THREAD

**Issue by baristahell** [open-mmlab/mmsegmentation#2410]
Hello team,

I can't seem to make the train/val pipeline work with my custom dataset, as validation always fails because of the following error, despite training working well:
```
2022-12-14 08:02:57,405 - mmseg - INFO - workflow: [('train', 1), ('val', 1)], max: 50 epochs
2022-12-14 08:02:57,405 - mmseg - INFO - Checkpoints will be saved to /.../work_dirs/config2 by HardDiskBackend.
2022-12-14 08:03:56,043 - mmseg - INFO - Iter [100/31700]	lr: 9.972e-03, eta: 5:07:08, time: 0.583, data_time: 0.021, memory: 5102, decode.loss_dice: 0.8474, decode.acc_seg: 42.2605, loss: 0.8474
2022-12-14 08:04:42,763 - mmseg - INFO - Iter [200/31700]	lr: 9.944e-03, eta: 4:35:42, time: 0.467, data_time: 0.003, memory: 5102, decode.loss_dice: 0.7940, decode.acc_seg: 47.1821, loss: 0.7940
2022-12-14 08:05:29,380 - mmseg - INFO - Iter [300/31700]	lr: 9.916e-03, eta: 4:24:32, time: 0.466, data_time: 0.003, memory: 5102, decode.loss_dice: 0.7608, decode.acc_seg: 50.3924, loss: 0.7608
2022-12-14 08:06:16,039 - mmseg - INFO - Iter [400/31700]	lr: 9.888e-03, eta: 4:18:37, time: 0.467, data_time: 0.003, memory: 5102, decode.loss_dice: 0.6118, decode.acc_seg: 46.8881, loss: 0.6118
2022-12-14 08:07:02,794 - mmseg - INFO - Iter [500/31700]	lr: 9.860e-03, eta: 4:14:52, time: 0.468, data_time: 0.003, memory: 5102, decode.loss_dice: 0.4972, decode.acc_seg: 47.7793, loss: 0.4972
2022-12-14 08:07:49,529 - mmseg - INFO - Iter [600/31700]	lr: 9.831e-03, eta: 4:12:04, time: 0.467, data_time: 0.003, memory: 5102, decode.loss_dice: 0.4916, decode.acc_seg: 46.0997, loss: 0.4916
2022-12-14 08:08:05,161 - mmseg - INFO - Saving checkpoint at 1 epochs
[                                                  ] 0/318, elapsed: 0s, ETA:Traceback (most recent call last):
  File "train.py", line 419, in <module>
[...]
File "/.../mmseg/models/segmentors/base.py", line 74, in forward_test
TypeError: imgs must be a list, but got <class 'torch.Tensor'> 

```
My val_dataset is well instantiated, the same way as my training set:
```
2022-12-14 09:34:17,283 - mmseg - INFO - Loaded 1269 images
2022-12-14 09:34:17,298 - mmseg - INFO - Loaded 318 images
```
My config is super simple and adapted from an existing demo:
```python
import os

norm_cfg = dict(type="BN", requires_grad=True)  # Segmentation usually uses SyncBN
data_root = "/home/user/"
data_dir = "data"
project_data_root_dir = os.path.join(data_root, data_dir)

classes = my list of classes
# palette = None
palette = [(0, 0, 0),
    (36, 179, 83),
    (116, 119, 108),
    (221, 238, 231),
    (42, 125, 209),
    (186, 80, 10),
    (250, 50, 83),
    (131, 224, 112)]

dataset_type = "CustomDataset"

img_norm_cfg = dict(
    mean=[0.485, 0.456, 0.406],
    std=[0.229, 0.224, 0.225],
    to_rgb=True,
)
crop_size = (256, 256)

device = "cuda"

img_dir_train, mask_dir_train = "images/train", "masks/train"
img_dir_val, mask_dir_val = "images/val", "masks/val"


model = dict(
    type="EncoderDecoder",
    pretrained=None,
    backbone=dict(
        type="UNet",
        in_channels=3,
        base_channels=64,
        num_stages=5,
        strides=(1, 1, 1, 1, 1),
        enc_num_convs=(2, 2, 2, 2, 2),
        dec_num_convs=(2, 2, 2, 2),
        downsamples=(True, True, True, True),
        enc_dilations=(1, 1, 1, 1, 1),
        dec_dilations=(1, 1, 1, 1),
        with_cp=False,
        conv_cfg=None,
        norm_cfg=norm_cfg,
        act_cfg=dict(type="ReLU"),
        upsample_cfg=dict(type="InterpConv"),
        norm_eval=False,
    ),
    decode_head=dict(
        type="FCNHead",
        in_channels=64,
        in_index=4,
        channels=64,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=len(classes),
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(type="DiceLoss"),
    ),  # , use_sigmoid=False, loss_weight=1.0)),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode="whole"),
)

train_pipeline = [
    dict(type="LoadImageFromFile"),
    dict(type="LoadAnnotations"),
    dict(type="Resize", img_scale=crop_size, min_size=crop_size, keep_ratio=False),
    dict(type="RandomCrop", crop_size=crop_size),
    dict(type="RandomFlip", flip_ratio=0.5),
    dict(type="PhotoMetricDistortion"),
    dict(type="Normalize", **img_norm_cfg),
    dict(type="ImageToTensor", keys=["img", "gt_semantic_seg"]),
    dict(type="Collect", keys=["img", "gt_semantic_seg"]),
]

test_pipeline = [
    dict(type="LoadImageFromFile"),
    dict(type="Resize", img_scale=crop_size, min_size=crop_size, keep_ratio=False),
    dict(type="RandomCrop", crop_size=crop_size),
    dict(type="RandomFlip", flip_ratio=0),
    # dict(type="PhotoMetricDistortion"),
    dict(type="Normalize", **img_norm_cfg),
    dict(type="ImageToTensor", keys=["img"]),
    dict(type="Collect", keys=["img"]),
]

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=1,
    train=dict(
        classes=classes,
        type=dataset_type,
        data_root=project_data_root_dir,
        img_dir=img_dir_train,
        img_suffix=".jpeg",
        ann_dir=mask_dir_train,
        seg_map_suffix=".png",
        pipeline=train_pipeline,
    ),
    val=dict(
        classes=classes,
        type=dataset_type,
        data_root=project_data_root_dir,
        img_dir=img_dir_val,
        img_suffix=".jpeg",
        ann_dir=mask_dir_val,
        seg_map_suffix=".png",
        pipeline=test_pipeline,
    ),
    test=dict(
        classes=classes,
        type=dataset_type,
        data_root=project_data_root_dir,
        img_dir=img_dir_val,
        img_suffix=".jpeg",
        ann_dir=mask_dir_val,
        seg_map_suffix=".png",
        pipeline=test_pipeline,
        flip=False,
    ),
)

log_config = dict(
    interval=100,
    hooks=[
        dict(type="TextLoggerHook", by_epoch=False),
        dict(type="TensorboardLoggerHook", by_epoch=False),
    ],
)

dist_params = dict(backend="nccl")  # Parameters to setup distributed training, the port can also be set.
log_level = "INFO"  # The level of logging.
load_from = None  # load models as a pre-trained model from a given path. This will not resume training.
resume_from = None  # Resume checkpoints from a given path, the training will be resumed from the iteration when the checkpoint"s is saved.
workflow = [
    ("train", 1),
    ("val", 1),
]  # Workflow for runner. [("train", 1)] means there is only one workflow and the workflow named "train" is executed once. The workflow trains the model by 40000 iterations according to the `runner.max_iters`.
cudnn_benchmark = True  # Whether use cudnn_benchmark to speed up, which is fast for fixed input size.
optimizer = dict(  # Config used to build optimizer, support all the optimizers in PyTorch whose arguments are also the same as those in PyTorch
    type="SGD",  # Type of optimizers, refer to https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/optimizer/default_constructor.py#L13 for more details
    lr=0.01,  # Learning rate of optimizers, see detail usages of the parameters in the documentation of PyTorch
    momentum=0.9,  # Momentum
    weight_decay=0.0005,
)  # Weight decay of SGD
optimizer_config = (
    dict()
)  # Config used to build the optimizer hook, refer to https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/optimizer.py#L8 for implementation details.
lr_config = dict(
    policy="poly",  # The policy of scheduler, also support Step, CosineAnnealing, Cyclic, etc. Refer to details of supported LrUpdater from https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py#L9.
    power=0.9,  # The power of polynomial decay.
    min_lr=0.0001,  # The minimum learning rate to stable the training.
    by_epoch=False,
)  # Whether count by epoch or not.
runner = dict(
    type="EpochBasedRunner", max_epochs=50  # Type of runner to use (i.e. IterBasedRunner or EpochBasedRunner)
)  # Total number of iterations. For EpochBasedRunner use `max_epochs`
checkpoint_config = dict(  # Config to set the checkpoint hook, Refer to https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py for implementation.
    by_epoch=True, interval=1  # Whether count by epoch or not.
)  # The save interval.
evaluation = (
    dict(  # The config to build the evaluation hook. Please refer to mmseg/core/evaluation/eval_hook.py for details.
        interval=1, metric=["mIoU", "mDice", "mFscore"]  # The interval of evaluation.
    )
)  # The evaluation metric.

```
Likewise my train.py is a copy of the existing demo:
```python
    datasets = [build_dataset(cfg.data.train)]
    if len(cfg.workflow) == 2:
        val_dataset = copy.deepcopy(cfg.data.val)
        val_dataset.pipeline = cfg.data.train.pipeline
        datasets.append(build_dataset(val_dataset))
    for d in datasets:
        print(f"Datasets: loaded {len(d)} images")

    if cfg.checkpoint_config is not None:
        # save mmseg version, config file content and class names in
        # checkpoints as meta data
        cfg.checkpoint_config.meta = dict(
            mmseg_version=f'{__version__}+{get_git_hash()[:7]}',
            config=cfg.pretty_text,
            CLASSES=datasets[0].CLASSES,
            PALETTE=datasets[0].PALETTE)

    # add an attribute for visualization convenience
    model.CLASSES = datasets[0].CLASSES
    # passing checkpoint meta for saving best checkpoint
    meta.update(cfg.checkpoint_config.meta)
    train_segmentor(
        model,
        datasets,
        cfg,
        distributed=distributed,
        validate=(not args.no_validate),
        timestamp=timestamp,
        meta=meta)
```
I can only find old issues about this and am starting to lose faith in my ability to debug the problem: https://github.com/open-mmlab/mmdetection/issues/1600

Does someone have an idea? Did I do something wrong in my config?

**Comment by baristahell** [comment]
Well, haven't found why I got this issue but my pipeline works without the (val, 1) step. And validation is still ran, after every training epoch. So I might have misunderstood the workflow.
