### ISSUE TITLE
1.x分支，运行get_flops.py时报错

### ISSUE THREAD

**Issue by lolikonloli** [open-mmlab/mmsegmentation#2454]
1.x分支运行如下代码报错
`python tools/analysis_tools/get_flops.py configs/unet/unet_s5-d16_deeplabv3_4xb4-40k_chase-db1-128x128.py `

报错信息：
```
/home/lolikonloli/medical_seg/mmseg/models/builder.py:44: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
Traceback (most recent call last):
  File "/home/lolikonloli/medical_seg/tools/analysis_tools/get_flops.py", line 60, in <module>
    main()
  File "/home/lolikonloli/medical_seg/tools/analysis_tools/get_flops.py", line 37, in main
    model = build_segmentor(
  File "/home/lolikonloli/medical_seg/mmseg/models/builder.py", line 47, in build_segmentor
    assert cfg.get('train_cfg') is None or train_cfg is None, \
AssertionError: train_cfg specified in both outer field and model field 
```

**Comment by MeowZheng** [comment]
Thanks for your bug report, we are working on rewriting flops computing for mmseg 1.0.
