### ISSUE TITLE
How can I know file name of current image when training?

### ISSUE THREAD

**Issue by dddzhzzz** [open-mmlab/mmsegmentation#2479]
I set the size of image as (256,256).
_______________________________________
In my code:
    def losses(self, seg_logit, seg_label):
        """Compute segmentation loss."""
        loss = dict()
        print('seg_logit.shape=',seg_logit.shape)
        print('seg_label.shape=', seg_label.shape)
        seg_logit = resize(
            input=seg_logit,
            size=seg_label.shape[2:],
            mode='bilinear',
            align_corners=self.align_corners)
        print('after bilinear: seg_logit.shape=', seg_logit.shape)
___________________________________________________
But my training log report:

seg_logit.shape= torch.Size([1, 1, 32, 32])
seg_label.shape= torch.Size([1, 1, 256, 256])
after bilinear: seg_logit.shape= torch.Size([1, 1, 256, 256])
seg_logit.shape= torch.Size([1, 1, 32, 32])
seg_label.shape= torch.Size([1, 1, 256, 256])
after bilinear: seg_logit.shape= torch.Size([1, 1, 256, 256])
seg_logit.shape= torch.Size([1, 1, 32, 32])
seg_label.shape= torch.Size([1, 1, 256, 256, 3])
Traceback (most recent call last):
  File "D:\New_Era_Project\Local_similarity_project\tools\train.py", line 242, in <module>
    main()
  File "D:\New_Era_Project\Local_similarity_project\tools\train.py", line 231, in main
    train_segmentor(
  File "D:\New_Era_Project\Local_similarity_project\mmseg\apis\train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mmcv\parallel\data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "D:\New_Era_Project\Local_similarity_project\mmseg\models\segmentors\base.py", line 138, in train_step
    losses = self(**data_batch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "D:\New_Era_Project\Local_similarity_project\mmseg\models\segmentors\base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "D:\New_Era_Project\Local_similarity_project\mmseg\models\segmentors\encoder_decoder.py", line 144, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "D:\New_Era_Project\Local_similarity_project\mmseg\models\segmentors\encoder_decoder.py", line 87, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "D:\New_Era_Project\Local_similarity_project\mmseg\models\decode_heads\decode_head.py", line 234, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "D:\New_Era_Project\Local_similarity_project\mmseg\models\decode_heads\decode_head.py", line 267, in losses
    seg_logit = resize(
  File "D:\New_Era_Project\Local_similarity_project\mmseg\ops\wrappers.py", line 27, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 3854, in interpolate
    raise ValueError(
ValueError: Input and output must have the same number of spatial dimensions, but got input with with spatial dimensions of [32, 32] and output size of torch.Size([256, 256, 3]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.

Process finished with exit code 1
 __________________________________________
 
 I don't know how the mask with shape (256, 256, 3) to be produced? it is different  from other mask with shape  (256, 256). I think there may be a wrong mask file in my dataset. How can I trace back to the wrong mask file?

**Comment by MengzhangLI** [comment]
It can be found in [`img_metas`](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py#L123).

**Comment by dddzhzzz** [comment]
Thank you! I have solved it.
