### ISSUE TITLE
ImportError: cannot import name 'build_dataloader' from 'mmseg.datasets' (unknown location)

### ISSUE THREAD

**Issue by BenoitKAO** [open-mmlab/mmsegmentation#2505]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
```none
Traceback (most recent call last):
  File "tools/train.py", line 17, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "/mmsegmentation/mmseg/apis/__init__.py", line 4, in <module>
    from .train import (get_root_logger, init_random_seed, set_random_seed,
  File "/mmsegmentation/mmseg/apis/train.py", line 16, in <module>
    from mmseg.datasets import build_dataloader, build_dataset
ImportError: cannot import name 'build_dataloader' from 'mmseg.datasets' (unknown location)
```
**Reproduction**

1. What command or script did you run?
```none
git pull
pip install -v -e .
python tools/train.py configs/unet/fcn_unet_s5-d16_256x256_40k.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
 No,
Yes.

3. What dataset did you use?
custom dataset

**Environment**
```none
/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
sys.platform: linux
Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA RTX A6000
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.7  (built against CUDA 11.8)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu117
OpenCV: 4.5.5
MMCV: 1.7.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.7
MMSegmentation: 0.30.0+5d49918
```
**Error traceback**

If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "tools/train.py", line 17, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "/mmsegmentation/mmseg/apis/__init__.py", line 4, in <module>
    from .train import (get_root_logger, init_random_seed, set_random_seed,
  File "/mmsegmentation/mmseg/apis/train.py", line 16, in <module>
    from mmseg.datasets import build_dataloader, build_dataset
ImportError: cannot import name 'build_dataloader' from 'mmseg.datasets' (unknown location)
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

Any help is appreciated!

**Comment by MeowZheng** [comment]
do you still meet this problem?

**Comment by BenoitKAO** [comment]
I solved this problem by using the archive of the previous version of MMCV and MMsegmentation.

**Comment by micklexqg** [comment]
> I solved this problem by using the archive of the previous version of MMCV and MMsegmentation.

which version do you install?

**Comment by Carol-Liu-lin** [comment]
> 

hello, how can you get the archive of the previous version of MMsegmentation? If I want to edit on it
