### ISSUE TITLE
Error during training about freeze_support()

### ISSUE THREAD

**Issue by artgru92** [open-mmlab/mmsegmentation#2514]
Hi i need help to solve my error. I coppied lines of code to python file from MMSegmentation_Tutorial.ipynb and change mainly paths to dataset. Error which i recevied is related with freeze_support (i copied error lines below my issue). Any suggestion or solutions? I only add that program still working until that i manually stopped.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\main3.py", line 157, in <module>
    train_segmentor(model, datasets, cfg, distributed=False, validate=True,
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\apis\train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\lib\site-packages\mmcv\runner\iter_based_runner.py", line 128, in run
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\lib\site-packages\mmcv\runner\iter_based_runner.py", line 128, in <listcomp>
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\lib\site-packages\mmcv\runner\iter_based_runner.py", line 25, in __init__
    self.iter_loader = iter(self._dataloader)
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 433, in __iter__
    self._iterator = self._get_iterator()
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1048, in __init__
    w.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by MengzhangLI** [comment]
Hi, similar problem is here: https://github.com/open-mmlab/mmdetection/issues/7597

please set `workers_per_gpu` to 0.

**Comment by artgru92** [comment]
Yes i know about site which you pasted and i read this before writing about my problem. Changing number of workers not work to solve my problem. Now i have something like this: ValueError: persistent_workers option needs num_workers > 0

"...
work_dir = './work_dirs/tutorial'
seed = 0
gpu_ids = range(0, 1)
device = 'cuda'

2023-01-30 07:28:18,885 - mmseg - INFO - Loaded 572 images
D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\models\backbones\resnet.py:431: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\models\losses\cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
Traceback (most recent call last):
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\main3.py", line 157, in <module>
    train_segmentor(model, datasets, cfg, distributed=False, validate=True,
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\apis\train.py", line 101, in train_segmentor
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\apis\train.py", line 101, in <listcomp>
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\mmsegmentation\mmseg\datasets\builder.py", line 153, in build_dataloader
    data_loader = DataLoader(
  File "D:\MOJE\ARTUR_G_WAT\Python\MMSegmentation3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 235, in __init__
    raise ValueError('persistent_workers option needs num_workers > 0')
ValueError: persistent_workers option needs num_workers > 0
"

**Comment by MengzhangLI** [comment]
> 

`ValueError: persistent_workers option needs num_workers > 0` would be caused when num_worker=0 and persistent_workers=True. That is because `persistent_workers` needs to collaborate with multiprocessing, so you can try to set `persistent_workers=False`.

**Comment by artgru92** [comment]
Ok it looks good what you write but where exactly this: persistent_workers=False should be implement? Main program or dataloader.py? Sorry probably i am not good programmer and your advice is obvious to you ;-) but i am a little confused.
