### ISSUE TITLE
Training and testing stucks after loading images

### ISSUE THREAD

**Issue by YushanZhang324** [open-mmlab/mmsegmentation#256]
I can succefully run domo, but when I run test or train, it performs like this:

2020-11-13 22:10:41,359 - mmseg - INFO - Loaded 500 images
[                                                  ] 0/500, elapsed: 0s, ETA:^CTraceback (most recent call last):
  File "tools/test.py", line 142, in <module>
    main()
  File "tools/test.py", line 120, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home1/users/zys/SemanticSegmentation/mmsegmentation/mmseg/apis/test.py", line 31, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home1/users/zys/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home1/users/zys/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home1/users/zys/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 798, in _get_data
    success, data = self._try_get_data()
  File "/home1/users/zys/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home1/users/zys/anaconda3/envs/open-mmlab/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home1/users/zys/anaconda3/envs/open-mmlab/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

It just doesn't move from zero. The dataset is placed as this repo sugested. Has anyone met the same problem and could offer some help? Thank a lot!

**Comment by xvjiarui** [comment]
Hi @YushanZhang324 
You may try to set `workers_per_gpu=0`.

**Comment by YushanZhang324** [comment]
Thanks for your advice. The test works for me now!
But the train.py still doesn't work. It says "AssertionError: Default process group is not initialized". And I could only train it by dist_train.py. Is it possible to use train.py instead of dist_train.py?
Thanks very much~

Best regards
Yushan


---------------- 

---------- Origin message ----------
>From："Jerry Jiarui XU" <notifications@github.com>
>To："open-mmlab/mmsegmentation" <mmsegmentation@noreply.github.com>
>Subject：Re: [open-mmlab/mmsegmentation] Training and testing stucks after loading images (#256)
>Date：2020-11-18 11:09:37Hi @YushanZhang324
You may try to set `workers_per_gpu=0`.

**Comment by krantiparida** [comment]
I am also facing the same issue. Kindly suggest what to do?

**Comment by YushanZhang324** [comment]
> I am also facing the same issue. Kindly suggest what to do?

hi, you might want to try dist_train.py or dist_test.py. It works for me. Btw, setting  workers_per_gpu=0 also works for me while testing.

**Comment by krantiparida** [comment]
Thanks for the reply. I wil try to use that.
