### ISSUE TITLE
mIoU is too high

### ISSUE THREAD

**Issue by blxl909** [open-mmlab/mmsegmentation#2587]
When I was testing code , I followed constraction of tutorial , but the training result seems to be really weird , the mIoU is about 100%.
here are my steps:
1、python tools/convert_datasets/vaihingen.py /path/to/vaihingen (it's worked and generated correctly)
2、python tools/train.py  ./configs/pspnet/pspnet_r50-d8_4x4_512x512_80k_vaihingen.py --work-dir logs/pspnet
[20230212_210726.log](https://github.com/open-mmlab/mmsegmentation/files/10716252/20230212_210726.log)

besides , I have problem when I use potsdam dataset 

d to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Making directories...
Find the data ['/home/xxguo/data/potsdam/2_Ortho_RGB.zip', '/home/xxguo/data/potsdam/5_Labels_all_noBoundary.zip']
Traceback (most recent call last):
  File "tools/convert_datasets/potsdam.py", line 157, in <module>
    main()
  File "tools/convert_datasets/potsdam.py", line 132, in main
    zip_file.extractall(tmp_dir)
  File "/home/xxguo/miniconda3/envs/openmmlab/lib/python3.8/zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/xxguo/miniconda3/envs/openmmlab/lib/python3.8/zipfile.py", line 1702, in _extract_member
    shutil.copyfileobj(source, target)
  File "/home/xxguo/miniconda3/envs/openmmlab/lib/python3.8/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/home/xxguo/miniconda3/envs/openmmlab/lib/python3.8/zipfile.py", line 940, in read
    data = self._read1(n)
  File "/home/xxguo/miniconda3/envs/openmmlab/lib/python3.8/zipfile.py", line 1016, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code lengths set

thanks for helping

**Comment by blxl909** [comment]
the problems have been solved，the dataset I upload had something wrong， so I just reloaded it ，and the other problem is I misused command.
