### ISSUE TITLE
验证的时候报错

### ISSUE THREAD

**Issue by kc-w** [open-mmlab/mmsegmentation#2646]
02/24 16:10:06 - mmengine - WARNING - The "loop" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:06 - mmengine - WARNING - The "dataset" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:06 - mmengine - WARNING - The "transform" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:06 - mmengine - WARNING - The "data sampler" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:08 - mmengine - WARNING - The "optimizer wrapper constructor" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:08 - mmengine - WARNING - The "optimizer" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:08 - mmengine - WARNING - The "optim_wrapper" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:08 - mmengine - WARNING - The "parameter scheduler" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
D:\Python\Python39\lib\site-packages\mmengine\evaluator\metric.py:47: UserWarning: The prefix is not set in metric class IoUMetric.
  warnings.warn('The prefix is not set in metric class '
02/24 16:10:08 - mmengine - WARNING - The "metric" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:09 - mmengine - WARNING - The "weight initializer" registry in mmseg did not set import location. Fallback to call `mmseg.utils.register_all_modules` instead.
02/24 16:10:09 - mmengine - INFO - Checkpoints will be saved to E:\projectTest\mmsegmentation-1.0.0rc5\tools\work.
02/24 16:10:27 - mmengine - INFO - Iter(train) [ 50/500]  lr: 7.2072e-03  eta: 0:02:40  time: 0.2555  data_time: 0.0037  memory: 6552  loss: 0.3131  decode.loss_ce: 0.0461  decode.acc_seg: 97.9019  aux_0.loss_ce: 0.0814  aux_0.acc_seg: 97.9019  aux_1.loss_ce: 0.0571  aux_1.acc_seg: 97.9019  aux_2.loss_ce: 0.0622  aux_2.acc_seg: 97.9019  aux_3.loss_ce: 0.0665  aux_3.acc_seg: 97.9019
02/24 16:10:40 - mmengine - INFO - Iter(train) [100/500]  lr: 9.4595e-03  eta: 0:02:02  time: 0.2558  data_time: 0.0033  memory: 2496  loss: 0.2686  decode.loss_ce: 0.0468  decode.acc_seg: 100.0000  aux_0.loss_ce: 0.0646  aux_0.acc_seg: 100.0000  aux_1.loss_ce: 0.0534  aux_1.acc_seg: 100.0000  aux_2.loss_ce: 0.0512  aux_2.acc_seg: 100.0000  aux_3.loss_ce: 0.0526  aux_3.acc_seg: 100.0000
02/24 16:10:40 - mmengine - INFO - Saving checkpoint at 100 iterations
02/24 16:10:55 - mmengine - INFO - Iter(train) [150/500]  lr: 1.1712e-02  eta: 0:01:47  time: 0.2568  data_time: 0.0035  memory: 2495  loss: 0.4821  decode.loss_ce: 0.0781  decode.acc_seg: 98.5080  aux_0.loss_ce: 0.1027  aux_0.acc_seg: 98.4848  aux_1.loss_ce: 0.0995  aux_1.acc_seg: 98.4848  aux_2.loss_ce: 0.1001  aux_2.acc_seg: 98.4848  aux_3.loss_ce: 0.1017  aux_3.acc_seg: 98.4848
02/24 16:11:08 - mmengine - INFO - Iter(train) [200/500]  lr: 1.3964e-02  eta: 0:01:28  time: 0.2570  data_time: 0.0034  memory: 2496  loss: 0.2719  decode.loss_ce: 0.0531  decode.acc_seg: 100.0000  aux_0.loss_ce: 0.0515  aux_0.acc_seg: 100.0000  aux_1.loss_ce: 0.0542  aux_1.acc_seg: 100.0000  aux_2.loss_ce: 0.0548  aux_2.acc_seg: 100.0000  aux_3.loss_ce: 0.0583  aux_3.acc_seg: 100.0000
02/24 16:11:08 - mmengine - INFO - Saving checkpoint at 200 iterations
02/24 16:11:22 - mmengine - INFO - Iter(train) [250/500]  lr: 1.6216e-02  eta: 0:01:13  time: 0.2568  data_time: 0.0034  memory: 2495  loss: 0.3065  decode.loss_ce: 0.0697  decode.acc_seg: 99.5457  aux_0.loss_ce: 0.0587  aux_0.acc_seg: 99.5457  aux_1.loss_ce: 0.0569  aux_1.acc_seg: 99.5457  aux_2.loss_ce: 0.0578  aux_2.acc_seg: 99.5457  aux_3.loss_ce: 0.0635  aux_3.acc_seg: 99.5457
02/24 16:11:24 - mmengine - INFO - Exp name: MyBisentV1_20230224_160959
02/24 16:11:35 - mmengine - INFO - Iter(train) [300/500]  lr: 1.8468e-02  eta: 0:00:57  time: 0.2550  data_time: 0.0032  memory: 2496  loss: 0.2579  decode.loss_ce: 0.0458  decode.acc_seg: 99.8228  aux_0.loss_ce: 0.0597  aux_0.acc_seg: 99.8228  aux_1.loss_ce: 0.0544  aux_1.acc_seg: 99.8228  aux_2.loss_ce: 0.0485  aux_2.acc_seg: 99.8228  aux_3.loss_ce: 0.0496  aux_3.acc_seg: 99.8228
02/24 16:11:35 - mmengine - INFO - Saving checkpoint at 300 iterations
02/24 16:11:49 - mmengine - INFO - Iter(train) [350/500]  lr: 2.0721e-02  eta: 0:00:43  time: 0.2576  data_time: 0.0033  memory: 2496  loss: 0.3042  decode.loss_ce: 0.0493  decode.acc_seg: 97.4975  aux_0.loss_ce: 0.0658  aux_0.acc_seg: 99.8045  aux_1.loss_ce: 0.0651  aux_1.acc_seg: 99.8045  aux_2.loss_ce: 0.0586  aux_2.acc_seg: 99.8045  aux_3.loss_ce: 0.0654  aux_3.acc_seg: 99.8045
02/24 16:12:02 - mmengine - INFO - Iter(train) [400/500]  lr: 2.2973e-02  eta: 0:00:28  time: 0.2580  data_time: 0.0032  memory: 2496  loss: 0.3546  decode.loss_ce: 0.0454  decode.acc_seg: 99.9675  aux_0.loss_ce: 0.0772  aux_0.acc_seg: 99.9675  aux_1.loss_ce: 0.0734  aux_1.acc_seg: 99.9675  aux_2.loss_ce: 0.0731  aux_2.acc_seg: 99.9675  aux_3.loss_ce: 0.0856  aux_3.acc_seg: 99.9675
02/24 16:12:02 - mmengine - INFO - Saving checkpoint at 400 iterations
02/24 16:12:17 - mmengine - INFO - Iter(train) [450/500]  lr: 2.5225e-02  eta: 0:00:14  time: 0.2575  data_time: 0.0039  memory: 2496  loss: 0.2534  decode.loss_ce: 0.0475  decode.acc_seg: 99.9622  aux_0.loss_ce: 0.0586  aux_0.acc_seg: 99.9622  aux_1.loss_ce: 0.0489  aux_1.acc_seg: 99.9622  aux_2.loss_ce: 0.0454  aux_2.acc_seg: 99.9622  aux_3.loss_ce: 0.0530  aux_3.acc_seg: 99.9622
02/24 16:12:30 - mmengine - INFO - Iter(train) [500/500]  lr: 2.7477e-02  eta: 0:00:00  time: 0.2569  data_time: 0.0033  memory: 2496  loss: 0.1511  decode.loss_ce: 0.0251  decode.acc_seg: 99.2332  aux_0.loss_ce: 0.0350  aux_0.acc_seg: 99.2222  aux_1.loss_ce: 0.0327  aux_1.acc_seg: 99.2222  aux_2.loss_ce: 0.0264  aux_2.acc_seg: 99.2222  aux_3.loss_ce: 0.0319  aux_3.acc_seg: 99.2222
02/24 16:12:30 - mmengine - INFO - Saving checkpoint at 500 iterations
Traceback (most recent call last):
  File "E:\projectTest\mmsegmentation-1.0.0rc5\tools\train.py", line 106, in <module>
    main()
  File "E:\projectTest\mmsegmentation-1.0.0rc5\tools\train.py", line 102, in main
    runner.train()
  File "D:\Python\Python39\lib\site-packages\mmengine\runner\runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "D:\Python\Python39\lib\site-packages\mmengine\runner\loops.py", line 270, in run
    self.runner.val_loop.run()
  File "D:\Python\Python39\lib\site-packages\mmengine\runner\loops.py", line 347, in run
    self.run_iter(idx, data_batch)
  File "D:\Python\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\mmengine\runner\loops.py", line 368, in run_iter
    self.evaluator.process(data_samples=outputs, data_batch=data_batch)
  File "D:\Python\Python39\lib\site-packages\mmengine\evaluator\evaluator.py", line 60, in process
    metric.process(data_batch, _data_samples)
  File "E:\projectTest\mmsegmentation-1.0.0rc5\mmseg\evaluation\metrics\iou_metric.py", line 60, in process
    num_classes = len(self.dataset_meta['classes'])
KeyError: 'classes'

**Comment by kc-w** [comment]
norm_cfg = dict(type='BN', requires_grad=True)
data_preprocessor = dict(
    type='SegDataPreProcessor',
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    bgr_to_rgb=True,
    pad_val=0,
    seg_pad_val=255,
    size=(1024, 1024))
model = dict(
    type='EncoderDecoder',
    data_preprocessor=dict(
        type='SegDataPreProcessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_val=0,
        seg_pad_val=255,
        size=(1024, 1024)),
    pretrained=None,
    backbone=dict(
        type='BiSeNetV2',
        detail_channels=(64, 64, 128),
        semantic_channels=(16, 32, 64, 128),
        semantic_expansion_ratio=6,
        bga_channels=128,
        out_indices=(0, 1, 2, 3, 4),
        init_cfg=None,
        align_corners=False),
    decode_head=dict(
        type='FCNHead',
        in_channels=128,
        in_index=0,
        channels=1024,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=3,
        norm_cfg=dict(type='BN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=[
        dict(
            type='FCNHead',
            in_channels=16,
            channels=16,
            num_convs=2,
            num_classes=3,
            in_index=1,
            norm_cfg=dict(type='BN', requires_grad=True),
            concat_input=False,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
        dict(
            type='FCNHead',
            in_channels=32,
            channels=64,
            num_convs=2,
            num_classes=3,
            in_index=2,
            norm_cfg=dict(type='BN', requires_grad=True),
            concat_input=False,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
        dict(
            type='FCNHead',
            in_channels=64,
            channels=256,
            num_convs=2,
            num_classes=3,
            in_index=3,
            norm_cfg=dict(type='BN', requires_grad=True),
            concat_input=False,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
        dict(
            type='FCNHead',
            in_channels=128,
            channels=1024,
            num_convs=2,
            num_classes=3,
            in_index=4,
            norm_cfg=dict(type='BN', requires_grad=True),
            concat_input=False,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))
    ],
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))

dataset_type = 'MyDataset'
data_root = 'D:/images/image1/mask/'
scale = (1440, 1080)
crop_size = (1024, 1024)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(
        type='RandomResize',
        scale=scale,
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='PackSegInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=scale, keep_ratio=True),
    dict(type='LoadAnnotations'),
    dict(type='PackSegInputs')
]
img_ratios = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
tta_pipeline = [
    dict(type='LoadImageFromFile', backend_args=dict(backend='local')),
    dict(
        type='TestTimeAug',
        transforms=[[{
            'type': 'Resize',
            'scale_factor': 0.5,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 0.75,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.0,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.25,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.5,
            'keep_ratio': True
        }, {
            'type': 'Resize',
            'scale_factor': 1.75,
            'keep_ratio': True
        }],
                    [{
                        'type': 'RandomFlip',
                        'prob': 0.0,
                        'direction': 'horizontal'
                    }, {
                        'type': 'RandomFlip',
                        'prob': 1.0,
                        'direction': 'horizontal'
                    }], [{
                        'type': 'LoadAnnotations'
                    }], [{
                        'type': 'PackSegInputs'
                    }]])
]
train_dataloader = dict(
    batch_size=2,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='img_dir/train',
            seg_map_path='ann_dir/train'
        ),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(
                type='RandomResize',
                scale=scale,
                ratio_range=(0.5, 2.0),
                keep_ratio=True),
            dict(
                type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(type='PackSegInputs')
        ]))
val_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='img_dir/val',
            seg_map_path='ann_dir/val'
            ),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=scale, keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ]))
test_dataloader = val_dataloader
val_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
test_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
default_scope = 'mmseg'
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='SegLocalVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    name='visualizer')
log_processor = dict(by_epoch=False)
log_level = 'INFO'
load_from = None
resume = False
tta_model = dict(type='SegTTAModel')
optimizer = dict(type='SGD', lr=0.05, momentum=0.9, weight_decay=0.0005)
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='SGD', lr=0.05, momentum=0.9, weight_decay=0.0005),
    clip_grad=None)
param_scheduler = [
    dict(type='LinearLR', by_epoch=False, start_factor=0.1, begin=0, end=1000),
    dict(
        type='PolyLR',
        eta_min=0.0001,
        power=0.9,
        begin=1000,
        end=160000,
        by_epoch=False)
]
train_cfg = dict(
    type='IterBasedTrainLoop', max_iters=500, val_interval=500)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50, log_metric_by_epoch=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', by_epoch=False, interval=100),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='SegVisualizationHook'))
launcher = 'none'

**Comment by xiexinch** [comment]
Hi @kc-w,
可以看一下你的数据集类是怎么定义的吗？是不是没有加上metainfo？
可以参考这个prhttps://github.com/open-mmlab/mmsegmentation/pull/2086 修改一下。
修改完成后可以用 --resume 命令恢复训练。

**Comment by kc-w** [comment]
from mmseg.registry import DATASETS
from .basesegdataset import BaseSegDataset

#自定义dataset数据文件
@DATASETS.register_module()
class MyDataset(BaseSegDataset):
  CLASSES = ("background","contamination","crack")#设置类别
  PALETTE = [[0,0,0],[255,0,0],[0,255,0]]#设置设置test.py标签mask的RGB颜色

  def __init__(self, **kwargs):
    super(MyDataset, self).__init__(
      img_suffix='.jpg',seg_map_suffix='.png',reduce_zero_label=False,**kwargs
    )

**Comment by xiexinch** [comment]
Closing the issue, as there is no activity for a while.
We hope your issue has been resolved. 
If not, please feel free to open a new one.

**Comment by yulongnan** [comment]
Mmsegmentation voc.py caused by differences between old and new code.
Position : mmseg\datasets\voc.py
Revise: CLASSES =change=>classes ; PALETTE =change=>palette

`METAINFO = dict(
        CLASSES = ( 'background', 'pitaya'),  **# error   CLASSES =change=>classes**
        PALETTE = [ [0, 0, 0], [53, 119, 181] ]  **# error   PALETTE =change=>palette**

        # classes=('background', 'aeroplane', 'bicycle', 'bird', 'boat',
        #          'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable',
        #          'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep',
        #          'sofa', 'train', 'tvmonitor'),
        # palette=[[0, 0, 0], [128, 0, 0], [0, 128, 0], [128, 128, 0],
        #          [0, 0, 128], [128, 0, 128], [0, 128, 128], [128, 128, 128],
        #          [64, 0, 0], [192, 0, 0], [64, 128, 0], [192, 128, 0],
        #          [64, 0, 128], [192, 0, 128], [64, 128, 128], [192, 128, 128],
        #          [0, 64, 0], [128, 64, 0], [0, 192, 0], [128, 192, 0],
        #          [0, 64, 128]]`
