### ISSUE TITLE
Errors when using tools/analysis_tools/analyze_logs.py

### ISSUE THREAD

**Issue by ArkhamKnight-AI** [open-mmlab/mmsegmentation#2666]
when I use analyze_logs.py to visualize the process of training, An Error occured:
  ax = plt.gca()
Traceback (most recent call last):
  File "E:/mmsegmentation/tools/analysis_tools/analyze_logs.py", line 130, in <module>
    main()
  File "E:/mmsegmentation/tools/analysis_tools/analyze_logs.py", line 126, in main
    plot_curve(log_dicts, args)
  File "E:/mmsegmentation/tools/analysis_tools/analyze_logs.py", line 48, in plot_curve
    ax = plt.gca()
  File "C:\Anaconda3\envs\mmseg\lib\site-packages\matplotlib\pyplot.py", line 2282, in gca
    return gcf().gca()
  File "C:\Anaconda3\envs\mmseg\lib\site-packages\matplotlib\pyplot.py", line 879, in gcf
    return figure()
  File "C:\Anaconda3\envs\mmseg\lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\mmseg\lib\site-packages\matplotlib\pyplot.py", line 813, in figure
    manager = new_figure_manager(
  File "C:\Anaconda3\envs\mmseg\lib\site-packages\matplotlib\pyplot.py", line 382, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "C:\Anaconda3\envs\mmseg\lib\site-packages\matplotlib\pyplot.py", line 360, in _warn_if_gui_out_of_main_thread
    if _get_required_interactive_framework(_get_backend_mod()):
  File "C:\Anaconda3\envs\mmseg\lib\site-packages\matplotlib\pyplot.py", line 208, in _get_backend_mod
    switch_backend(rcParams._get("backend"))
  File "C:\Anaconda3\envs\mmseg\lib\site-packages\matplotlib\pyplot.py", line 331, in switch_backend
    manager_pyplot_show = vars(manager_class).get("pyplot_show")
TypeError: vars() argument must have __dict__ attribute

Process finished with exit code 1

the args I used in command line is as follows:
![QQ截图20230302143618](https://user-images.githubusercontent.com/73521466/222350035-5d0e7ee2-2f01-43b5-9b79-7e61eca5df11.png)

the json file in folder is as follows:
![QQ截图](https://user-images.githubusercontent.com/73521466/222350376-7b09e31a-4082-4600-b7e5-8bd69f1a06f5.png)

Looking forward to hear from you! thanks~

**Comment by MeowZheng** [comment]
I just clone this [jog](https://download.openmmlab.com/mmsegmentation/v0.5/maskformer/maskformer_r50-d32_8xb2-160k_ade20k-512x512/maskformer_r50-d32_8xb2-160k_ade20k-512x512_20221030_182724.json)
then  run 
```
python tools/analysis_tools/analyze_logs.py maskformer_r50-d32_8xb2-160k_ade20k-512x512_20221030_182724.json --keys mIoU mAcc
```
and I got 
![image](https://user-images.githubusercontent.com/76149310/222356717-22e537f2-6795-4bb2-a148-36079906e5d8.png)

**Comment by ArkhamKnight-AI** [comment]
yes, I debug the code and find that high version of matplotlib leads to this problem, so I uninstalled matplotlib==3.6.0 and installed matplotlib==3.2.0.
Then the problem is solved. Thank you for taking your time!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmsegmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmsegmentation] Errors when using tools/analysis_tools/analyze_logs.py (Issue #2666)





 
I just clone this jog
 then  run
 python tools/analysis_tools/analyze_logs.py maskformer_r50-d32_8xb2-160k_ade20k-512x512_20221030_182724.json --keys mIoU mAcc  
and I got
