### ISSUE TITLE
TypeError: MyDataset: __init__() got an unexpected keyword argument 'dataset'

### ISSUE THREAD

**Issue by TaoBowoa180011** [open-mmlab/mmsegmentation#2669]
**I have created my dataset on  mmseg/datasets/mydataset.py** 

import os.path as osp

from .builder import DATASETS
from .custom import CustomDataset

@DATASETS.register_module()
class MyDataset(CustomDataset):
    """MyDataset.

    In segmentation map annotation for STARE, 0 stands for background, which is
    included in 2 categories. ``reduce_zero_label`` is fixed to False. The
    ``img_suffix`` is fixed to '.png' and ``seg_map_suffix`` is fixed to
    '.ah.png'.
    """

    CLASSES = ('background', 'cancer')

    PALETTE = [[0, 0, 0], [255, 255, 255]]

    def __init__(self, **kwargs):
        super(MyDataset, self).__init__(
            img_suffix='.png',
            seg_map_suffix='.png',
            reduce_zero_label=False,
            **kwargs)
        assert osp.exists(self.img_dir)

**and configs/_base_/datasets/mydataset.py**

# dataset settings
dataset_type = 'MyDataset'
data_root = 'data/my_dataset'
img_norm_cfg = dict(
    mean=[203.49, 197.62, 202.72], std=[41.82, 45.64, 43.09], to_rgb=True)

img_scale = (2000, 2000)
crop_size = (512, 512)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=img_scale, ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]

data = dict(
    samples_per_gpu=16,
    workers_per_gpu=2,
    train=dict(
        type= dataset_type,
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            img_dir='images/train',
            ann_dir='masks/train',
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='images/val',
        ann_dir='masks/val',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='images/val',
        ann_dir='masks/val',
        pipeline=test_pipeline)
)

**but when i run python tools/train.py configs/unet/pspnet_unet_s5-d16_ce-1.0-dice-3.0_256x256_40k_hrf.py, I got this problem below**
 
{'type': 'MyDataset', 'dataset': {'type': 'MyDataset', 'data_root': 'data/my_dataset', 'img_dir': 'images/train', 'ann_dir': 'masks/train', 'pipeline': [{'type': 'LoadImageFromFile'}, {'type': 'LoadAnnotations'}, {'type': 'Resize', 'img_scale': (2000, 2000), 'ratio_range': (0.5, 2.0)}, {'type': 'RandomCrop', 'crop_size': (512, 512), 'cat_max_ratio': 0.75}, {'type': 'RandomFlip', 'prob': 0.5}, {'type': 'PhotoMetricDistortion'}, {'type': 'Normalize', 'mean': [203.49, 197.62, 202.72], 'std': [41.82, 45.64, 43.09], 'to_rgb': True}, {'type': 'Pad', 'size': (512, 512), 'pad_val': 0, 'seg_pad_val': 255}, {'type': 'DefaultFormatBundle'}, {'type': 'Collect', 'keys': ['img', 'gt_semantic_seg']}]}}
<class 'mmseg.datasets.mydataset.MyDataset'>
Traceback (most recent call last):
  File "/home/www4/.local/lib/python3.9/site-packages/mmcv/utils/registry.py", line 70, in build_from_cfg
    return obj_cls(**args)
  File "/opt/data/tb/code/mmsegmentation/mmseg/datasets/mydataset.py", line 23, in __init__
    super(MyDataset, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'dataset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/data/tb/code/膜浆阳癌区分割/mmsegmentation/tools/train.py", line 242, in <module>
    main()
  File "/opt/data/tb/code/膜浆阳癌区分割/mmsegmentation/tools/train.py", line 214, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/opt/data/tb/code/mmsegmentation/mmseg/datasets/builder.py", line 86, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/www4/.local/lib/python3.9/site-packages/mmcv/utils/registry.py", line 73, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MyDataset: __init__() got an unexpected keyword argument 'dataset'

**Comment by MeowZheng** [comment]
did you import MyDataset in `mmseg/datasets/__init__.py`?

**Comment by Yu-zhengbo** [comment]
Check the dataset.py you wrote, and you would find the 'dataset' in you dict.
![image](https://user-images.githubusercontent.com/72426381/224345989-ad301233-d580-4c38-bfa7-321c79489c16.png)
