### ISSUE TITLE
OSError: [Errno 95] Operation not supported

### ISSUE THREAD

**Issue by jajajajaja121** [open-mmlab/mmsegmentation#273]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I save checkpoint, the program is broke, but iter_8000.pth has been saved.

**Reproduction**

1. What command or script did you run?

    ```
    python tools/train.py convert-label/config/deeplabv3plus_r50-d8_769x769_80k_cityscapes.py --gpu-ids 2 --work-dir convert-label/workdir/
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I have change the data root, and worker per gpu set to zero.
3. What dataset did you use?
I use my owe dataset.

**Environment**
```
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]                                                                                
CUDA available: True                                                                                                                      
GPU 0,1,2: GeForce RTX 2080 Ti                                                                                                            
CUDA_HOME: /usr/local/cuda                                                                                                                
NVCC: Cuda compilation tools, release 10.1, V10.1.105                                                                                     
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0                                                                                              
PyTorch: 1.6.0+cu101                                                                                                                      
PyTorch compiling details: PyTorch built with:                                                                                            
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;$
gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
- Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDE$
UG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=ret$
rn-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -$
no-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error
=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-col
or=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-strin
gop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_M
KL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.2.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: not available
MMSegmentation: 0.8.0+15cca88

```
**Error traceback**

If applicable, paste the error trackback here.

```
Traceback (most recent call last):                                                                                                        
  File "tools/train.py", line 164, in <module>                                                                                            
    main()                                                                                                                                
  File "tools/train.py", line 160, in main                                                                                                
    meta=meta)                                                                                                                            
  File "/home/xiongpan/code/mmsegmentation/mmseg/apis/train.py", line 118, in train_segmentor                                             
    runner.run(data_loaders, cfg.workflow)                                                                                                
  File "/opt/conda/envs/mms/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run                               
    iter_runner(iter_loaders[i], **kwargs)                                                                                                
  File "/opt/conda/envs/mms/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train                              
    self.call_hook('after_train_iter')                                                                                                    
  File "/opt/conda/envs/mms/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook                               
    getattr(hook, fn_name)(self)                                                                                                          
  File "/opt/conda/envs/mms/lib/python3.7/site-packages/mmcv/runner/hooks/checkpoint.py", line 101, in after_train_iter                   
    self._save_checkpoint(runner)                                                                                                         
  File "/opt/conda/envs/mms/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 97, in wrapper                                   
    return func(*args, **kwargs)                                                                                                          
  File "/opt/conda/envs/mms/lib/python3.7/site-packages/mmcv/runner/hooks/checkpoint.py", line 62, in _save_checkpoint                    
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)                                                                        
  File "/opt/conda/envs/mms/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 213, in save_checkpoint                   
    mmcv.symlink(filename, dst_file)                                                                                                      
  File "/opt/conda/envs/mms/lib/python3.7/site-packages/mmcv/utils/path.py", line 36, in symlink                                          
    os.symlink(src, dst, **kwargs)                                                                                                        
OSError: [Errno 95] Operation not supported: 'iter_8000.pth' -> '/home/xiongpan/code/mmsegmentation/convert-label/workdir/latest.pth'     
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xvjiarui** [comment]
Hi @jajajajaja121 
You may set `create_symlink=False` in `checkpoint_config`.
