### ISSUE TITLE
Train deeplabv3+

### ISSUE THREAD

**Issue by xiaoachen98** [open-mmlab/mmsegmentation#275]
When I train deeplabv3+ on Cityscapes dataset, although I followed all the instructions you provided, I ran into the following problem:
   (open-mmlab) chenlin@amax:/data4/chenlin/code/segmentation/mmsegmentation-master$ python tools/train.py configs/deeplabv3plus/deeplabv3plus_r101-d8_769x769_80k_cityscapes.py --options model.backbone.with_cp=True

Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 135, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/data4/chenlin/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmseg/datasets/builder.py", line 73, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/data4/chenlin/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/data4/chenlin/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmseg/datasets/cityscapes.py", line 36, in __init__
    **kwargs)
  File "/data4/chenlin/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmseg/datasets/custom.py", line 86, in __init__
    self.pipeline = Compose(pipeline)
  File "/data4/chenlin/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmseg/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/data4/chenlin/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'prob'

Please help me to answer my doubts, thanks a lot

**Comment by xiaoachen98** [comment]
And if I want to start trainning on Cityscapes with Deeplabv3+ and one GPU, what should I type on the command line

**Comment by YLyeliang** [comment]
According to your error log, you should check your dataset config file. Checkout your train_pipeline in your config file.
The default of cityscape is like below:
```python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(2049, 1025), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
```
I'm very sure that in your config file, there exist some operations that have the word 'prob', check out that and make sure you have the correct arguments.

2. The command line can be very easy:
```shell
python tools/train.py your_config_path your_work_dir_path --gpu-ids your_pointed_gpu_number
```
