### ISSUE TITLE
BiSeNetV2: __init__() got an unexpected keyword argument 'pretrained'

### ISSUE THREAD

**Issue by Buling-Knight** [open-mmlab/mmsegmentation#2773]
**Describe the bug**
BiSeNetV2: __init__() got an unexpected keyword argument 'pretrained'

environment:
mmcv-full 1.4.7
pytorch 1.11.0
3060GPU

I found it difficult to use "predtrained" in the config file. What should I do?

**Comment by Buling-Knight** [comment]
This is all the record! I'll appreciate it!

023-03-19 13:09:34,418 - mmseg - INFO - Set random seed to 1993062338, deterministic: False
Traceback (most recent call last):
  File "D:\Anaconda\envs\mmlab\lib\site-packages\mmcv\utils\registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'pretrained'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\mmlab\lib\site-packages\mmcv\utils\registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "E:\codelib\mmsegmentation-master\mmseg\models\segmentors\encoder_decoder.py", line 36, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "E:\codelib\mmsegmentation-master\mmseg\models\builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: BiSeNetV2: __init__() got an unexpected keyword argument 'pretrained'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/codelib/mmsegmentation-master/tools/train.py", line 242, in <module>
    main()
  File "E:/codelib/mmsegmentation-master/tools/train.py", line 198, in main
    model = build_segmentor(
  File "E:\codelib\mmsegmentation-master\mmseg\models\builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "D:\Anaconda\envs\mmlab\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\Anaconda\envs\mmlab\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: EncoderDecoder: BiSeNetV2: __init__() got an unexpected keyword argument 'pretrained'

**Comment by Buling-Knight** [comment]
When I don't use the "pretrained" order, the file named "train.py" can be runed, but I got only 58 of mIoU!

**Comment by Buling-Knight** [comment]
When I don't use the "pretrained" order, the file named "train.py" can be runed, but I got only 58 of mIoU!
And I note that some net config file include the "pretrained" order, some file have not used it in mmsegmentation.
It's a little wired for me.

**Comment by xiexinch** [comment]
Hi @Buling-Knight,
Do you make any modifications to the source code or config files? The `BiSeNetV2` is a model trained from scratch, it's no need to set `pretrained` param to this model. Ref: https://arxiv.org/pdf/2004.02147.pdf

Since I don't know what your dataset is, I have no idea about 58 mIoU, so you can describe it in detail.

**Comment by Buling-Knight** [comment]
@xiexinch Thanks for your reply!
I use the origin source code and config file.
config file: bisenetv2_fcn_4x4_1024x1024_160k_cityscapes.py.
The following is my train record!(the smooth rate is 0)
![image](https://user-images.githubusercontent.com/91008145/226530881-1bde8a80-6fa8-42a7-ad43-463095cfeb8c.png)
![image](https://user-images.githubusercontent.com/91008145/226530924-50330544-dc1a-4810-8be5-fe08b1d21068.png)

I wonder if I should run for more iterations?

**Comment by xiexinch** [comment]
Hi @Buling-Knight,
How many GPUs do you use for training? We train it with 4 GPUs.

**Comment by Buling-Knight** [comment]
I use only one GPU, and the batch size is 2. So you mean I need train for more iterations?

**Comment by xiexinch** [comment]
In general, it is desirable to increase the number of iterations, but there is no guarantee that the results will be achieved.

**Comment by Buling-Knight** [comment]
Thanks for your patience. I will try to train for more iterations.
