### ISSUE TITLE
ValueError: size shape must match input shape. Input is 1D, size is 2 

### ISSUE THREAD

**Issue by HUANGL1NJIE** [open-mmlab/mmsegmentation#2774]
I run a command `python tools/train.py configs/knet/knet_s3_fcn_r50-d8_8x2_512x512_adamw_80k_ade20k.py` for knet training. The code can successfully run at the begining. However, after the  first model evalution/validation, it stopped and reported a ValueError: size shape must match input shape. Input is 1D, size is 2.  

Hope someone can help me！

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Environment**

Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: n/a
PyTorch: 1.8.1+cu111
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829913
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-genco
de;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_
FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_
NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.9.1+cu111
OpenCV: 4.6.0
MMCV: 1.5.3
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.1
MMSegmentation: 0.30.0+

**Error traceback**

Traceback (most recent call last):
  File "tools/train.py", line 246, in <module>
    main()
  File "tools/train.py", line 235, in main
    train_segmentor(
  File "d:\mmsegmentation-0.30.0\mmseg\apis\train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 70, in val
    self.run_iter(data_batch, train_mode=False)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\mmcv\parallel\data_parallel.py", line 97, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "d:\mmsegmentation-0.30.0\mmseg\models\segmentors\base.py", line 155, in val_step
    losses = self(**data_batch)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\mmcv\runner\fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "d:\mmsegmentation-0.30.0\mmseg\models\segmentors\base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "d:\mmsegmentation-0.30.0\mmseg\models\segmentors\encoder_decoder.py", line 144, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "d:\mmsegmentation-0.30.0\mmseg\models\segmentors\encoder_decoder.py", line 87, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "d:\mmsegmentation-0.30.0\mmseg\models\decode_heads\decode_head.py", line 233, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "d:\mmsegmentation-0.30.0\mmseg\models\decode_heads\knet_head.py", line 453, in losses
    loss = self.kernel_generate_head.losses(logit, seg_label)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\mmcv\runner\fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "d:\mmsegmentation-0.30.0\mmseg\models\decode_heads\decode_head.py", line 264, in losses
    seg_logit = resize(
  File "d:\mmsegmentation-0.30.0\mmseg\ops\wrappers.py", line 27, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\torch\nn\functional.py", line 3475, in interpolate
    raise ValueError(
ValueError: size shape must match input shape. Input is 1D, size is 2

**Comment by AI-Tianlong** [comment]
* I noticed Error information mentioned the `return F.interpolate(input, size, scale_factor, mode, align_corners)
File "D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\torch\nn\functional.py", line 3475, in interpolate`.  
* I think you can `print()` the `input` and `size` at `D:\ProgramData\Anaconda3\envs\mmselfsup\lib\site-packages\torch\nn\functional.py, line 3475`  to observe further details

**Comment by xiexinch** [comment]
Closing the issue, as there is no activity for a while.
We hope your issue has been resolved. 
If not, please feel free to open a new one.
