### ISSUE TITLE
Visualization issue when using multiple GPU

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmsegmentation#2776]
**Describe the bug**
There is an issue during trainning, when one is using multiple GPU and validation image visualization (also called prediciton drawing), and more than 1 GPU.

Ps: I'm on 1.X RC, more info below.

**Reproduction**

1. What command or script did you run?

I'm using a in validation set drawer using this config (subset):
```
train_cfg = dict(
    type='IterBasedTrainLoop', max_iters=EPOCH_INTERVAL*TRAIN_EPOCH, val_interval=CHECKPOINT_VAL_INTERVAL*EPOCH_INTERVAL)
val_cfg = dict(type='ValLoop')

visualizer = dict(
    type='SegLocalVisualizer', vis_backends=VIS_BACKEND, name='visualizer')

default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=LOGGING_INTERVAL, log_metric_by_epoch=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', by_epoch=False, interval = CHECKPOINT_VAL_INTERVAL*EPOCH_INTERVAL),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='SegVisualizationHook', draw=True, interval = CHECKPOINT_VAL_INTERVAL*EPOCH_INTERVAL),
    )
```
When launching the script with 1 GPU (`mmsegmentation/tools.train.py <config>`) it works well.
When using multiple GPU  via `bash mmsegmentation/tools/dist_train.sh <config> 2` it crash (traceback below).

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes and Yes

3. What dataset did you use?
Custom Dataset

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA GeForce RTX 3090 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0
OpenCV: 4.7.0
MMEngine: 0.6.0
MMSegmentation: 1.0.0rc6+
```

**Error traceback**
   ```
   Traceback (most recent call last):
  File "external/mmsegmentation/tools/train.py", line 106, in <module>
    main()
  File "external/mmsegmentation/tools/train.py", line 102, in main
    runner.train()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 270, in run
    self.runner.val_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 347, in run
    self.run_iter(idx, data_batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 369, in run_iter
    self.runner.call_hook(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1748, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/hooks/hook.py", line 256, in after_val_iter
    self._after_iter(
  File "/erx-torch/external/mmsegmentation/mmseg/engine/hooks/visualization_hook.py", line 89, in _after_iter
    img = mmcv.imfrombytes(img_bytes, channel_order='rgb')
  File "/opt/conda/lib/python3.8/site-packages/mmcv/image/io.py", line 287, in imfrombytes
    cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
   ```

**Comment by csatsurnh** [comment]
hi @joihn, this error
```
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```
occurs when data is not correctly loaded, do you mind providing the full config used?

**Comment by joihn** [comment]
I'm was using a customized version of mmseg. Despite my best effort, I realized I can't reproduce the bug on vannilla mmseg, suggesting the bug is on my side only, I'll do further inverstigation.
Thanks you for your attention nevertheless.
