### ISSUE TITLE
KeyError: 'EncoderDecoder: \'`cfg` or `default_args` must contain the key "type", but got

### ISSUE THREAD

**Issue by Wanttoretire** [open-mmlab/mmsegmentation#2875]
I'm trying to replace the decoder head of swin transformer, but I got the KeyError and I don't know how to solve it:
```
2023-04-10 14:34:46,693 - mmseg - INFO - Set random seed to 451499853, deterministic: False
Traceback (most recent call last):
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 39, in __init__
    self._init_decode_head(decode_head)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 49, in _init_decode_head
    self.decode_head = builder.build_head(decode_head)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/builder.py", line 30, in build_head
    return HEADS.build(cfg)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 41, in build_from_cfg
    raise KeyError(
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'decode_head\': {\'type\': \'SegformerHead\', \'in_channels\': [96, 192, 384, 768],
 \'in_index\': [0, 1, 2, 3], \'channels\': 512, \'dropout_ratio\': 0.1, \'num_classes\': 150, \'norm_cfg\': {\'type\': \'SyncBN\', \'requires_grad\': True}, \'align_corners\': False, \'loss_decode\': {\'type\': \'CrossEntropyLoss\',
 \'use_sigmoid\': False, \'loss_weight\': 1.0}}, \'in_channels\': [96, 192, 384, 768], \'num_classes\': 150}\nNone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 249, in <module>
    main()
  File "tools/train.py", line 205, in main
    model = build_segmentor(
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'EncoderDecoder: \'`cfg` or `default_args` must contain the key "type", but got {\\\'decode_head\\\': {\\\'type\\\': \\\'SegformerHead\\\', 
\\\'in_channels\\\': [96, 192, 384, 768], \\\'in_index\\\': [0, 1, 2, 3], \\\'channels\\\': 512, \\\'dropout_ratio\\\': 0.1, \\\'num_classes\\\': 150, 
\\\'norm_cfg\\\': {\\\'type\\\': \\\'SyncBN\\\', \\\'requires_grad\\\': True}, \\\'align_corners\\\': False, \\\'loss_decode\\\': {\\\'type\\\': \\\'CrossEntropyLoss\\\', \\\'use_sigmoid\\\': False, \\\'loss_weight\\\': 1.0}}, 
\\\'in_channels\\\': [96, 192, 384, 768], \\\'num_classes\\\': 150}\\nNone\''
```

The /configs/_base_/models file is:
```
norm_cfg = dict(type='SyncBN', requires_grad=True) 
backbone_norm_cfg = dict(type='LN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained=None,
    backbone=dict(         
        type='SwinTransformer',
        pretrain_img_size=224,
        embed_dims=96,
        patch_size=4,
        window_size=7,
        mlp_ratio=4,
        depths=[2, 2, 6, 2],  
        num_heads=[3, 6, 12, 24],
        strides=(4, 2, 2, 2),
        out_indices=(0, 1, 2, 3),
        qkv_bias=True,
        qk_scale=None,
        patch_norm=True,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.3,
        use_abs_pos_embed=False,
        act_cfg=dict(type='GELU'),
        norm_cfg=backbone_norm_cfg),
    decode_head=dict(            
        decode_head=dict(
        type='SegformerHead',
        in_channels=[96, 192, 384, 768],
        in_index=[0, 1, 2, 3],
        channels=512,
        dropout_ratio=0.1,
        num_classes=19,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))),

    auxiliary_head=dict(
        type='FCNHead',          
        in_channels=384,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,      
        dropout_ratio=0.1,       
        num_classes=19,          
        norm_cfg=norm_cfg,       
        align_corners=False,    
        loss_decode=dict(        
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    # model training and testing settings
    train_cfg=dict(),  
    test_cfg=dict(mode='whole'))
```

And the config file is :

```
_base_ = [
    '../_base_/models/segformer_swin.py',  
    '../_base_/datasets/cityscapes.py',      
    '../_base_/default_runtime.py', 
    '../_base_/schedules/schedule_160k.py'  
]
checkpoint_file = 
'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/swin/swin_tiny_patch4_window7_224_20220317-1cdeb081.pth'  # noqa
model = dict(
    backbone=dict(
        init_cfg=dict(type='Pretrained', checkpoint=checkpoint_file),
        embed_dims=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        use_abs_pos_embed=False,
        drop_path_rate=0.3,
        patch_norm=True),
    decode_head=dict(in_channels=[96, 192, 384, 768], num_classes=19),
    auxiliary_head=dict(in_channels=384, num_classes=19))

# AdamW optimizer, no weight decay for position embedding & layer norm
# in backbone
optimizer = dict(
    _delete_=True,  
    type='AdamW',
    lr=0.00006,
    betas=(0.9, 0.999),
    weight_decay=0.01,
    paramwise_cfg=dict(
        custom_keys={
            'absolute_pos_embed': dict(decay_mult=0.),
            'relative_position_bias_table': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.)
        }))

lr_config = dict(
    _delete_=True,
    policy='poly',
    warmup='linear',
    warmup_iters=1500,
    warmup_ratio=1e-6,
    power=1.0,
    min_lr=0.0,
    by_epoch=False)

# By default, models are trained on 8 GPUs with 2 images per GPU
data = dict(samples_per_gpu=2)

```

Here is my envs:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
addict                    2.4.0                    pypi_0    pypi
aom                       3.5.0                h27087fc_0    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
blessed                   1.19.1                   pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
cityscapesscripts         2.2.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
contourpy                 1.0.6                    pypi_0    pypi
cudatoolkit               10.2.89             h713d32c_11    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.4            py38hfa26641_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
ffmpeg                    5.1.2           gpl_h13415ed_104    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               hc2a2eb6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.7.8                hf3e180e_0    conda-forge
gpustat                   1.0.0                    pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                      pypi_0    pypi
importlib-metadata        5.1.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.14.0           py38h7f3c49e_0    conda-forge
ipython                   8.4.0            py38h578d9bd_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jpeg                      9b                   h024ee3a_2  
jupyter_client            7.4.8              pyhd8ed1ab_0    conda-forge
jupyter_core              5.1.0            py38h578d9bd_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
libdrm                    2.4.114              h166bdaf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpciaccess              0.17                 h166bdaf_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtasn1                  4.19.0               h166bdaf_0    conda-forge
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libva                     2.16.0               h166bdaf_0    conda-forge
libvpx                    1.11.0               h9c3ff4c_3    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               15.0.6               he0ac6c6_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.4.1                    pypi_0    pypi
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h95df7f1_0    conda-forge
mkl_fft                   1.3.1            py38h8666266_1    conda-forge
mkl_random                1.2.2            py38h1abd341_0    conda-forge
mmcls                     0.25.0                   pypi_0    pypi
mmcv-full                 1.7.0                    pypi_0    pypi
mmsegmentation            0.29.1                    dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
nettle                    3.8.1                hc379101_1    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
numpy                     1.23.4           py38h14f4228_0  
numpy-base                1.23.4           py38h31eccc5_0  
nvidia-ml-py              11.495.46                pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.6.0.66                 pypi_0    pypi
openh264                  2.3.1                h27087fc_1    conda-forge
openmim                   0.3.3                    pypi_0    pypi
openssl                   3.0.7                h0b41bf4_1    conda-forge
ordered-set               4.1.0                    pypi_0    pypi
p11-kit                   0.24.1               hc5aa10d_0    conda-forge
packaging                 22.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.2                    pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    7.1.2            py38hb39fc2d_0  
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.6.0              pyhd8ed1ab_0    conda-forge
prettytable               3.5.0                    pypi_0    pypi
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
psutil                    5.9.4            py38h0a891b7_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pyqt5                     5.15.7                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.0                  pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
python                    3.8.15          h4a9ceb5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytorch                   1.8.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
pytz                      2022.6                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1           py38hfc09fa9_1    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
rich                      12.6.0                   pypi_0    pypi
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
svt-av1                   1.4.0                h27087fc_0    conda-forge
tabulate                  0.9.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
torchaudio                0.8.0                      py38    pytorch
torchvision               0.9.0                py38_cu102    pytorch
tornado                   6.2              py38h0a891b7_1    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.7.0              pyhd8ed1ab_0    conda-forge
typing                    3.7.4.3                  pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    conda-forge
urllib3                   1.26.13                  pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yapf                      0.32.0                   pypi_0    pypi
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```

Waiting for your help
Best,

**Comment by Wanttoretire** [comment]
In both files I add 
```
_delete_=True
```
in`decode_head=dict()`
but it still got the error
```
Traceback (most recent call last):
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/decode_heads/segformer_head.py", line 102, in __init__
    super().__init__(input_transform='multiple_select', **kwargs)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 81, in __init__
    self._init_inputs(in_channels, in_index, input_transform)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 172, in _init_inputs
    assert isinstance(in_index, (list, tuple))
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 39, in __init__
    self._init_decode_head(decode_head)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 49, in _init_decode_head
    self.decode_head = builder.build_head(decode_head)
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/builder.py", line 30, in build_head
    return HEADS.build(cfg)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: SegformerHead: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 249, in <module>
    main()
  File "tools/train.py", line 205, in main
    model = build_segmentor(
  File "/home/newDisk/wzx/mmsegmentation/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/newDisk/wzx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: EncoderDecoder: SegformerHead:
```

**Comment by zhongyas** [comment]
I also encountered this problem. Have you solved it now?

**Comment by amberhappy** [comment]
I also encountered this problem. Have you solved it now?

**Comment by Wanttoretire** [comment]
yes. I suggest you check your code. I got this error because I copy the code without deleting the original{}我不知道你是不是中国人但是我已经很久不碰英文课英文太烂了，简而言之就是你查一下你的代码，我当时有错是因为我复制的时候没有删掉最外层的大括号，我也不知道咋描述了你可以看一下我贴的代码最外层的括号是有问题的这种错误一般就是配置文件缺少括号之类的发自我的手机-------- 原始邮件 --------发件人： Amber ***@***.***>日期： 2024年9月26日周四 14:01收件人： open-mmlab/mmsegmentation ***@***.***>抄送： Wanttoretire ***@***.***>, Author ***@***.***>主    题： Re: [open-mmlab/mmsegmentation] KeyError: 'EncoderDecoder: \'`cfg` or `default_args` must contain the key "type", but got (Issue #2875)
I also encountered this problem. Have you solved it now?
