### ISSUE TITLE
model trains well on 1 GPU but crashes after saving the first checkpoint 

### ISSUE THREAD

**Issue by fschvart** [open-mmlab/mmsegmentation#2876]
Thanks for building this outstanding platform!
I'm running a model based on mmsegmentation 0.27.0. (InternImage)
and I run into a weird issue, when I train the model on single GPU (python train.py ...), everything works well. 
When I train using dist_train on my two RTX3090, the training crashes with the following error.

It seems like the system has a memory issue. 
When I train the using the same repo, but a lighter model, the training runs well. 

I guess that the problem is the beginning of inference. Is this a torchrun/pytorch distributed launch bug? Is there anything I can do?

It might be important to note that I'm using with_cp=True in order to fit the model in the memory.

2023-04-10 08:38:47,838 - mmseg - INFO - Iter [2000/160000]     lr: 1.662e-06, eta: 2 days, 12:56:23, time: 1.678, data_time: 0.053, memory: 19979, decode.loss_ce: 0.0211, decode.acc_seg: 99.6272, aux.loss_ce: 0.0270, aux.acc_seg: 99.4153, loss: 0.0480, grad_norm: 0.4636
[                                                  ] 0/23, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./train.py", line 258, in <module>
    main()
  File "./train.py", line 248, in main
    train_segmentor(model,
  File "/usr/local/lib/python3.8/dist-packages/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/hooks/evaluation.py", line 262, in after_train_iter
    self._do_evaluate(runner)
  File "/usr/local/lib/python3.8/dist-packages/mmseg/core/evaluation/eval_hooks.py", line 117, in _do_evaluate
    results = multi_gpu_test(
  File "/usr/local/lib/python3.8/dist-packages/mmseg/apis/test.py", line 208, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1158, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1112, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/segmentors/base.py", line 110, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmseg/models/segmentors/base.py", line 84, in forward_test
    ori_shapes = [_['ori_shape'] for _ in img_meta]
TypeError: 'DataContainer' object is not iterable
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 431 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 432) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 770, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-10_08:38:59
  host      : f7163cd66158
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 432)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
root@f7163cd66158:/data/InternImage/segmentation# /usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 28 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by lxj1999** [comment]
I meet the same problem, have you solved it?

**Comment by wujiang0156** [comment]
me to

**Comment by wujiang0156** [comment]
help? help? @
