### ISSUE TITLE
 'ChaseDB1Dataset' object has no attribute 'file_client'

### ISSUE THREAD

**Issue by leizhenyu-lzy** [open-mmlab/mmsegmentation#2878]
my env:
```
mmcv                                 2.0.0                /home/lzy/Project/mmcv
mmengine                             0.7.0
mmsegmentation                       1.0.0                /home/lzy/Project/mmsegmentation
```

when i try to use chaseDB1 in command line i encounter this problem

command:
```
python3 tools/train.py configs/unet/unet_s5-d16_deeplabv3_4xb4-40k_chase-db1-128x128.py --work-dir log_info
```

problem:
```
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 100, in main
    runner.train()
  File "/home/lzy/miniconda3/envs/pytorch/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1667, in train
    self._train_loop = self.build_train_loop(
  File "/home/lzy/miniconda3/envs/pytorch/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1459, in build_train_loop
    loop = LOOPS.build(
  File "/home/lzy/miniconda3/envs/pytorch/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/lzy/miniconda3/envs/pytorch/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AttributeError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: class `ChaseDB1Dataset` in mmseg/datasets/chase_db1.py: 'ChaseDB1Dataset' object has no attribute 'file_client'
```

how can i solve this problem? i try to update the mmengine, but it doesn't work

**Comment by joljal** [comment]
Me too, but I haven't found a solution

**Comment by ChenglongWang** [comment]
Same issue occurred on HRFdataset.

**Comment by gjustin40** [comment]
I don't know if this is the best way, but I solved the same problem as follows

in each dataset config file(ex. [chase_db1.py](https://github.com/open-mmlab/mmsegmentation/blob/b600f7cb26829afa2c785af41755391626fbb446/mmseg/datasets/chase_db1.py#L30) or [hrf.py](https://github.com/open-mmlab/mmsegmentation/blob/b600f7cb26829afa2c785af41755391626fbb446/mmseg/datasets/hrf.py#L30)), there is such line at the bottom.
```python
# remove
assert self.file_client.exists(self.data_prefix['img_path'])
```

just remove it.
best.

**Comment by louan1998** [comment]
> I don't know if this is the best way, but I solved the same problem as follows
> 
> in each dataset config file(ex. [chase_db1.py](https://github.com/open-mmlab/mmsegmentation/blob/b600f7cb26829afa2c785af41755391626fbb446/mmseg/datasets/chase_db1.py#L30) or [hrf.py](https://github.com/open-mmlab/mmsegmentation/blob/b600f7cb26829afa2c785af41755391626fbb446/mmseg/datasets/hrf.py#L30)), there is such line at the bottom.
> 
> ```python
> # remove
> assert self.file_client.exists(self.data_prefix['img_path'])
> ```
> 
> just remove it. best.



> I don't know if this is the best way, but I solved the same problem as follows
> 
> in each dataset config file(ex. [chase_db1.py](https://github.com/open-mmlab/mmsegmentation/blob/b600f7cb26829afa2c785af41755391626fbb446/mmseg/datasets/chase_db1.py#L30) or [hrf.py](https://github.com/open-mmlab/mmsegmentation/blob/b600f7cb26829afa2c785af41755391626fbb446/mmseg/datasets/hrf.py#L30)), there is such line at the bottom.
> 
> ```python
> # remove
> assert self.file_client.exists(self.data_prefix['img_path'])
> ```
> 
> just remove it. best.

It worked!!! but why???
