### ISSUE TITLE
mmcls import报错，不知道是不是版本的问题？

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmsegmentation#2881]
我的环境：
torch                        1.10.0
torchaudio                   0.10.0+cu113
torchlibrosa                 0.0.9
torchmetrics                 0.11.0
torchvision                  0.11.1+cu113
mmaction2                    0.24.1              /mnt/bn/shuaizzz/codes/mmaction2
mmcls                        0.25.0
mmengine                     0.7.2
mmpretrain                   1.0.0rc7            /mnt/bn/shuaizzz/codes/mmclassification

错误详情：
1、先是报了mmcv版本错误：
mmcls文件/usr/local/lib/python3.7/dist-packages/mmcls/__init__.py，第51行要求mmcv最高版本为：mmcv_maximum_version = '1.9.0'。
但是mmseg文件/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/__init__.py，第10行要求mmcv最低版本为：MMCV_MIN = '2.0.0rc4'。
两个版本要求相冲突，于是我手动修改最高版本为mmcv_maximum_version = '2.0.0'后，这个错误貌似skip了。

2、但是接下来又报了下面的错误：
torch.distributed: socket accepted connection from 127.0.0.1:50896. (To turn off this message, please set BYTED_TORCH_C10D_LOG_LEVEL={WARNING, ERROR, CRITICAL})
torch.distributed: socket accepted connection from 127.0.0.1:50898. (To turn off this message, please set BYTED_TORCH_C10D_LOG_LEVEL={WARNING, ERROR, CRITICAL})
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
      File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
imported_tmp = import_module(imp)    
    imported_tmp = import_module(imp)  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
imported_tmp = import_module(imp)

  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
imported_tmp = import_module(imp)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/__init__.py", line 2, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/__init__.py", line 2, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/__init__.py", line 2, in <module>
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
          File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
from .backbones import *  # noqa: F401,F403from .backbones import *  # noqa: F401,F403

  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/__init__.py", line 2, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/__init__.py", line 2, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
    from .backbones import *  # noqa: F401,F403  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/__init__.py", line 2, in <module>

      File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/__init__.py", line 2, in <module>
from .alexnet import AlexNet    
from .alexnet import AlexNet
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/alexnet.py", line 4, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/alexnet.py", line 4, in <module>
    from .alexnet import AlexNet
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/alexnet.py", line 4, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/__init__.py", line 2, in <module>
    from .alexnet import AlexNet
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/alexnet.py", line 4, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/__init__.py", line 2, in <module>
    from ..builder import BACKBONES    
from ..builder import BACKBONES  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/builder.py", line 2, in <module>

  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/builder.py", line 2, in <module>
    from .alexnet import AlexNet
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/alexnet.py", line 4, in <module>
    from .alexnet import AlexNet
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/alexnet.py", line 4, in <module>
    from ..builder import BACKBONES
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/builder.py", line 2, in <module>
    from .alexnet import AlexNet
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/alexnet.py", line 4, in <module>
    from .alexnet import AlexNet
  File "/usr/local/lib/python3.7/dist-packages/mmcls/models/backbones/alexnet.py", line 4, in <module>
    from mmcv.cnn import MODELS as MMCV_MODELS
ImportError: cannot import name 'MODELS' from 'mmcv.cnn' (/usr/local/lib/python3.7/dist-packages/mmcv/cnn/__init__.py)

During handling of the above exception, another exception occurred:

from mmcv.cnn import MODELS as MMCV_MODELS
During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmengine/config/config.py", line 181, in fromfile
ImportError  File "/usr/local/lib/python3.7/dist-packages/mmengine/config/config.py", line 181, in fromfile
  File "/usr/local/lib/python3.7/dist-packages/mmengine/config/config.py", line 181, in fromfile
: cannot import name 'MODELS' from 'mmcv.cnn' (/usr/local/lib/python3.7/dist-packages/mmcv/cnn/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmengine/config/config.py", line 181, in fromfile
        import_modules_from_strings(**cfg_dict['custom_imports'])import_modules_from_strings(**cfg_dict['custom_imports'])

  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
      File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/usr/local/lib/python3.7/dist-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
        raise ImportError(f'Failed to import {imp}')raise ImportError(f'Failed to import {imp}')

ImportError    ImportError: from mmcv.cnn import MODELS as MMCV_MODELS: Failed to import mmcls.models
Failed to import mmcls.modelsImportError

**Comment by Ezra-Yu** [comment]
try 
```
pip uninstall mmcls, mmpretrain
pip install mmcls==1.0.0rc6
```

next version of mmseg will use mmpretrain instead of mmcls

**Comment by shuaizzZ** [comment]
> try
> 
> ```
> pip uninstall mmcls, mmpretrain
> pip install mmcls==1.0.0rc6
> ```
> 
> next version of mmseg will use mmpretrain instead of mmcls

Tried your suggestion, but it didn't solve, a new error appeared.

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/./tools/zs_train.py", line 11, in <module>
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/./tools/zs_train.py", line 11, in <module>
Traceback (most recent call last):
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/./tools/zs_train.py", line 11, in <module>
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/./tools/zs_train.py", line 11, in <module>
Traceback (most recent call last):
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/./tools/zs_train.py", line 11, in <module>
Traceback (most recent call last):
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/./tools/zs_train.py", line 11, in <module>
Traceback (most recent call last):
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/./tools/zs_train.py", line 11, in <module>
    from mmseg.registry import RUNNERS
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    from mmseg.registry import RUNNERS
    from mmseg.registry import RUNNERS  File "/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/__init__.py", line 59, in <module>

      File "/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/__init__.py", line 59, in <module>
from mmseg.registry import RUNNERS
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    from mmseg.registry import RUNNERS
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    from mmseg.registry import RUNNERS
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    from mmseg.registry import RUNNERS

  File "/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/__init__.py", line 59, in <module>
    mmcv_version = digit_version(mmcv.__version__)
AttributeError: module 'mmcv' has no attribute '__version__'
    mmcv_version = digit_version(mmcv.__version__)
    AttributeError    mmcv_version = digit_version(mmcv.__version__): mmcv_version = digit_version(mmcv.__version__)    
module 'mmcv' has no attribute '__version__'
mmcv_version = digit_version(mmcv.__version__)AttributeErrorAttributeError

**Comment by shuaizzZ** [comment]
> try
> 
> ```
> pip uninstall mmcls, mmpretrain
> pip install mmcls==1.0.0rc6
> ```
> 
> next version of mmseg will use mmpretrain instead of mmcls

my mmcv version is 2.0.0

**Comment by Ezra-Yu** [comment]
which version mmseg do you use? 1.0.0?

**Comment by Xie-Muxi** [comment]
> 需要查看一下mmseg的版本，是0.x还是1.x?
> 
> 最近OpenMMLab有次大的更新，从0.x 到 1.x(有些从1.x 到2.x)，你最好重新配置一个环境，不然会乱。

应该是一些模块需要调用mmcls，但是现在的mmseg需要mmcv2.0，mmcls又没有mmcv2.0的版本，直接装mmpretrain又不能给需要mmcls的模块用，现在就很尴尬，除非全部都配0.x的版本

**Comment by shuaizzZ** [comment]
> 

mmeg是1.0.0

**Comment by shuaizzZ** [comment]
> > 需要查看一下mmseg的版本，是0.x还是1.x?
> > 最近OpenMMLab有次大的更新，从0.x 到 1.x(有些从1.x 到2.x)，你最好重新配置一个环境，不然会乱。
> 
> 应该是一些模块需要调用mmcls，但是现在的mmseg需要mmcv2.0，mmcls又没有mmcv2.0的版本，直接装mmpretrain又不能给需要mmcls的模块用，现在就很尴尬，除非全部都配0.x的版本

感觉是这个问题，希望尽快修复啊，版本有点混乱。。。。

**Comment by shuaizzZ** [comment]
> 

按照你的方法，跑通了！！
