### ISSUE TITLE
test.py No module named 'mmseg.datasets.samplers'

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmsegmentation#2883]
my environment list:
- branch: dev-1.x
- mmcv :  2.0.0rc4 
- mmdet : 3.0.0rc6
- mmengine  :  0.7.0     
- mmsegmentation  : 1.0.0rc6  

command:
```
python /opt/mmsegmentation/tools/test.py /opt/mmsegmentation/configs/pspnet/pspnet_r50-d8_4xb2-40k_cityscapes-512x1024.py pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth  --out work-dir
```

Traceback:
```
Traceback (most recent call last):
  File "/opt/mmsegmentation/mmengine/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/mmsegmentation/mmengine/mmengine/runner/loops.py", line 410, in __init__
    super().__init__(runner, dataloader)
  File "/opt/mmsegmentation/mmengine/mmengine/runner/base_loop.py", line 27, in __init__
    dataloader, seed=runner.seed, diff_rank_seed=diff_rank_seed)
  File "/opt/mmsegmentation/mmengine/mmengine/runner/runner.py", line 1360, in build_dataloader
    default_args=dict(dataset=dataset, seed=sampler_seed))
  File "/opt/mmsegmentation/mmengine/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/mmsegmentation/mmengine/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/opt/mmsegmentation/mmengine/mmengine/registry/registry.py", line 442, in get
    self.import_from_location()
  File "/opt/mmsegmentation/mmengine/mmengine/registry/registry.py", line 376, in import_from_location
    import_module(loc)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mmseg.datasets.samplers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mmsegmentation/tools/test.py", line 123, in <module>
    main()
  File "/opt/mmsegmentation/tools/test.py", line 119, in main
    runner.test()
  File "/opt/mmsegmentation/mmengine/mmengine/runner/runner.py", line 1745, in test
    self._test_loop = self.build_test_loop(self._test_loop)  # type: ignore
  File "/opt/mmsegmentation/mmengine/mmengine/runner/runner.py", line 1553, in build_test_loop
    evaluator=self._test_evaluator))
  File "/opt/mmsegmentation/mmengine/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/mmsegmentation/mmengine/mmengine/registry/build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
ModuleNotFoundError: class `TestLoop` in mmengine/runner/loops.py: No module named 'mmseg.datasets.samplers'
```

**Comment by zhangzhengbin96** [comment]
我也遇到了同样的问题，如果有解决办法的话可以通知一声

**Comment by pekopoke** [comment]
> 我也遇到了同样的问题，如果有解决办法的话可以通知一声

After re-executing, I found that the problem has been resolved.
