### ISSUE TITLE
自带的配置文件都不能兼容版本？

### ISSUE THREAD

**Issue by Xie-Muxi** [open-mmlab/mmsegmentation#2884]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/97820350/231421149-8c26640c-3684-4902-8d5f-9a6b2580fc8b.png">

python tools/train.py configs/convnext/convnext-tiny_upernet_8xb2-amp-160k_ade20k-512x512.py

Traceback (most recent call last):
  File "/root/PycharmProjects/xmx/mmsegmentation/tools/train.py", line 104, in <module>
    main()
  File "/root/PycharmProjects/xmx/mmsegmentation/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
  File "/root/anaconda3/envs/XMX/lib/python3.9/site-packages/mmengine/config/config.py", line 181, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/root/anaconda3/envs/XMX/lib/python3.9/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/root/anaconda3/envs/XMX/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/anaconda3/envs/XMX/lib/python3.9/site-packages/mmcls/__init__.py", line 55, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.4.2, <=1.9.0.

**Comment by Xie-Muxi** [comment]
解决

```shell
pip uninstall mmcv mmcv-full mmcls mmpretrain
mim install mmcv
pip install mmcls==1.0.0rc6
```
