### ISSUE TITLE
模型导出错误：'EncoderDecoder' object has no attribute 'forward_dummy'

### ISSUE THREAD

**Issue by shuaizzZ** [open-mmlab/mmsegmentation#2915]
1、先是报如下错误：
Traceback (most recent call last):
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/tools/deployment/pytorch2torchscript_defect.py", line 201, in <module>
    segmentor = build_segmentor(
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/mmseg/models/builder.py", line 49, in build_segmentor
    assert cfg.get('test_cfg') is None or test_cfg is None, \
AssertionError: test_cfg specified in both outer field and model field 

我通过修改pytorch2torchscript.py文件的segmentor定义为test_cfg=None解决了这个报错。

2、然后又报错：
KeyError: 'SegDataPreProcessor is not in the model registry. Please check whether the value of `SegDataPreProcessor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

我通过修改pytorch2torchscript.py文件，添加如下两行，解决了上述报错：
from mmseg.utils import register_all_modules
register_all_modules()

3、随后又报错：
Traceback (most recent call last):
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/tools/deployment/pytorch2torchscript_defect.py", line 213, in <module>
    pytorch2libtorch(
  File "/mnt/bn/shuaizzz/codes/mmsegmentation/tools/deployment/pytorch2torchscript_defect.py", line 125, in pytorch2libtorch
    model.forward = model.forward_dummy
  File "/root/miniconda3/envs/mmseg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'EncoderDecoder' object has no attribute 'forward_dummy'

请问该如何解决？

**Comment by earthpopo** [comment]
I also have the same issue, I think it's a version issue. You can return to version 0. x or wait for updates

**Comment by sammilei** [comment]
Got the same issue with trained segmenter tiny .pth trained on mmcv=1.6.0 to .torchscript on mmcv=2.0.0! It also failed in mmcv=1.6.0 but I forgot what that issue it was.
```
Traceback (most recent call last):
  File "tools/deployment/pytorch2torchscript.py", line 180, in <module>
    pytorch2libtorch(
  File "tools/deployment/pytorch2torchscript.py", line 117, in pytorch2libtorch
    model.forward = model.forward_dummy
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'EncoderDecoder' object has no attribute 'forward_dummy'
```

**Comment by successAI** [comment]
> I also met the same problem. Have you solved it

**Comment by earthpopo** [comment]
> > I also met the same problem. Have you solved it？
you can try the mmdeploy,it successfully exported the onnx model

**Comment by ZiAn-Su** [comment]
delete 'model.forward = model.forward_dummy' in pytorch2torchscript.py

**Comment by nothingws** [comment]
me too

**Comment by nothingws** [comment]
> We recommend using English or English & Chinese for issues so that we could have broader discussion.
May I know if you have resolved the issue?

**Comment by geoeo** [comment]
This worked for me.
