### ISSUE TITLE
Stable installation guide for MMCV==1.7.1

### ISSUE THREAD

**Issue by Arshadoid** [open-mmlab/mmsegmentation#2916]
Hi Everyone, 

I'm trying to follow simple installation [guide](https://github.com/open-mmlab/mmsegmentation/blob/0.x/docs/en/get_started.md#installation) for V.0, to utilize MMCV 1.7.1, butI get stuck at demo inference step.

```
C:\ProgramData\Anaconda3\envs\mmsegmentation\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "demo/image_demo.py", line 6, in <module>
    from mmseg.apis import inference_model, init_model, show_result_pyplot
  File "c:\users\arsha\sysc5903\mmsegmentation\mmseg\__init__.py", line 61, in <module>
    assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4.

```
Was wondering if you could suggest how to overcome this issue?

**Comment by LhysX** [comment]
The same problem, have you solved it?

**Comment by LhysX** [comment]
The same problem but my mmseg's version is 1.1.2, have you solved it?

**Comment by Jessieh3k9** [comment]
Try reinstalling mmcv? Uninstall mmcv-full and use mmcv2.0.0 or above.

**Comment by erencoskunofficial** [comment]
I got a similiar error and I fixed it. You should install mmcv==2.0.0rc4 and mmcv_full==1.7.1 and pip install ftfy
