### ISSUE TITLE
a error when try to train

### ISSUE THREAD

**Issue by a5336033** [open-mmlab/mmsegmentation#2937]
Hello, when I try to train, I always report the following error, I use git down code, and it has not been modified, can you answer my doubts?

raceback (most recent call last):
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/tian/PycharmProjects/mmsegmentation/mmseg/datasets/voc.py", line 39, in __init__
    assert fileio.exists(self.data_prefix['img_path'],
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/dataset/dataset_wrapper.py", line 46, in __init__
    self.datasets.append(DATASETS.build(dataset))
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `PascalVOCDataset` in mmseg/datasets/voc.py: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/runner/loops.py", line 219, in __init__
    super().__init__(runner, dataloader)
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `ConcatDataset` in mmengine/dataset/dataset_wrapper.py: class `PascalVOCDataset` in mmseg/datasets/voc.py: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tian/PycharmProjects/mmsegmentation/tools/train.py", line 104, in <module>
    main()
  File "/home/tian/PycharmProjects/mmsegmentation/tools/train.py", line 100, in main
    runner.train()
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1672, in train
    self._train_loop = self.build_train_loop(
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1464, in build_train_loop
    loop = LOOPS.build(
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/tian/miniconda3/envs/mmseg/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: class `ConcatDataset` in mmengine/dataset/dataset_wrapper.py: class `PascalVOCDataset` in mmseg/datasets/voc.py:

**Comment by xiexinch** [comment]
Hi @a5336033,
Did you follow our [data preparing guide](https://mmsegmentation.readthedocs.io/en/latest/user_guides/2_dataset_prepare.html#pascal-voc) to preprocess the data?

**Comment by xiexinch** [comment]
Closing the issue, as there is no activity for a while.
We hope your issue has been resolved. 
If not, please feel free to open a new one.
