### ISSUE TITLE
pytorch2torchscript.py error at test_cfg

### ISSUE THREAD

**Issue by sammilei** [open-mmlab/mmsegmentation#2939]
pytorch2torchscript.py error at test_cfg
====
**Describe the bug**
I am running mmseg Colab tutorial to train with mask2former with the default `mask2former_r50_8xb2-160k_ade20k-512x512.py` and downloaded ADE20k dataset accordingly.
Training worked well and I tried to **convert pytorch to torchscript** but it failed with the error below: 
```
/content/mmsegmentation/mmseg/models/builder.py:44: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
Traceback (most recent call last):
  File "/content/mmsegmentation/tools/deployment/pytorch2torchscript.py", line 171, in <module>
    segmentor = build_segmentor(
  File "/content/mmsegmentation/mmseg/models/builder.py", line 49, in build_segmentor
    assert cfg.get('test_cfg') is None or test_cfg is None, \
AssertionError: test_cfg specified in both outer field and model field
```
The config py has `test_cfg = dict(type='TestLoop')` and the `pytorch2torchscript.py` ran it as
```
# build the model and load checkpoint
cfg.model.train_cfg = None
segmentor = build_segmentor(
    cfg.model, train_cfg=None, test_cfg=cfg.get('test_cfg'))
```
**Reproduction**

1. What command or script did you run?

   ```none
   !python3 tools/deployment/pytorch2torchscript.py /content/mmsegmentation/work_dirs/mask2former_r50_8xb2-160k_ade20k-512x512/mask2former_r50_8xb2-160k_ade20k-512x512.py --checkpoint /content/mmsegmentation/work_dirs/mask2former_r50_8xb2-160k_ade20k-512x512/iter_200.pth --shape 594 960 --show
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified? - No.

**Environment**
```
sys.platform: linux
Python: 3.9.16 (main, Dec  7 2022, 01:11:51) [GCC 9.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1+cu118
OpenCV: 4.7.0
MMEngine: 0.7.2
MMSegmentation: 1.0.0+e566f98
```
Plus, mmdet is `mmdet-3.0.0`

Thank you in advance!!

**Comment by peanutpaste** [comment]
I also have this problem with mmseg1.0.0 and I can't solve it either

**Comment by successAI** [comment]
Me,too

**Comment by nothingws** [comment]
> # pytorch2torchscript.py error at test_cfg
> **Describe the bug** I am running mmseg Colab tutorial to train with mask2former with the default `mask2former_r50_8xb2-160k_ade20k-512x512.py` and downloaded ADE20k dataset accordingly. Training worked well and I tried to **convert pytorch to torchscript** but it failed with the error below:
> 
> ```
> /content/mmsegmentation/mmseg/models/builder.py:44: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
>   warnings.warn(
> Traceback (most recent call last):
>   File "/content/mmsegmentation/tools/deployment/pytorch2torchscript.py", line 171, in <module>
>     segmentor = build_segmentor(
>   File "/content/mmsegmentation/mmseg/models/builder.py", line 49, in build_segmentor
>     assert cfg.get('test_cfg') is None or test_cfg is None, \
> AssertionError: test_cfg specified in both outer field and model field
> ```
> 
> The config py has `test_cfg = dict(type='TestLoop')` and the `pytorch2torchscript.py` ran it as
> 
> ```
> # build the model and load checkpoint
> cfg.model.train_cfg = None
> segmentor = build_segmentor(
>     cfg.model, train_cfg=None, test_cfg=cfg.get('test_cfg'))
> ```
> 
> **Reproduction**
> 
> 1. What command or script did you run?
>    ```
>    !python3 tools/deployment/pytorch2torchscript.py /content/mmsegmentation/work_dirs/mask2former_r50_8xb2-160k_ade20k-512x512/mask2former_r50_8xb2-160k_ade20k-512x512.py --checkpoint /content/mmsegmentation/work_dirs/mask2former_r50_8xb2-160k_ade20k-512x512/iter_200.pth --shape 594 960 --show
>    ```
> 2. Did you make any modifications on the code or config? Did you understand what you have modified? - No.
> 
> **Environment**
> 
> ```
> sys.platform: linux
> Python: 3.9.16 (main, Dec  7 2022, 01:11:51) [GCC 9.4.0]
> CUDA available: True
> numpy_random_seed: 2147483648
> GPU 0: Tesla T4
> CUDA_HOME: /usr/local/cuda
> NVCC: Cuda compilation tools, release 11.8, V11.8.89
> GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> PyTorch: 2.0.0+cu118
> PyTorch compiling details: PyTorch built with:
>   - GCC 9.3
>   - C++ Version: 201703
>   - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - LAPACK is enabled (usually provided by MKL)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 11.8
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
>   - CuDNN 8.7
>   - Magma 2.6.1
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 
> 
> TorchVision: 0.15.1+cu118
> OpenCV: 4.7.0
> MMEngine: 0.7.2
> MMSegmentation: 1.0.0+e566f98
> ```
> 
> Plus, mmdet is `mmdet-3.0.0`
> 
> Thank you in advance!!

May I know if you have resolved the issue?

**Comment by sammilei** [comment]
I haven't solved this issue. I am testing this feature with the new code again but no luck. @xiexinch @nothingws

**Comment by aenoca** [comment]
To solve this one, one simply needs to add the following at the top of pytorch2torchscript.py

'''
from mmseg.utils import register_all_modules
register_all_modules()
'''
