### ISSUE TITLE
A bug in tools/analysis_tools/get_flops.py

### ISSUE THREAD

**Issue by ZJLauu** [open-mmlab/mmsegmentation#2958]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
(ValueError: "input_shape" and "inputs" cannot be both set.) occurs while running tools/analysis_tools/get_flops.py

**Reproduction**

1. What command or script did you run?

 ```none
python tools/analysis_tools/get_flops.py config.py
```
or
 ```none
python tools/analysis_tools/get_flops.py config.py --shape (512, 512)
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
3. What dataset did you use?
customdataset

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.

sys.platform: win32
Python: 3.9.0 (default, Nov 15 2020, 08:30:55) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4080
CUDA_HOME: D:\Program Files\NVIDAI GPU Computing Toolkit\CUDA\v11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32216.1 版
GCC: n/a
PyTorch: 2.0.0+cu118
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 193431937
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm
_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO
_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=O
FF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.15.1+cu118
OpenCV: 4.7.0
MMEngine: 0.7.2
MMSegmentation: 1.0.0+462fad8

**Error traceback**

If applicable, paste the error trackback here.

```none
d:\pythonproject\mmsegmentation\mmseg\models\builder.py:36: UserWarning: ``build_loss`` would be deprecated soon, please use ``mmseg.registry.MODELS.build()``
  warnings.warn('``build_loss`` would be deprecated soon, please use '
Traceback (most recent call last):
  File "D:\Pythonproject\mmsegmentation\tools\analysis_tools\get_flops.py", line 124, in <module>
    main()
  File "D:\Pythonproject\mmsegmentation\tools\analysis_tools\get_flops.py", line 104, in main
    result = inference(args, logger)
  File "D:\Pythonproject\mmsegmentation\tools\analysis_tools\get_flops.py", line 87, in inference
    outputs = get_model_complexity_info(
  File "d:\pythonproject\mmengine\mmengine\analysis\print_helper.py", line 725, in get_model_complexity_info
    raise ValueError('"input_shape" and "inputs" cannot be both set.')
ValueError: "input_shape" and "inputs" cannot be both set.

```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by AI-Tianlong** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/e64548fda0221ad708f5da29dc907e51a644c345/tools/analysis_tools/get_flops.py#L89

**Comment by AI-Tianlong** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/e64548fda0221ad708f5da29dc907e51a644c345/tools/analysis_tools/get_flops.py#L89
Modifying `input_shape = None` might be useful.

**Comment by AI-Tianlong** [comment]
It seems that the issue has been fixed in the latest version. Please update your mmseg to the latest version.

**Comment by wujiang0156** [comment]
@xiexinch @AI-Tianlong @ZJLauu I have the same bug and I use the latest version.  How to fix
![image](https://github.com/open-mmlab/mmsegmentation/assets/7938373/7c873e65-2567-4c8f-8f64-241b24fcdc77)

**Comment by kaizhong2021** [comment]
I meet the same error

**Comment by twsha** [comment]
> @xiexinch @AI-Tianlong @ZJLauu I have the same bug and I use the latest version. How to fix ![image](https://private-user-images.githubusercontent.com/7938373/248236065-7c873e65-2567-4c8f-8f64-241b24fcdc77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjYwMDcsIm5iZiI6MTcwNjE2NTcwNywicGF0aCI6Ii83OTM4MzczLzI0ODIzNjA2NS03Yzg3M2U2NS0yNTY3LTRjOGYtOGY2NC0yNDFiMjRmY2RjNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDY1NTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjgzZjMxMjdiNzgyZDIxM2EwNjg2N2MyYjgxNzkwZDIxNWEyZWRjNGY2MTJkNzBmNDZiYWJjYzI4OGRjZmVkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f1vPXYU7ffvEYGaZMI3tWLlW5eRc0jURi3QfgG2PSFc) the bug is : ![image](https://private-user-images.githubusercontent.com/7938373/248236918-4e33db89-365d-4c5b-981b-c600f9b8f8af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjYwMDcsIm5iZiI6MTcwNjE2NTcwNywicGF0aCI6Ii83OTM4MzczLzI0ODIzNjkxOC00ZTMzZGI4OS0zNjVkLTRjNWItOTgxYi1jNjAwZjliOGY4YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDY1NTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE3ZDExMDFmODdkNTdkOTVkOTVkYmQ0YmJkYzYzYTczMDAzMDhkMzY4YTBlZWM3ZmZjMTVhMDQzYWYzOTM4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TgP1U6ILvHkRs_MmdOrIZ39GEbcWN_r7aK3eVqiYgr4)
> 
> ---->
> 
> ![image](https://private-user-images.githubusercontent.com/7938373/248237032-d08e05c0-049c-4f8b-9349-6c0cd57c5ae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjYwMDcsIm5iZiI6MTcwNjE2NTcwNywicGF0aCI6Ii83OTM4MzczLzI0ODIzNzAzMi1kMDhlMDVjMC0wNDljLTRmOGItOTM0OS02YzBjZDU3YzVhZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDY1NTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjY0NmE2M2FkMTVlYmE5YjQ2YzQzYzIwMjZjMjhlMmMzODlhNmY1YzZlOWU3ODA3N2U4MTExOWVmYzEyMzJkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4L45Hn2cGodpjWXu7yqEOx0MVgmt5naLQw7ZCDbU368) Icommented this part of the code:
> 
> ![image](https://private-user-images.githubusercontent.com/7938373/248240074-ea8be22a-3ad4-44ef-af7f-bd3bea1ec9ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjYwMDcsIm5iZiI6MTcwNjE2NTcwNywicGF0aCI6Ii83OTM4MzczLzI0ODI0MDA3NC1lYThiZTIyYS0zYWQ0LTQ0ZWYtYWY3Zi1iZDNiZWExZWM5ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDY1NTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBjNjhjZTliYjk4OTVhMzY5Mjc5ZTJkOGUxZGNhNmYxNjI0YWM5MTM4YmMwYWYwZTY4OTc4MDc4MmU2YzY3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ebeZpgxBA2BUwlWpqBeRgu_rM-6CxF7nYYKW3kK2rYU) or ![image](https://private-user-images.githubusercontent.com/7938373/248237853-c2bc76f0-0d47-4966-8122-b34953505b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjYwMDcsIm5iZiI6MTcwNjE2NTcwNywicGF0aCI6Ii83OTM4MzczLzI0ODIzNzg1My1jMmJjNzZmMC0wZDQ3LTQ5NjYtODEyMi1iMzQ5NTM1MDViOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDY1NTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzAxOTIzMjlmNjlmNDg2OTVmYTAxZTFiMzY0OTcwZTAwMWVhMzk2OTFkNTUxMjdjOWZmMGZmNTE0Yjg1ZTZkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.klO7-w1597HSYJDwlMPdYPkLreF6-eLXS3PwltPue_g)
> 
> the result is ![image](https://private-user-images.githubusercontent.com/7938373/248238113-69409183-e635-4ccd-ae12-0f052aa690c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjYwMDcsIm5iZiI6MTcwNjE2NTcwNywicGF0aCI6Ii83OTM4MzczLzI0ODIzODExMy02OTQwOTE4My1lNjM1LTRjY2QtYWUxMi0wZjA1MmFhNjkwYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDY1NTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI5NTNiN2JjYTZhM2ZkNjE2ZjRiOWEwODQ5N2E2M2Q0ZWNhNGNiZGY1NzZjMjIzMDI5NTFmMjBhMTlhMzBmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Rga1GZ3csjN9pWRPwOAj9T_TbG8Gf7GqTwcBIyEbpdI)

hi,I also tried my model through the code you modified. The 4-channel input of my model still reported an error after changing the inputs to none. Could it be that the 4-channel cannot be calculated?
![image](https://github.com/open-mmlab/mmsegmentation/assets/86956907/d0da057f-eb68-4931-9d18-356404e25f2e)
