### ISSUE TITLE
使用convnext作为backbone来进行分割实验出现的问题

### ISSUE THREAD

**Issue by ychenghan** [open-mmlab/mmsegmentation#2991]
以下是报错信息：
Traceback (most recent call last):
  File "/export/home/huhaigen/.miniconda3/envs/openmmlab_ych/lib/python3.8/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/export/home/huhaigen/.miniconda3/envs/openmmlab_ych/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mmcls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/home/huhaigen/.miniconda3/envs/openmmlab_ych/lib/python3.8/site-packages/mmengine/config/config.py", line 181, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/export/home/huhaigen/.miniconda3/envs/openmmlab_ych/lib/python3.8/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import mmcls.models

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
  File "/export/home/huhaigen/.miniconda3/envs/openmmlab_ych/lib/python3.8/site-packages/mmengine/config/config.py", line 183, in fromfile
    raise ImportError('Failed to custom import!') from e
ImportError: Failed to custom import!

我运行的代码是：python tools/train.py configs/convnext/convnext-base_upernet_8xb2-amp-160k_ade20k-512x512.py

**Comment by ychenghan** [comment]
请问，该报错是否意味着我需要在我的环境中安装mmcls，但mmclassfication项目已经改名为mmpretrain了，我需要怎么做

**Comment by ychenghan** [comment]
问题已解决，我修改了config文件中导入的路径，将原来的mmcls.ConvNeXt修改为了mmpretrain.ConvNeXt，并且在环境中下载mmpr包后，问题就解决了。官方可以考虑将config文件中涉及到mmcls的（例如config中使用convnext作为backbone部分的网络）统一改为mmpretrain。

**Comment by VividLe** [comment]
First, install [mmpretrain](https://mmpretrain.readthedocs.io/zh_CN/latest/get_started.html#id2)
Then, modify `mmcls` into `mmpretrain`.

**Comment by ztfmars** [comment]
> 

mmpr的权重和mmcls是一样的吧？我看mmpr那边的下载链接也是原来的mmcls的，好像没变
