### ISSUE TITLE
Unable to download SegFormer's 'pretrain/mit_b0.pth'

### ISSUE THREAD

**Issue by danishnazir** [open-mmlab/mmsegmentation#2992]
Hi,

**Describe the bug**
How to download  `pretrain/mit_b0.pth` for SegFormer? Please tell me the download link?

**Reproduction**

1. What command or script did you run?

   ```
   python train.py /content/mmsegmentation/configs/segformer/segformer_mit-b0_8xb1-160k_cityscapes-1024x1024.py
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
Cityscapes
**Environment**

  ```
sys.platform: linux
Python: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1+cu118
OpenCV: 4.7.0
MMEngine: 0.7.0
MMSegmentation: 1.0.0rc6+0601f28
  ```

**Error traceback**

If applicable, paste the error trackback here.

```
Traceback (most recent call last):
  File "/content/mmsegmentation/train.py", line 104, in <module>
    main()
  File "/content/mmsegmentation/train.py", line 100, in main
    runner.train()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1687, in train
    self._init_model_weights()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 894, in _init_model_weights
    model.init_weights()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/base_module.py", line 130, in init_weights
    m.init_weights()
  File "/content/mmsegmentation/mmseg/models/backbones/mit.py", line 436, in init_weights
    super().init_weights()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/base_module.py", line 138, in init_weights
    initialize(self, pretrained_cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/weight_init.py", line 610, in initialize
    _initialize(module, cp_cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/weight_init.py", line 518, in _initialize
    func(module)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/weight_init.py", line 490, in __call__
    load_checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/checkpoint.py", line 606, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/checkpoint.py", line 518, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/checkpoint.py", line 300, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/checkpoint.py", line 316, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: pretrain/mit_b0.pth can not be found.
```

**Comment by marcelampc** [comment]
Hello, if you go to the original repo [https://github.com/NVlabs/SegFormer](SegFormer), you can find the download link (that is also [HERE](https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia)) for the pretrained weights. Save them in a folder called ```pretrain``` and be it should work.
