### ISSUE TITLE
'EncoderDecoder is not in the model registry.

### ISSUE THREAD

**Issue by MatCorr** [open-mmlab/mmsegmentation#2997]
I am installing mmsegmentation on a sif image exactly as it is recommended on this official [Dockerfile](https://github.com/open-mmlab/mmsegmentation/blob/main/docker/Dockerfile). Here's what I am doing:

```
# Install MMCV
ARG MMCV="2.0.0"
RUN ["/bin/bash", "-c", "pip install openmim"]
RUN ["/bin/bash", "-c", "mim install mmengine"]
RUN ["/bin/bash", "-c", "mim install mmcv==${MMCV}"]

# Install MMSEGMENTATION
RUN git clone -b main https://github.com/open-mmlab/mmsegmentation.git /mmsegmentation
WORKDIR /mmsegmentation
ENV FORCE_CUDA="1"
run pip install -v -e .
```

Yet, when I try to run a training script via Slurm, this is the error I get:

_Traceback (most recent call last):
  File "/mmsegmentation/tools/train.py", line 104, in <module>
    main()
  File "/mmsegmentation/tools/train.py", line 93, in main
    runner = Runner.from_cfg(cfg)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'EncoderDecoder is not in the model registry. Please check whether the value of `EncoderDecoder` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'_

In case it's important, here's the slurm call I am making:

```
IMAGE="path_to_image/image.sif"
CONFIG="path_to_config/config.py"
OUTDIR="path_to_dir/output_dir/"
COMMAND="python -u /mmsegmentation/tools/train.py ${CONFIG} --work-dir ${OUTDIR}"

srun -N 1 singularity exec --nv --pwd /mmsegmentation $IMAGE $COMMAND
```

Can anyone tell me what's wrong? I've been banging my head against this error for quite a while.

**Comment by MatCorr** [comment]
Ok, I fixed this.

I am not sure what was causing the issue, but it turns out that it all worked when rather than placing the config.py file in a random location, I placed it inside the mmsegmentation/configs/setr path.

**Comment by bobleegogogo** [comment]
@openmmlab-bot is there a official singularity file provided for mmsegmentation? for those who run it in HPC

**Comment by bobleegogogo** [comment]
@MatCorr is that possible to share the sif you used for singularity? otherwise a def file would be also very helfpul. Thank you in advance

**Comment by MatCorr** [comment]
@bobleegogogo, I'm sending you the Dockerfile I'm using to generate the SIF. I hope it's helpful!

```
FROM nvcr.io/nvidia/pytorch:23.04-py3

# SLURM PMI2 version 20.11.9
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        bzip2 \
        file \
        make \
        perl \
        tar \
        wget && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir -p /var/tmp && wget -q -nc --no-check-certificate -P /var/tmp https://download.schedmd.com/slurm/slurm-20.11.9.tar.bz2 && \
    mkdir -p /var/tmp && tar -x -f /var/tmp/slurm-20.11.9.tar.bz2 -C /var/tmp -j && \
    cd /var/tmp/slurm-20.11.9 &&   ./configure --prefix=/usr/local/slurm-pmi2 && \
    cd /var/tmp/slurm-20.11.9 && \
    make -C contribs/pmi2 install && \
    rm -rf /var/tmp/slurm-20.11.9 /var/tmp/slurm-20.11.9.tar.bz2

# Install MMCV
ARG MMCV="2.0.0"
RUN ["/bin/bash", "-c", "pip install openmim"]
RUN ["/bin/bash", "-c", "mim install mmengine"]
RUN ["/bin/bash", "-c", "mim install mmcv==${MMCV}"]

# Install MMSEGMENTATION
RUN git clone -b main https://github.com/open-mmlab/mmsegmentation.git /mmsegmentation
WORKDIR /mmsegmentation
ENV FORCE_CUDA="1"
run pip install -v -e .
```

**Comment by bobleegogogo** [comment]
@MatCorr great, really appreciate it ;)

**Comment by Sere1nz** [comment]
I didnt build mmsegmentation from source. Where should I place the config file? I still get this error. It is so confusing.

**Comment by MatCorr** [comment]
@Sere1nz, if I remember correctly, if you create a new config file, you can't just place it anywhere you feel like. You must place it inside the configs folder of mmsegmentation; that is, somewhere inside one of [these](https://github.com/open-mmlab/mmsegmentation/tree/main/configs)folders.

**Comment by reviewjie** [comment]
> 即使我们将文件放在 configs > any_model > your_config.py下，此问题仍然存在。我不知道是什么原因导致了问题，并检查了所有模型字段。 ![图像](https://private-user-images.githubusercontent.com/23635935/286757953-287bb96a-b76a-4824-a46d-4d9a69c3899e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDgwNjYsIm5iZiI6MTcxMDE0Nzc2NiwicGF0aCI6Ii8yMzYzNTkzNS8yODY3NTc5NTMtMjg3YmI5NmEtYjc2YS00ODI0LWE0NmQtNGQ5YTY5YzM4OTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YTUyYzgxOTZlYjA0YTFjYWZlODU5NTZlN2ViZWVmMGY2YzdjOWE4NGE5ODU4MmZiYjM2ZDU4YmE5ZjZlNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nVPuyP-gwpe6kENVVmlxEUl6OWycJ4Y5Lx_Oy_I3QaM)

I have some problem ,you have  solved it ?

**Comment by reviewjie** [comment]
> 即使我们将文件放在 configs > any_model > your_config.py下，此问题仍然存在。我不知道是什么原因导致了问题，并检查了所有模型字段。 ![图像](https://private-user-images.githubusercontent.com/23635935/286757953-287bb96a-b76a-4824-a46d-4d9a69c3899e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDgwNjYsIm5iZiI6MTcxMDE0Nzc2NiwicGF0aCI6Ii8yMzYzNTkzNS8yODY3NTc5NTMtMjg3YmI5NmEtYjc2YS00ODI0LWE0NmQtNGQ5YTY5YzM4OTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YTUyYzgxOTZlYjA0YTFjYWZlODU5NTZlN2ViZWVmMGY2YzdjOWE4NGE5ODU4MmZiYjM2ZDU4YmE5ZjZlNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nVPuyP-gwpe6kENVVmlxEUl6OWycJ4Y5Lx_Oy_I3QaM)

I have same problem ,you have solved it ?

**Comment by kresimirfijacko** [comment]
try to put 
`default_scope = 'mmseg'`
in your config file

then you can have config file wherever you want

**Comment by reviewjie** [comment]
> try to put `default_scope = 'mmseg'` in your config file
> 
> then you can have config file wherever you want
Thank you,I have solved
