### ISSUE TITLE
SETR Backbone Question - num_layers and num_heads doesn't match those of pre-trained ViT

### ISSUE THREAD

**Issue by MatCorr** [open-mmlab/mmsegmentation#3045]
I am training a SETR model and when checking out the config file more carefully, I stumbled upon something that made me curious.

Here's how the backbone (a ViT) of the model is shown in the config file:

backbone=dict(
        type='VisionTransformer',
        img_size=(512, 512),
        patch_size=16,
        in_channels=3,
        embed_dims=1024,
        **num_layers=24,
        num_heads=16,**
        out_indices=(5, 11, 17, 23),
        drop_rate=0.0,
        norm_cfg=dict(type='LN', eps=1e-06, requires_grad=True),
        with_cls_token=False,
        interpolate_mode='bilinear',
        init_cfg=dict(
            type='Pretrained',
            checkpoint=
            'path_th_pretrained_weights/weights.pth'
        ))

Note that num_layers and num_heads are automatically set to 24 and 16. However, my pre-trained ViT has 12 layers and 12 heads. 

The training works, but I am not getting good results. I basically have two questions:

1. Can this disparity affect training results?

2. If that's the case, how can I change the config file to accurately represent my ViT? I am asking this because I tried to set those values as 12 and 12, but then I was forced to change embed_dims from 1024 to a number divisible by 12. I settled on 1032, but that caused an incompatibility with the next layer of the SETR model: the MLA Neck. The error I am getting can be seen below.

```
Traceback (most recent call last):
  File "/mmsegmentation/tools/train.py", line 104, in <module>
    main()
  File "/mmsegmentation/tools/train.py", line 100, in main
    runner.train()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 278, in run
    self.run_iter(data_batch)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 301, in run_iter
    outputs = self.runner.model.train_step(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mmsegmentation/mmseg/models/segmentors/base.py", line 94, in forward
    return self.loss(inputs, data_samples)
  File "/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 172, in loss
    x = self.extract_feat(inputs)
  File "/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 119, in extract_feat
    x = self.neck(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mmsegmentation/mmseg/models/necks/mla_neck.py", line 105, in forward
    assert len(inputs) == len(self.in_channels)
AssertionError
srun: error: gr13b01n04: task 0: Exited with exit code 1
```

**Comment by MatCorr** [comment]
I did some digging and ended up solving my own problem.

It was related to the out_indices parameter. Since I reduced the num_layers to 12, indices 17 and 23 no longer existed, which was leading to shape mismatch captured by the assert verification. I updated out_indices to 5, 7, 9, 11, and it worked.
