### ISSUE TITLE
Cannot use both '--tta' and '--out' while testing

### ISSUE THREAD

**Issue by nightrain01** [open-mmlab/mmsegmentation#3064]
Cannot use both '--tta' and '--out' while testing.

When use:
`python tools/test.py config.py weight.pth --tta --out ./out_dir`

Will report an error:
```console
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 119, in main
    runner.test()
  File "/home/xxx/.conda/envs/mmseg/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1767, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/home/xxx/.conda/envs/mmseg/lib/python3.8/site-packages/mmengine/runner/loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "/home/xxx/.conda/envs/mmseg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/.conda/envs/mmseg/lib/python3.8/site-packages/mmengine/runner/loops.py", line 455, in run_iter
    self.evaluator.process(data_samples=outputs, data_batch=data_batch)
  File "/home/xxx/.conda/envs/mmseg/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 60, in process
    metric.process(data_batch, _data_samples)
  File "/data/xxx/xxx/mmsegmentation/mmseg/evaluation/metrics/iou_metric.py", line 90, in process
    data_sample['img_path']))[0]
KeyError: 'img_path'
```

**Comment by nightrain01** [comment]
I found a solution, modify the file `mmseg/models/segmentors/seg_tta.py` as follows:

```diff
# Copyright (c) OpenMMLab. All rights reserved.
from typing import List

import torch
from mmengine.model import BaseTTAModel
from mmengine.structures import PixelData

from mmseg.registry import MODELS
from mmseg.structures import SegDataSample
from mmseg.utils import SampleList


@MODELS.register_module()
class SegTTAModel(BaseTTAModel):

    def merge_preds(self, data_samples_list: List[SampleList]) -> SampleList:
        """Merge predictions of enhanced data to one prediction.

        Args:
            data_samples_list (List[SampleList]): List of predictions
                of all enhanced data.

        Returns:
            SampleList: Merged prediction.
        """
        predictions = []
        for data_samples in data_samples_list:
            seg_logits = data_samples[0].seg_logits.data
            logits = torch.zeros(seg_logits.shape).to(seg_logits)
            for data_sample in data_samples:
                seg_logit = data_sample.seg_logits.data
                if self.module.out_channels > 1:
                    logits += seg_logit.softmax(dim=0)
                else:
                    logits += seg_logit.sigmoid()
            logits /= len(data_samples)
            if self.module.out_channels == 1:
                seg_pred = (logits > self.module.decode_head.threshold
                            ).to(logits).squeeze(1)
            else:
                seg_pred = logits.argmax(dim=0)
            data_sample = SegDataSample(
                **{
                    'pred_sem_seg': PixelData(data=seg_pred),
                    'gt_sem_seg': data_samples[0].gt_sem_seg,
+                  'img_path': data_samples[0].img_path
                })
            predictions.append(data_sample)
        return predictions

```
