### ISSUE TITLE
配置mmseg的时候出现问题ModuleNotFoundError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: No module named 'mmseg.datasets.samplers'

### ISSUE THREAD

**Issue by lyk595** [open-mmlab/mmsegmentation#3078]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
/home/lyk/lyk/mmsegmentation-1.0.0rc6/mmseg/datasets/transforms/loading.py:78: UserWarning: `reduce_zero_label` will be deprecated, if you would like to ignore the zero label, please set `reduce_zero_label=True` when dataset initialized
  warnings.warn('`reduce_zero_label` will be deprecated, '
Traceback (most recent call last):
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/runner/loops.py", line 219, in __init__
    super().__init__(runner, dataloader)
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1358, in build_dataloader
    sampler = DATA_SAMPLERS.build(
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/registry/registry.py", line 442, in get
    self.import_from_location()
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/registry/registry.py", line 376, in import_from_location
    import_module(loc)
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mmseg.datasets.samplers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 101, in <module>
    main()
  File "train.py", line 97, in main
    runner.train()
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1687, in train
    self._train_loop = self.build_train_loop(
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1479, in build_train_loop
    loop = LOOPS.build(
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/lyk/anaconda3/envs/mmseg106/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
ModuleNotFoundError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: No module named 'mmseg.datasets.samplers'

**Reproduction**

1. What command or script did you run?

python tools/train.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
我只是在根据教程配置mmseg。

3. What dataset did you use?
voc2012和ade20都出现这种情况。

**Environment**

sys.platform: linux
Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) [GCC 11.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu111
OpenCV: 4.7.0
MMEngine: 0.7.4
MMSegmentation: 1.0.0rc6+

**Comment by xiexinch** [comment]
Hi @lyk595,
可以看一下怎么配置的吗？

**Comment by HePengguang** [comment]
same issue, did you sovle this?

**Comment by 0xrjman** [comment]
I have also encountered the same issue.

My solution was to upgrade mmseg to version `1.1.0` or higher.
version <= v1.0.0rc6
![image](https://github.com/open-mmlab/mmsegmentation/assets/44558375/49da3add-f7ab-423f-a74d-7267bcc371e0)
version >= v1.0.0
![image](https://github.com/open-mmlab/mmsegmentation/assets/44558375/87bc5a46-b152-45b8-b174-0da5f0938350)
