### ISSUE TITLE
TypeError: Mask2FormerHead.forward() missing 1 required positional argument: 'batch_data_samples'

### ISSUE THREAD

**Issue by juri200405** [open-mmlab/mmsegmentation#3105]
Hello, I am looking for a way to forward propagation of `Mask2Former` using `EncoderDecoder`.
However, I get an error that there are not enough arguments for `forward` of `decoder_head`.

sample code:
```python
import torch

from mmseg.registry import MODELS
from mmengine import Config
from mmengine.registry import init_default_scope

cfg = Config.fromfile("mask2former.py")
init_default_scope(cfg.get('default_scope', 'mmseg'))

model = MODELS.build(cfg.model)

image = torch.ones(3, 256, 256).float()
data = {"inputs": [image]}
input = model.data_preprocessor(data)
model(**input)
```

config (not minimum):
```python
num_classes = 5
image_size = (256, 256)

default_scope = 'mmseg'

model = dict(
    type='EncoderDecoder',
    data_preprocessor=dict(
        type='SegDataPreProcessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_val=0,
        seg_pad_val=255,
        size=image_size),
    backbone=dict(
        type='SwinTransformer',
        pretrain_img_size=384,
        embed_dims=192,
        depths=[2, 2, 18, 2],
        num_heads=[6, 12, 24, 48],
        window_size=12,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.3,
        patch_norm=True,
        out_indices=(0, 1, 2, 3),
        with_cp=False,
        frozen_stages=-1,
        init_cfg=dict(
            type='Pretrained',
            checkpoint=
            'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/swin/swin_large_patch4_window12_384_22k_20220412-6580f57d.pth'
        )),
    decode_head=dict(
        type='Mask2FormerHead',
        in_channels=[192, 384, 768, 1536],
        strides=[4, 8, 16, 32],
        feat_channels=256,
        out_channels=256,
        num_classes=num_classes,
        num_queries=100,
        num_transformer_feat_level=3,
        align_corners=False,
        pixel_decoder=dict(
            type='mmdet.MSDeformAttnPixelDecoder',
            num_outs=3,
            norm_cfg=dict(type='GN', num_groups=32),
            act_cfg=dict(type='ReLU'),
            encoder=dict(
                num_layers=6,
                layer_cfg=dict(
                    self_attn_cfg=dict(
                        embed_dims=256,
                        num_heads=8,
                        num_levels=3,
                        num_points=4,
                        im2col_step=64,
                        dropout=0.0,
                        batch_first=True,
                        norm_cfg=None,
                        init_cfg=None),
                    ffn_cfg=dict(
                        embed_dims=256,
                        feedforward_channels=1024,
                        num_fcs=2,
                        ffn_drop=0.0,
                        act_cfg=dict(type='ReLU', inplace=True))),
                init_cfg=None),
            positional_encoding=dict(num_feats=128, normalize=True),
            init_cfg=None),
        enforce_decoder_input_project=False,
        positional_encoding=dict(num_feats=128, normalize=True),
        transformer_decoder=dict(
            return_intermediate=True,
            num_layers=9,
            layer_cfg=dict(
                self_attn_cfg=dict(
                    embed_dims=256,
                    num_heads=8,
                    attn_drop=0.0,
                    proj_drop=0.0,
                    dropout_layer=None,
                    batch_first=True),
                cross_attn_cfg=dict(
                    embed_dims=256,
                    num_heads=8,
                    attn_drop=0.0,
                    proj_drop=0.0,
                    dropout_layer=None,
                    batch_first=True),
                ffn_cfg=dict(
                    embed_dims=256,
                    feedforward_channels=2048,
                    num_fcs=2,
                    act_cfg=dict(type='ReLU', inplace=True),
                    ffn_drop=0.0,
                    dropout_layer=None,
                    add_identity=True)),
            init_cfg=None),
        loss_cls=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=False,
            loss_weight=2.0,
            reduction='mean',
            class_weight=[1.0] * num_classes + [0.1]),
        loss_mask=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
            reduction='mean',
            loss_weight=5.0),
        loss_dice=dict(
            type='mmdet.DiceLoss',
            use_sigmoid=True,
            activate=True,
            reduction='mean',
            naive_dice=True,
            eps=1.0,
            loss_weight=5.0),
        train_cfg=dict(
            num_points=12544,
            oversample_ratio=3.0,
            importance_sample_ratio=0.75,
            assigner=dict(
                type='mmdet.HungarianAssigner',
                match_costs=[
                    dict(type='mmdet.ClassificationCost', weight=2.0),
                    dict(
                        type='mmdet.CrossEntropyLossCost',
                        weight=5.0,
                        use_sigmoid=True),
                    dict(
                        type='mmdet.DiceCost',
                        weight=5.0,
                        pred_act=True,
                        eps=1.0)
                ]),
            sampler=dict(type='mmdet.MaskPseudoSampler'))),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'),
    )
```
error:
```
Traceback (most recent call last):
  File "/contents/src/tmp.py", line 15, in <module>
    model(**input)
  File "/root/micromamba/envs/pl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/micromamba/envs/pl/lib/python3.11/site-packages/mmseg/models/segmentors/base.py", line 98, in forward
    return self._forward(inputs, data_samples)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/micromamba/envs/pl/lib/python3.11/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 237, in _forward
    return self.decode_head.forward(x)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Mask2FormerHead.forward() missing 1 required positional argument: 'batch_data_samples'
```

if use `mode="predict"`, no error found. 
```python
model(**input, mode="predict")
```
But I am not sure if this is the proper way to handle this as I would like to run only forward propagation with mmsegmentation and use my own loss function to conduct the training.

Could you please tell me how to deal with this problem?

**Comment by IamRecalcitrance** [comment]
I'm having the same problem and don't know how to fix it.

**Comment by apple2373** [comment]
I also want to know how to fix this bug. I tried the following: 

```
class M2FAdapter(nn.Module):
    def __init__(self, model, align_corners=True):
        super().__init__()
        self.model = model
        self.align_corners = align_corners

    def forward(self, x):
        x = self.model(x,mode="predict")
        x = torch.stack([x[i].seg_logits.data for i in range(len(x))])
        return x

model = M2FAdapter(model)
```

But the training was unsuccessful. 

What I want is very simple. I want to have a model that takes an image tensor (BCHW) and outputs a semantic segmentation mask (BNHW).  In this way, I can train using a simple pixel-wise cross-entropy loss.

```
loss = nn.CrossEntropyLoss()
loss(model(x), y)
```
where x is input tensor (BCHW), and y is the segmentation mask (BNHW).

Most models in this library can be used this way but why mask2former cannot?

**Comment by Major-333** [comment]
same problem

**Comment by boxes-code** [comment]
I've found a way around this problem, and by looking at the catalog, we can define a method that contains the following：

img_meta = dict(img_shape=inputs.shape,
pad_shape=labels.shape)
data_sample = SegDataSample()
gt_segmentations = PixelData(metainfo=img_meta)
gt_segmentations.data = labels.squeeze()
data_sample.gt_sem_seg = gt_segmentations

And then put it into the model for training

**Comment by Ankit-4-code** [comment]
Maybe pretty late to this. But I had the same problem. So I found the fix, which was to just go to the mmseg/models/segmentors/encoder_decoder.py and inside the forward function I had to pass the data_samples in  **return self.decode_head.forward(x, data_samples)**. 

And also I tested the pipeline like this 
` dataset = CityscapesRGBDataset(data_root=data_root, data_prefix=data_prefix, test_mode=False,
                                pipeline=train_pipeline, requires_ann=True)

bs = 2 
channels = 3 
height = 224
width = 224

data_samples = [dataset[i] for i in range(bs)]

inputs = torch.stack([sample['inputs'] for sample in data_samples]).to(device)
print('shape of inputs ', inputs.shape)
batch_data_samples = [sample['data_samples'] for sample in data_samples]

model.eval()

with torch.no_grad():
    output = model(inputs, batch_data_samples)

print(output) `
