### ISSUE TITLE
TypeError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: __init__() got an unexpected keyword argument 'pipeline'

### ISSUE THREAD

**Issue by yanhaoerer** [open-mmlab/mmsegmentation#3180]
在运行PIDnet时遇到了下面错误：
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'pipeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\runner\loops.py", line 219, in __init__
    super().__init__(runner, dataloader)
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\runner\base_loop.py", line 27, in __init__
    dataloader, seed=runner.seed, diff_rank_seed=diff_rank_seed)
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\runner\runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\registry\registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\registry\build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
TypeError: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: __init__() got an unexpected keyword argument 'pipeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/YH/mmsegmentation-main/tools/train.py", line 107, in <module>
    main()
  File "D:/YH/mmsegmentation-main/tools/train.py", line 103, in main
    runner.train()
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\runner\runner.py", line 1673, in train
    self._train_loop)  # type: ignore
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\runner\runner.py", line 1467, in build_train_loop
    runner=self, dataloader=self._train_dataloader))
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\registry\registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\Administrator\.conda\envs\torch\lib\site-packages\mmengine\registry\build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
TypeError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: __init__() got an unexpected keyword argument 'pipeline'

数据集格式：
# dataset settings
dataset_type = 'myDataset'
data_root = 'D:\YH\mmsegmentation-master\mydata'
img_scale = (512, 256)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(
        type='RandomResize',
        scale=img_scale,
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='PackSegInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=img_scale, keep_ratio=True),
    # add loading annotation after ``Resize`` because ground truth
    # does not need to do resize data transform
    dict(type='LoadAnnotations'),
    dict(type='PackSegInputs')
]
img_ratios = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
tta_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(
        type='TestTimeAug',
        transforms=[
            [
                dict(type='Resize', scale_factor=r, keep_ratio=True)
                for r in img_ratios
            ],
            [
                dict(type='RandomFlip', prob=0., direction='horizontal'),
                dict(type='RandomFlip', prob=1., direction='horizontal')
            ], [dict(type='LoadAnnotations')], [dict(type='PackSegInputs')]
        ])
]
train_dataloader = dict(
    batch_size=4,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type='RepeatDataset',
        times=40000,
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            data_prefix=dict(
                img_path='img_dir/train',
                seg_map_path='ann_dir/train'),
            pipeline=train_pipeline)))
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='img_dir/test',
            seg_map_path='ann_dir/test'),
        pipeline=test_pipeline))
test_dataloader = val_dataloader

val_evaluator = dict(type='IoUMetric', iou_metrics=['mIou'])
test_evaluator = val_evaluator

**Comment by yanhaoerer** [comment]
mim list
Package    Version    Source
---------  ---------  -----------------------------------------
mmaction2  1.0.0      https://github.com/open-mmlab/mmaction2
mmcv       2.0.1      https://github.com/open-mmlab/mmcv
mmcv-full  1.7.1      https://github.com/open-mmlab/mmcv
mmdet      3.0.0      https://github.com/open-mmlab/mmdetection
mmengine   0.7.1      https://github.com/open-mmlab/mmengine
mmrotate   0.3.4      https://github.com/open-mmlab/mmrotate

**Comment by snachi2s** [comment]
@yanhaoerer Were you able to solve this?
