### ISSUE TITLE
Error in "Get started: Install and Run MMSeg" Guide

### ISSUE THREAD

**Issue by brendanartley** [open-mmlab/mmsegmentation#3182]
I am currently trying to get started with mmsegmentation and I am following the [Get started: Install and Run MMSeg](https://mmsegmentation.readthedocs.io/en/latest/get_started.html) guide.

### Versions

CUDA Version: 12.0
Torch Version: 2.0.1

When I get to the "verify the installation" step, I keep getting an error.

Step 1. We need to download config and checkpoint files.
```
mim download mmsegmentation --config pspnet_r50-d8_4xb2-40k_cityscapes-512x1024 --dest .
```

### Error

```
Traceback (most recent call last):
  File "./miniconda3/envs/openmmlab/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 70, in cli
    download(package, configs, dest_root, check_certificate, dataset)
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 107, in download
    return _download_configs(package, configs, dest_root,
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 132, in _download_configs
    model_info = get_model_info(
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/search.py", line 189, in get_model_info
    dataframe = convert2df(metadata)
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/search.py", line 367, in convert2df
    collection_info.update(_parse(data))
  File "./miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/search.py", line 339, in _parse
    if isinstance(value[0], dict):
IndexError: list index out of range
```

Has anyone else encountered this? Any ideas would be appreciated!

**Comment by shallweiwei** [comment]
#3163 This one

**Comment by brendanartley** [comment]
Thanks @shallweiwei! This solved the issue.

**Comment by liuhhx** [comment]
I also encountered the same problem.

**Comment by brendanartley** [comment]
> I also encountered the same problem.

@liuhhx, see this answer [here](https://github.com/open-mmlab/mmsegmentation/issues/3163#issuecomment-1621393505). It worked for me.
