### ISSUE TITLE
docker runtime error in mutil GPU train

### ISSUE THREAD

**Issue by Atumyugi** [open-mmlab/mmsegmentation#3186]
it's well when i run trainning in ubuntu - flask -- gunicore

but it's error when i run trainning in docker -- flask -- gunicore :

here's bug trace:

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 34367) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
/bigareaserver/yoyiTrain.py FAILED
-----------------------------------------------------
Failures:
[1]:
  time      : 2023-07-12_05:36:47
  host      : 287e54b75912
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 34368)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 34368
[2]:
  time      : 2023-07-12_05:36:47
  host      : 287e54b75912
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 34369)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 34369
[3]:
  time      : 2023-07-12_05:36:47
  host      : 287e54b75912
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 34370)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 34370
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-12_05:36:47
  host      : 287e54b75912
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 34367)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 34367
=====================================================

**Comment by Atumyugi** [comment]
/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/usr/local/lib/python3.10/dist-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 34367) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
/bigareaserver/yoyiTrain.py FAILED
-----------------------------------------------------
Failures:
[1]:
  time      : 2023-07-12_05:36:47
  host      : 287e54b75912
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 34368)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 34368
[2]:
  time      : 2023-07-12_05:36:47
  host      : 287e54b75912
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 34369)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 34369
[3]:
  time      : 2023-07-12_05:36:47
  host      : 287e54b75912
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 34370)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 34370
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-12_05:36:47
  host      : 287e54b75912
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 34367)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 34367
