### ISSUE TITLE
ImportError: cannot import name 'revert_sync_batchnorm' from 'mmcv.cnn.utils' 

### ISSUE THREAD

**Issue by PapaMadeleine2022** [open-mmlab/mmsegmentation#3211]
Hello~ When I run `tools/train.py`, it shows error:

```
  File "tools/train.py", line 12, in <module>
    from mmcv.cnn.utils import revert_sync_batchnorm
ImportError: cannot import name 'revert_sync_batchnorm' from 'mmcv.cnn.utils' (/xxxpy3.8/lib/python3.8/site-packages/mmcv/cnn/utils/__init__.py)
```
My envs are:
```
python3.8
torch==1.13.0
mmcv==2.0.0
```

How to fix it ?
Looking forward to your reply.

**Comment by ChinWicky** [comment]
I have the same error.

**Comment by TaoBowoa180011** [comment]
same error

**Comment by PapaMadeleine2022** [comment]
try:
```
mim uninstall mmcv

mim install mmcv-full

mim install mmcv==1.6.0
```

**Comment by huarzone** [comment]
> try:
> 
> ```
> mim uninstall mmcv
> 
> mim install mmcv-full
> 
> mim install mmcv==1.6.0
> ```

new error：

```
AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=2.0.0rc4.
```

**Comment by tejchemikala** [comment]
Did anyone find a solution for this error?

**Comment by JimmyMa99** [comment]
same error

**Comment by WJHash** [comment]
try lower version of mmcv

**Comment by xuans29** [comment]
in mmcv2.0.0 and higher version this error happens
,but when i install lower version,it turns out to :

Traceback (most recent call last):
  File "tools/train-deeplabv3plus.py", line 16, in <module>
    from mmseg import __version__
  File "/home/dell/Software/Anaconda3/envs/openmmlabnew/lib/python3.8/site-packages/mmseg/__init__.py", line 61, in <module>
    assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
AssertionError: MMCV==1.7.2 is used but incompatible. Please install mmcv>=2.0.0rc4.

really confused,i think the train.py code should be edited

**Comment by CVLee** [comment]
I installed mmcv and MMCV-full =1.7.2 to fix the problem
