### ISSUE TITLE
My training stops abrupt

### ISSUE THREAD

**Issue by CEwoudi** [open-mmlab/mmsegmentation#3217]
When I train with the method pspnet on my conda environment, the training stops abrupt:
<<
07/21 14:16:33 - mmengine - INFO - Checkpoints will be saved to C:\Users\ewoud\Documents\Semester_11\SemEIT\mmsegmentation\results\result_densecl_200.
Traceback (most recent call last):
  File "C:\Users\ewoud\Documents\Semester_11\SemEIT\mmsegmentation\tools\train.py", line 104, in <module>
    main()
  File "C:\Users\ewoud\Documents\Semester_11\SemEIT\mmsegmentation\tools\train.py", line 100, in main
    runner.train()
  File "C:\Users\ewoud\Anaconda3\envs\mmss\lib\site-packages\mmengine\runner\runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "C:\Users\ewoud\Anaconda3\envs\mmss\lib\site-packages\mmengine\runner\loops.py", line 278, in run
    self.run_iter(data_batch)
  File "C:\Users\ewoud\Anaconda3\envs\mmss\lib\site-packages\mmengine\runner\loops.py", line 301, in run_iter
    outputs = self.runner.model.train_step(
  File "C:\Users\ewoud\Anaconda3\envs\mmss\lib\site-packages\mmengine\model\base_model\base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "C:\Users\ewoud\Anaconda3\envs\mmss\lib\site-packages\mmengine\model\base_model\base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
.......................................
.......................................
return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\ewoud\Anaconda3\envs\mmss\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([4, 2048, 1, 1], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(2048, 512, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    memory_format = Contiguous
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 000002512C091230
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 4, 2048, 1, 1,
    strideA = 2048, 1, 1, 1,
output: TensorDescriptor 000002512C0A0B20
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 4, 512, 1, 1,
    strideA = 512, 1, 1, 1,
weight: FilterDescriptor 0000025124796FB0
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 512, 2048, 1, 1,
Pointer addresses:
    input: 0000000601561C00
    output: 0000000601569C00
    weight: 00000006073A0000
>>

Here are my settings:
System environment:
    sys.platform: win32
    Python: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:51:25) [MSC v.1934 64 bit (AMD64)]
    CUDA available: True
    numpy_random_seed: 1173707213
    GPU 0: NVIDIA GeForce 920MX
    CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
    NVCC: Cuda compilation tools, release 10.2, V10.2.8
    GCC: n/a
    PyTorch: 1.13.1
    PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

    TorchVision: 0.14.1
    OpenCV: 4.7.0
    MMEngine: 0.7.4

Runtime environment:
    cudnn_benchmark: True
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 1173707213
    Distributed launcher: none
    Distributed training: False
    GPU number: 1

**Comment by CEwoudi** [comment]
please does this happen because of the memory?
