### ISSUE TITLE
mim下载权重报错，帮忙看下谢谢

### ISSUE THREAD

**Issue by upupbo** [open-mmlab/mmsegmentation#3225]
环境
python==3.8.17
openmim==0.3.9
mmcv==2.0.1

下载预训练权重指令：
mim download mmsegmentation --config pspnet_r50-d8_4xb2-40k_cityscapes-512x1024 --dest .

报错信息：
mim download mmsegmentation --config pspnet_r50-d8_4xb2-40k_cityscapes-512x1024 --dest .
Traceback (most recent call last):
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/mim/commands/download.py", line 70, in cli
    download(package, configs, dest_root, check_certificate, dataset)
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/mim/commands/download.py", line 107, in download
    return _download_configs(package, configs, dest_root,
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/mim/commands/download.py", line 132, in _download_configs
    model_info = get_model_info(
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/mim/commands/search.py", line 189, in get_model_info
    dataframe = convert2df(metadata)
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/mim/commands/search.py", line 367, in convert2df
    collection_info.update(_parse(data))
  File "/home/engineers/chenbo/miniconda3/envs/mmlab/lib/python3.8/site-packages/mim/commands/search.py", line 339, in _parse
    if isinstance(value[0], dict):
IndexError: list index out of range

**Comment by upupbo** [comment]
帮忙看下报错，谢谢

**Comment by CastleDream** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/3163
一样的错误，更新MMSegmentation v1.1.1版本
https://github.com/open-mmlab/mmsegmentation/issues/3163#issuecomment-1649009208

**Comment by CastleDream** [comment]
> 帮忙看下报错，谢谢

https://github.com/open-mmlab/mmsegmentation/issues/3163
一样的错误，更新MMSegmentation v1.1.1版本
https://github.com/open-mmlab/mmsegmentation/issues/3163#issuecomment-1649009208
