### ISSUE TITLE
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by zbl929** [open-mmlab/mmsegmentation#3250]
I have been using the custom data set for mmseg training, before the training process is relatively smooth. 
Today I will update the images in the dataset, but the dataset type is the same, only the data _ root is replaced.
 Error in training :
_assert osp.exists(self.img_dir) and self.split is not None_
*****************************************

Later I annotated him：
*****
_Traceback (most recent call last):
  File "./train.py", line 254, in <module>
    main()
  File "./train.py", line 243, in main
    train_segmentor(
  File "/home/zhangbulin/mmseg-0.23.0/mmseg/apis/train.py", line 175, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 59, in train
    data_batch = next(data_loader)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhangbulin/mmseg-0.23.0/mmseg/datasets/custom.py", line 215, in __getitem__
    return self.prepare_train_img(idx)
  File "/home/zhangbulin/mmseg-0.23.0/mmseg/datasets/custom.py", line 232, in prepare_train_img
    return self.pipeline(results)
  File "/home/zhangbulin/mmseg-0.23.0/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/zhangbulin/mmseg-0.23.0/mmseg/datasets/pipelines/loading.py", line 61, in __call__
    img_bytes = self.file_client.get(filename)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 993, in get
    return self.client.get(filepath)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 518, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhangbulin/mmseg-0.23.0/newdata_1/JPEGImages/389.jpg'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23834) of binary: /home/zhangbulin/anaconda3/envs/mmseg23/bin/python
Traceback (most recent call last):
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhangbulin/anaconda3/envs/mmseg23/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:_ 
*************************************
I delete 389.jpg in FileNotFoundError : [ Errno 2 ] No such file or directory : ' / home / zhangbulin / mmseg-0.23.0 / newdata _ 1 / JPEGImages / 389.jpg ', there will be other jpg can not be found.

I am sure that my jpg file exists and is configured correctly, and I am familiar with the mmseg framework.

**Comment by zbl929** [comment]
And the model has loaded the number of pictures
_2023-08-09 00:00:52,055 - mmseg - INFO - Loaded 602 images
2023-08-09 00:00:52,056 - mmseg - INFO - Loaded 99 images
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2023-08-09 00:01:28,581 - mmseg - INFO - Loaded 99 images
2023-08-09 00:01:28,623 - mmseg - INFO - load checkpoint from local path: /home/zhangbulin/mmseg-0.23.0/pretrain/fpn_80k_nextvit_base.pth
2023-08-09 00:01:29,035 - mmseg - WARNING - The model and loaded state dict do not match exactly_

**Comment by zbl929** [comment]
mmseg=0.23.0
mmcv-full=1.5.0

**Comment by bugaway1** [comment]
Hello, may I ask how you solved it? I have the same problem as you
<img width="577" alt="26d2e94ad912d9be7cdcc73d3bd35aa" src="https://github.com/open-mmlab/mmsegmentation/assets/161917031/6192a9b8-541c-4049-9191-e1ec0f8812de">

**Comment by taoxingwang** [comment]
> 您好，请问您是如何解决的？我和你有同样的问题 <img alt="26d2e94ad912d9be7cdcc73d3bd35aa" width="577" src="https://private-user-images.githubusercontent.com/161917031/309443195-6192a9b8-541c-4049-9191-e1ec0f8812de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTgxOTUsIm5iZiI6MTcxMDMxNzg5NSwicGF0aCI6Ii8xNjE5MTcwMzEvMzA5NDQzMTk1LTYxOTJhOWI4LTU0MWMtNDA0OS05MTkxLWUxZWMwZjg4MTJkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwODE4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTlhNDA1NDcxODQwOGJlODU1ZjkyOWU0NjNhODgzZTdhMTYzZTAxY2Y4NTE4NzZkZTZjNjBiMDE4MTUwNzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AfB_jBKa3Y19McCrk5nw0_cfz0PmXQ5RImr5B-FVyUc">

您好请问您现在解决了吗？
