### ISSUE TITLE
KeyError: 'PALETTE'

### ISSUE THREAD

**Issue by AndrewLaPre** [open-mmlab/mmsegmentation#3278]
Hi there, 

I'm just trying to use the SegFormer B1 model and am getting this error when calling init_model.  I'm able to use the psp model to evaluate images just fine but having issues with B1. 

```
Traceback (most recent call last):
  File "C:\Users\andy\Documents\GitHub\SDARIT-SegFormerDemo\main.py", line 59, in <module>
    model = init_model(config_file, checkpoint_file, device='cuda:0')
  File "C:\Users\andy\AppData\Local\anaconda3\envs\SDARIT-SegFormerDemo\lib\site-packages\mmseg\apis\inference.py", line 65, in init_model
    palette = checkpoint['meta']['PALETTE']
KeyError: 'PALETTE'
```

This is the script: 
```
from mmseg.apis import inference_model, init_model, show_result_pyplot

config_file = 'configs/segformer/segformer_mit-b1_8xb2-160k_ade20k-512x512.py'
checkpoint_file = 'checkpoints/mit_b1.pth'

model = init_model(config_file, checkpoint_file, device='cuda:0')
```
I found another closed issue with the same KeyError but the solution wasn't clear. Any help would be appreciated.

**Comment by AndrewLaPre** [comment]
Also, I realized the checkpoint file should be
"mit_b1_20220624-02e5a6a1.pth"
for the config I'm using, but it produces the same result. 

Thanks in advance.
