### ISSUE TITLE
Produce wrong label in the loveda dataset

### ISSUE THREAD

**Issue by DotWang** [open-mmlab/mmsegmentation#3279]
mmseg 1.x generates label ``7'' in the prediction of the loveda dataset (seven classes, should be 0-6), causing an error in the online evaluation:

```python
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/tmp/codalab/tmpPCJY6X/run/program/evaluate.py:153: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  gt = imread(truthp).astype(np.float) - 1
Traceback (most recent call last):
  File "/tmp/codalab/tmpPCJY6X/run/program/evaluate.py", line 158, in 
    metric.forward(gt[valid_inds], mask[valid_inds])
  File "/tmp/codalab/tmpPCJY6X/run/program/evaluate.py", line 22, in forward
    cm = sparse.coo_matrix((v, (y_true, y_pred)), shape=(self.num_classes, self.num_classes), dtype=np.float32)
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 196, in __init__
    self._check()
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 285, in _check
    raise ValueError('column index exceeds matrix dimensions')
ValueError: column index exceeds matrix dimensions
```

Where is the wrong with my config? I don't change `mmseg/datasets/loveda.py`.

```

dataset_type = 'LoveDADataset'
data_root = '/dataset/loveda_dataset'
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(
        type='RandomResize',
        scale=(512, 512),
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='PackSegInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='PackSegInputs')
]

train_dataloader = dict(
    batch_size=1,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='trainval/images', seg_map_path='trainval/labels'),
        pipeline=train_pipeline))

test_dataloader = dict(
    batch_size=1,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(img_path='test/images', seg_map_path='test/labels'),
        pipeline=test_pipeline))

test_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'], format_only=True)

# optimizer
...

# learning policy
...

data_preprocessor = dict(
    type='SegDataPreProcessor',
    size = crop_size,
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    bgr_to_rgb=True,
    pad_val=0,
    seg_pad_val=255)
model = dict(
    ...
    decode_head=dict(
        num_classes=7,
        ignore_index=255
    ),
    auxiliary_head=dict(
        num_classes=7,
        ignore_index=255
    ),
    train_cfg=dict(),
    test_cfg=dict(mode='slide', stride=(384,384), crop_size=(512,512)))
```

**Comment by joray86** [comment]
read the result img and substract 1

**Comment by DotWang** [comment]
@joray86 So this process cannot be automatically operated by mmseg 1.x, is it? I know the mmseg 0.x can

**Comment by joray86** [comment]
seems so, i didn't get the problem when using mmseg 0.x
