### ISSUE TITLE
ValueError: need at least one array to concatenate when training with custom .tif dataset

### ISSUE THREAD

**Issue by GabrielBG0** [open-mmlab/mmsegmentation#3280]
I'm trying to port a config file that I had back from the 0.X version and I'm getting the following error:
```
Traceback (most recent call last):
  File "/mmsegmentation/tools/train.py", line 104, in <module>
    main()
  File "/mmsegmentation/tools/train.py", line 100, in main
    runner.train()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1703, in train
    self._train_loop = self.build_train_loop(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1495, in build_train_loop
    loop = LOOPS.build(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1353, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mmsegmentation/mmseg/datasets/basesegdataset.py", line 142, in __init__
    self.full_init()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 305, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 765, in _serialize_data
    data_bytes = np.concatenate(data_list)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```

My config file is this one: 
```
_base_ = [
    '_base_/models/segformer_mit-b0.py', '_base_/datasets/ade20k.py',
    '_base_/default_runtime.py', '_base_/schedules/schedule_160k.py'
]

backbone_norm_cfg = dict(type='LN', eps=1e-06, requires_grad=True)
norm_cfg = dict(type='SyncBN', requires_grad=True)


checkpoint = 'pretrain/mit_b5_20220624-658746d9.pth'
num_classes=6
classes = ['Upper','Middle','Lower','Rijnland/Chalk','Scruff','Zechstein']
palette = [[75, 112, 187],[150, 194, 221],[227, 246, 249],[250, 223, 119],[245, 120, 75],[216, 40, 36]]
dataset_type = 'BaseSegDataset'
data_root = 'data/f3'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

norm_cfg = dict(type='SyncBN', requires_grad=True)
model =  dict(
    backbone=dict(
        init_cfg=dict(type='Pretrained', checkpoint=checkpoint),
        embed_dims=64,
        num_heads=[1, 2, 5, 8],
        num_layers=[3, 6, 40, 3]),
    decode_head=dict(in_channels=[64, 128, 320, 512]))

train_pipeline = [
    dict(type='LoadImageFromFile', imdecode_backend='tifffile', to_float32=True),
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(
        type='RandomResize',
        scale=(2048, 512),
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='PackSegInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile', imdecode_backend='tifffile', to_float32=True),
    dict(type='Resize', scale=(2048, 512), keep_ratio=True),
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(type='PackSegInputs')
]
img_ratios = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
tta_pipeline = [
    dict(type='LoadImageFromFile', imdecode_backend='tifffile', to_float32=True),
    dict(
        type='TestTimeAug',
        transforms=[
            [
                dict(type='Resize', scale_factor=r, keep_ratio=True)
                for r in img_ratios
            ],
            [
                dict(type='RandomFlip', prob=0., direction='horizontal'),
                dict(type='RandomFlip', prob=1., direction='horizontal')
            ], [dict(type='LoadAnnotations')], [dict(type='PackSegInputs')]
        ])
]

test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        data_prefix=dict(
            img_path='images/test',
            seg_map_path='annotations/test'),
        data_root=data_root,
        pipeline=test_pipeline,
        type=dataset_type),
        img_suffix=".tif",
        seg_map_suffix='.png',
        classes=classes,
        palette=palette,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))

train_dataloader = dict(
    batch_size=10,
    dataset=dict(
        data_prefix=dict(
            img_path='images/train', seg_map_path='annotations/train'),
        data_root=data_root,
        pipeline=train_pipeline,
        type=dataset_type),
        img_suffix=".tif",
        seg_map_suffix='.png',
        classes=classes,
        palette=palette,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='InfiniteSampler'))

val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        data_prefix=dict(
            img_path='images/val',
            seg_map_path='annotations/val'),
        data_root=data_root,
        pipeline=test_pipeline,
        type=dataset_type),
        img_suffix=".tif",
        seg_map_suffix='.png',
        classes=classes,
        palette=palette,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=0.0001, weight_decay=0.0005))


default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    checkpoint=dict(type='CheckpointHook', by_epoch=True, interval=40),
    logger=dict(type='LoggerHook', interval=10, log_metric_by_epoch=True),
    visualization=dict(type='SegVisualizationHook')
)
vis_backends = [dict(type='LocalVisBackend'),
                dict(type='TensorboardVisBackend')]
visualizer = dict(
    type='SegLocalVisualizer', vis_backends=vis_backends, name='visualizer')

# The `val_interval` is the original `evaluation.interval`.
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=400, val_interval=40)
val_cfg = dict(type='ValLoop') # Use the default validation loop.
test_cfg = dict(type='TestLoop') # Use the default test loop.


checkpoint_config = dict(by_epoch=True, interval=40)

val_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
test_evaluator = val_evaluator
```

I've read in MatCorr's issue (#3015) that I should use `img_suffix` and `seg_map_suffix` to set the proper file formats, but the error persists for me. I've verified that the path set does contain the images.

Am I missing something?

**Comment by HePengguang** [comment]
I met the same issue, did you solve this problem?

**Comment by GabrielBG0** [comment]
not yet, unfortunately... :/

**Comment by StoneMau** [comment]
You may try setup again, use "pip install -v -e ." blablabla in the instruction, for it needs setup again every time you change files in configs or something. It works for me.

**Comment by ttppss** [comment]
> You may try setup again, use "pip install -v -e ." blablabla in the instruction, for it needs setup again every time you change files in configs or something. It works for me.

I tried but not working for me, and this will be wield if we need to pip install it every time something changes.

**Comment by idchacon28** [comment]
I am having the same issue. I only modified a path in my custom_dataset.py (which used to work well) inside of _base_ and now I get ValueError: need at least one array to concatenate. Has anyone solved this please? I tried "pip install -v -e ." but is not working for me.
