### ISSUE TITLE
ValueError: palette does not match classes as metainfo

### ISSUE THREAD

**Issue by 1wang11lijian1** [open-mmlab/mmsegmentation#3285]
Hello, I have a problem. I have created a data set with the same format as cityscapes, but I only have one category (not including the background). The following error occurred during model training. After I changed the number of categories in the configuration file to 2, it still failed, I don't know what went wrong with me.

Below I provide error information and configuration file information,

Error message
```
Traceback (most recent call last):
  File "F:\Weizhun\DeepSeg\mmsegmentation\train.py", line 104, in <module>
    main()
  File "F:\Weizhun\DeepSeg\mmsegmentation\train.py", line 100, in main
    runner.train()
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\runner\runner.py", line 1703, in train
    self._train_loop = self.build_train_loop(
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\runner\runner.py", line 1495, in build_train_loop
    loop = LOOPS.build(
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\runner\loops.py", line 219, in __init__
    super().__init__(runner, dataloader)
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\runner\base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\runner\runner.py", line 1353, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\ProgramData\Anaconda3\envs\mmseg\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "F:\Weizhun\DeepSeg\mmsegmentation\mmseg\datasets\cityscapes.py", line 33, in __init__
    super().__init__(
  File "F:\Weizhun\DeepSeg\mmsegmentation\mmseg\datasets\basesegdataset.py", line 131, in __init__
    updated_palette = self._update_palette()
  File "F:\Weizhun\DeepSeg\mmsegmentation\mmseg\datasets\basesegdataset.py", line 225, in _update_palette
    raise ValueError('palette does not match classes '
ValueError: palette does not match classes as metainfo is {'classes': 'Particle', 'palette': [[0, 0, 255]], 'label_map': None, 'reduce_zero_label': False}.
```

Configuration file
`mobilenet-v3-d8-s_lraspp_4xb4-320k_cityscapes-512x1024.py`
```
_base_ = './mobilenet-v3-d8_lraspp_4xb4-320k_cityscapes-512x1024.py'
norm_cfg = dict(type='SyncBN', eps=0.001, requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='open-mmlab://contrib/mobilenet_v3_small',
    backbone=dict(
        type='MobileNetV3',
        arch='small',
        out_indices=(0, 1, 12),
        norm_cfg=norm_cfg),
    decode_head=dict(
        type='LRASPPHead',
        in_channels=(16, 16, 576),
        in_index=(0, 1, 2),
        channels=128,
        input_transform='multiple_select',
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=norm_cfg,
        act_cfg=dict(type='ReLU'),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)))
```

`mobilenet-v3-d8_lraspp_4xb4-320k_cityscapes-512x1024.py`
```
_base_ = [
    '../_base_/models/lraspp_m-v3-d8.py', '../_base_/datasets/cityscapes.py',
    '../_base_/default_runtime.py', '../_base_/schedules/schedule_160k.py'
]
crop_size = (512, 1024)
data_preprocessor = dict(size=crop_size)
model = dict(
    data_preprocessor=data_preprocessor,
    pretrained='open-mmlab://contrib/mobilenet_v3_large')

# Re-config the data sampler.
train_dataloader = dict(batch_size=4, num_workers=4)
val_dataloader = dict(batch_size=1, num_workers=4)
test_dataloader = val_dataloader

runner = dict(type='IterBasedRunner', max_iters=320000)
```

`lraspp_m-v3-d8.py`

```
# model settings
norm_cfg = dict(type='SyncBN', eps=0.001, requires_grad=True)
data_preprocessor = dict(
    type='SegDataPreProcessor',
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    bgr_to_rgb=True,
    pad_val=0,
    seg_pad_val=255)
model = dict(
    type='EncoderDecoder',
    data_preprocessor=data_preprocessor,
    backbone=dict(
        type='MobileNetV3',
        arch='large',
        out_indices=(1, 3, 16),
        norm_cfg=norm_cfg),
    decode_head=dict(
        type='LRASPPHead',
        in_channels=(16, 24, 960),
        in_index=(0, 1, 2),
        channels=128,
        input_transform='multiple_select',
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=norm_cfg,
        act_cfg=dict(type='ReLU'),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
```

`cityscapes.py`
```
# dataset settings
dataset_type = 'CityscapesDataset'
data_root = 'data/Keyboard_data_En_cityscapes/'
crop_size = (512, 1024)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(
        type='RandomResize',
        scale=(2048, 1024),
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='PackSegInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
    # add loading annotation after ``Resize`` because ground truth
    # does not need to do resize data transform
    dict(type='LoadAnnotations'),
    dict(type='PackSegInputs')
]
img_ratios = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
tta_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(
        type='TestTimeAug',
        transforms=[
            [
                dict(type='Resize', scale_factor=r, keep_ratio=True)
                for r in img_ratios
            ],
            [
                dict(type='RandomFlip', prob=0., direction='horizontal'),
                dict(type='RandomFlip', prob=1., direction='horizontal')
            ], [dict(type='LoadAnnotations')], [dict(type='PackSegInputs')]
        ])
]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='leftImg8bit/train', seg_map_path='gtFine/train'),
        pipeline=train_pipeline))
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='leftImg8bit/val', seg_map_path='gtFine/val'),
        pipeline=test_pipeline))
test_dataloader = val_dataloader

val_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
test_evaluator = val_evaluator
```

**Comment by ShahinNamin** [comment]
How did you resolve this @1wang11lijian1 ? I'm encountering the same issue

**Comment by trinh91** [comment]
@ShahinNamin: I got same problem and solved it! Here is what I did: 
- Define ur class and palette as follow: 
classes = ('background', 'foreground')
palette = [[0, 0, 0], [255, 255, 255]]
- Set num_classes = 2  in config file:
cfg.model.decode_head.num_classes = 2
cfg.model.auxiliary_head.num_classes = 2

Hope it help!

**Comment by ysh-0130** [comment]
> 请问 怎么解决的？我也遇到了一样的错
请问你解决了吗？
