### ISSUE TITLE
Keyerror:backbone.rel_pos_bias.relative_position_bias_tabe

### ISSUE THREAD

**Issue by WdBlink** [open-mmlab/mmsegmentation#3287]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I try to use the pertained model which trained by MMPretrain, I got the error.

**Reproduction**

1. What command or script did you run?

   ```
   python tools/train.py configs/beit/beit-base_upernet
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
LOVEDA
**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
 $ python mmseg/utils/collect_env.py
sys.platform: linux
Python: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.15.1+cu117
OpenCV: 4.7.0
MMEngine: 0.8.4
MMSegmentation: 1.1.1+30a3f94

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```
08/25 13:25:57 - mmengine - WARNING - The prefix is not set in metric class IoUMetric.
Loads checkpoint by local backend from path: pretrain/beitv2_vit-base-p16_8xb256-amp-coslr-300e_in1k_20221212-a157be30.pth
Traceback (most recent call last):
  File "/mnt/f/GitHub/mmsegmentation/tools/train.py", line 104, in <module>
    main()
  File "/mnt/f/GitHub/mmsegmentation/tools/train.py", line 100, in main
    runner.train()
  File "/home/wdblink/anaconda3/envs/LLM/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1723, in train
    self._init_model_weights()
  File "/home/wdblink/anaconda3/envs/LLM/lib/python3.10/site-packages/mmengine/runner/runner.py", line 906, in _init_model_weights
    model.init_weights()
  File "/home/wdblink/anaconda3/envs/LLM/lib/python3.10/site-packages/mmengine/model/base_module.py", line 136, in init_weights
    m.init_weights()
  File "/mnt/f/GitHub/mmsegmentation/mmseg/models/backbones/beit.py", line 501, in init_weights
    state_dict = self.resize_rel_pos_embed(checkpoint)
  File "/mnt/f/GitHub/mmsegmentation/mmseg/models/backbones/beit.py", line 463, in resize_rel_pos_embed
    dst_num_pos, _ = self.state_dict()[key].size()
KeyError: 'backbone.rel_pos_bias.relative_position_bias_table'
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Venn2336** [comment]
I have the same problems too.

**Comment by fengyan-cv** [comment]
> I have the same problems too.

Do you solve this problem?
