### ISSUE TITLE
error from k8s pod : multi GPU training

### ISSUE THREAD

**Issue by Atumyugi** [open-mmlab/mmsegmentation#3288]
this is my k8s pods enviorment:
nvidia 3090
torch 1.13.1

this is my train.sh:
CONFIG=$1
GPUS=$2
NNODES=${NNODES:-1}
NODE_RANK=${NODE_RANK:-0}
PORT=${PORT:-29500}
MASTER_ADDR=$3
echo CONFIG $CONFIG
echo GPUS $GPUS
echo NNODES $NNODES
echo NODE_RANK $NODE_RANK
echo MASTER_ADDR $MASTER_ADDR

export PYTHONPATH="/code/bigareaserver:$PYTHONPATH"
export MKL_SERVICE_FORCE_INTEL=1
python3 -m torch.distributed.launch \
    --nnodes=$NNODES \
    --node_rank=$NODE_RANK \
    --master_addr=$MASTER_ADDR \
    --nproc_per_node=$GPUS \
    --master_port=$PORT \
    yoyiTrain.py \
    $CONFIG \
    --launcher pytorch ${@:4}

this is my error trace:
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 139 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 138) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
===================================================
/ssd/data3/code/bigareaserver/yoyiTrain.py FAILED
---------------------------------------------------
Failures:
[1]:
  time      : 2023-08-25_07:50:33
  host      : master-k8s
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 140)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 140
[2]:
  time      : 2023-08-25_07:50:33
  host      : master-k8s
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 141)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 141
---------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-25_07:50:33
  host      : master-k8s
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 138)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 138

**Comment by Atumyugi** [comment]
I want to achieve training similar to a single machine with multiple GPU on one k8s pod
