### ISSUE TITLE
KeyError: "EncoderDecoder: 'XX is not in the models registry'"

### ISSUE THREAD

**Issue by heorhiikalaichev** [open-mmlab/mmsegmentation#3304]
Hi!

I'm trying to train my segmentation model with my own model.
I model code I add

@BACKBONES.register_module()
class FastViT(nn.Module):

But I still have the same error

KeyError: "EncoderDecoder: 'FastViT is not in the models registry'".

Traceback (most recent call last):
  File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 36, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmseg/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmcv/utils/registry.py", line 215, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'FastViT is not in the models registry'

**Comment by jinxianwei** [comment]
> Hi!
> 
> I'm trying to train my segmentation model with my own model. I model code I add
> 
> @BACKBONES.register_module() class FastViT(nn.Module):
> 
> But I still have the same error
> 
> KeyError: "EncoderDecoder: 'FastViT is not in the models registry'".
> 
> Traceback (most recent call last): File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg return obj_cls(**args) File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 36, in **init** self.backbone = builder.build_backbone(backbone) File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmseg/models/builder.py", line 20, in build_backbone return BACKBONES.build(cfg) File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmcv/utils/registry.py", line 215, in build return self.build_func(*args, **kwargs, registry=self) File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg return build_from_cfg(cfg, registry, default_args) File "/home/paperspace/miniconda3/envs/mmcv_env/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg f'{obj_type} is not in the {registry.name} registry') KeyError: 'FastViT is not in the models registry'

1. install form source
![image](https://github.com/open-mmlab/mmsegmentation/assets/81373517/ac683c77-acb5-4b3e-8a03-ea8deec5afdc)
2. add decorator
![image](https://github.com/open-mmlab/mmsegmentation/assets/81373517/0a79b3a4-2230-42e4-bf98-61fb39c1ffe6)
3. add model in __init__.py
![image](https://github.com/open-mmlab/mmsegmentation/assets/81373517/cd8ac857-1aa3-49de-813c-9486c7e139b0)

you can try this

**Comment by nitec427** [comment]
Hey I have the same problem and I installed it from the source. Here is the error traceback.
<img width="1166" alt="Screenshot 2023-11-29 at 23 55 47" src="https://github.com/open-mmlab/mmsegmentation/assets/23635935/103558c8-384c-458d-aebd-73f7bfba9185">

**Comment by jinxianwei** [comment]
what is the mmengine version

**Comment by jinxianwei** [comment]
> Hey I have the same problem and I installed it from the source. Here is the error traceback. <img alt="Screenshot 2023-11-29 at 23 55 47" width="1166" src="https://private-user-images.githubusercontent.com/23635935/286739886-103558c8-384c-458d-aebd-73f7bfba9185.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDcwMzQsIm5iZiI6MTcwMTMwNjczNCwicGF0aCI6Ii8yMzYzNTkzNS8yODY3Mzk4ODYtMTAzNTU4YzgtMzg0Yy00NThkLWFlYmQtNzNmN2JmYmE5MTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAxMTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNmVmNTI5ZDhjNGVjMWIyM2IwNDlkZWIyYmFlNzhkMzI2ZTg5ZjBhMDgxZjMwM2FmZmNhZDY1MjNjNzI1ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5lBI4lcFECiboQIHjnLasjr7G5Gk2irDudSXZ9p36ks">

what is the mmengine version?
