### ISSUE TITLE
Exporting Segformer to JIT does not work

### ISSUE THREAD

**Issue by Bycob** [open-mmlab/mmsegmentation#3327]
I tried to use the script `tools/deployment/pytorch2torchscript.py` to export my model to TorchScript and I get errors.

I followed the installation in the README and I'm running on the main branch, commit = https://github.com/open-mmlab/mmsegmentation/commit/30a3f94f3e2916e27fa38c67cc3b8c69c1893fe8

Command line:
```bash
python3 tools/deployment/pytorch2torchscript.py configs/segformer/segformer_mit-b0_8xb2-160k_ade20k-512x512.py --output-file segformer_b0_512.pt
```

Output:
```
Traceback (most recent call last):
  File "tools/deployment/pytorch2torchscript.py", line 178, in <module>
    segmentor = build_segmentor(cfg.model)
  File "/home/bycob/repos/0_papers/mmsegmentation/mmseg/models/builder.py", line 51, in build_segmentor
    return SEGMENTORS.build(
  File "/home/bycob/.local/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/bycob/.local/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/bycob/.local/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/bycob/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 83, in __init__
    super().__init__(
  File "/home/bycob/mmsegmentation/mmseg/models/segmentors/base.py", line 30, in __init__
    super().__init__(
  File "/home/bycob/.local/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 78, in __init__
    self.data_preprocessor = MODELS.build(data_preprocessor)
  File "/home/bycob/.local/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/bycob/.local/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/bycob/.local/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'SegDataPreProcessor is not in the mmengine::model registry. Please check whether the value of `SegDataPreProcessor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```
I had to fix one error before I could obtain that output, here is the patch:
```git
diff --git a/tools/deployment/pytorch2torchscript.py b/tools/deployment/pytorch2torchscript.py
index 4b74c8f..f1428ad 100644
--- a/tools/deployment/pytorch2torchscript.py
+++ b/tools/deployment/pytorch2torchscript.py
@@ -175,8 +175,7 @@ if __name__ == '__main__':
 
     # build the model and load checkpoint
     cfg.model.train_cfg = None
-    segmentor = build_segmentor(
-        cfg.model, train_cfg=None, test_cfg=cfg.get('test_cfg'))
+    segmentor = build_segmentor(cfg.model)
     # convert SyncBN to BN
     segmentor = _convert_batchnorm(segmentor)
```

It seems like `SegDataPreProcessor` exists here https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/models/data_preprocessor.py and seems to be correctly registered, so I don't know what is causing the issue.

**Comment by Bycob** [comment]
I did not, rolled back to a version that supports mmcv-full 1.5.0

more detailled instructions here https://github.com/jolibrain/deepdetect/tree/master/tools/torch#export-segformer-model

**Comment by aenoca** [comment]
I believe the solution is to add 

`from mmseg.utils import register_all_modules

register_all_modules()`
