### ISSUE TITLE
When I execute "inference_model()", got an unexpected keyword argument 'img_scale'

### ISSUE THREAD

**Issue by zh-jp** [open-mmlab/mmsegmentation#3330]
**Describe the bug**
When executing following code:
```python
test_path = '1_1.5level_500X.jpg'
model = init_model(config_file, checkpoint_file, device='cuda:0')
res = inference_model(model, test_path)
```
and got an error:
```bash
Traceback (most recent call last):
  File "D:\workspace\recurrent\process.py", line 33, in <module>
    res = inference_model(model, test_path)
  File "D:\env\anaconda3\envs\openmmlab\lib\site-packages\mmseg\apis\inference.py", line 143, in inference_model
    data, is_batch = _preprare_data(img, model)
  File "D:\env\anaconda3\envs\openmmlab\lib\site-packages\mmseg\apis\inference.py", line 113, in _preprare_data
    pipeline = Compose(cfg.test_pipeline)
  File "D:\env\anaconda3\envs\openmmlab\lib\site-packages\mmengine\dataset\base_dataset.py", line 36, in __init__
    transform = TRANSFORMS.build(transform)
  File "D:\env\anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\env\anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'img_scale'
```
**Reproduction**

I didn't make any modification to the library file and just import it.

**Environment**

```bash
OrderedDict([('sys.platform', 'win32'),
             ('Python',
              '3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]'),
             ('CUDA available', True),
             ('numpy_random_seed', 2147483648),
             ('GPU 0', 'NVIDIA GeForce RTX 3080 Ti'),
             ('CUDA_HOME', None),
             ('GCC', 'n/a'),
             ('PyTorch', '2.0.1'),
             ('PyTorch compiling details',
              'PyTorch built with:\n  - C++ Version: 199711\n  - MSVC 193431937\n  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 2019\n  - LAPACK is enabled (usually provided by MKL)\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.7\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.5\n  - Magma 2.5.4\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, \n'),
             ('TorchVision', '0.15.2'),
             ('OpenCV', '4.8.0'),
             ('MMEngine', '0.8.4'),
             ('MMSegmentation', '1.1.1+')])
```

The way of installing PyTorch is `conda`

**Comment by zh-jp** [comment]
Well... I find it. The variable 'config_file' connect to old config file and in this file some parameters had changed. So replace the relevant config file to the latest and solve.

In my situation, I used `fcn_r50-d8_512x1024_80k_cityscapes.py` in my code, but get some change in new version. So I replace it with `fcn_r50-d8_4xb2-80k_cityscapes-512x1024.py`.

Finally , **pay attention to version**
