### ISSUE TITLE
Training of PP-MobileSeg 

### ISSUE THREAD

**Issue by rpl-alan-shangguan** [open-mmlab/mmsegmentation#3344]
Can I use mmsegmentation to train my own PP-MobileSeg model?

I didn't find loss_decode in pp_mobileseg config file, and When I add it to the decode_head and run the training, I got 
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 93, in main
    runner = Runner.from_cfg(cfg)
  File "/home/alan/Downloads/mmengine/mmengine/runner/runner.py", line 446, in from_cfg
    runner = cls(
  File "/home/alan/Downloads/mmengine/mmengine/runner/runner.py", line 413, in __init__
    self.model = self.build_model(model)
  File "/home/alan/Downloads/mmengine/mmengine/runner/runner.py", line 820, in build_model
    model = MODELS.build(model)
  File "/home/alan/Downloads/mmengine/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/alan/Downloads/mmengine/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/alan/Downloads/mmengine/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 92, in __init__
    self._init_decode_head(decode_head)
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 102, in _init_decode_head
    self.decode_head = MODELS.build(decode_head)
  File "/home/alan/Downloads/mmengine/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/alan/Downloads/mmengine/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/alan/Downloads/mmengine/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'loss_decode'

**Comment by JH95-ai** [comment]
I also find this error .Have you solved it yet? @rpl-alan-shangguan

**Comment by Qiang-Z** [comment]
+1

**Comment by litterqi** [comment]
I met the same problem. It seems that we still can not train pp_mobileseg in mmsegmentation.
