### ISSUE TITLE
In CAT_Seg model, Trained weights are used incorrectly, KeyError: 'meta'

### ISSUE THREAD

**Issue by zsc1220** [open-mmlab/mmsegmentation#3355]
When i used cat_seg configs file and model file you have provide in demo/image_demo.py, The following error occurred when i run .
`

Traceback (most recent call last):
  File "demo/image_demo.py", line 45, in <module>
    main()
  File "demo/image_demo.py", line 27, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/home/xxx/code/mmsegmentation/mmseg/apis/inference.py", line 56, in init_model
    dataset_meta = checkpoint['meta'].get('dataset_meta', None)
KeyError: 'meta'

`
How to solve this error ? Thank you so much !

**Comment by zsc1220** [comment]
`123`
