### ISSUE TITLE
Why AssertionError: The length of classes should be equal to palette？

### ISSUE THREAD

**Issue by lizixiaoboluo** [open-mmlab/mmsegmentation#3371]
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 93, in main
    runner = Runner.from_cfg(cfg)
  File "/home/tjf22/.conda/envs/openmmlab1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/home/tjf22/.conda/envs/openmmlab1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 399, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/home/tjf22/.conda/envs/openmmlab1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 786, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/home/tjf22/.conda/envs/openmmlab1/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/tjf22/.conda/envs/openmmlab1/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 119, in build_from_cfg
    obj = obj_cls.get_instance(**args)  # type: ignore
  File "/home/tjf22/.conda/envs/openmmlab1/lib/python3.8/site-packages/mmengine/visualization/visualizer.py", line 1184, in get_instance
    instance = super().get_instance(name, **kwargs)
  File "/home/tjf22/.conda/envs/openmmlab1/lib/python3.8/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/home/tjf22/mmsegmentation-main1/mmsegmentation-main/mmseg/visualization/local_visualizer.py", line 79, in __init__
    self.set_dataset_meta(palette, classes, dataset_name)
  File "/home/tjf22/mmsegmentation-main1/mmsegmentation-main/mmseg/visualization/local_visualizer.py", line 251, in set_dataset_meta
    assert len(classes) == len(
AssertionError: The length of classes should be equal to palette

**Comment by shakhbozabdigapporov** [comment]
You should try to check the mmseg/utils/class_names.py and change classes name and palette information there as well.
