### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.utils.config' when init_model

### ISSUE THREAD

**Issue by Sere1nz** [open-mmlab/mmsegmentation#3393]
Traceback (most recent call last):
  File "/mnt/c/Users/raych/github_project/mine/usqualitycls/combine_inference.py", line 45, in <module>
    model = init_model(cfg, checkpoint_file, device='cuda:0')
  File "/home/zzm/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmseg/apis/inference.py", line 60, in init_model
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "/home/zzm/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/zzm/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/zzm/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/zzm/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 347, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/zzm/anaconda3/envs/mmseg/lib/python3.8/site-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/home/zzm/anaconda3/envs/mmseg/lib/python3.8/site-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/home/zzm/anaconda3/envs/mmseg/lib/python3.8/site-packages/torch/serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'mmcv.utils.config'

package version:
mmcv                     2.1.0
mmsegmentation           1.2.1
mmengine                 0.9.0

**Comment by Sere1nz** [comment]
I didn't import mmcv.utils.config in my python script
`import torch
import torch.nn as nn
from torchvision import transforms
import torchvision.models as models
import cv2
import numpy as np
from mmseg.apis import inference_model,init_model
from mmengine import Config
#from mmcv.runner import load_checkpoint
#from mmseg.models import build_segmentor
from mmseg.registry import DATASETS
from mmseg.datasets import BaseSegDataset`
