### ISSUE TITLE
java.lang.ClassCastException occured when starting torchserve

### ISSUE THREAD

**Issue by hahamyt** [open-mmlab/mmsegmentation#3436]
I followed the official document about torchserve part, generated `a.mar` file.

`a.mar` is store in `wor_dir` folder that is `model_store` folder.

Then using following script to start the model serving

```torchserve --start --ncs --model-store work_dir --models a.mar```

But the java.lang.ClassCastException  was occured:

```shell
2023-11-15T02:53:32,277 [WARN ] main org.pytorch.serve.util.ConfigManager - Your torchserve instance can access any URL to load models. When deploying to production, make sure to limit the set of allowed_urls in config.properties
2023-11-15T02:53:32,282 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2023-11-15T02:53:32,331 [INFO ] main org.pytorch.serve.metrics.configuration.MetricConfiguration - Successfully loaded metrics configuration from /root/anaconda3/envs/serve/lib/python3.10/site-packages/ts/configs/metrics.yaml
2023-11-15T02:53:32,437 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.9.0
TS Home: /root/anaconda3/envs/serve/lib/python3.10/site-packages
Current directory: /root/workspace
Temp directory: /tmp
Metrics config path: /root/anaconda3/envs/serve/lib/python3.10/site-packages/ts/configs/metrics.yaml
Number of GPUs: 1
Number of CPUs: 16
Max heap size: 7956 M
Python executable: /root/anaconda3/envs/serve/bin/python
Config file: config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /root/workspace/work_dir
Initial Models: a.mar
Log dir: /root/workspace/logs
Metrics dir: /root/workspace/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Enable metrics API: true
Metrics mode: log
Disable system metrics: false
Workflow Store: /root/workspace/work_dir
Model config: N/A
2023-11-15T02:53:32,453 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2023-11-15T02:53:32,477 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: segformer_b3s2_rscloud_seg.mar
2023-11-15T02:53:40,528 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
        at org.pytorch.serve.archive.utils.ArchiveUtils.readYamlFile(ArchiveUtils.java:69)
        at org.pytorch.serve.archive.model.ModelArchive.getModelConfig(ModelArchive.java:226)
        at org.pytorch.serve.wlm.Model.<init>(Model.java:72)
        at org.pytorch.serve.wlm.ModelManager.createModel(ModelManager.java:301)
        at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:143)
        at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:264)
        at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:396)
        at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:118)
        at org.pytorch.serve.ModelServer.main(ModelServer.java:99)
```

**Comment by hahamyt** [comment]
version mismatch
