### ISSUE TITLE
Release gpu memory of training when testing

### ISSUE THREAD

**Issue by xinfu607** [open-mmlab/mmsegmentation#344]
Could you please tell me how to release gpu memory of training when testing ?
I run dist_train.py and meet error after testing some images. I find that the gpu memory of training isn't released when testing.

2021-01-13 12:17:11,930 - mmseg - INFO - Iter [50/200]  lr: 7.788e-03, eta: 0:02:40, time: 1.072, data_time: 0.015, memory: 8777, decode.loss_seg: 3.1868, decode.acc_seg: 28.9936, aux.loss_seg: 1.4023, aux.acc_seg: 27.9485, loss: 4.5891
2021-01-13 12:18:02,601 - mmseg - INFO - Saving checkpoint at 100 iterations
[                                                  ] 0/120, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/train.py", line 181, in <module>
    main()
  File "./tools/train.py", line 177, in main
    meta=meta)
  File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/apis/train.py", line 106, in train_segmentor
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/root/anaconda3/envs/py36tf112/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/root/anaconda3/envs/py36tf112/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/root/anaconda3/envs/py36tf112/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/core/evaluation/eval_hooks.py", line 78, in after_train_iter
    gpu_collect=self.gpu_collect)
  File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/apis/test.py", line 112, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/root/anaconda3/envs/py36tf112/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/py36tf112/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/envs/py36tf112/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/py36tf112/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/models/segmentors/base.py", line 124, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/models/segmentors/base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
 File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/models/segmentors/encoder_decoder.py", line 265, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/models/segmentors/encoder_decoder.py", line 250, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/models/segmentors/encoder_decoder.py", line 224, in whole_inference
    warning=False)
  File "/opt/data/private/fuxin/mmsegmentation/ccnet_base/mmseg/ops/wrappers.py", line 29, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "/root/anaconda3/envs/py36tf112/lib/python3.6/site-packages/torch/nn/functional.py", line 3163, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, sfl[0], sfl[1])
RuntimeError: CUDA out of memory. Tried to allocate 3.69 GiB (GPU 1; 11.91 GiB total capacity; 1.16 GiB already allocated; 2.84 GiB free; 8.41 GiB reserved in total by PyTorch)
^M[                                 ] 1/120, 0.3 task/s, elapsed: 3s, ETA:   341s^M[                                 ] 2/120, 0.7 task/s, elapsed: 3s, ETA:   169s^M[                                 ] 3/120, 0.8 task/s, elapsed: 4s, ETA:   145s^M[>                                ] 4/120, 1.1 task/s, elapsed: 4s, ETA:   108s^M[>                                ] 5/120, 1.1 task/s, elapsed: 5s, ETA:   105s^M[>                                ] 6/120, 1.3 task/s, elapsed: 5s, ETA:    87s^M[>                                ] 7/120, 1.3 task/s, elapsed: 5s, ETA:    88s^M[>>                               ] 8/120, 1.5 task/s, elapsed: 5s, ETA:    77s^M[>>                               ] 9/120, 1.6 task/s, elapsed: 6s, ETA:    71s^M[>>                              ] 10/120, 1.7 task/s, elapsed: 6s, ETA:    63s^M[>>                              ] 11/120, 1.6 task/s, elapsed: 7s, ETA:    66s^M[>>>                             ] 12/120, 1.8 task/s, elapsed: 7s, ETA:    60s^M[>>>                             ] 13/120, 1.7 task/s, elapsed: 8s, ETA:    62s^M[>>>                             ] 14/120, 1.9 task/s, elapsed: 8s, ETA:    57s^M[>>>>                            ] 15/120, 2.0 task/s, elapsed: 8s, ETA:    53s^M[>>>>                            ] 16/120, 2.1 task/s, elapsed: 8s, ETA:    50s^M[>>>>                            ] 17/120, 2.0 task/s, elapsed: 9s, ETA:    52s^M[>>>>                            ] 18/120, 2.1 task/s, elapsed: 9s, ETA:    48s^M[>>>>>                           ] 19/120, 2.2 task/s, elapsed: 9s, ETA:    46s^M[>>>>>                           ] 20/120, 2.3 task/s, elapsed: 9s, ETA:    43s^M[>>>>>                          ] 21/120, 2.2 task/s, elapsed: 10s, ETA:    45s^M[>>>>>                          ] 22/120, 2.3 task/s, elapsed: 10s, ETA:    43s^M[>>>>>                          ] 23/120, 2.4 task/s, elapsed: 10s, ETA:    41s^M[>>>>>>                         ] 24/120, 2.5 task/s, elapsed: 10s, ETA:    39s^M[>>>>>>                         ] 25/120, 2.3 task/s, elapsed: 11s, ETA:    41s^M[>>>>>>                         ] 26/120, 2.4 task/s, elapsed: 11s, ETA:    39s^M[>>>>>>                         ] 27/120, 2.3 task/s, elapsed: 12s, ETA:    40s^M[>>>>>>>                        ] 28/120, 2.4 task/s, elapsed: 12s, ETA:    39s^M[>>>>>>>                        ] 29/120, 2.4 task/s, elapsed: 12s, ETA:    37s^M[>>>>>>>                        ] 30/120, 2.5 task/s, elapsed: 12s, ETA:    36s^M[>>>>>>>>                       ] 31/120, 2.4 task/s, elapsed: 13s, ETA:    37s^M[>>>>>>>>                      @@@

**Comment by xvjiarui** [comment]
We don't need to manually release memory. Maybe it is because your testing image scale is large?

**Comment by xvjiarui** [comment]
We already support memory efficient test in #330
