### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by renqingshi** [open-mmlab/mmsegmentation#3468]
I want to debug the SAN model using a segmentation model. I used the COCO Stuff164k dataset as per official requirements, but this error may occur. The error is as follows

Traceback (most recent call last):
  File "E:\mmsegmentation-main\tools\train.py", line 104, in <module>
    main()
  File "E:\mmsegmentation-main\tools\train.py", line 100, in main
    runner.train()
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmengine\runner\runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmengine\runner\loops.py", line 277, in run
    data_batch = next(self.dataloader_iterator)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmengine\runner\loops.py", line 164, in __next__
    data = next(self._iterator)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "E:\anaconda\envs\segmmentation\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "E:\anaconda\envs\segmmentation\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\anaconda\envs\segmmentation\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\anaconda\envs\segmmentation\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmengine\dataset\base_dataset.py", line 410, in __getitem__
    data = self.prepare_data(idx)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmengine\dataset\base_dataset.py", line 793, in prepare_data
    return self.pipeline(data_info)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmengine\dataset\base_dataset.py", line 60, in __call__
    data = t(data)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmcv\transforms\base.py", line 12, in __call__
    return self.transform(results)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmcv\transforms\loading.py", line 345, in transform
    self._load_seg_map(results)
  File "E:\mmsegmentation-main\mmseg\datasets\transforms\loading.py", line 99, in _load_seg_map
    img_bytes = fileio.get(
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmengine\fileio\io.py", line 181, in get
    return backend.get(filepath)
  File "E:\anaconda\envs\segmmentation\lib\site-packages\mmengine\fileio\backends\local_backend.py", line 33, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\mmsegmentation-main\\data\\coco-stuff164k\\annotations/train2017\\000000214373_labelTrainIds.png'

What should I do？

**Comment by go-ahead-maker** [comment]
hi, did you tackled this problem?
