### ISSUE TITLE
FileNotFoundError: img file does not exist: data/DRIVE/annotations/validation/20_manual1.png

### ISSUE THREAD

**Issue by meetviolet** [open-mmlab/mmsegmentation#347]
**Describe the bug**

I tried to reproduce the result of experiment on dataset DRIVE. using this [config](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/unet/deeplabv3_unet_s5-d16_64x64_40k_drive.py).

But the program showed :"FileNotFoundError: img file does not exist: data/DRIVE/annotations/validation/20_manual1.png"

Then I found that the dataset DRIVE doesn't have the 1st_manual folder in testing.zip.

It is said in the docs that the 1st_manual is not provided officially. So I wonder how your results is obtained. If you could share a way to fix it or the validation labels of DRIVE, it would be very helpful.

**Reproduction**

1. What command or script did you run?

    ```shell
    bash dist_train.sh /path/to/mmsegmentation/configs/unet/deeplabv3_unet_s5-d16_64x64_40k_drive.py 2 output/unet_drive_deeplabv3
    ```

2. Did you make any modifications on the code or config?  NO modifications.
3. Did you understand what you have modified? NO modifications.
3. What dataset did you use?
DRIVE

**Error traceback**

```shell
Traceback (most recent call last):
  File "/data/vy/seg/mmsegmentation/tools/train.py", line 161, in <module>
    main()
  File "/data/vy/seg/mmsegmentation/tools/train.py", line 157, in main
    meta=meta)
  File "/data/vy/seg/mmsegmentation/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/data/vy/seg/mmcv/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/data/vy/seg/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/data/vy/seg/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/data/vy/seg/mmsegmentation/mmseg/core/evaluation/eval_hooks.py", line 92, in after_train_iter
    self.evaluate(runner, results)
  File "/data/vy/seg/mmsegmentation/mmseg/core/evaluation/eval_hooks.py", line 45, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/data/vy/seg/mmsegmentation/mmseg/datasets/custom.py", line 331, in evaluate
    gt_seg_maps = self.get_gt_seg_maps(efficient_test)
  File "/data/vy/seg/mmsegmentation/mmseg/datasets/custom.py", line 239, in get_gt_seg_maps
    seg_map, flag='unchanged', backend='pillow')
  File "/data/vy/seg/mmcv/mmcv/image/io.py", line 155, in imread
    f'img file does not exist: {img_or_path}')
  File "/data/vy/seg/mmcv/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: data/DRIVE/annotations/validation/20_manual1.png
Traceback (most recent call last):
  File "/data/vy/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/vy/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/vy/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/data/vy/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/data/vy/anaconda3/envs/open-mmlab/bin/python', '-u', '/data/vy/seg/mmsegmentation/tools/train.py'
, '--local_rank=1', '/data/vy/seg/mmsegmentation/configs/unet/deeplabv3_unet_s5-d16_64x64_40k_drive.py', '--work-dir', 'output/unet_s5d16', 
'--launcher', 'pytorch']' returned non-zero exit status 1.
```

More details to reproduce the aforementioned results is needed.

**Comment by Junjun2016** [comment]
Hi @meetviolet 
The official provided testing dataset, but not the official does not provide anymore. You can download it from other repo.

**Comment by meetviolet** [comment]
Hi,
Sorry to bother,

**I can't find the exact way to get the testing dataset.**😭

Could you please give me more details?

“ You can download it from other repo. ”
For example, which repo could I find the right dataset?
Could you please provide the right dataset url？

**Comment by Junjun2016** [comment]
> Hi,
> Sorry to bother,
> 
> I can't find the exact way to get the testing dataset.
> 
> Could you please give me more details?
> 
> “ You can download it from other repo. ”
> For example, which repo could I find the right dataset?
> Could you please provide the right dataset url？

**Comment by Junjun2016** [comment]
> > Hi,
> > Sorry to bother,
> > I can't find the exact way to get the testing dataset.
> > Could you please give me more details?
> > “ You can download it from other repo. ”
> > For example, which repo could I find the right dataset?
> > Could you please provide the right dataset url？

@yamengxi

**Comment by yamengxi** [comment]
> Hi,
> Sorry to bother,
> 
> I can't find the exact way to get the testing dataset.😭
> 
> Could you please give me more details?
> 
> “ You can download it from other repo. ”
> For example, which repo could I find the right dataset?
> Could you please provide the right dataset url？

I download DRIVE from [here](https://download.csdn.net/download/weixin_42332891/12821989?utm_source=bbsseo)
