### ISSUE TITLE
'SegLocalVisualizer is not in the mmengine::visualizer registry

### ISSUE THREAD

**Issue by mxmdpc** [open-mmlab/mmsegmentation#3506]
conduct python tools/test.py configs/mask2former/mask2former_swin-l.py work_dirs/mask2former_swin-l/best_mIoU_iter_100000.pth --cfg-options test_evaluator.type=IoUMetric

01/08 19:36:52 - mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` package.
01/08 19:36:52 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "visualizer" registry tree. As a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 116, in main
    runner = Runner.from_cfg(cfg)
  File "/KONGdehui/cdp/anaconda3/envs/pvic/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/KONGdehui/cdp/anaconda3/envs/pvic/lib/python3.8/site-packages/mmengine/runner/runner.py", line 416, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/KONGdehui/cdp/anaconda3/envs/pvic/lib/python3.8/site-packages/mmengine/runner/runner.py", line 803, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/KONGdehui/cdp/anaconda3/envs/pvic/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/KONGdehui/cdp/anaconda3/envs/pvic/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'SegLocalVisualizer is not in the mmengine::visualizer registry. Please check whether the value of `SegLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by interpretty** [comment]
i meet this problem too, and i found that i use the wrong conda enviroment. You can check and reinstall your virtual environment.

**Comment by mxmdpc** [comment]
> i meet this problem too, and i found that i use the wrong conda enviroment. You can check and reinstall your virtual environment.

Thank you, I will reinstall the environment!

**Comment by vsingh1998** [comment]
@mxmdpc did you fix the error? I am facing the same error. If yes, can you please share your environment.yml file.

**Comment by 961116** [comment]
the third-party library I started with had this error 'SegLocalVisualizer is not in the mmengine::visualizer registry. '  No such error occurs when the mmsegmentation is installed directly.
pip install "mmsegmentation>=1.0.0" -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by realTravisYou** [comment]
`cd mmsegmentaton`
`pip install -v -e .`
