### ISSUE TITLE
there is no 'pspnet_r50-d8_512x1024_40k_cityscapes' & No module named 'mmengine'

### ISSUE THREAD

**Issue by minyeo** [open-mmlab/mmsegmentation#3525]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

I encounter an error when running the test code after installation. When executing the code "mim download mmsegmentation --config pspnet_r50-d8_512x1024_40k_cityscapes --dest .", it shows an error saying that the file 'pspnet_r50-d8_512x1024_40k_cityscapes' does not exist.

When running the code "python demo/image_demo.py demo/demo.png configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2**c.pth --device cuda:0 --out-file result.jpg", it throws a ModuleNotFoundError: No module named 'mmengine'.

After that, I tried to install mmcv through Customize Installation, but the first code still gives the same error, and when running the second test code, it throws a ModuleNotFoundError: No module named 'ftfy'.
![image](https://github.com/open-mmlab/mmsegmentation/assets/58988225/84b86f5d-b47b-4e47-bea5-c5eb7e9265d7)
What could be the problem?

**Reproduction**

1. What command or script did you run?
```none 
pip install -U openmim
mim install mmcv-full
git clone https://github.com/open-mmlab/mmsegmentation.git
cd mmsegmentation
pip install -v -e .

mim download mmsegmentation --config pspnet_r50-d8_512x1024_40k_cityscapes --dest .
python demo/image_demo.py demo/demo.png configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth --device cuda:0 --out-file result.jpg

pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12/index.html
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
didn't modify 

3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ayshaashra** [comment]
(openmmlab) D:\Toolkit\mmsegmentation>python mmseg/utils/collect_env.py
Traceback (most recent call last):
  File "mmseg/utils/collect_env.py", line 3, in <module>
    from mmengine.utils.dl_utils import collect_env as collect_base_env
  File "C:\ProgramData\anaconda3\envs\openmmlab\lib\site-packages\mmengine\utils\dl_utils\__init__.py", line 3, in <module>
    from .collect_env import collect_env
  File "C:\ProgramData\anaconda3\envs\openmmlab\lib\site-packages\mmengine\utils\dl_utils\collect_env.py", line 10, in <module>
    import torch
  File "C:\ProgramData\anaconda3\envs\openmmlab\lib\site-packages\torch\__init__.py", line 130, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\ProgramData\anaconda3\envs\openmmlab\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.
