### ISSUE TITLE
mim download mmsegmentation --config pspnet_r50-d8_4xb2-40k_cityscapes-512x1024 --dest .

### ISSUE THREAD

**Issue by Isla0628** [open-mmlab/mmsegmentation#3535]
When I download config and checkpoint files,there are some issues occurring：
/home/anaconda3/envs/mmsegmentation/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmsegmentation/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/anaconda3/envs/mmsegmentation/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/anaconda3/envs/mmsegmentation/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/anaconda3/envs/mmsegmentation/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/anaconda3/envs/mmsegmentation/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anaconda3/envs/mmsegmentation/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/anaconda3/envs/mmsegmentation/lib/python3.8/site-packages/mim/commands/download.py", line 49, in cli
    download(package, configs, dest_root)
  File "/home/anaconda3/envs/mmsegmentation/lib/python3.8/site-packages/mim/commands/download.py", line 85, in download
    raise ValueError(
ValueError: Expected configs: dict_keys(['ann_r50-d8_512x1024_40k_cityscapes','ann_r101-d8_512x1024_40k_cityscapes', 'ann_r50-d8_769x769_40k_cityscapes'，......, 'upernet_deit-b16_ln_mln_512x512_160k_ade20k']), but got {'pspnet_r50-d8_4xb2-40k_cityscapes-512x1024'}
I tried to modify the MIM and mmsegmentation versions, but it didn't work！
But when i used command “mim download mmsegmentation --config pspnet_r50-d8_512x1024_40k_cityscapes --dest .”，it is correct!
But there is no pspnet_r50-d8_512x1024_40k_cityscapes.py in the config with mmsegmentation=1.2.2

**Comment by Isla0628** [comment]
![企业微信截图_17061754235627](https://github.com/open-mmlab/mmsegmentation/assets/43298195/c76521f4-761b-473f-a4e0-117a2095e0f3)

**Comment by anamce** [comment]
Install using pip
