### ISSUE TITLE
A error report about "ValueError: need at least one array to concatenate"

### ISSUE THREAD

**Issue by CHIGIRI19** [open-mmlab/mmsegmentation#3576]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

I have installed the mmsegmentation correctly. And I create my own dataset throught your guidance, and I want to train it by deeplabv3+. But after writing the config ,when I training the dataset, an error occur.
 
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 100, in main
    runner.train()
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1728, in train
    self._train_loop = self.build_train_loop(
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1520, in build_train_loop
    loop = LOOPS.build(
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 219, in __init__
    super().__init__(runner, dataloader)
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/public/home/dukr6/mmsegmentation/mmseg/datasets/yuchang.py", line 18, in __init__
    super().__init__(
  File "/public/home/dukr6/mmsegmentation/mmseg/datasets/basesegdataset.py", line 142, in __init__
    self.full_init()
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 307, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/public/home/dukr6/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 768, in _serialize_data
    data_bytes = np.concatenate(data_list)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

Could you help me solve the issue? I'l appreciate it a lot.

**Comment by Muscle-king** [comment]
How did you solve it? Can you share it?

**Comment by svoeff** [comment]
How did you solve it? Can you share it?
