### ISSUE TITLE
Error installing mmengine under lico

### ISSUE THREAD

**Issue by Lamero-y** [open-mmlab/mmsegmentation#3613]
Description of the problem：
1. installation environment：
LICO 7.1.0 , Create my environment using code:  singularity build openmmlab.sif docker://cnstark/pytorch:2.0.1-py3.9.17-cuda11.8.0-ubuntu20.04
>>singularity shell openmmlab.sif
>> pip install openmim 
>> pip install mmengine
>> pip install mmcv
End of installation and  run train.py
2. Environment
![微信截图_20240324193709](https://github.com/open-mmlab/mmsegmentation/assets/69893204/9e546789-4787-4a0d-a03a-4f9efc469a90)
![微信截图_20240324193732](https://github.com/open-mmlab/mmsegmentation/assets/69893204/3b4eff57-263e-4391-acf2-b43d2087b9c5)
![微信截图_20240324193745](https://github.com/open-mmlab/mmsegmentation/assets/69893204/364d2613-0e37-46f8-9f6d-8ec0f7ab6ee1)
![微信截图_20240324193824](https://github.com/open-mmlab/mmsegmentation/assets/69893204/57d83f92-2afa-4ef4-95f1-3596073c2605)
2. questions
(1) Installation error with command：mim install mmengine
Error Reporting Results： bash: mim: command not found 
solution：pip install mmengine
(2) error occurs：from mmengine.runner import Runner
Error Reporting Results：
Traceback (most recent call last):                                                                      
  File "<stdin>", line 1, in <module>                                                                   
  File "/share/home/A0075/.local/lib/python3.9/site-packages/mmengine/runner/__init__.py", line 2, in <m
odule>                                                                                                  
    from ._flexible_runner import FlexibleRunner                                                        
  File "/share/home/A0075/.local/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 
20, in <module>                                                                                         
    from mmengine.hooks import Hook                                                                     
  File "/share/home/A0075/.local/lib/python3.9/site-packages/mmengine/hooks/__init__.py", line 9, in <mo
dule>                                                                                                   
    from .naive_visualization_hook import NaiveVisualizationHook                                        
  File "/share/home/A0075/.local/lib/python3.9/site-packages/mmengine/hooks/naive_visualization_hook.py"
, line 5, in <module>                                                                                   
    import cv2                                                                                          
  File "/share/home/A0075/.local/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>    
    bootstrap()                                                                                         
  File "/share/home/A0075/.local/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap   
    native_module = importlib.import_module("cv2")                                                      
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module                     
    return _bootstrap._gcd_import(name[level:], package, level)                                         
ImportError: libGL.so.1: cannot open shared object file: No such file or directory 

Question: Which step did I go wrong, please guide me, thank you!

**Comment by Zoulinx** [comment]
Try reinstalling mmengine. Sometimes, relinking can resolve issues with missing shared libraries.
