### ISSUE TITLE
模型config有问题

### ISSUE THREAD

**Issue by Grizemc** [open-mmlab/mmsegmentation#3619]
Traceback (most recent call last):
  File "tools/test.py", line 130, in <module>
    main()
  File "tools/test.py", line 125, in main
    runner.test()
  File "/home/grize/mmsegmentation/mmsegmentation-main/mmengine/mmengine/runner/runner.py", line 1811, in test
    raise RuntimeError(
RuntimeError: `self._test_loop` should not be None when calling test method. Please provide `test_dataloader`, `test_cfg` and `test_evaluator` arguments when initializing runner.
这里是不是config文件内容缺失

**Comment by zzzcccxx** [comment]
> Traceback (most recent call last): File "tools/test.py", line 130, in main() File "tools/test.py", line 125, in main runner.test() File "/home/grize/mmsegmentation/mmsegmentation-main/mmengine/mmengine/runner/runner.py", line 1811, in test raise RuntimeError( RuntimeError: `self._test_loop` should not be None when calling test method. Please provide `test_dataloader`, `test_cfg` and `test_evaluator` arguments when initializing runner. 这里是不是config文件内容缺失

同样的问题，请问最后解决了吗？

**Comment by pandascd** [comment]
同样的问题，配置文件里有：
`test_cfg = dict(type='TestLoop')`
不知道哪里还需要配置
