### ISSUE TITLE
mmsegmentation is not installed

### ISSUE THREAD

**Issue by PreWisdom** [open-mmlab/mmsegmentation#3623]
I followed the tutorial to install mmsegmentation with the command `pip install -v -e .`
but it still shows this info `RuntimeError: mmsegmentation is not installed. Please install it first.`
what should I do?

full error report:

Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/Openmm/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.conda/envs/Openmm/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/Openmm/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.conda/envs/Openmm/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.conda/envs/Openmm/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.conda/envs/Openmm/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/Openmm/lib/python3.8/site-packages/mim/commands/download.py", line 70, in cli
    download(package, configs, dest_root, check_certificate, dataset)
  File "/home/ubuntu/.conda/envs/Openmm/lib/python3.8/site-packages/mim/commands/download.py", line 107, in download
    return _download_configs(package, configs, dest_root,
  File "/home/ubuntu/.conda/envs/Openmm/lib/python3.8/site-packages/mim/commands/download.py", line 127, in _download_configs
    raise RuntimeError(
RuntimeError: mmsegmentation is not installed. Please install it first.

**Comment by Zoulinx** [comment]
The installation tutorial is still working as expected. The reason for potential errors might be due to the installation of PyTorch versions above 2.2, leading to subsequent errors in the installation of mmcv components, as there is currently no compiled version of mmcv for PyTorch 2.2. Please try using PyTorch versions 2.1.2 and below, then reinstall following the tutorial.

**Comment by PreWisdom** [comment]
> The installation tutorial is still working as expected. The reason for potential errors might be due to the installation of PyTorch versions above 2.2, leading to subsequent errors in the installation of mmcv components, as there is currently no compiled version of mmcv for PyTorch 2.2. Please try using PyTorch versions 2.1.2 and below, then reinstall following the tutorial.

thanks for reply. I solved this problem already but I think I should record this situation for other users.
here is the solution:
1. deactivate the current environment twice or more until no environments are activated.
2. follow the tutorial to construct a new environment and install mmcv and so on.
cause of the problem:
an environment embeds another environment. for example (env_1 embed env_2):
`(env_1) ubuntu@user : conda deactivate`
`(env_2) ubuntu@user : conda deactivate`
`ubuntu@user : `

Hope it's useful to others
