### ISSUE TITLE
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

### ISSUE THREAD

**Issue by shidizai-swpu** [open-mmlab/mmsegmentation#3625]
Thanks for your error report and we appreciate it a lot.

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

(openmmlab) D:\Desktop\openmmlab\mmsegmentation>python demo/image_demo.py demo/demo.png configs/pspnet/pspnet_r50-d8_4xb2-40k_cityscapes-512x1024.py pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth --device cuda:0 --out-file result.jpg
Traceback (most recent call last):
  File "demo/image_demo.py", line 6, in <module>
    from mmseg.apis import inference_model, init_model, show_result_pyplot
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\apis\__init__.py", line 2, in <module>
    from .inference import inference_model, init_model, show_result_pyplot
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\apis\inference.py", line 14, in <module>
    from mmseg.models import BaseSegmentor
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\models\__init__.py", line 3, in <module>
    from .backbones import *  # noqa: F401,F403
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\models\backbones\__init__.py", line 2, in <module>
    from .beit import BEiT
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\models\backbones\beit.py", line 19, in <module>
    from ..utils import PatchEmbed
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\models\utils\__init__.py", line 2, in <module>
    from .basic_block import BasicBlock, Bottleneck
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\models\utils\basic_block.py", line 10, in <module>
    from mmseg.utils import OptConfigType
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\utils\__init__.py", line 24, in <module>
    from .mask_classification import MatchMasks, seg_data_to_instance_data
  File "d:\desktop\openmmlab\mmsegmentation\mmseg\utils\mask_classification.py", line 5, in <module>
    from mmcv.ops import point_sample
  File "D:\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Anaconda3\envs\openmmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

**Comment by Zoulinx** [comment]
It seems that mmcv may not have been installed correctly. As of today, there is still no compiled version of mmcv for PyTorch 2.2. A possible solution is to install a version of PyTorch below 2.1.2 and then reinstall following the official process for mmseg.
