### ISSUE TITLE
CC attention can run on fp16 during training but not for evaluation

### ISSUE THREAD

**Issue by baibaidj** [open-mmlab/mmsegmentation#370]
The snippet of my training config is like:
```
optimizer_config = dict(type='Fp16OptimizerHook', loss_scale=512., # distributed = True,
                        grad_clip = dict(max_norm = 2, norm_type = 2))
log_config = dict(interval = 10)
# runtime settings
num_gpu = 1
runner = dict(type='IterBasedRunner', max_iters=15526)
# runner = dict(type='EpochBasedRunner', max_epochs=nb_epochs)
checkpoint_config = dict(by_epoch=True, interval= nb_epochs//4) #total_iters//4
evaluation = dict(interval = 20, by_epoch = False, metric='mIoU') # total_iters//40 need_logits = True
```

So I have set the log interval to 10 and it seemed the CCA module was running just fine on FP16 during training as judged by the training log as follows. But the module failed running on FP16 during evaluation. 

```
2021-02-04 10:51:38,202 - mmseg - INFO - workflow: [('train', 1)], max: 15526 iters
2021-02-04 10:52:11,246 - mmseg - INFO - Iter [10/15526]        lr: 1.202e-04, eta: 14:08:09, time: 3.280, data_time: 0.236, memory: 12996, decode.loss_seg: 0.8608, decode.acc_seg: 88.3896, aux.loss_seg: 3.1586, loss: 4.0$
94
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 161, in main
    train_segmentor(
  File "/home/whos/git/mmseg4med/mmseg/apis/train.py", line 117, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/whos/miniconda3/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/whos/miniconda3/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/whos/miniconda3/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/whos/git/mmseg4med/mmseg/core/evaluation/eval_hooks_med.py", line 31, in after_train_iter
    results = single_gpu_test4med(runner.model, self.dataloader, show=False,
  File "/home/whos/git/mmseg4med/mmseg/apis/test_med.py", line 44, in single_gpu_test4med
    result = model(return_loss=False, rescale=not show,
  File "/home/whos/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whos/miniconda3/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/whos/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/whos/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whos/miniconda3/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/whos/git/mmseg4med/mmseg/models/segmentors/base.py", line 124, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/whos/git/mmseg4med/mmseg/models/segmentors/base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/whos/git/mmseg4med/mmseg/models/segmentors/encoder_decoder_med.py", line 237, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/home/whos/git/mmseg4med/mmseg/models/segmentors/encoder_decoder_med.py", line 210, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "/home/whos/git/mmseg4med/mmseg/models/segmentors/encoder_decoder_med.py", line 146, in whole_inference
    seg_logit = self.encode_decode(img, img_meta)
  File "/home/whos/git/mmseg4med/mmseg/models/segmentors/encoder_decoder_med.py", line 50, in encode_decode
    out = self._decode_head_forward_test(x, img_metas)
  File "/home/whos/git/mmseg4med/mmseg/models/segmentors/encoder_decoder.py", line 110, in _decode_head_forward_test
    seg_logits = self.decode_head.forward_test(x, img_metas, self.test_cfg)
  File "/home/whos/git/mmseg4med/mmseg/models/decode_heads/decode_head.py", line 205, in forward_test
    return self.forward(inputs)
  File "/home/whos/git/mmseg4med/mmseg/models/decode_heads/cc_head_med.py", line 54, in forward
    output0 = self.cca(output0)
  File "/home/whos/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whos/miniconda3/lib/python3.8/site-packages/mmcv/ops/cc_attention.py", line 85, in forward
    energy = ca_weight(proj_query, proj_key)
  File "/home/whos/miniconda3/lib/python3.8/site-packages/mmcv/ops/cc_attention.py", line 23, in forward
    ext_module.ca_forward(t, f, weight)
RuntimeError: "ca_forward" not implemented for 'Half'
Exception raised from operator() at /tmp/mmcv/mmcv/ops/csrc/pytorch/cc_attention_cuda.cu:35 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fc8698458b2 in /home/whos/miniconda3/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2c556 (0x7fc630fe0556 in /home/whos/miniconda3/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
frame #2: CAForwardCUDAKernelLauncher(at::Tensor, at::Tensor, at::Tensor) + 0x3bb (0x7fc630fe09d7 in /home/whos/miniconda3/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
frame #3: ca_forward_cuda(at::Tensor, at::Tensor, at::Tensor) + 0x67 (0x7fc631078dd7 in /home/whos/miniconda3/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
frame #4: ca_forward(at::Tensor, at::Tensor, at::Tensor) + 0xf6 (0x7fc6310797c6 in /home/whos/miniconda3/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x8a133 (0x7fc63103e133 in /home/whos/miniconda3/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x8e2ea (0x7fc6310422ea in /home/whos/miniconda3/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
<omitting python frames>
frame #12: THPFunction_apply(_object*, _object*) + 0x93d (0x7fc80c29f2dd in /home/whos/miniconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
```
Any suggestions are welcomed. Thank you.

**Comment by xvjiarui** [comment]
Hi @baibaidj 
Thanks for the feedback. We haven't implemented fp16 for cc net operation yet.
