### ISSUE TITLE
RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 0

### ISSUE THREAD

**Issue by ZhoumingZhang** [open-mmlab/mmsegmentation#3715]
Traceback (most recent call last):
  File "C:\Git clone\mmsegmentation\tools\train.py", line 104, in <module>
    main()
  File "C:\Git clone\mmsegmentation\tools\train.py", line 100, in main
    runner.train()
  File "C:\Users\13785\.conda\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "C:\Users\13785\.conda\envs\pytorch\lib\site-packages\mmengine\runner\loops.py", line 287, in run
    self.run_iter(data_batch)
  File "C:\Users\13785\.conda\envs\pytorch\lib\site-packages\mmengine\runner\loops.py", line 311, in run_iter
    outputs = self.runner.model.train_step(
  File "C:\Users\13785\.conda\envs\pytorch\lib\site-packages\mmengine\model\base_model\base_model.py", line 113, in train_step
    data = self.data_preprocessor(data, True)
  File "C:\Users\13785\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Git clone\mmsegmentation\mmseg\models\data_preprocessor.py", line 118, in forward
    inputs = [(_input - self.mean) / self.std for _input in inputs]
  File "C:\Git clone\mmsegmentation\mmseg\models\data_preprocessor.py", line 118, in <listcomp>
    inputs = [(_input - self.mean) / self.std for _input in inputs]
RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 0

**Comment by pomelloa** [comment]
Did you use the data transforms called 'PhotoMetricDistortion'? The step may convert color from BGR to HSV, so the data is limited to a(3).
