### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered when training PIDNet with Cityscapes

### ISSUE THREAD

**Issue by anhphan2705** [open-mmlab/mmsegmentation#3724]
**Notice**

Reimplement a model in the model zoo using the provided configs.

**Checklist**

1. I have searched for related issues but cannot get the expected help.
2. The issue has not been fixed in the latest version.

**Describe the issue**

I tried to train PIDNet with Cityscapes dataset using the default config provided, but getting `RuntimeError: CUDA error: device-side assert triggered`.  I would appreciate any recommendation and help.

I have downloaded and put the `cityscapes` dataset into the correct directory. I applied the dataset conversion necessary as described in [the documentation](https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/user_guides/2_dataset_prepare.md#cityscapes). Then I use the provided command [here](https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/user_guides/4_train_test.md#training-on-a-single-gpu) to train.

**Reproduction**

1. What command or script did you run?

```
python tools/dataset_converters/cityscapes.py data/cityscapes --nproc 8
python tools/train.py configs\pidnet\pidnet-s_2xb6-120k_1024x1024-cityscapes.py
```

2. What config dir you run?

```
configs\pidnet\pidnet-s_2xb6-120k_1024x1024-cityscapes.py
```

3. Did you make any modifications to the code or config? Did you understand what you have modified?
I did not modified anything.

4. What dataset did you use? Cityscapes

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmseg/utils/collect_env.py` to collect the necessary environment information and paste it here.

```
sys.platform: win32
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: n/a
PyTorch: 2.1.2+cu118
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37     
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /utf-8 /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.2+cu118
OpenCV: 4.8.0
MMEngine: 0.10.4
MMSegmentation: 1.2.2+
```

**Results**

```
07/02 10:52:35 - mmengine - WARNING - The prefix is not set in metric class IoUMetric.
07/02 10:52:35 - mmengine - INFO - Loads checkpoint by http backend from path: https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/pidnet/pidnet-s_imagenet1k_20230306-715e6273.pth
07/02 10:52:35 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
07/02 10:52:35 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
07/02 10:52:35 - mmengine - INFO - Checkpoints will be saved to C:\Users\black\Desktop\Projects\computer-vision\autonomous_vehicle\camera_perc\models\mmsegmentation-main\work_dirs\pidnet-s_2xb6-120k_1024x1024-cityscapes.
C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\utils\wrappers.py:22: UserWarning: When align_corners=True, the output would more aligned if input size (128, 128) is `x+1` and out size (1024, 1024) is `nx+1`
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\black\Desktop\Projects\computer-vision\autonomous_vehicle\camera_perc\models\mmsegmentation-main\tools\train.py", line 104, in <module>
    main()
  File "C:\Users\black\Desktop\Projects\computer-vision\autonomous_vehicle\camera_perc\models\mmsegmentation-main\tools\train.py", line 100, in main
    runner.train()
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\runner\runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\runner\loops.py", line 287, in run
    self.run_iter(data_batch)
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\runner\loops.py", line 311, in run_iter
    outputs = self.runner.model.train_step(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\model\base_model\base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\model\base_model\base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\segmentors\base.py", line 94, in forward
    return self.loss(inputs, data_samples)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 178, in loss
    loss_decode = self._decode_head_forward_train(x, data_samples)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 139, in _decode_head_forward_train
    loss_decode = self.decode_head.loss(inputs, data_samples,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\decode_heads\decode_head.py", line 262, in loss
    losses = self.loss_by_feat(seg_logits, batch_data_samples)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\decode_heads\pid_head.py", line 175, in loss_by_feat
    loss['loss_sem_i'] = self.loss_decode[1](i_logit, sem_label)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\losses\ohem_cross_entropy_loss.py", line 62, in forward
    pred = F.softmax(score, dim=1)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\functional.py", line 1856, in softmax
    ret = input.softmax(dim)
          ^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

This is when I passed CUDA_LAUNCH_BLOCKING=1 into train.py 
```07/02 12:20:12 - mmengine - WARNING - The prefix is not set in metric class IoUMetric.
07/02 12:20:12 - mmengine - INFO - Loads checkpoint by http backend from path: https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/pidnet/pidnet-s_imagenet1k_20230306-715e6273.pth
07/02 12:20:12 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
07/02 12:20:12 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
07/02 12:20:12 - mmengine - INFO - Checkpoints will be saved to C:\Users\black\Desktop\Projects\computer-vision\autonomous_vehicle\camera_perc\models\mmseg_pidnet\work_dirs\pidnet-s_2xb6-120k_1024x1024-cityscapes.
C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\utils\wrappers.py:22: UserWarning: When align_corners=True, the output would more aligned if input size (128, 128) is `x+1` and out size (1024, 1024) is `nx+1`
  warnings.warn(
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [525,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [525,0,0], thread: [97,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [525,0,0], thread: [98,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [525,0,0], thread: [99,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [525,0,0], thread: [100,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.   
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [525,0,0], thread: [101,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.   
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [513,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [513,0,0], thread: [97,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [513,0,0], thread: [98,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [513,0,0], thread: [99,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [513,0,0], thread: [100,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.   
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [513,0,0], thread: [101,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.   
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [515,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [515,0,0], thread: [97,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [515,0,0], thread: [98,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [515,0,0], thread: [99,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [515,0,0], thread: [100,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.   
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [515,0,0], thread: [101,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.   
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [511,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [511,0,0], thread: [97,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [511,0,0], thread: [98,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [511,0,0], thread: [99,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [511,0,0], thread: [100,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.   
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [511,0,0], thread: [101,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.   
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [737,0,0], thread: [31,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.    
Traceback (most recent call last):
  File "C:\Users\black\Desktop\Projects\computer-vision\autonomous_vehicle\camera_perc\models\mmseg_pidnet\tools\train.py", line 105, in <module>
    main()
  File "C:\Users\black\Desktop\Projects\computer-vision\autonomous_vehicle\camera_perc\models\mmseg_pidnet\tools\train.py", line 100, in main
    runner.train()
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\runner\runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\runner\loops.py", line 287, in run
    self.run_iter(data_batch)
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\runner\loops.py", line 311, in run_iter
    outputs = self.runner.model.train_step(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\model\base_model\base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmengine\model\base_model\base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\segmentors\base.py", line 94, in forward
    return self.loss(inputs, data_samples)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 178, in loss
    loss_decode = self._decode_head_forward_train(x, data_samples)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 139, in _decode_head_forward_train
    loss_decode = self.decode_head.loss(inputs, data_samples,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\decode_heads\decode_head.py", line 262, in loss
    losses = self.loss_by_feat(seg_logits, batch_data_samples)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\decode_heads\pid_head.py", line 173, in loss_by_feat
    loss['loss_sem_p'] = self.loss_decode[0](
                         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\losses\cross_entropy_loss.py", line 286, in forward
    loss_cls = self.loss_weight * self.cls_criterion(
                                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\losses\cross_entropy_loss.py", line 66, in cross_entropy
    label_weights = torch.stack([class_weight[cls] for cls in label
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\Desktop\Projects\computer-vision\comvis_env\Lib\site-packages\mmseg\models\losses\cross_entropy_loss.py", line 66, in <listcomp>
    label_weights = torch.stack([class_weight[cls] for cls in label
                                 ~~~~~~~~~~~~^^^^^
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Is `class_weight` the problem?

**Comment by anhphan2705** [comment]
The solution originally posted by @talebolano in [issues#3574](https://github.com/open-mmlab/mmsegmentation/issues/3574#issuecomment-1996773726) worked. However, I don't know if it is a good way to fix it (literally just removing the problematic line).

I went to the `cross_entrophy_loss.py` which was installed in my venv `\comvis_env\Lib\site-packages\mmseg\models\losses\cross_entropy_loss.py`. Basiclly commented out the `label_weights` as such

```python
    # apply weights and do the reduction
    # average loss over non-ignored elements
    # pytorch's official cross_entropy average loss over non-ignored elements
    # refer to https://github.com/pytorch/pytorch/blob/56b43f4fec1f76953f15a627694d4bba34588969/torch/nn/functional.py#L2660  # noqa
    if (avg_factor is None) and reduction == 'mean':
        if class_weight is None:
            if avg_non_ignore:
                avg_factor = label.numel() - (label== ignore_index).sum().item()
            else:
                avg_factor = label.numel()

        # else:
        #     # the average factor should take the class weights into account
        #     label_weights = torch.stack([class_weight[cls] for cls in label
        #                                  ]).to(device=class_weight.device)

        #     if avg_non_ignore:
        #         label_weights[label == ignore_index] = 0
        #     avg_factor = label_weights.sum()

    if weight is not None:
        weight = weight.float()
    loss = weight_reduce_loss(
        loss, weight=weight, reduction=reduction, avg_factor=avg_factor)

    return loss
```

**Comment by AAAdecade** [comment]
Hello!
I'm a beginner and also reproducing pidnet recently and I'm having the same problem as you, thank you so much for the solution!
Also, when I test on the cityscapes dataset based on mmsegmentation, why don't I generate the official 1525 test images and still use 500 val images? Is there any problem with my operation? Looking forward to your help and reply!

What command or script did you run?
python tools/test.py  configs/pidnet/pidnet-s_2xb6-120k_1024x1024-cityscapes.py  outputs/iter_120000.pth  --work-dir  /root/autodl-tmp/mmsegmentation/results

results:
![image](https://github.com/open-mmlab/mmsegmentation/assets/145337236/98233636-2b8d-40ac-bc9d-342959d383b5)

**Comment by anhphan2705** [comment]
Hi. 

If you look inside `configs/_base_/datasets/cityscapes.py`, you will see this

```python
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='leftImg8bit/train', seg_map_path='gtFine/train'),
        pipeline=train_pipeline))
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='leftImg8bit/val', seg_map_path='gtFine/val'),
        pipeline=test_pipeline))
test_dataloader = val_dataloader
```

`test_dataloader = val_dataloader` should answer your question why. You can change `test_dataloader` to the example below and see what it does. Since this is the base configuration, you should check if any other config file is overwriting this one. You might or might not have to retrain your model.

```python
test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(
            img_path='leftImg8bit/test', seg_map_path='gtFine/test'),
        pipeline=test_pipeline))
```

By the way, this is an unrelated problem from the original post. You should open a new issue request for proper help and bug-fixing purposes.

**Comment by AAAdecade** [comment]
Thank you very much for your reply. I searched for the cityscapes.py file and made modifications to the test_dataloader. 
However, currently i am still unable to obtain 1525 images predicted by Cityscapes for the test output, so we are unable to submit the test data to the official website. May I ask if mmsegmentation did not join the test for PIDNet, or if there was an issue with my operation. As a beginner, I hope to receive your guidance. Thanks.
![clipboard-image-1720529879](https://github.com/open-mmlab/mmsegmentation/assets/145337236/0f070245-8060-4273-ba12-d663d16d98de)
![image](https://github.com/open-mmlab/mmsegmentation/assets/145337236/c0a69b60-dbb6-42ea-a7cc-60104f9b7652)

**Comment by anhphan2705** [comment]
Hi.
I suggest you open a new issue so others can see the question and help you. I don't know the answer to your question. However, you can make a test file yourself and run a video through the model. If you don't know how to, I have made an inference file for testing [here](https://github.com/anhphan2705/im_pidnet)

**Comment by AAAdecade** [comment]
> Hi. I suggest you open a new issue so others can see the question and help you. I don't know the answer to your question. However, you can make a test file yourself and run a video through the model. If you don't know how to, I have made an inference file for testing [here](https://github.com/anhphan2705/im_pidnet)

Thank you very much for your reply! I have seen your repository and it has helped me a lot, thank you!
