### ISSUE TITLE
How to use deeplabv3_unet_s5-d16 to train VOC Dataset？

### ISSUE THREAD

**Issue by madexin** [open-mmlab/mmsegmentation#398]
I want to use U-Net to train VOC Dataset，I make the configs like this：

_base_ = [
    '../_base_/models/deeplabv3_unet_s5-d16.py', '../_base_/datasets/pascal_voc12.py',
    '../_base_/default_runtime.py', '../_base_/schedules/schedule_40k.py'
]
model = dict(test_cfg=dict(crop_size=(256, 256), stride=(170, 170)))
evaluation = dict(metric='mDice')

But, Unfortunately, the training process encountered a problem

Traceback (most recent call last):
  File "./tools/train.py", line 163, in <module>
    main()
  File "./tools/train.py", line 137, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/hp/anaconda3/envs/open-mmlab-seg-0.11/lib/python3.7/site-packages/mmcv/utils/config.py", line 43, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'train'
Traceback (most recent call last):
  File "/home/hp/anaconda3/envs/open-mmlab-seg-0.11/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hp/anaconda3/envs/open-mmlab-seg-0.11/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hp/anaconda3/envs/open-mmlab-seg-0.11/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/hp/anaconda3/envs/open-mmlab-seg-0.11/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hp/anaconda3/envs/open-mmlab-seg-0.11/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/unet/deeplabv3_unet_s5-d16_256x256_40k_hrf.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

How can we use U-Net to train the dataset?

**Comment by xiexinch** [comment]
Hi @madexin
In your config settings, the **base** config list should be named **\_base\_** , and the dir name is also **\_base\_** .
Furthermore, in the **model** dict, we should specify **num_classes** to decode_head and auxiliary_head.
