### ISSUE TITLE
used custom data to train mmsegmentation, the training loss did not go down

### ISSUE THREAD

**Issue by 15122901359** [open-mmlab/mmsegmentation#453]
Hello, when I used custom data to train mmsegmentation, the training loss did not go down. Could you please tell me the reason? The following is my parameter setting
train Process:
"
{"mode": "train", "epoch": 1, "iter": 3050, "lr": 0.00983, "memory": 19394, "data_time": 0.00386, "decode.loss_seg": 0.11016, "decode.acc_seg": 86.9765, "aux.loss_seg": 0.04462, "aux.acc_seg": 86.9765, "loss": 0.15478, "time": 0.40774}
{"mode": "train", "epoch": 2, "iter": 15650, "lr": 0.00912, "memory": 19394, "data_time": 0.00391, "decode.loss_seg": 0.14214, "decode.acc_seg": 79.69231, "aux.loss_seg": 0.05745, "aux.acc_seg": 79.69231, "loss": 0.19959, "time": 0.40296}

"

custom data:
Class: 2, foreground and background, corresponding to seg_mask value [1,0]
Modified network parameters
the num_class category for the network to 2,

```

from .builder import DATASETS
from .custom import CustomDataset
@DATASETS.register_module()
class ADE20KDataset(CustomDataset):

    CLASSES = (
        'background','person')

    PALETTE = [[120, 120, 120], [180, 120, 120]]

    def __init__(self, **kwargs):
        super(ADE20KDataset, self).__init__(
            img_suffix='.jpg',
            seg_map_suffix='.jpg',
            reduce_zero_label=True,
            **kwargs)
```
configs:  deeplabv3plus_s101-d8_512x512_160k_ade20k
base_model config:
```
# model settings
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='open-mmlab://resnet50_v1c',
    backbone=dict(
        type='ResNetV1c',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=norm_cfg,
        norm_eval=False,
        style='pytorch',
        contract_dilation=True),
    decode_head=dict(
        type='DepthwiseSeparableASPPHead',
        in_channels=2048,
        in_index=3,
        channels=512,
        dilations=(1, 12, 24, 36),
        c1_in_channels=256,
        c1_channels=48,
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
```

another question when i test model used I trained, The 'RuntimeError: cuda runtime error' problem that often comes up ,

```
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(type='Resize', img_scale=(2048, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 512),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', img_scale=(512, 512)),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir=data_root+'bust_img',
        ann_dir=data_root+'bust_mask',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_root=data_root_val,
        img_dir=data_root_val+'bust_img',
        ann_dir=data_root_val+'bust_mask',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root_test,
        img_dir=data_root_test+'bust_img',
        ann_dir=data_root_test+'bust_mask',
        pipeline=test_pipeline))
```
test problem
"
[>>>                                               ] 124/1991, 0.7 task/s, elapsed: 182s, ETA:  2736sTraceback (most recent call last):
  File "./tools/test.py", line 153, in <module>
    main()
  File "./tools/test.py", line 138, in main
    args.gpu_collect, efficient_test)
  File "/root/workspace/semantic_seg/mmsegmentation/mmseg/apis/test.py", line 140, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/root/.local/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/.local/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/.local/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/workspace/PANDA/mmcv/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/root/workspace/semantic_seg/mmsegmentation/mmseg/models/segmentors/base.py", line 124, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/root/workspace/semantic_seg/mmsegmentation/mmseg/models/segmentors/base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/root/workspace/semantic_seg/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 265, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/root/workspace/semantic_seg/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 250, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "/root/workspace/semantic_seg/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 224, in whole_inference
    warning=False)
  File "/root/workspace/semantic_seg/mmsegmentation/mmseg/ops/wrappers.py", line 29, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "/root/.local/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 3554, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: CUDA out of memory. Tried to allocate 23.53 GiB (GPU 0; 31.75 GiB total capacity; 879.06 MiB already allocated; 14.11 GiB free; 2.40 GiB reserved in total by PyTorch)
"

**Comment by xvjiarui** [comment]
Hi @15122901359 
You may fine-tune your model from provided checkpoints. 
I am not sure about the CUDA out of memory. Could you please check if you could run the provided config to inference?

**Comment by 15122901359** [comment]
> e-tune your model from provided checkpoi
hello,this is my config,could you please help me check what the problem is? Thank you very much
`norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='open-mmlab://resnest101',
    backbone=dict(
        type='ResNeSt',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True,
        stem_channels=128,
        radix=2,
        reduction_factor=4,
        avg_down_stride=True),
    decode_head=dict(
        type='DepthwiseSeparableASPPHead',
        in_channels=2048,
        in_index=3,
        channels=512,
        dilations=(1, 12, 24, 36),
        c1_in_channels=256,
        c1_channels=48,
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=150,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'ADE20KDataset'
data_root = '/root/ftp/PosterImage_v1/train/*/'
data_root_val = '/root/ftp/PosterImage_v1/val/*/'
data_root_test = '/root/ftp/PosterImage_v1/test/*/'
img_name = 'merge_bustimg'
mask_name = 'merge_bustmask'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(type='Resize', img_scale=(2048, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size=(512, 512), pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 512),
        flip=False,
        transforms=[
            dict(type='Resize', img_scale=(512, 512)),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type='ADE20KDataset',
        data_root='/root/ftp/PosterImage_v1/train/*/',
        img_dir='/root/ftp/PosterImage_v1/train/*/merge_bustimg',
        ann_dir='/root/ftp/PosterImage_v1/train/*/merge_bustmask',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', reduce_zero_label=True),
            dict(type='Resize', img_scale=(2048, 512), ratio_range=(0.5, 2.0)),
            dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(512, 512), pad_val=0, seg_pad_val=255),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='ADE20KDataset',
        data_root='/root/ftp/PosterImage_v1/val/*/',
        img_dir='/root/ftp/PosterImage_v1/val/*/merge_bustimg',
        ann_dir='/root/ftp/PosterImage_v1/val/*/merge_bustmask',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(2048, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', img_scale=(512, 512)),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='ADE20KDataset',
        data_root='/root/ftp/PosterImage_v1/test/*/',
        img_dir='/root/ftp/PosterImage_v1/test/*/merge_bustimg',
        ann_dir='/root/ftp/PosterImage_v1/test/*/merge_bustmask',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(2048, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', img_scale=(512, 512)),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50, hooks=[dict(type='TextLoggerHook', by_epoch=False)])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = './checkpoints/deeplabv3plus_s101-d8_512x512_160k_ade20k_20200807_144503-27b26226.pth'
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(type='SGD', lr=0.00125, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict()
lr_config = dict(policy='poly', power=0.9, min_lr=0.0001, by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=121500)
checkpoint_config = dict(by_epoch=False, interval=8100)
evaluation = dict(interval=8100, metric='mIoU')
work_dir = './work_dirs/deeplabv3plus_s101-d8_512x512_160k_ade20k'
gpu_ids = range(0, 1)
`

**Comment by MengzhangLI** [comment]
Hi, could you re-check the checkpoints in inference pipeline because in this case we could tell whether the checkpoints works basically on your customized dataset.

After that, you could use training pipeline to fine-tune your model in your own dataset. 

Best,
