### ISSUE TITLE
After I installed mmsegmentation, I tested and found the following errors

### ISSUE THREAD

**Issue by THEBEST-cloud** [open-mmlab/mmsegmentation#496]
Traceback (most recent call last):
  File "e:/master/master1/RSISS/mmcv/mmsegmentation/ceshi.py", line 1, in <module>
    from mmseg.apis import inference_segmentor, init_segmentor
  File "e:\master\master1\RSISS\mmcv\mmsegmentation\mmseg\apis\__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "e:\master\master1\RSISS\mmcv\mmsegmentation\mmseg\apis\inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "e:\master\master1\RSISS\mmcv\mmsegmentation\mmseg\models\__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "e:\master\master1\RSISS\mmcv\mmsegmentation\mmseg\models\backbones\__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "e:\master\master1\RSISS\mmcv\mmsegmentation\mmseg\models\backbones\fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "e:\master\master1\RSISS\mmcv\mmsegmentation\mmseg\models\decode_heads\__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "e:\master\master1\RSISS\mmcv\mmsegmentation\mmseg\models\decode_heads\cc_head.py", line 7, in <module>
    from mmcv.ops import CrissCrossAttention
  File "D:\Anaconda3\envs\open-mmlab\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "D:\Anaconda3\envs\open-mmlab\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "D:\Anaconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Anaconda3\envs\open-mmlab\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed:  The specified module could not be found.

Can you help me look at this problem and tell me how to solve it？

**Comment by xiexinch** [comment]
Hi @THEBEST-cloud 
You may try install the latest mmcv-full.

**Comment by THEBEST-cloud** [comment]
It doesn't seem to work, because mmcv-full 1.3.0 windows cannot be installed, only version 1.1.5 can be installed

**Comment by THEBEST-cloud** [comment]
@xiexinch It doesn't seem to work, because mmcv-full 1.3.0 windows cannot be installed, only version 1.1.5 can be installed

**Comment by MengzhangLI** [comment]
> @xiexinch It doesn't seem to work, because mmcv-full 1.3.0 windows cannot be installed, only version 1.1.5 can be installed

Could you show snapshot of installation error of mmcv-full 1.3.0 on windows?

To be honest, most of us use Linux thus we seldom face those errors in windows. Maybe we could try to figure it out together.

Best,

**Comment by vaghasiatirth24** [comment]
Hi I'm having the same issue with it I have pytorch 1.6.0 and mmcv full 1.1.5 cpu only. Did you find the solution for it?

**Comment by Zihang-Wei** [comment]
C:\Users\uif46395\Miniconda3\envs\pytorch\lib\site-packages\mmcv\cnn\bricks\transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-5-8c48e7f98d8f>](https://localhost:8080/#) in <module>
----> 1 from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
      2 from mmseg.core.evaluation import get_palette

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\apis\__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .inference import inference_segmentor, init_segmentor, show_result_pyplot
      3 from .test import multi_gpu_test, single_gpu_test
      4 from .train import (get_root_logger, init_random_seed, set_random_seed,
      5                     train_segmentor)

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\apis\inference.py in <module>
      7 
      8 from mmseg.datasets.pipelines import Compose
----> 9 from mmseg.models import build_segmentor
     10 
     11 

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\models\__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .backbones import *  # noqa: F401,F403
      3 from .builder import (BACKBONES, HEADS, LOSSES, SEGMENTORS, build_backbone,
      4                       build_head, build_loss, build_segmentor)
      5 from .decode_heads import *  # noqa: F401,F403

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\models\backbones\__init__.py in <module>
      5 from .cgnet import CGNet
      6 from .erfnet import ERFNet
----> 7 from .fast_scnn import FastSCNN
      8 from .hrnet import HRNet
      9 from .icnet import ICNet

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\models\backbones\fast_scnn.py in <module>
      5 from mmcv.runner import BaseModule
      6 
----> 7 from mmseg.models.decode_heads.psp_head import PPM
      8 from mmseg.ops import resize
      9 from ..builder import BACKBONES

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\models\decode_heads\__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .ann_head import ANNHead
      3 from .apc_head import APCHead
      4 from .aspp_head import ASPPHead
      5 from .cc_head import CCHead

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\models\decode_heads\ann_head.py in <module>
      6 from ..builder import HEADS
      7 from ..utils import SelfAttentionBlock as _SelfAttentionBlock
----> 8 from .decode_head import BaseDecodeHead
      9 
     10 

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\models\decode_heads\decode_head.py in <module>
     10 from mmseg.ops import resize
     11 from ..builder import build_loss
---> 12 from ..losses import accuracy
     13 
     14 

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\models\losses\__init__.py in <module>
      4                                  cross_entropy, mask_cross_entropy)
      5 from .dice_loss import DiceLoss
----> 6 from .focal_loss import FocalLoss
      7 from .lovasz_loss import LovaszLoss
      8 from .tversky_loss import TverskyLoss

c:\users\uif46395\desktop\data\radar_points\test\mmsegmentation\mmseg\models\losses\focal_loss.py in <module>
      4 import torch.nn as nn
      5 import torch.nn.functional as F
----> 6 from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
      7 
      8 from ..builder import LOSSES

~\Miniconda3\envs\pytorch\lib\site-packages\mmcv\ops\__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .active_rotated_filter import active_rotated_filter
      3 from .assign_score_withk import assign_score_withk
      4 from .ball_query import ball_query
      5 from .bbox import bbox_overlaps

~\Miniconda3\envs\pytorch\lib\site-packages\mmcv\ops\active_rotated_filter.py in <module>
     10 ext_module = ext_loader.load_ext(
     11     '_ext',
---> 12     ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
     13 
     14 

~\Miniconda3\envs\pytorch\lib\site-packages\mmcv\utils\ext_loader.py in load_ext(name, funcs)
     11 
     12     def load_ext(name, funcs):
---> 13         ext = importlib.import_module('mmcv.' + name)
     14         for fun in funcs:
     15             assert hasattr(ext, fun), f'{fun} miss in module {name}'

~\Miniconda3\envs\pytorch\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ImportError: DLL load failed: The specified procedure could not be found.
