### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by DMing11** [open-mmlab/mmsegmentation#500]
**I  used 4 gpus to train deeplabv3plus with A2D2(Audi) dataset, and got an MemoryError when saving checkpoints after evalutation.
The A2D2 dataset include 36459 images to train and 4818 images to evalutation. The error messages and my config are as follows, Have anyone ever had this problem?**

  2021-04-20 09:59:06,140 - mmseg - INFO - Start running, host: l4@instance-ogqzut76-3, work_dir: /data/zhangliming/models/mmsegmentation/tools/work_dirs/deeplabv3plus_r18-d8_512x1024_80k_cityscapes
2021-04-20 09:59:06,140 - mmseg - INFO - workflow: [('train', 1)], max: 80000 iters
2021-04-20 09:59:23,081 - mmseg - INFO - Iter [50/80000]	lr: 9.995e-03, eta: 6:01:40, time: 0.271, data_time: 0.027, memory: 17757, decode.loss_seg: 2.0984, decode.acc_seg: 33.2466, aux.loss_seg: 0.9505, aux.acc_seg: 27.8273, loss: 3.0490
2021-04-20 09:59:30,733 - mmseg - INFO - Saving checkpoint at 100 iterations
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4820/4818, 38.3 task/s, elapsed: 126s, ETA:     0sTraceback (most recent call last):
  File "./train.py", line 166, in <module>
    main()
  File "./train.py", line 162, in main
    meta=meta)
  File "/data/zhangliming/models/mmsegmentation/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/data/zhangliming/models/mmsegmentation/mmseg/core/evaluation/eval_hooks.py", line 89, in after_train_iter
    gpu_collect=self.gpu_collect)
  File "/data/zhangliming/models/mmsegmentation/mmseg/apis/test.py", line 160, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/data/zhangliming/models/mmsegmentation/mmseg/apis/test.py", line 185, in collect_results_cpu
    mmcv.dump(result_part, osp.join(tmpdir, 'part_{}.pkl'.format(rank)))
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/fileio/io.py", line 80, in dump
    handler.dump_to_path(obj, file, **kwargs)
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    obj, filepath, mode='wb', **kwargs)
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/fileio/handlers/base.py", line 25, in dump_to_path
    self.dump_to_fileobj(obj, f, **kwargs)
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 22, in dump_to_fileobj
    pickle.dump(obj, file, **kwargs)
MemoryError
Traceback (most recent call last):
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/l4/anaconda3/envs/jiuwei/bin/python', '-u', './train.py', '--local_rank=3', '../configs/deeplabv3plus/deeplabv3plus_r18-d8_512x1024_80k_cityscapes.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
(jiuwei) l4@instance-ogqzut76-3:/data/zhangliming/models/mmsegmentation/tools$ timed out waiting for input: auto-logout

**I got another error when I use 1 GPU** 

2021-04-20 16:39:34,545 - mmseg - INFO - Saving checkpoint at 2000 iterations
[                                                  ] 0/4818, elapsed: 0s, ETA:Traceback (most recent call last):
  File "train.py", line 166, in <module>
    main()
  File "train.py", line 162, in main
    meta=meta)
  File "/data/zhangliming/models/mmsegmentation/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/l4/zhangziqi/JiuweiNet/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/data/zhangliming/models/mmsegmentation/mmseg/core/evaluation/eval_hooks.py", line 30, in after_train_iter
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/data/zhangliming/models/mmsegmentation/mmseg/apis/test.py", line 61, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/l4/anaconda3/envs/jiuwei/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Config**

norm_cfg = dict(type='BN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained='open-mmlab://resnet18_v1c',
    backbone=dict(
        type='ResNetV1c',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True),
    decode_head=dict(
        type='DepthwiseSeparableASPPHead',
        in_channels=512,
        in_index=3,
        channels=128,
        dilations=(1, 12, 24, 36),
        c1_in_channels=64,
        c1_channels=12,
        dropout_ratio=0.1,
        num_classes=19,
        norm_cfg=dict(type='BN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=256,
        in_index=2,
        channels=64,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=19,
        norm_cfg=dict(type='BN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'A2D2Dataset'
data_root = '/data/zhangliming/data/A2D2'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 1024)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(1920, 1208), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=(512, 1024), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size=(512, 1024), pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1920, 1208),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=16,
    workers_per_gpu=0,
    train=dict(
        type='A2D2Dataset',
        data_root='/data/zhangliming/data/A2D2',
        img_dir='image/train',
        ann_dir='label/train',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(
                type='Resize', img_scale=(1920, 1208), ratio_range=(0.5, 2.0)),
            dict(type='RandomCrop', crop_size=(512, 1024), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(512, 1024), pad_val=0, seg_pad_val=255),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='A2D2Dataset',
        data_root='/data/zhangliming/data/A2D2',
        img_dir='image/val',
        ann_dir='label/val',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1920, 1208),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='A2D2Dataset',
        data_root='/data/zhangliming/data/A2D2',
        img_dir='image/val',
        ann_dir='label/val',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1920, 1208),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))

**Comment by shiomi326** [comment]
I got same error.  
But it didn't happen in the same environment before. (I'm training with 4 GPUs)
My env: cuda 10.2, python3.7, pytorch1.6, mmcv=1.3.3, mmsegmentation=0.13.0, network: deeplabv3plus

**Comment by xvjiarui** [comment]
Hi @DMing11 
Please try `efficient_test=True`

**Comment by shiomi326** [comment]
I will try that. thank you @xvjiarui
