### ISSUE TITLE
I made an error during training. I would like to ask if you have a solution. I am looking forward to your reply.

### ISSUE THREAD

**Issue by Ygya** [open-mmlab/mmsegmentation#518]
2021-04-26 10:23:01,206 - mmseg - INFO - workflow: [('train', 1)], max: 80000 iters
Traceback (most recent call last):
  File "tools/train.py", line 163, in <module>
    main()
  File "tools/train.py", line 159, in main
    meta=meta)
  File "/home/zc/1T/YGY/mmsegmentation/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/zc/1T/YGY/mmsegmentation/mmcv/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/zc/1T/YGY/mmsegmentation/mmcv/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/zc/1T/YGY/mmsegmentation/mmcv/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/zc/1T/YGY/mmsegmentation/mmseg/models/segmentors/base.py", line 152, in train_step
    losses = self(**data_batch)
  File "/home/zc/anaconda3/envs/mmseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zc/1T/YGY/mmsegmentation/mmcv/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/zc/1T/YGY/mmsegmentation/mmseg/models/segmentors/base.py", line 122, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/zc/1T/YGY/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 158, in forward_train
    gt_semantic_seg)
  File "/home/zc/1T/YGY/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 102, in _decode_head_forward_train
    self.train_cfg)
  File "/home/zc/1T/YGY/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 187, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "/home/zc/1T/YGY/mmsegmentation/mmcv/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/zc/1T/YGY/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 222, in losses
    align_corners=self.align_corners)
  File "/home/zc/1T/YGY/mmsegmentation/mmseg/ops/wrappers.py", line 26, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "/home/zc/anaconda3/envs/mmseg/lib/python3.7/site-packages/torch/nn/functional.py", line 3163, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, sfl[0], sfl[1])
RuntimeError: It is expected output_size equals to 2, but got size 3
段错误 (核心已转储)

**Comment by xvjiarui** [comment]
Hi @Ygya 
Could you please provide the command and config you run? You may directly use the error report template.

**Comment by Ygya** [comment]
Thank you for your kindness, I have done it

**Comment by sowmen** [comment]
@Ygya  How did you solve it? I am having the same error.

**Comment by giddyyupp** [comment]
Hi @sowmen, i solved same problem by saving mask images as gray scale.
