### ISSUE TITLE
KeyError: 'OffroadDataset is not in the dataset registry'

### ISSUE THREAD

**Issue by ray401** [open-mmlab/mmsegmentation#627]
i want to use my own dataset to train a model,.
i 've changed the configs file to adapt the dataset path.

but when i run the command : "python tools/train.py configs/fcn/fcn_d6_r101-d16_769x769_40k_offroad.py"，i got the errors like this:
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 138, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ray/Documents/mmsegmentation/mmseg/datasets/builder.py", line 73, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'OffroadDataset is not in the dataset registry'

Anyone can give me a advice?
Thanks

**Comment by MengzhangLI** [comment]
Hi, it is usually caused by registry mechanism of mmcv.

Perhaps you need to define a class of your datasets before using it.

https://github.com/open-mmlab/mmdetection/issues/1324#issuecomment-844764581

Hoping it is helpful to you and looking forward to your reply.

Best,
