### ISSUE TITLE
error when training using deepscene dataset

### ISSUE THREAD

**Issue by ray401** [open-mmlab/mmsegmentation#645]
Traceback (most recent call last):
  File "/home/ray/Documents/mmsegmentation/tools/train.py", line 169, in <module>
    main()
  File "/home/ray/Documents/mmsegmentation/tools/train.py", line 165, in main
    meta=meta)
  File "/home/ray/Documents/mmsegmentation/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ray/Documents/mmsegmentation/mmseg/models/segmentors/base.py", line 137, in train_step
    losses = self(**data_batch)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/segmentors/base.py", line 107, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 143, in forward_train
    gt_semantic_seg)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 87, in _decode_head_forward_train
    self.train_cfg)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 185, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 184, in new_func
    return old_func(*args, **kwargs)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 220, in losses
    align_corners=self.align_corners)
  File "/home/ray/Documents/mmsegmentation/mmseg/ops/wrappers.py", line 17, in resize
    output_h, output_w = tuple(int(x) for x in size)
ValueError: too many values to unpack (expected 2)

------------------------------------------------------------------------------------------------------------------------------------------------------------
first, i thought it was because of the image size. so i changed all the image size to the same size with the cityscapes.
but it doesn't work.

then i change the code in /home/ray/Documents/mmsegmentation/mmseg/ops/wrappers.py", in line 17 to 
"output_h, output_w, _ = tuple(int(x) for x in size)" to fit for the three values.

but i got another error like this:
Traceback (most recent call last):
  File "/home/ray/Documents/mmsegmentation/tools/train.py", line 169, in <module>
    main()
  File "/home/ray/Documents/mmsegmentation/tools/train.py", line 165, in main
    meta=meta)
  File "/home/ray/Documents/mmsegmentation/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ray/Documents/mmsegmentation/mmseg/models/segmentors/base.py", line 137, in train_step
    losses = self(**data_batch)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/segmentors/base.py", line 107, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 143, in forward_train
    gt_semantic_seg)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 87, in _decode_head_forward_train
    self.train_cfg)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 185, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 184, in new_func
    return old_func(*args, **kwargs)
  File "/home/ray/Documents/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 220, in losses
    align_corners=self.align_corners)
  File "/home/ray/Documents/mmsegmentation/mmseg/ops/wrappers.py", line 27, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "/home/ray/anaconda3/envs/mmsegmentation/lib/python3.7/site-packages/torch/nn/functional.py", line 3163, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, sfl[0], sfl[1])
RuntimeError: It is expected output_size equals to 2, but got size 3

Anyone has met this error?
Can u give a advice? Thanks

**Comment by MengzhangLI** [comment]
Hi, @ray401, sorry for late reply.

Please use template of Error report in our issue, just check it out in "New issue" bottom.

From your description, your actual label types in `./data/YOURDATASET/` folder are not the same as what you told to the model a.k.a the type number of predictions in config of this experiment.  

Do you set up your new config file and pass it successfully? If not, please check the [customized dataset tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md) and [config tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/config.md).

Best,

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/550 maybe useful to you.

**Comment by ray401** [comment]
Hi,thanks for your advice!
I do changed the num_classes in the config file, but i still got the same error :
 File "/home/ray/Documents/mmsegmentation/mmseg/ops/wrappers.py", line 17, in resize
output_h, output_w = tuple(int(x) for x in size)
ValueError: too many values to unpack (expected 2)

what matters most is, i had trained successfully on my own made dataset, all work well. so it may not because of the config file.
but when training on another dataset(deepscene), i got the error. 

please be sure to tell me if you have any advice.
And if i solved it, i will reply here.

**Comment by MengzhangLI** [comment]
`but when training on another dataset(deepscene), i got the error.`

Seems like it should be `two separate config file for two dataset` but the codebase only used one fixed config?

I suggest you check whether config files of two times training procedure are not different.

Best,

**Comment by ray401** [comment]
I guess it's not because of the config file, and the usage of the config file are the same for the different case.
But still thanks for your reply.

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Have fixed this problem?

Seems like label generation of `deepscene` is not correct (`(2,1,769,769,3)` rather than `(2,1,769,769)` )

Can you check its data preparation process especially the shape of ground truth in `./data/YOUR_CUSTOMIZED_DATASET/`?

Best,

**Comment by KenRamzes** [comment]
when I use the woodscpe dataset， I meet the same issue，How can we solve this？

**Comment by zhongqiu1245** [comment]
@MengzhangLI @ray401 
Hi! I met this error too. I think I found the reason and solution.
I converted my own dataset to VOC format, and I met this error when the mmseg was training.

Reason:
MMCV will convert masks(or labels) to bytes first, and reconvert bytes to masks in 'mmseg/model/datasets/pipelines/loading.py, class LoadAnnotations'.
But, I found that it is seem that MMCV doesn't reconvet correctlly all the time when it reconverts bytes to image. 

You got a weird vector shape (2,1,769,769,3). In fact, the "3" means 3 channels, which is your masks channels. But, I found if you want mmseg run correctlly, the mask channels must be 1, which means the shape of that weird vector should be (2,1,769,769).

Solution:
I found 2 ways can solve this error, but, ...emmmmm, is not elegant.
1: You can reconvert your dataset again. But in this time, you should use 'labelme' to generate your mask(And the format should be VOC). I found mmseg can reconvert mask correctlly when the masks are generated by 'labelme', but can't reconvert mask correctlly if masks are generated by 'opencv-python'. (which is very weird).

2:Or you can modify the code in class LoadAnnotations, which in 'mmseg/model/datasets/pipelines/loading.py', line 134. You can set 'flag=grey' to get singel channel masks, but you should calculate the pixels value of your classes again.

I will create a ERROR REPORT.

**Comment by Jackieam** [comment]
> 

Amazing! 24bit to 8bit code! Really Thanks!
