### ISSUE TITLE
PSPNET not a checkpoint file 

### ISSUE THREAD

**Issue by gulzainali98** [open-mmlab/mmsegmentation#647]
**Describe the bug**
I download pspnet .pth file but in the training segmentor API call, after few minutes of wait i get `pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth is not a checkpoint file`

**Reproduction**

1. What command or script did you run?
I am running customized configuration provided in the google colab
    ```none
    python pspnet_r50.py;
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, i did and all of the config is fine. 
3. What dataset did you use?
I am using it on custom dataset
**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.

`sys.platform: linux                                                                                                     Python: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]                                                              CUDA available: True                                                                                                    GPU 0: GeForce RTX 3090                                                                                                 GPU 1: GeForce GTX 1050 Ti                                                                                              CUDA_HOME: /usr/local/cuda                                                                                              NVCC: Build cuda_11.0_bu.TC445_37.28845127_0                                                                            GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0                                                                           PyTorch: 1.5.0+cu101                                                                                                    PyTorch compiling details: PyTorch built with:                                                                            - GCC 7.3                                                                                                               - C++ Version: 201402                                                                                                   - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications        - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)                                          - OpenMP 201511 (a.k.a. OpenMP 4.5)                                                                                     - NNPACK is enabled                                                                                                     - CPU capability usage: AVX2                                                                                            - CUDA Runtime 10.1                                                                                                     - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37                                                                             - CuDNN 7.6.3                                                                                                           - Magma 2.5.2                                                                                                           - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,                                                                                                                                                                       TorchVision: 0.6.0+cu101                                                                                                OpenCV: 4.5.2                                                                                                           MMCV: 1.3.5                                                                                                             MMCV Compiler: GCC 7.3                                                                                                  MMCV CUDA Compiler: 10.1                                                                                                MMSegmentation: 0.14.1+98067be`

2. You may add addition that may be helpful for locating the problem, such as
    - Followed the whole tutorial provided in this google colab: https://colab.research.google.com/github/open-mmlab/mmsegmentation/blob/master/demo/MMSegmentation_Tutorial.ipynb#scrollTo=2hd41IGaiNet

**Error traceback**

If applicable, paste the error trackback here.

```Traceback (most recent call last):                                                                                        File "pspnet_r50.py", line 172, in <module>                                                                               train_segmentor(model, datasets, cfg, distributed=False, validate=True,                                               File "/cluster_home/mkhan/weed_detection/mmsegmentation/mmseg/apis/train.py", line 115, in train_segmentor                runner.load_checkpoint(cfg.load_from)                                                                                 File "/home/gulzain/gen-env/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 316, in load_checkpoint         return load_checkpoint(                                                                                               File "/home/gulzain/gen-env/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint          checkpoint = _load_checkpoint(filename, map_location, logger)                                                         File "/home/gulzain/gen-env/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint         return CheckpointLoader.load_checkpoint(filename, map_location, logger)                                               File "/home/gulzain/gen-env/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint          return checkpoint_loader(filename, map_location)                                                                      File "/home/gulzain/gen-env/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 260, in load_from_local          raise IOError(f'{filename} is not a checkpoint file')                                                               OSError: /netscratch/mkhan/segmenation_models/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth is not a checkpoint file
```

**Comment by gulzainali98** [comment]
I updated the pytorch to 1.7.0 as well and it still doesn't work. I downgraded, mmcv 1.3.4 and it gives a totally different error. This is given below: 
`Traceback (most recent call last):                                                                                        File "pspnet_r50.py", line 1, in <module>                                                                                 from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot                                        File "/cluster_home/mkhan/weed_detection/mmsegmentation/mmseg/apis/__init__.py", line 1, in <module>                      from .inference import inference_segmentor, init_segmentor, show_result_pyplot                                        File "/cluster_home/mkhan/weed_detection/mmsegmentation/mmseg/apis/inference.py", line 8, in <module>                     from mmseg.models import build_segmentor                                                                              File "/cluster_home/mkhan/weed_detection/mmsegmentation/mmseg/models/__init__.py", line 1, in <module>                    from .backbones import *  # noqa: F401,F403                                                                           File "/cluster_home/mkhan/weed_detection/mmsegmentation/mmseg/models/backbones/__init__.py", line 10, in <module>         from .vit import VisionTransformer                                                                                    File "/cluster_home/mkhan/weed_detection/mmsegmentation/mmseg/models/backbones/vit.py", line 7, in <module>               from mmcv.cnn import (build_conv_layer, build_norm_layer, constant_init,                                            ImportError: cannot import name 'trunc_normal_init' from 'mmcv.cnn' (/home/gulzain/gen-env/lib/python3.8/site-packages/mmcv/cnn/__init__.py)`

**Comment by YLyeliang** [comment]
This error happened when your given path is not correct or the checkpoint file is damaged.
Firstly, the second repo is the version problem and you don't need to downgrade, just make sure all versions are matched.
For the first repo, you may try to make sure your checkpoint path is correct.

**Comment by MengzhangLI** [comment]
Hi, @gulzainali98:

have you fixed this error?

Thanks for your kindly answer very much! @YLyeliang 

Best,

**Comment by gulzainali98** [comment]
No i didn't fix it. And the path is correct to to the pspnet model.

**Comment by MengzhangLI** [comment]
> No i didn't fix it. And the path is correct to to the pspnet model.

Sorry for late reply.

Could you run any other `.pth` model in the same settings?

If yes, it may caused by wrong model. If not, it may caused by wrong checkpoint path thus no model could be loaded.

Looking forward to your responses!

Best,

**Comment by MengzhangLI** [comment]
We uploaded some new checkpoints already, I guess this problem should be solved. Feel free anytime to re-open it if some people meet similar problems.
