### ISSUE TITLE
Train my own data, and when the validate is over, the program gets stuck.

### ISSUE THREAD

**Issue by simobupt** [open-mmlab/mmsegmentation#66]
Why I am training my own data, and when the verification is over, the program gets stuck.
Like this.

2020-08-13 15:19:04,379 - mmseg - INFO - Iter [1950/20000]      lr: 9.127e-03, eta: 11:16:39, time: 2.096, data_time: 0.001, memory: 25119, decode.loss_seg: 0.0001, decode.acc_seg: 0.8459, aux.loss_seg: 0.0001, aux.acc_seg: 0.8459, loss: 0.0002
2020-08-13 15:20:50,742 - mmseg - INFO - Saving checkpoint at 2000 iterations
[>>>>>>>>>>>                                      ] 1873/7811, 1.8 task/s, elapsed: 1069[  ] 1874/7811,[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 7811/7811, 1.7 task/s, elapsed: 4545s, ETA:     0s

^CTraceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)

**Comment by xvjiarui** [comment]
Hi @simobupt 
It takes a while to evaluate in distributed mode. You may try to directly eval the checkpoint using `tools/test.py`.

**Comment by simobupt** [comment]
Right, the eval time is so long.
