### ISSUE TITLE
RuntimeError: Only one file(not dir) is allowed in the zipfile

### ISSUE THREAD

**Issue by qingzwang** [open-mmlab/mmsegmentation#687]
When I train the Swin model using `./tools/dist_train.sh configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_22
4x224_1K.py 2`, I meet the runtime error. It seems that I cannot load the pre-trained Swin backbone.

**Comment by sennnnn** [comment]
Sry, can you post your error message which may help us to locate the error? 
Thx

**Comment by qingzwang** [comment]
> Sry, can you post your error message which may help us to locate the error?
> Thx

Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 134, in main
    model.init_weights()
  File "/mnt/qingzhong/envs/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/mnt/qingzhong/src/mmsegmentation/mmseg/models/backbones/swin.py", line 706, in init_weights
    self.pretrained, logger=logger, map_location='cpu')
  File "/mnt/qingzhong/envs/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/mnt/qingzhong/envs/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/mnt/qingzhong/envs/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/mnt/qingzhong/envs/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/hub.py", line 490, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile

**Comment by sennnnn** [comment]
Alright, this may cause by the pytorch version. You can refer to [this issue](https://github.com/pytorch/pytorch/issues/42239). We train and evaluate these models on pytorch1.8. So, the ckpt is saved as zip format in default. We will modify these ckpts in recent prs or you can deploy your workflow on pytorch > 1.6.

**Comment by qingzwang** [comment]
Thx, I use the pytorch=1.6.0 as described in the get_start.md. I will try to upgrade PyTorch.
