### ISSUE TITLE
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by renmmmmmm** [open-mmlab/mmsegmentation#69]
2020-08-14 21:26:59,786 - mmseg - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.0 (default, Oct  9 2018, 10:31:47) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0,1,2,3,4,5,6: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.3.0
MMCV: 1.0.5
MMSegmentation: 0.5.1+381eacb
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
------------------------------------------------------------

2020-08-14 21:26:59,787 - mmseg - INFO - Distributed training: True
2020-08-14 21:27:00,150 - mmseg - INFO - Config:
norm_cfg = dict(type='SyncBN', requires_grad=True)

2020-08-14 21:27:38,119 - mmseg - INFO - Loaded 2975 images
2020-08-14 21:27:38,678 - mmseg - INFO - Loaded 500 images
2020-08-14 21:27:38,678 - mmseg - INFO - Start running, host: rss@ps, work_dir: /home/rss/mmsegmentation/work_dirs/deeplabv3plus_r50-d8_769x769_40k_cityscapes
2020-08-14 21:27:38,678 - mmseg - INFO - workflow: [('train', 1)], max: 40000 iters
Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 157, in main
    meta=meta)
  File "/home/rss/mmsegmentation/mmseg/apis/train.py", line 106, in train_segmentor
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 119, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 55, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/rss/mmsegmentation/mmseg/models/segmentors/base.py", line 152, in train_step
    losses = self(**data_batch)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/rss/mmsegmentation/mmseg/models/segmentors/base.py", line 122, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/rss/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 163, in forward_train
    x, img_metas, gt_semantic_seg)
  File "/home/rss/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 125, in _auxiliary_head_forward_train
    x, img_metas, gt_semantic_seg, self.train_cfg)
  File "/home/rss/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 185, in forward_train
    seg_logits = self.forward(inputs)
  File "/home/rss/mmsegmentation/mmseg/models/decode_heads/fcn_head.py", line 65, in forward
    output = self.convs(x)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 185, in forward
    x = self.conv(x)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 157, in main
    meta=meta)
  File "/home/rss/mmsegmentation/mmseg/apis/train.py", line 106, in train_segmentor
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 119, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 55, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/rss/mmsegmentation/mmseg/models/segmentors/base.py", line 152, in train_step
    losses = self(**data_batch)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/rss/mmsegmentation/mmseg/models/segmentors/base.py", line 122, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/rss/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 163, in forward_train
    x, img_metas, gt_semantic_seg)
  File "/home/rss/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 125, in _auxiliary_head_forward_train
    x, img_metas, gt_semantic_seg, self.train_cfg)
  File "/home/rss/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 185, in forward_train
    seg_logits = self.forward(inputs)
  File "/home/rss/mmsegmentation/mmseg/models/decode_heads/fcn_head.py", line 65, in forward
    output = self.convs(x)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 185, in forward
    x = self.conv(x)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/home/rss/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
单张显卡可以运行，多张显卡时会报这种错误？请问环境怎么解决？需要重新配置cuda10.1吗？

**Comment by xvjiarui** [comment]
Hi @renmmmmmm 
I haven't encountered this before. Does it always occur may distributed training or just now and then?

**Comment by renmmmmmm** [comment]
> Hi @renmmmmmm
> Please use English or English/Chinese for the issue.
> If your GPU memory is not enough, you may try the following.
> 
> 1. Use FP16 mix precision.
> 2. Pass in `--options model.backbone.with_cp=True`.

Thanks！What is the batchsize of your experimental model? Because my running accuracy is lower than yours? How can I solve this problem?

**Comment by xvjiarui** [comment]
Hi @renmmmmmm 
All of our models are trained with 4 GPUs, as indicated in [model zoo](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/model_zoo.md#common-settings).

**Comment by NickChang97** [comment]
Hi @renmmmmmm  How do you fix your problem, I get the same situation. When I use the single GPU, nothing wrong, but when I use multi-gpu, it failed. And I have already have a multi-gpu running programm. 
Can't I lanuch two multi-gpu task in one machine?

**Comment by NickChang97** [comment]
I am very sorry. After checking my code, I have find that there is a bug in my code, it's the label of data does not satisfy 0~num_classes-1.  And I find something interesting, when I use this in F.crossentropy, it did not report a error in the code. When I change to binary_cross_entropy, I find it.

**Comment by SBCV** [comment]
In my case the `cuDNN error: CUDNN_STATUS_INTERNAL_ERROR` was thrown due to incorrect installation of some dependencies.
I've installed pytorch and cudatoolkit with `conda install pytorch=1.6.0 torchvision cudatoolkit=10.1 -c pytorch`
However, the system was running `cuda 11.1`
Note: If you have to reinstall pytorch and cudatoolkit you must also adapt the installation of mmcv (see this [issue](https://github.com/open-mmlab/mmcv/issues/1478))
