### ISSUE TITLE
UnboundLocalError: local variable 'checkpoint' referenced before assignment

### ISSUE THREAD

**Issue by xiaoguoguo2018** [open-mmlab/mmsegmentation#747]
I have configured my own dataset for training and the model is pspnet_r50-d8.py. The configuration is fine, but this problem occurs when I run it, and I don't know what is the real reason. If there is encountered the problem, I hope to provide me with help

**Describe the bug**
UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
2021-08-03 15:08:49,165 - mmcv - INFO - load model from: open-mmlab://resnet50_v1c
2021-08-03 15:08:49,165 - mmcv - INFO - Use load_from_openmmlab loader
Traceback (most recent call last):
  File "/home1/xiaotao/project/mmsegmentation-master/tools/train.py", line 184, in <module>
    main()
  File "/home1/xiaotao/project/mmsegmentation-master/tools/train.py", line 149, in main
    model.init_weights()
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 45, in init_weights
    initialize(self, self.init_cfg)
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 527, in initialize
    _initialize(module, cp_cfg)
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 432, in _initialize
    func(module)
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 411, in __call__
    load_checkpoint(
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 405, in load_from_openmmlab
    checkpoint = load_from_http(model_url, map_location=map_location)
  File "/home1/xiaotao/anaconda3/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 290, in load_from_http
    return checkpoint
UnboundLocalError: local variable 'checkpoint' referenced before assignment

**Reproduction**

1. What command or script did you run?

  pspnet_r50-d8.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
 have configured my own dataset for training and l think the dataset configuration is fine

3. What dataset did you use?
 my own dataset，and the configuration is fine

**Comment by Junjun2016** [comment]
Hi @xiaoguoguo2018 
Could you please provide the full config?
You may also refer to https://github.com/open-mmlab/mmdetection/issues/1751.

**Comment by Junjun2016** [comment]
Try official supported datasets.

**Comment by Junjun2016** [comment]
Did you use multi-node multi-gpu?

**Comment by xiaoguoguo2018** [comment]
> Hi @xiaoguoguo2018
> Could you please provide the full config?
> You may also refer to [open-mmlab/mmdetection#1751](https://github.com/open-mmlab/mmdetection/issues/1751).



> Hi @xiaoguoguo2018
> Could you please provide the full config?
> You may also refer to [open-mmlab/mmdetection#1751](https://github.com/open-mmlab/mmdetection/issues/1751).

open-mmlab/mmdetection#1751 did not help me solve the problem, I did not find the configuration path for checkpoint. If you can please help me to see what is wrong, I have uploaded my file to github and run train.py

https://github.com/xiaoguoguo2018/mmesg

Thanks!

**Comment by xiaoguoguo2018** [comment]
> Did you use multi-node multi-gpu?



> Did you use multi-node multi-gpu?

There are no multiple gpu's used, only a single gpu is used

**Comment by Junjun2016** [comment]
Which config did you run?
Please also provide the specific cmd.

**Comment by xiaoguoguo2018** [comment]
> Which config did you run?
> Please also provide the specific cmd.

I use this config

../configs/pspnet/pspnet_r50-d8_480x480_40k_potsdam.py

https://github.com/xiaoguoguo2018/mmesg

**Comment by Junjun2016** [comment]
command?

**Comment by xiaoguoguo2018** [comment]
> command?

just run this command

**python tools/tarin.py**

config files is ../configs/pspnet/pspnet_r50-d8_480x480_40k_potsdam.py. this configuration file has been set to the default value in train.py

**Comment by Junjun2016** [comment]
Try [distributed training](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/train.md#launch-multiple-jobs-on-a-single-machine).

**Comment by Junjun2016** [comment]
@xiaoguoguo2018 any news?

**Comment by luoshuifeiyang** [comment]
应该是mmcv版本的问题

**Comment by zhouzaida** [comment]
solved by https://github.com/open-mmlab/mmcv/pull/1396
