### ISSUE TITLE
Export DeeplabV3 model from torch to tensorflow failed when export to onnx

### ISSUE THREAD

**Issue by LingCoderSonoscape** [open-mmlab/mmsegmentation#795]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
The task that I am currently handling is converting the pytorch model generated by mmsegmentation to tensorflow-1.14. However, when I tried to use the convert file from _**mmsegmentation_root/tools/pytorch2onnx.py**_ to convert it to onnx model first, I met an error that I don't know how to fix. 
**Reproduction**

1. What command or script did you run?
    
    RUN pytorch2onnx.py changed opset-version 
    ```
    python tools/pytorch2onnx.py /home/wlx/mmsegmentation/configs/my_config.py --checkpoint ./work-dir/iter_80000.pth --verify **_--opset-version 9_** --shape 400 400 --show
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Yes I did make some modification on the config file where I created my own config file for training and testing but no big difference comparing to official deeplabV3 config files. It is just the same as the  **_deeplabv3_r50-d8_512x1024_40k_cityscape.py_** but with the num_class changed to 4 in decode_head and auxiliary_head and the input size set to 400x400.
   Then in order to use _**"nearest mode"**_ in _**F.interpolation**_ I have modified the config file above. I changed the align_corners value to _**None**_. 
  All the rest keeps the same as the official file.

3. What dataset did you use?

The dataset I used has 4 classes including the background, which is obtained from our company which is not public acceptable.

**Environment**
The environment is:
pytorch-1.6 
mmsegmentation-0.12.0
mmcv-full-1.3.9
onnx-1.8

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 345, in <module>
    dynamic_export=args.dynamic_export)
  File "tools/pytorch2onnx.py", line 175, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/usr/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/usr/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 557, in _export
    _check_onnx_proto(proto)
RuntimeError: Node (Slice_196) has input size 4 not in range [min=1, max=1].

==> Context: Bad node spec: input: "569" input: "571" input: "572" input: "570" output: "573" name: "Slice_196" op_type: "Slice"
```

**Bug fix**

I have tested the model using sample images from my dataset which was fine and perfect. Due to the model weight is confidential so I cannot publish the model here but you can reproduce a similar model using a dataset that has 3 classes(1 class for background). 
Also I used opset-version 9 to export onnx model because it will be more stable to use **_onnx-tensorflow SDK** to get the final model. However, if there is a better way to generate the final tensorflow model, it will be OK the use opset-11. 

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by MengzhangLI** [comment]
Hi, right now the `Convert to ONNX` is still experimental, check out the [docs](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/useful_tools.md). 

Could you try to update your PyTorch version to 1.8+, and give a shot agian?

Looking forward to your feedback.

Best,

**Comment by LingCoderSonoscape** [comment]
> Hi, right now the `Convert to ONNX` is still experimental, check out the [docs](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/useful_tools.md).
> 
> Could you try to update your PyTorch version to 1.8+, and give a shot agian?
> 
> Looking forward to your feedback.
> 
> Best,

Hi! Thanks for your reply, I just upgraded my torch version from 1.6 to 1.7, 1.8 and 1.9. Then I found that in 1.7 it threw the same error again. 
However, in 1.8 and 1.9 it threw the _**undefined symbol**_ error log which I think caused by the incompatible versions between pytorch and mmcv. see below:
![undefined-symbol-error-log](https://user-images.githubusercontent.com/85982797/129652479-11740b7b-9207-4d8f-a195-26972a7eeae8.PNG)

I have re-checked the traceback and the pytorch2onnx.py file. I think there is something wrong with one of the nodes which will be converted into _**slice**_ node relatively in the onnx model but I cannot find out which exactly node it is. The interesting thing is it did not throw an error out when using opset-version 11 and built up the model successfully.
So, by concluding all the conditions above, I think the "Slice" node has some trouble to support input size 4 in opset-version 9 but will be handled in version 11.
I have found out where the node is:
![slice (1)](https://user-images.githubusercontent.com/85982797/129653720-5300ac0e-c4db-4e88-a1ba-66374c4a22b6.PNG)
So do you have any suggestion that how I can solve this problem?

Looking forward to your reply!

**Comment by MengzhangLI** [comment]
Hi, please check out related issue https://github.com/open-mmlab/mmsegmentation/issues/693

There are usually version conflictss because it is only experimental right now, we hope we could fix it in the future.

"1.8 and 1.9 it threw the undefined symbol error log which I think caused by the incompatible versions between pytorch and mmcv". And try to **make pytorch and mmcv version suitable**? 

https://github.com/open-mmlab/mmcv

![image](https://user-images.githubusercontent.com/24582831/129664153-530700bf-d420-4a5c-af9c-d844f49d7d69.png)


If it still not work, please tell us know and we will try to solve it.

Best,

**Comment by LingCoderSonoscape** [comment]
Sorry, I have rechecked the version of the mmcv and found that, I used the latest mmcv-full with torch-1.7 cuda-10.2. Then I ran the converting file again but nothing has changed. Still reporting the error message related to the _**Slice**_ node. 
So, needs to do further check?

**Comment by RunningLeon** [comment]
@LingCoderSonoscape Strongly suggests use opset=11 instead of opset=9. 

> However, in 1.8 and 1.9 it threw the undefined symbol error log which I think caused by the incompatible versions between pytorch and mmcv. see below:

If you changed PyTorch version in the same python environment, you have to rebuild mmcv after removing the old built files in `MMCV_HOME/build` directory.

**Comment by LingCoderSonoscape** [comment]
Thank you for your suggestion, I understand that opset=11 is better in some way. However, as I said if I use opset=11 to generate onnx model, it will be perfectly fine and no problem occurred. But the onnx model in opset-11 will cause many problems when using _**onnx-tensorflow SDK**_ to generate the tensorflow model. I have tried to use opset-11 onnx model to generate tensorflow model using onnx-tensorflow but it threw the 
_Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow_ ERROR.
This, as I known, means the **_Resize_** node which comes from opset-11 is not supported by the SDK.
So that's why I have to use opset-9 to generate the model, which can avoid such nodes appear in the model.

Also, I actually uninstall both pytorch and mmcv first then reinstall pytorch first then mmcv evertime I test the environment.

**Comment by RunningLeon** [comment]
@LingCoderSonoscape Maybe you could try the opset conversion tool of onnx: opset11 -> opset9 https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md

**Comment by LingCoderSonoscape** [comment]
> @LingCoderSonoscape Maybe you could try the opset conversion tool of onnx: opset11 -> opset9 https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md

I just tried to run the opset-converter to lower the opset-version from 11 to 9. However, it seems like this function is still under development. An index error occurred which tells "Input 641 is undefined". I have tried to put the function "add_value_info_for_constants" to fix the bug but nothing has changed. 
I feel I am stucked here and it is hard to find a way to get the right model out. Any other suggestions?

**Comment by RunningLeon** [comment]
> > @LingCoderSonoscape Maybe you could try the opset conversion tool of onnx: opset11 -> opset9 https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md
> 
> I just tried to run the opset-converter to lower the opset-version from 11 to 9. However, it seems like this function is still under development. An index error occurred which tells "Input 641 is undefined". I have tried to put the function "add_value_info_for_constants" to fix the bug but nothing has changed.
> I feel I am stucked here and it is hard to find a way to get the right model out. Any other suggestions?

You could post your issue on the ONNX repo since they are responsible for the opset version conversion tool.
