### ISSUE TITLE
AttributeError: 'list' object has no attribute 'data'

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#799]
I met this problem when running mmsegemenattion. Having took a lot time to debug, I still cannot find solutions.

tils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 81, in <dictcomp
>
    for key in batch[0]
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 76, in collate
    transposed = zip(*batch)
TypeError: zip argument #2 must support iteration

Traceback (most recent call last):
  File "tools/train.py", line 167, in <module>
    main()
  File "tools/train.py", line 163, in main
    meta=meta)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/apis/train.py", line 120, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 133, in 
run
    iter_runner(iter_loaders[i], **kwargs)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 58, in t
rain
    data_batch = next(data_loader)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/d
ataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/d
ataloader.py", line 846, in _process_data
    data.reraise()
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/_utils.py", 
line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/_
utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/_
utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 81, in <dictcomp
>
    for key in batch[0]
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 31, in collate
    [sample.data for sample in batch[i:i + samples_per_gpu]])
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 31, in <listcomp
>
    [sample.data for sample in batch[i:i + samples_per_gpu]])
AttributeError: 'list' object has no attribute 'data'

Traceback (most recent call last):
  File "tools/train.py", line 167, in <module>
    main()
  File "tools/train.py", line 163, in main
    meta=meta)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/apis/train.py", line 120, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 133, in 
run
    iter_runner(iter_loaders[i], **kwargs)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 58, in t
rain
    data_batch = next(data_loader)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 32, in _
_next__
    data = next(self.iter_loader)
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/d
ataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/d
ataloader.py", line 846, in _process_data
    data.reraise()
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/_utils.py", 
line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/_
utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/lustre/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/_
utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 81, in <dictcomp
>
    for key in batch[0]
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 31, in collate
    [sample.data for sample in batch[i:i + samples_per_gpu]])
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/parallel/collate.py", line 31, in <listcomp
>
    [sample.data for sample in batch[i:i + samples_per_gpu]])
AttributeError: 'list' object has no attribute 'data'

srun: error: SH-IDC1-10-198-6-134: tasks 1-7: Exited with exit code 1
srun: Terminating job step 3238718.0
slurmstepd: *** STEP 3238718.0 ON SH-IDC1-10-198-6-134 CANCELLED AT 2021-08-18T02:06:22 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.

**Comment by MengHao666** [comment]
@xvjiarui @xiexinch @sennnnn

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/356

**Comment by Junjun2016** [comment]
Hi @MengHao666 
Please check the train_pipeline and val_pipeline carefully.
