### ISSUE TITLE
Input image size doesn't match model

### ISSUE THREAD

**Issue by Benybrahim** [open-mmlab/mmsegmentation#848]
Hello, while training everything was fine until evalutation step when I got this error related to difference between image size and model size. It always stop at 552!

**Error traceback**

```none
2021-09-02 12:31:14,658 - mmseg - INFO - Saving checkpoint at 4000 iterations
[>>>>>>>>>>>>>>>>>>>>>>>>>>>                       ] 552/1000, 1.4 task/s, elapsed: 401s, ETA:   325sTraceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 176, in main
    meta=meta)
  File "/workspace/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/workspace/mmseg/core/evaluation/eval_hooks.py", line 30, in after_train_iter
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/workspace/mmseg/apis/test.py", line 60, in single_gpu_test
    result = model(return_loss=False, **data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/workspace/mmseg/models/segmentors/base.py", line 124, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/workspace/mmseg/models/segmentors/base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/workspace/mmseg/models/segmentors/encoder_decoder.py", line 266, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/workspace/mmseg/models/segmentors/encoder_decoder.py", line 249, in inference
    seg_logit = self.slide_inference(img, img_meta, rescale)
  File "/workspace/mmseg/models/segmentors/encoder_decoder.py", line 194, in slide_inference
    crop_seg_logit = self.encode_decode(crop_img, img_meta)
  File "/workspace/mmseg/models/segmentors/encoder_decoder.py", line 87, in encode_decode
    x = self.extract_feat(img)
  File "/workspace/mmseg/models/segmentors/encoder_decoder.py", line 79, in extract_feat
    x = self.backbone(img)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/mmseg/models/backbones/vit_mla.py", line 348, in forward
    x = self.patch_embed(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/mmseg/models/backbones/vit_mla.py", line 152, in forward
    f"Input image size ({H}*{W}) doesn't match model ({self.img_size[0]}*{self.img_size[1]})."
AssertionError: Input image size (615*768) doesn't match model (768*768).
```

**Config file**

```python
norm_cfg = dict(type='BN', requires_grad=True)  # BN is used instead of SyncBn because we use only 1 GPU
model = dict(
    type='EncoderDecoder',
    backbone=dict(
        type='VIT_MLA',
        model_name='vit_base_patch16_224',
        img_size=768,
        patch_size=16,
        in_chans=3,
        embed_dim=768,
        depth=12,
        num_heads=12,
        num_classes=19,
        drop_rate=0.0,
        norm_cfg=dict(type='BN', requires_grad=True),
        pos_embed_interp=True,
        align_corners=False,
        mla_channels=256,
        mla_index=(5, 7, 9, 11)),
    decode_head=dict(
        type='VIT_MLAHead',
        in_channels=1024,
        channels=512,
        img_size=768,
        mla_channels=256,
        mlahead_channels=128,
        num_classes=104,
        norm_cfg=dict(type='BN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=[
        dict(
            type='VIT_MLA_AUXIHead',
            in_channels=256,
            channels=512,
            in_index=0,
            img_size=768,
            num_classes=104,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
        dict(
            type='VIT_MLA_AUXIHead',
            in_channels=256,
            channels=512,
            in_index=1,
            img_size=768,
            num_classes=104,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
        dict(
            type='VIT_MLA_AUXIHead',
            in_channels=256,
            channels=512,
            in_index=2,
            img_size=768,
            num_classes=104,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
        dict(
            type='VIT_MLA_AUXIHead',
            in_channels=256,
            channels=512,
            in_index=3,
            img_size=768,
            num_classes=104,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4))
    ])
train_cfg = dict()
test_cfg = dict(mode='slide', crop_size=(768, 768), stride=(512, 512))
dataset_type = 'CustomDataset'
data_root = './data/UECFOODPIXCOMPLETE'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (768, 768)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(2049, 1025), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=(768, 768), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size=(768, 768), pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2049, 1025),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type='CustomDataset',
        data_root='./data/UECFOODPIXCOMPLETE/',
        img_dir='img/train',
        ann_dir='ann/train',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(
                type='Resize', img_scale=(2049, 1025), ratio_range=(0.5, 2.0)),
            dict(type='RandomCrop', crop_size=(768, 768), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(768, 768), pad_val=0, seg_pad_val=255),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='CustomDataset',
        data_root='./data/UECFOODPIXCOMPLETE',
        img_dir='img/test',
        ann_dir='ann/test',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(2049, 1025),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CustomDataset',
        data_root='./data/UECFOODPIXCOMPLETE',
        img_dir='img/test',
        ann_dir='ann/test',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(2049, 1025),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50, hooks=[dict(type='TextLoggerHook', by_epoch=False)])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = "./models/iter_80000.pth"
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(
    type='SGD',
    lr=0.002,
    momentum=0.9,
    weight_decay=0.0,
    paramwise_cfg=dict(custom_keys=dict(head=dict(lr_mult=10.0))))
optimizer_config = dict(type="Fp16OptimizerHook")
lr_config = dict(policy='poly', power=0.9, min_lr=0.0001, by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=80000)
checkpoint_config = dict(by_epoch=False, interval=4000)
evaluation = dict(interval=4000, metric='mIoU') 
find_unused_parameters = True
work_dir = 'train_results/'
gpu_ids = range(0, 1)
```

**DATASET**

- Original model: https://github.com/LARC-CMU-SMU/FoodSeg103-Benchmark-v1
- The data that I'm trying to fine tune: https://mm.cs.uec.ac.jp/uecfoodpix/

**REMARK**

I wanted to fine tune the model so I added this chunk of code to `tools/train.py` file:

```python

    model = build_segmentor(
        cfg.model,
        train_cfg=cfg.get('train_cfg'),
        test_cfg=cfg.get('test_cfg'))

     ### ADDED CODE
    # change number of classes
    model.decode_head.conv_seg.out_channels = 102
    model.decode_head.cls.out_channels = 102
    model.auxiliary_head[0].conv_seg.out_channels = 102
    model.auxiliary_head[1].conv_seg.out_channels = 102
    model.auxiliary_head[2].conv_seg.out_channels = 102
    model.auxiliary_head[3].conv_seg.out_channels = 102
    # freeze module
    for param in model.backbone.parameters():
        param.requires_grad = False

    logger.info(model)

```

Thank you in advance for any insight.

**Comment by MengzhangLI** [comment]
Hi, @Benybrahim
I think it is caused by the No.`552` figure in your validation set whose size is (615*768) and is smaller than the model input size (768*768). During training it's fine because training pipeline would use crop size images instead of whole image. It would use `padding` operation if meet smaller images. You could check out the smallest width/height of your image and set it as `img_size` or just discard some images which are somewhat small.

**Comment by Benybrahim** [comment]
Ok noted, Thank you

**Comment by Benybrahim** [comment]
After checking the data, it turn out that there is not image with (615 * 768) in all the 1000 images of test data.
Many images are indeed smaller than 768x768, but I think if this is what caused the problem it should stop early on test step, ot until 552.
Here is all the shapes ordered:
```
[(71, 99, 3), (100, 133, 3), (120, 160, 3), (120, 160, 3), (120, 160, 3), (120, 160, 3), (120, 160, 3), (120, 160, 3), (123, 250, 3), (124, 165, 3), (126, 123, 3), (126, 186, 3), (126, 186, 3), (126, 186, 3), (127, 180, 3), (130, 180, 3), (132, 176, 3), (132, 180, 3), (135, 169, 3), (135, 180, 3), (135, 180, 3), (135, 180, 3), (139, 160, 3), (139, 191, 3), (140, 175, 3), (140, 180, 3), (140, 186, 3), (140, 187, 3), (140, 190, 3), (140, 200, 3), (141, 180, 3), (143, 217, 3), (143, 228, 3), (144, 176, 3), (144, 176, 3), (144, 192, 3), (145, 210, 3), (147, 196, 3), (147, 196, 3), (147, 196, 3), (147, 196, 3), (147, 220, 3), (149, 250, 3), (150, 150, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 200, 3), (150, 220, 3), (150, 230, 3), (150, 230, 3), (150, 338, 3), (150, 340, 3), (150, 500, 3), (151, 220, 3), (154, 176, 3), (154, 200, 3), (155, 205, 3), (155, 207, 3), (155, 287, 3), (156, 200, 3), (156, 200, 3), (157, 200, 3), (157, 205, 3), (157, 210, 3), (158, 210, 3), (158, 210, 3), (158, 210, 3), (158, 212, 3), (158, 250, 3), (160, 160, 3), (160, 164, 3), (160, 240, 3), (160, 250, 3), (160, 250, 3), (160, 250, 3), (161, 200, 3), (161, 220, 3), (165, 220, 3), (165, 220, 3), (165, 220, 3), (165, 230, 3), (167, 220, 3), (168, 224, 3), (169, 215, 3), (169, 220, 3), (169, 260, 3), (170, 170, 3), (172, 227, 3), (173, 230, 3), (173, 231, 3), (173, 256, 3), (174, 508, 3), (175, 235, 3), (180, 172, 3), (180, 180, 3), (180, 200, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 240, 3), (180, 270, 3), (180, 270, 3), (180, 320, 3), (180, 320, 3), (181, 259, 3), (182, 227, 3), (185, 233, 3), (187, 250, 3), (187, 250, 3), (187, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (188, 250, 3), (190, 240, 3), (190, 285, 3), (192, 255, 3), (192, 256, 3), (192, 256, 3), (192, 256, 3), (192, 320, 3), (194, 182, 3), (194, 280, 3), (195, 225, 3), (195, 260, 3), (195, 260, 3), (195, 260, 3), (199, 300, 3), (199, 300, 3), (200, 199, 3), (200, 200, 3), (200, 200, 3), (200, 200, 3), (200, 200, 3), (200, 250, 3), (200, 250, 3), (200, 250, 3), (200, 250, 3), (200, 250, 3), (200, 250, 3), (200, 250, 3), (200, 250, 3), (200, 255, 3), (200, 260, 3), (200, 265, 3), (200, 266, 3), (200, 284, 3), (200, 300, 3), (200, 300, 3), (200, 300, 3), (200, 300, 3), (202, 255, 3), (202, 270, 3), (203, 270, 3), (205, 250, 3), (210, 280, 3), (210, 280, 3), (213, 283, 3), (213, 319, 3), (213, 319, 3), (213, 320, 3), (213, 320, 3), (213, 320, 3), (213, 320, 3), (214, 285, 3), (218, 290, 3), (218, 290, 3), (219, 172, 3), (219, 330, 3), (220, 220, 3), (220, 250, 3), (220, 270, 3), (220, 280, 3), (220, 292, 3), (224, 280, 3), (224, 295, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 300, 3), (225, 500, 3), (226, 300, 3), (229, 305, 3), (230, 230, 3), (230, 230, 3), (230, 230, 3), (230, 230, 3), (230, 230, 3), (230, 230, 3), (230, 230, 3), (230, 230, 3), (230, 230, 3), (230, 295, 3), (230, 300, 3), (230, 320, 3), (230, 346, 3), (231, 308, 3), (235, 316, 3), (238, 318, 3), (238, 423, 3), (239, 186, 3), (240, 167, 3), (240, 180, 3), (240, 180, 3), (240, 283, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 320, 3), (240, 330, 3), (240, 350, 3), (240, 400, 3), (242, 301, 3), (242, 361, 3), (245, 245, 3), (245, 327, 3), (245, 330, 3), (245, 553, 3), (246, 250, 3), (247, 300, 3), (248, 320, 3), (249, 360, 3), (250, 250, 3), (250, 250, 3), (250, 250, 3), (250, 411, 3), (251, 300, 3), (252, 332, 3), (253, 380, 3), (255, 170, 3), (256, 357, 3), (257, 343, 3), (260, 390, 3), (260, 390, 3), (260, 484, 3), (262, 350, 3), (262, 350, 3), (263, 300, 3), (263, 350, 3), (263, 350, 3), (263, 350, 3), (263, 350, 3), (263, 350, 3), (263, 350, 3), (263, 351, 3), (264, 352, 3), (264, 352, 3), (264, 352, 3), (265, 318, 3), (265, 350, 3), (265, 400, 3), (266, 400, 3), (268, 400, 3), (269, 198, 3), (269, 320, 3), (269, 340, 3), (270, 360, 3), (270, 480, 3), (271, 340, 3), (272, 350, 3), (274, 520, 3), (275, 390, 3), (276, 368, 3), (280, 280, 3), (281, 426, 3), (285, 380, 3), (285, 380, 3), (285, 565, 3), (287, 400, 3), (288, 352, 3), (288, 352, 3), (288, 352, 3), (288, 384, 3), (288, 384, 3), (288, 384, 3), (288, 384, 3), (288, 384, 3), (289, 353, 3), (289, 450, 3), (290, 350, 3), (290, 450, 3), (291, 296, 3), (291, 389, 3), (292, 233, 3), (295, 450, 3), (296, 360, 3), (297, 374, 3), (297, 395, 3), (299, 450, 3), (299, 450, 3), (300, 214, 3), (300, 300, 3), (300, 300, 3), (300, 300, 3), (300, 300, 3), (300, 300, 3), (300, 300, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 400, 3), (300, 450, 3), (300, 600, 3), (301, 400, 3), (301, 450, 3), (302, 350, 3), (306, 408, 3), (307, 384, 3), (309, 400, 3), (312, 416, 3), (313, 320, 3), (314, 360, 3), (315, 420, 3), (315, 420, 3), (315, 420, 3), (315, 420, 3), (315, 420, 3), (315, 420, 3), (315, 420, 3), (317, 423, 3), (318, 476, 3), (319, 425, 3), (319, 425, 3), (319, 425, 3), (319, 500, 3), (320, 180, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 240, 3), (320, 320, 3), (320, 320, 3), (320, 320, 3), (320, 360, 3), (320, 480, 3), (320, 640, 3), (321, 450, 3), (322, 430, 3), (323, 430, 3), (324, 350, 3), (325, 216, 3), (325, 465, 3), (326, 379, 3), (326, 491, 3), (327, 450, 3), (328, 434, 3), (329, 480, 3), (330, 500, 3), (332, 331, 3), (332, 424, 3), (333, 448, 3), (333, 500, 3), (333, 500, 3), (333, 500, 3), (333, 500, 3), (333, 500, 3), (333, 500, 3), (334, 500, 3), (336, 448, 3), (336, 448, 3), (337, 450, 3), (337, 450, 3), (337, 450, 3), (337, 450, 3), (338, 450, 3), (338, 450, 3), (338, 450, 3), (338, 450, 3), (338, 450, 3), (338, 450, 3), (338, 450, 3), (338, 450, 3), (338, 450, 3), (338, 450, 3), (338, 451, 3), (338, 451, 3), (339, 450, 3), (340, 340, 3), (340, 340, 3), (340, 423, 3), (340, 434, 3), (340, 480, 3), (344, 512, 3), (345, 460, 3), (345, 460, 3), (346, 461, 3), (346, 461, 3), (346, 461, 3), (347, 350, 3), (350, 350, 3), (350, 350, 3), (352, 264, 3), (354, 640, 3), (355, 389, 3), (356, 600, 3), (357, 400, 3), (360, 360, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 480, 3), (360, 600, 3), (360, 600, 3), (360, 600, 3), (360, 600, 3), (360, 640, 3), (363, 460, 3), (364, 498, 3), (365, 220, 3), (366, 500, 3), (370, 300, 3), (370, 500, 3), (372, 425, 3), (373, 280, 3), (373, 280, 3), (373, 280, 3), (373, 280, 3), (373, 280, 3), (373, 280, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 500, 3), (375, 600, 3), (377, 640, 3), (378, 283, 3), (380, 440, 3), (380, 640, 3), (383, 640, 3), (384, 512, 3), (384, 512, 3), (384, 512, 3), (384, 512, 3), (384, 640, 3), (384, 640, 3), (389, 500, 3), (390, 520, 3), (390, 540, 3), (392, 400, 3), (392, 639, 3), (397, 450, 3), (398, 600, 3), (400, 240, 3), (400, 300, 3), (400, 300, 3), (400, 300, 3), (400, 400, 3), (401, 301, 3), (403, 500, 3), (407, 400, 3), (408, 544, 3), (408, 615, 3), (416, 500, 3), (420, 301, 3), (420, 630, 3), (424, 640, 3), (425, 567, 3), (426, 640, 3), (427, 640, 3), (428, 500, 3), (432, 576, 3), (435, 650, 3), (445, 600, 3), (448, 336, 3), (448, 600, 3), (448, 600, 3), (449, 600, 3), (449, 600, 3), (449, 600, 3), (450, 338, 3), (450, 410, 3), (450, 598, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 600, 3), (450, 630, 3), (450, 800, 3), (450, 800, 3), (450, 800, 3), (450, 800, 3), (450, 800, 3), (450, 800, 3), (450, 800, 3), (450, 800, 3), (450, 800, 3), (458, 610, 3), (462, 616, 3), (466, 700, 3), (473, 610, 3), (473, 630, 3), (473, 630, 3), (478, 608, 3), (478, 640, 3), (478, 640, 3), (479, 800, 3), (480, 267, 3), (480, 267, 3), (480, 267, 3), (480, 267, 3), (480, 287, 3), (480, 332, 3), (480, 334, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 360, 3), (480, 480, 3), (480, 480, 3), (480, 480, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 640, 3), (480, 800, 3), (480, 800, 3), (480, 800, 3), (480, 800, 3), (480, 800, 3), (482, 600, 3), (490, 650, 3), (495, 330, 3), (497, 330, 3), (498, 280, 3), (499, 500, 3), (500, 333, 3), (500, 335, 3), (500, 347, 3), (500, 364, 3), (500, 375, 3), (500, 375, 3), (500, 400, 3), (500, 667, 3), (501, 334, 3), (502, 600, 3), (516, 689, 3), (519, 389, 3), (521, 600, 3), (529, 800, 3), (529, 800, 3), (530, 465, 3), (531, 800, 3), (531, 800, 3), (532, 800, 3), (533, 399, 3), (533, 400, 3), (533, 800, 3), (535, 800, 3), (555, 800, 3), (563, 709, 3), (575, 390, 3), (576, 432, 3), (577, 392, 3), (587, 389, 3), (589, 280, 3), (589, 697, 3), (600, 600, 3), (600, 798, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (600, 800, 3), (602, 400, 3), (622, 414, 3), (628, 800, 3), (630, 800, 3), (640, 359, 3), (640, 359, 3), (640, 383, 3), (640, 384, 3), (640, 480, 3), (640, 480, 3), (640, 480, 3), (640, 480, 3), (640, 480, 3), (640, 480, 3), (640, 480, 3), (640, 480, 3), (640, 480, 3), (640, 480, 3), (640, 640, 3), (640, 640, 3), (667, 500, 3), (667, 800, 3), (692, 800, 3), (699, 465, 3), (701, 465, 3), (705, 470, 3), (706, 536, 3), (725, 800, 3), (800, 600, 3), (800, 600, 3), (800, 600, 3)]

```
