### ISSUE TITLE
Mmsegmentation doesn't work on macOS as a third-party library due to "No module named 'mmcv._ext'" error.

### ISSUE THREAD

**Issue by gadylshintr** [open-mmlab/mmsegmentation#871]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
 
**Reproduction**

1. What command or script did you run?

```
from mmseg.apis import inference_segmentor
```

**Environment**

OS: macOS
Installation:
```
conda install pytorch==1.6.0 torchvision==0.7.0 -c pytorch
pip install mmcv
pip install mmsegmentation
```
Vesions:
mmcv 1.3.13
mmsegmentation 0.17.0

**Error traceback**

```
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmseg/apis/__init__.py", line 2, in <module>
  from .inference import inference_segmentor, init_segmentor, show_result_pyplot
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmseg/apis/inference.py", line 9, in <module>
  from mmseg.models import build_segmentor
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmseg/models/__init__.py", line 2, in <module>
  from .backbones import * # noqa: F401,F403
 File "..../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmseg/models/backbones/__init__.py", line 3, in <module>
  from .fast_scnn import FastSCNN
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
  from mmseg.models.decode_heads.psp_head import PPM
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmseg/models/decode_heads/__init__.py", line 18, in <module>
  from .point_head import PointHead
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmseg/models/decode_heads/point_head.py", line 7, in <module>
  from mmcv.ops import point_sample
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmcv/ops/__init__.py", line 2, in <module>
  from .bbox import bbox_overlaps
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmcv/ops/bbox.py", line 4, in <module>
  ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
  ext = importlib.import_module('mmcv.' + name)
 File ".../miniconda3/envs/mac_mmseg/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

**Bug fix**

The problem is that `__init__.py` in mmseg.models imports all backbones and decode_heads, and there is no handling of `mmcv._ext` absence in `mmseg.models.backbones` `__init__.py` (and `mmseg.models.decode_heads`). So such handling should be added.

**Comment by Junjun2016** [comment]
Should install mmcv-full.

**Comment by Junjun2016** [comment]
Maybe we should not import cuda ops if the only mmcv is installed.
We will discuss it.

**Comment by Junjun2016** [comment]
Hi @gadylshintr 
Thanks for your feedback.

**Comment by gadylshintr** [comment]
Hi @Junjun2016 
Thank you!
