### ISSUE TITLE
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgcodecs/src/loadsave.cpp:726: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'

### ISSUE THREAD

**Issue by MengHao666** [open-mmlab/mmsegmentation#878]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I run mmsegmentation, two errors appear as follows:

1. `2021-09-15 22:59:43,293 - mmseg - INFO - Loaded 2214515 images                                                                                                                                              
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                                                                                                         
Use '--' to separate paths from revisions, like this:                                                                                                                                                       
'git <command> [<revision>...] -- [<file>...]'                                                                                                                                                              
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                                                                                                         
Use '--' to separate paths from revisions, like this:                                                                                                                                                       
'git <command> [<revision>...] -- [<file>...]'                                                                                                                                                              
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                                                                                                         
Use '--' to separate paths from revisions, like this:                                                                                                                                                       
'git <command> [<revision>...] -- [<file>...]'                                                                                                                                                              
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                                                                                                         
Use '--' to separate paths from revisions, like this:                                                                                                                                                       
'git <command> [<revision>...] -- [<file>...]'                                                                                                                                                              
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                                                                                                         
Use '--' to separate paths from revisions, like this:                                                                                                                                                       
'git <command> [<revision>...] -- [<file>...]'                                                                                                                                                              
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                                                                                                         
Use '--' to separate paths from revisions, like this:                                                                                                                                                       
'git <command> [<revision>...] -- [<file>...]'                                                                                                                                                              
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                                                                                                         
Use '--' to separate paths from revisions, like this:                                                                                                                                                       
'git <command> [<revision>...] -- [<file>...]'                                                                                                                                                              
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                                                                                                         
Use '--' to separate paths from revisions, like this:                                                                                                                                                       
'git <command> [<revision>...] -- [<file>...]'                                                                                                                                                              
2021-09-15 22:59:46,490 - mmseg - INFO - Loaded 10000 images                                                                                                                                                
2021-09-15 22:59:46,491 - mmseg - INFO - Start running, host: menghao@SH-IDC1-10-198-4-89, work_dir: /mnt/lustre/menghao/projects/0914_mmsegmentation/work_dirs/0912_right_visible                          
2021-09-15 22:59:46,491 - mmseg - INFO - Hooks will be executed in the following order: `

2.
![image](https://user-images.githubusercontent.com/47114466/133537736-c7a3b8f7-c14c-44c8-88e0-81ffcc4ad3f2.png)

![image](https://user-images.githubusercontent.com/47114466/133537772-dca644d2-78de-4ae3-9142-13f2bfbdf4ec.png)

The first might not stop the program, however, the last one could kill the program. I don't know the reason about the last one, as the program seems to have succeeded to train and validate for one epoch.

I just use the latest mmsegmentation, so is this version is buggy or are the dependicies very sensitive?

**Reproduction**

1. What command or script did you run?

    ```none
    just follow the offical guide
    ```

2. Did you make any modifications on the code or config? Did you understand what you have modified? Yes, I think it is right
3. What dataset did you use?  my own dataset

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.

`(pt1.3v1) [menghao@SH-IDC1-10-198-4-31 mmsegmentation]$ python mmseg/utils/collect_env.py                                             
No CUDA runtime is found, using CUDA_HOME='/mnt/cache/share/platform/dep/cuda-9.0-cudnn7.6'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
sys.platform: linux
Python: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
CUDA available: False
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 1.3.0
PyTorch compiling details: PyTorch built with:
  - GCC 4.8
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201107 (a.k.a. OpenMP 3.1)
  - NNPACK is enabled
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-st
rict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NN
PACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.2.2
OpenCV: 4.1.1
MMCV: 1.3.13
MMCV Compiler: GCC 4.8
MMCV CUDA Compiler: not available
MMSegmentation: 0.17.0+HEAD

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!`

**Comment by MengHao666** [comment]
I also meet error like following:

`2021-09-19 00:43:34,677 - mmseg - INFO - Iter [2800/800000]     lr: 5.582e-01, eta: 16 days, 6:21:05, time: 1.764, data_time: 0.028, memory: 29323, decode_0.loss_seg: 0.0792, decode_0.acc_seg: 91.5680, de
code_1.loss_seg: 0.1936, decode_1.acc_seg: 91.7062, loss: 0.2728
Traceback (most recent call last):
  File "tools/train.py", line 170, in <module>
    main()
  File "tools/train.py", line 166, in main
    meta=meta)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/apis/train.py", line 120, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 58, in train
    data_batch = next(data_loader)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/mnt/cache/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/mnt/cache/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/mnt/cache/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/mnt/cache/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/cache/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/cache/share/platform/env/miniconda3.6/envs/pt1.3v1/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/custom.py", line 196, in __getitem__
    return self.prepare_train_img(idx)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/custom.py", line 213, in prepare_train_img
    return self.pipeline(results)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/mnt/lustre/menghao/projects/mmsegmentation/mmseg/datasets/pipelines/loading.py", line 135, in __call__
    backend=self.imdecode_backend).squeeze().astype(np.uint8)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/mmcv/image/io.py", line 230, in imfrombytes
    img = Image.open(buff)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/PIL/Image.py", line 2657, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f3c5ef9c620>

srun: error: SH-IDC1-10-198-4-119: task 5: Exited with exit code 1
srun: Terminating job step 3704140.0
slurmstepd: *** STEP 3704140.0 ON SH-IDC1-10-198-4-119 CANCELLED AT 2021-09-19T00:45:11 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: SH-IDC1-10-198-4-119: task 2: Killed
srun: error: SH-IDC1-10-198-4-119: tasks 0-1,4: Killed
srun: error: SH-IDC1-10-198-4-119: tasks 3,6: Killed
srun: error: SH-IDC1-10-198-4-119: task 7: Killed
(pt1.3v1) [menghao@SH-IDC1-10-198-4-31 mmsegmentation]$ 
`

**Comment by IritaSee** [comment]
> I think it is caused by customized dataset, the index of data may have something wrong.

Hello! I am facing similar issue, to be precise what index of data that might be wrong?

And @MengHao666 can you explain how to solve this issue? I am assuming you already solved it since the issue has been closed
