### ISSUE TITLE
Raising error at validation after training (训练完做验证时报错)

### ISSUE THREAD

**Issue by FDInSky** [open-mmlab/mmsegmentation#891]
[>>>>>>>>>>>>>>>>>>>>>>>> ] 9829/10000, 96.1 task/s, elapsed: 102s, ETA:     2s
[>>>>>>>>>>>>>>>>>>>>>>>> ] 9830Traceback (most recent call last):
  File "tools/train_mmseg.py", line 180, in <module>
Traceback (most recent call last):
  File "tools/train_mmseg.py", line 180, in <module>
Traceback (most recent call last):
  File "tools/train_mmseg.py", line 180, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train_mmseg.py", line 180, in <module>
  File "tools/train_mmseg.py", line 180, in <module>
Traceback (most recent call last):
  File "tools/train_mmseg.py", line 180, in <module>
Traceback (most recent call last):
  File "tools/train_mmseg.py", line 180, in <module>
    main()
  File "tools/train_mmseg.py", line 169, in main
    main()
  File "tools/train_mmseg.py", line 169, in main
    main()
      File "tools/train_mmseg.py", line 169, in main
main()
  File "tools/train_mmseg.py", line 169, in main
    main()
  File "tools/train_mmseg.py", line 169, in main
    main()
  File "tools/train_mmseg.py", line 169, in main
    main()
  File "tools/train_mmseg.py", line 169, in main
    train_segmentor(
  File "/opt/conda/lib/python3.8/site-packages/mmseg/apis/train.py", line 116, in train_segmentor
        train_segmentor(train_segmentor(

  File "/opt/conda/lib/python3.8/site-packages/mmseg/apis/train.py", line 116, in train_segmentor
  File "/opt/conda/lib/python3.8/site-packages/mmseg/apis/train.py", line 116, in train_segmentor
    train_segmentor(
  File "/opt/conda/lib/python3.8/site-packages/mmseg/apis/train.py", line 116, in train_segmentor
    train_segmentor(
    train_segmentor(  File "/opt/conda/lib/python3.8/site-packages/mmseg/apis/train.py", line 116, in train_segmentor

  File "/opt/conda/lib/python3.8/site-packages/mmseg/apis/train.py", line 116, in train_segmentor
    train_segmentor(
  File "/opt/conda/lib/python3.8/site-packages/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 133, in run
    runner.run(data_loaders, cfg.workflow)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 133, in run
    runner.run(data_loaders, cfg.workflow)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 133, in run
    runner.run(data_loaders, cfg.workflow)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 133, in run
    runner.run(data_loaders, cfg.workflow)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 133, in run
    runner.run(data_loaders, cfg.workflow)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 133, in run
    runner.run(data_loaders, cfg.workflow)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    iter_runner(iter_loaders[i], **kwargs)    
iter_runner(iter_loaders[i], **kwargs)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    self.call_hook('after_train_iter')
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
        self.call_hook('after_train_iter')self.call_hook('after_train_iter')

  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    self.call_hook('after_train_iter')
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    self.call_hook('after_train_iter')
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    self.call_hook('after_train_iter')
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
    getattr(hook, fn_name)(self)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
    getattr(hook, fn_name)(self)    
getattr(hook, fn_name)(self)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
        getattr(hook, fn_name)(self)getattr(hook, fn_name)(self)

  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
    getattr(hook, fn_name)(self)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
    self.log(runner)    
    self.log(runner)  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 177, in log
self.log(runner)

  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 177, in log
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 177, in log
    self.log(runner)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 177, in log
    self.log(runner)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 177, in log
    self.log(runner)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 177, in log
    self.log(runner)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 177, in log
    self._log_info(log_dict, runner)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info
    self._log_info(log_dict, runner)    
self._log_info(log_dict, runner)  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info

  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info
        self._log_info(log_dict, runner)self._log_info(log_dict, runner)
    
self._log_info(log_dict, runner)  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info

  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info
    self._log_info(log_dict, runner)
  File "/home/xiaolong.sun/model/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info
    log_str += f'time: {log_dict["time"]:.3f}, ' \
KeyError: 'data_time'
    log_str += f'time: {log_dict["time"]:.3f}, ' \    
log_str += f'time: {log_dict["time"]:.3f}, ' \
    log_str += f'time: {log_dict["time"]:.3f}, ' \
KeyErrorKeyError: : 'data_time'    'data_time'
log_str += f'time: {log_dict["time"]:.3f}, ' \    

KeyErrorlog_str += f'time: {log_dict["time"]:.3f}, ' \
: 'data_time'
    log_str += f'time: {log_dict["time"]:.3f}, ' \
KeyError: 'data_time'
KeyError: 'data_time'
KeyError: 'data_time'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', 'tools/train_mmseg.py', '--local_rank=7', 'experiments/seg/lane/ocrnet_hr48.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
/10000, 96.1 task/s, elapsed: 102s, ETA:     2s
[>>>>>>>>>>>>>>>>>>>>>>>> ] 9831/10000, 96.1 task/s, elapsed: 102s, ETA:     2s

**Comment by MengzhangLI** [comment]
I think it is caused by the conflict between your input size and image size, for example the size of 9834th image is smaller than your input size in config file.

You can check out size of validation set to testify my conjunction.

**Comment by FDInSky** [comment]
> I think it is caused by the conflict between your input size and image size, for example the size of 9834th image is smaller than your input size in config file.
> 
> You can check out size of validation set to testify my conjunction.

我git pull了一下mmcv，目前没有这个问题了；根据你的意见，我会在检查一下数据的；
