### ISSUE TITLE
RuntimeError: It is expected output_size equals to 2, but got size 3

### ISSUE THREAD

**Issue by yjyyy** [open-mmlab/mmsegmentation#91]
when i use a new dataset as the VOC form, i met the question below. and i have run the VOC dataset successfully.

Traceback (most recent call last):
  File "./tools/train.py", line 162, in <module>
    main()
  File "./tools/train.py", line 158, in main
    meta=meta)
  File "/home/zkyd/yjy/code/mmsegmentation-master/mmseg/apis/train.py", line 106, in train_segmentor
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/zkyd/anaconda3/envs/mmseg/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 119, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/zkyd/anaconda3/envs/mmseg/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 55, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/zkyd/anaconda3/envs/mmseg/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/zkyd/yjy/code/mmsegmentation-master/mmseg/models/segmentors/base.py", line 152, in train_step
    losses = self(**data_batch)
  File "/home/zkyd/anaconda3/envs/mmseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zkyd/anaconda3/envs/mmseg/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/zkyd/yjy/code/mmsegmentation-master/mmseg/models/segmentors/base.py", line 122, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/zkyd/yjy/code/mmsegmentation-master/mmseg/models/segmentors/encoder_decoder.py", line 158, in forward_train
    gt_semantic_seg)
  File "/home/zkyd/yjy/code/mmsegmentation-master/mmseg/models/segmentors/encoder_decoder.py", line 102, in _decode_head_forward_train
    self.train_cfg)
  File "/home/zkyd/yjy/code/mmsegmentation-master/mmseg/models/decode_heads/decode_head.py", line 186, in forward_train
    losses = self.losses(seg_logits, gt_semantic_seg)
  File "/home/zkyd/anaconda3/envs/mmseg/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/zkyd/yjy/code/mmsegmentation-master/mmseg/models/decode_heads/decode_head.py", line 221, in losses
    align_corners=self.align_corners)
  File "/home/zkyd/yjy/code/mmsegmentation-master/mmseg/ops/wrappers.py", line 25, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "/home/zkyd/anaconda3/envs/mmseg/lib/python3.7/site-packages/torch/nn/functional.py", line 2530, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
RuntimeError: It is expected output_size equals to 2, but got size 3

**Comment by xvjiarui** [comment]
Hi @yjyyy 
You may check if your annotation image is `2-dim` or `3-dim`.

**Comment by yjyyy** [comment]
> Hi @yjyyy
> You may check if your annotation image is `2-dim` or `3-dim`.

it's all 3-dim

**Comment by xvjiarui** [comment]
Hi @yjyyy 
You may refer to this [doc](https://mmsegmentation.readthedocs.io/en/latest/tutorials/new_dataset.html) about adding a new dataset. The annotation file should be of 2-dim, shape (H, W).

**Comment by yjyyy** [comment]
@xvjiarui if the annotations are 2-dim, how to reflect the RGB color in every pixel. and the annotations of VOC2012 are all 3-dim.

**Comment by xvjiarui** [comment]
The color is reflected by `palette`. Since all we need is the class label of each pixel, color is not necessary.

**Comment by yjyyy** [comment]
and what is the suffix of annotation file? how about '.png'

**Comment by xvjiarui** [comment]
Yep. `.png` could be a suffix. For cityscapes, the suffix of the annotation file could be `_gtFine_labelTrainIds.png`.

**Comment by yjyyy** [comment]
@xvjiarui  thank you so much! i have already solved my problem.

**Comment by huang45** [comment]
Same question. How do you solve that please, if I only have colorful masks of VOC format? @yjyyy

**Comment by huang45** [comment]
@xvjiarui could you help? thank you.

**Comment by yuefanhao** [comment]
> @xvjiarui thank you so much! i have already solved my problem.

How do you solve it, could you share it? thank you.

**Comment by yuefanhao** [comment]
> @xvjiarui thank you so much! i have already solved my problem.

@yjyyy How do you solve it? could you share it?
