### ISSUE TITLE
TypeError: cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by chiba1sonny** [open-mmlab/mmsegmentation#948]
I got this problem.

[                                                  ] 0/45, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 176, in main
    meta=meta)
  File "/home/maruyama/mmsegmentation/mmseg/apis/train.py", line 120, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 232, in after_train_iter
    self._do_evaluate(runner)
  File "/home/maruyama/mmsegmentation/mmseg/core/evaluation/eval_hooks.py", line 50, in _do_evaluate
    runner.model, self.dataloader, show=False, pre_eval=self.pre_eval)
  File "/home/maruyama/mmsegmentation/mmseg/apis/test.py", line 91, in single_gpu_test
    result = model(return_loss=False, **data)
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/maruyama/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/maruyama/mmsegmentation/mmseg/models/segmentors/base.py", line 110, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/maruyama/mmsegmentation/mmseg/models/segmentors/base.py", line 92, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/maruyama/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 256, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/home/maruyama/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 239, in inference
    seg_logit = self.slide_inference(img, img_meta, rescale)
  File "/home/maruyama/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 162, in slide_inference
    h_stride, w_stride = self.test_cfg.stride
TypeError: cannot unpack non-iterable int object

**Comment by chiba1sonny** [comment]
Sorry, didn't get what you mean. Is the mistake in encoder_decoder.py? If so, which line should I change?

**Comment by chiba1sonny** [comment]
I'm sorry that I didn't get what you mean.
