### ISSUE TITLE
ImportError：

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#981]
您好，我是在Linux系统上搭建该架构：pytoch1.6 CUDA10.1 MMsegmentation 0.11
原本该架构可以很好的运行，但在重新安装相同的环境后，出现了以下错误：

Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/lsz/Transformer/mytransformer/Swin-low-cnn/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/lsz/Transformer/mytransformer/Swin-low-cnn/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/lsz/Transformer/mytransformer/Swin-low-cnn/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/lsz/Transformer/mytransformer/Swin-low-cnn/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/lsz/Transformer/mytransformer/Swin-low-cnn/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/lsz/Transformer/mytransformer/Swin-low-cnn/mmseg/models/decode_heads/__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "/home/lsz/Transformer/mytransformer/Swin-low-cnn/mmseg/models/decode_heads/cc_head.py", line 7, in <module>
    from mmcv.ops import CrissCrossAttention
  File "/home/anaconda3/envs/pytorch3.7_torch1.6/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/anaconda3/envs/pytorch3.7_torch1.6/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/anaconda3/envs/pytorch3.7_torch1.6/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/anaconda3/envs/pytorch3.7_torch1.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/anaconda3/envs/pytorch3.7_torch1.6/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

期待您的答复
Thanks for your help

**Comment by Lsz-20** [comment]
> I think it is caused by MMCV version conflict.
> 
> Because most codebases of OpenMMLab utilize MMCV for many operations instead of normal standard PyTorch function, we should notice the MMCV version.
> 
> You could uninstall current MMCV and re-install [MMCV-full](https://github.com/open-mmlab/mmcv) again, choose the suitable MMCV with PyTorch and CUDA version.
> 
> Best,

thanks for your answer.I have installed all as official shows：mmcv-full==1.2.7
